In [1]:
# urls :
# https://www.sharesansar.com/mutual-fund-navs

In [2]:
# https://www.sharesansar.com/live-trading

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

options = Options()
options.add_argument("--headless")

driver = webdriver.Chrome(options=options)
driver.get("https://www.sharesansar.com/live-trading")

time.sleep(10)


data=driver.find_element(By.ID,"headFixed").text
data

'S.No Symbol LTP Point Change % Change Open High Low Volume Prev. Close\n1 ACLBSL 967.00 18.00 1.90 977.40 977.40 954.00 470.00 949.00\n2 ADBL 315.30 2.30 0.73 317.90 318.50 312.30 41,552.00 313.00\n3 ADBLD83 1,051.90 -18.10 -1.69 1,051.90 1,051.90 1,051.90 25.00 1,070.00\n4 AHL 506.00 -9.00 -1.75 505.00 518.50 504.00 14,648.00 515.00\n5 AHPC 289.00 5.00 1.76 275.00 289.00 275.00 83,890.00 284.00\n6 AKJCL 417.80 15.80 3.93 402.00 420.00 402.00 1,278,371.00 402.00\n7 AKPL 277.80 3.30 1.20 275.00 278.80 271.00 171,946.00 274.50\n8 ALBSL 1,123.00 8.00 0.72 1,086.00 1,125.00 1,086.00 6,362.00 1,115.00\n9 ALICL 455.30 3.00 0.66 459.90 459.90 452.00 7,840.00 452.30\n10 ANLB 5,996.00 95.00 1.61 5,801.00 5,996.00 5,733.00 867.00 5,901.00\n11 API 360.80 3.60 1.01 359.00 363.00 357.20 429,359.00 357.20\n12 AVYAN 1,146.00 7.00 0.61 1,082.10 1,159.00 1,082.10 4,714.00 1,139.00\n13 BANDIPUR 865.00 -10.90 -1.24 910.00 910.00 855.00 56,430.00 875.90\n14 BARUN 357.40 6.30 1.79 352.00 359.00 351.00 34,727.00 351.10\n15 BBC 4,822.00 22.00 0.46 4,818.90 4,832.90 4,766.10 182.00 4,800.00\n16 BEDC 383.60 6.70 1.78 395.70 395.70 377.30 39,932.00 376.90\n17 BFC 462.40 4.40 0.96 464.00 469.00 460.10 12,243.00 458.00\n18 BGWT 666.40 5.40 0.82 665.00 674.00 665.00 1,017.00 661.00\n19 BHCL 596.00 30.00 5.30 566.00 604.90 566.00 108,733.00 566.00\n20 BHDC 478.10 14.50 3.13 461.20 480.00 461.20 40,973.00 463.60\n21 BHL 228.70 2.70 1.19 237.00 237.00 225.00 161,537.00 226.00\n22 BHPL 533.20 3.40 0.64 530.10 537.80 530.00 4,458.00 529.80\n23 BJHL 989.00 36.00 3.78 952.00 1,000.00 945.00 14,617.00 953.00\n24 BNHC 337.10 4.00 1.20 333.10 343.00 332.00 7,278.00 333.10\n25 BNL 14,819.00 431.90 3.00 14,818.70 14,819.00 14,818.70 20.00 14,387.10\n26 BNT 11,890.00 299.40 2.58 11,590.00 11,900.00 11,590.00 50.00 11,590.60\n27 BPCL 705.00 6.00 0.86 699.00 709.00 680.00 51,676.00 699.00\n28 BUNGAL 734.00 -80.00 -9.83 773.30 773.30 706.00 78,697.00 814.00\n29 C30MF 10.00 0.17 1.73 9.89 10.20 9.89 11,500.00 9.83\n30 CBBL 923.00 6.00 0.65 924.30 924.30 918.00 14,775.00 917.00\n31 CFCL 504.00 1.00 0.20 510.00 510.00 496.00 5,723.00 503.00\n32 CGH 803.00 -0.80 -0.10 799.00 814.70 795.00 28,593.00 803.80\n33 CHCL 489.90 7.90 1.64 482.50 490.00 482.50 67,158.00 482.00\n34 CHDC 2,313.00 13.00 0.57 2,300.00 2,328.00 2,286.00 10,817.00 2,300.00\n35 CHL 299.00 2.00 0.67 288.10 302.00 288.10 43,600.00 297.00\n36 CIT 1,773.80 6.80 0.38 1,767.00 1,789.90 1,765.00 4,119.00 1,767.00\n37 CITY 377.00 6.00 1.62 374.00 383.90 373.00 119,087.00 371.00\n38 CKHL 677.50 3.60 0.53 658.00 688.00 658.00 578.00 673.90\n39 CLI 458.00 6.00 1.33 452.00 459.80 452.00 17,291.00 452.00\n40 CMF2 10.01 -0.13 -1.28 10.00 10.25 10.00 2,620.00 10.14\n41 CORBL 2,010.00 -56.00 -2.71 2,050.00 2,079.00 2,000.00 14,937.00 2,066.00\n42 CREST 1,240.00 -78.00 -5.92 1,252.10 1,260.00 1,143.00 21,491.00 1,318.00\n43 CSY 9.45 0.00 0.00 9.17 9.47 9.17 5,290.00 9.45\n44 CYCL 1,484.70 14.60 0.99 1,482.00 1,485.00 1,463.00 373.00 1,470.10\n45 CZBIL 209.10 1.60 0.77 197.20 210.40 197.20 46,684.00 207.50\n46 DDBL 855.00 2.00 0.23 859.00 870.00 853.00 6,122.00 853.00\n47 DHEL 672.40 4.30 0.64 650.00 684.90 650.00 44,779.00 668.10\n48 DHPL 304.00 2.00 0.66 303.00 311.00 303.00 3,251.00 302.00\n49 DLBS 1,281.10 6.10 0.48 1,271.00 1,295.00 1,271.00 258.00 1,275.00\n50 DOLTI 363.00 4.10 1.14 341.00 364.90 341.00 48,936.00 358.90\n51 DORDI 283.50 6.00 2.16 277.10 287.90 277.10 53,943.00 277.50\n52 EBL 711.00 1.00 0.14 719.90 719.90 710.30 26,329.00 710.00\n53 EBLD85 1,197.00 -1.00 -0.08 1,197.00 1,197.00 1,197.00 10.00 1,198.00\n54 EBLD91 1,081.00 -4.00 -0.37 1,081.10 1,081.10 1,081.00 100.00 1,085.00\n55 EDBL 587.10 7.10 1.22 583.00 595.00 583.00 4,358.00 580.00\n56 EHPL 400.20 5.70 1.44 395.00 402.50 395.00 22,372.00 394.50\n57 ENL 903.00 5.00 0.56 912.30 912.30 887.20 533.00 898.00\n58 FMDBL 797.00 9.70 1.23 792.00 799.00 792.00 11,070.00 787.30\n59 FOWAD 1,050.10 6.10 0.58 1,068.90 1,068.90 1,047.00 2,184.00 1,044.00\n60 GBBL 421.60 0.60 0.14 421.00 425.00 420.00 28,164.00 421.00\n61 GBILD86/87 1,086.00 5.90 0.55 1,086.00 1,086.00 1,086.00 25.00 1,080.10\n62 GBIME 238.90 2.10 0.89 236.00 239.00 235.20 62,203.00 236.80\n63 GBIMESY2 9.57 0.26 2.79 9.31 9.58 9.25 4,300.00 9.31\n64 GBLBS 779.00 3.10 0.40 788.00 788.00 766.00 3,269.00 775.90\n65 GCIL 435.00 11.00 2.59 418.20 435.00 418.00 60,458.00 424.00\n66 GFCL 631.10 -3.90 -0.61 635.00 643.00 630.20 5,277.00 635.00\n67 GHL 245.90 3.90 1.61 245.00 247.90 241.30 66,641.00 242.00\n68 GIBF1 11.00 0.00 0.00 10.90 11.33 10.90 6,100.00 11.00\n69 GILB 1,155.00 25.00 2.21 1,125.00 1,157.00 1,125.00 990.00 1,130.00\n70 GLBSL 1,830.00 21.00 1.16 1,830.00 1,850.00 1,805.00 232.00 1,809.00\n71 GLH 277.50 3.50 1.28 274.00 279.00 274.00 47,553.00 274.00\n72 GMFBS 1,285.10 -0.90 -0.07 1,261.00 1,315.00 1,261.00 1,237.00 1,286.00\n73 GMFIL 475.90 6.00 1.28 479.90 479.90 466.40 1,570.00 469.90\n74 GMLI 1,279.00 9.10 0.72 1,270.00 1,300.00 1,261.00 3,192.00 1,269.90\n75 GRDBL 1,096.50 -13.50 -1.22 1,061.10 1,129.90 1,061.10 9,289.00 1,110.00\n76 GSY 10.00 0.00 0.00 9.99 10.10 9.91 72,200.00 10.00\n77 GUFL 540.00 5.00 0.93 520.00 544.80 520.00 7,738.00 535.00\n78 GVL 495.50 3.60 0.73 492.00 500.00 492.00 12,681.00 491.90\n79 H8020 12.01 0.03 0.25 12.33 12.33 11.81 21,735.00 11.98\n80 HATHY 805.00 6.00 0.75 810.90 810.90 803.00 2,755.00 799.00\n81 HBL 206.10 3.10 1.53 202.00 207.00 200.80 53,929.00 203.00\n82 HBLD83 1,065.00 29.00 2.80 1,036.00 1,065.00 1,036.00 45.00 1,036.00\n83 HDHPC 233.50 2.80 1.21 230.70 236.00 230.70 197,364.00 230.70\n84 HDL 1,171.90 4.00 0.34 1,180.00 1,180.00 1,168.00 19,914.00 1,167.90\n85 HEI 533.20 -2.70 -0.50 535.00 583.00 533.00 8,419.00 535.90\n86 HEIP 326.00 6.00 1.88 328.90 328.90 326.00 599.00 320.00\n87 HFIN 1,024.00 24.00 2.40 985.00 1,042.00 985.00 70,467.00 1,000.00\n88 HHL 377.00 -1.00 -0.26 396.90 396.90 376.00 64,136.00 378.00\n89 HIDCL 274.90 3.40 1.25 270.00 276.80 270.00 71,736.00 271.50\n90 HIDCLP 210.00 2.70 1.30 209.20 210.70 207.40 169,639.00 207.30\n91 HIMSTAR 908.00 -10.00 -1.09 900.00 929.50 900.00 7,807.00 918.00\n92 HLBSL 900.00 2.00 0.22 910.00 920.00 893.00 622.00 898.00\n93 HLI 342.20 2.40 0.71 344.00 344.30 340.00 38,472.00 339.80\n94 HLICF 9.00 0.13 1.47 9.10 9.12 8.90 40,060.00 8.87\n95 HPPL 385.10 4.10 1.08 381.30 388.00 381.00 12,833.00 381.00\n96 HRL 652.10 10.70 1.67 641.00 661.00 640.50 106,053.00 641.40\n97 HURJA 267.90 4.90 1.86 262.00 269.00 262.00 75,441.00 263.00\n98 ICFC 637.00 6.00 0.95 630.90 639.50 629.00 6,510.00 631.00\n99 ICFCD88 1,145.00 -5.00 -0.43 1,145.00 1,145.00 1,145.00 25.00 1,150.00\n100 ICFCD89 1,090.00 -9.00 -0.82 1,081.00 1,095.00 1,081.00 125.00 1,099.00\n101 IGI 438.10 8.10 1.88 439.90 439.90 431.80 8,904.00 430.00\n102 IHL 443.00 1.00 0.23 442.00 451.10 425.00 112,943.00 442.00\n103 ILBS 940.00 0.10 0.01 935.00 947.20 920.10 3,288.00 939.90\n104 ILI 442.00 2.10 0.48 437.00 444.00 437.00 5,940.00 439.90\n105 JBBL 367.00 5.50 1.52 343.50 367.90 343.50 30,802.00 361.50\n106 JBLB 1,310.00 8.00 0.61 1,305.00 1,325.00 1,305.00 2,812.00 1,302.00\n107 JFL 414.50 6.50 1.59 409.00 414.90 409.00 2,169.00 408.00\n108 JHAPA 1,492.00 -7.00 -0.47 1,480.00 1,543.70 1,438.00 23,875.00 1,499.00\n109 JOSHI 288.00 3.50 1.23 282.10 290.00 282.10 14,635.00 284.50\n110 JSLBB 1,084.10 -5.00 -0.46 1,078.50 1,084.10 1,078.10 101.00 1,089.10\n111 KBL 223.40 4.70 2.15 220.00 224.00 219.00 259,047.00 218.70\n112 KBSH 1,500.00 0.00 0.00 1,470.20 1,500.20 1,470.20 280.00 1,500.00\n113 KDBY 11.65 0.20 1.75 11.41 11.70 11.41 278,200.00 11.45\n114 KDL 834.00 7.20 0.87 850.00 850.00 812.00 1,582.00 826.80\n115 KEF 10.81 0.06 0.56 10.75 10.81 10.72 12,900.00 10.75\n116 KKHC 271.50 5.40 2.03 273.50 273.50 266.00 51,459.00 266.10\n117 KMCDB 861.20 1.20 0.14 860.00 869.00 855.00 1,147.00 860.00\n118 KPCL 501.50 8.00 1.62 490.00 502.00 490.00 8,128.00 493.50\n119 KSBBL 489.90 7.80 1.62 484.00 490.00 484.00 35,926.00 482.10\n120 KSBBLD87 1,132.00 1.00 0.09 1,132.00 1,132.00 1,132.00 25.00 1,131.00\n121 KSBBLP 269.00 0.00 0.00 269.00 269.00 269.00 14,079.00 269.00\n122 KSY 9.90 0.10 1.02 9.80 9.90 9.61 21,900.00 9.80\n123 LBBL 495.50 4.50 0.92 498.10 498.10 491.00 32,203.00 491.00\n124 LEC 236.90 3.90 1.67 222.00 237.90 222.00 111,358.00 233.00\n125 LICN 822.00 9.00 1.11 829.00 829.00 813.00 3,955.00 813.00\n126 LLBS 937.20 -20.80 -2.17 958.00 965.00 937.20 820.00 958.00\n127 LSL 225.50 -0.40 -0.18 215.00 244.00 215.00 84,240.00 225.90\n128 LUK 10.00 0.05 0.50 9.95 10.20 9.95 5,825.00 9.95\n129 LVF2 10.19 0.19 1.90 9.80 10.19 9.80 4,600.00 10.00\n130 MABEL 755.00 -5.00 -0.66 760.00 782.00 747.00 30,326.00 760.00\n131 MAKAR 508.00 -1.70 -0.33 535.10 535.10 504.00 8,703.00 509.70\n132 MANDU 830.00 11.10 1.36 815.00 830.00 815.00 1,007.00 818.90\n133 MATRI 891.00 -4.00 -0.45 881.00 913.00 880.00 518.00 895.00\n134 MBJC 289.80 3.80 1.33 286.00 292.00 281.30 24,276.00 286.00\n135 MBL 254.90 2.00 0.79 253.70 256.80 253.70 84,848.00 252.90\n136 MBLD2085 1,200.00 -35.00 -2.83 1,200.00 1,200.00 1,200.00 100.00 1,235.00\n137 MBLEF 10.00 -0.05 -0.50 9.93 10.21 9.93 6,009.00 10.05\n138 MCHL 320.10 -2.80 -0.87 323.00 329.90 313.40 23,615.00 322.90\n139 MDB 613.20 -1.40 -0.23 615.00 618.00 612.20 12,000.00 614.60\n140 MEHL 385.10 5.10 1.34 379.00 390.00 379.00 2,302.00 380.00\n141 MEL 244.00 5.90 2.48 238.00 245.00 235.10 22,153.00 238.10\n142 MEN 608.00 4.00 0.66 610.00 615.00 606.50 65,116.00 604.00\n143 MERO 720.80 2.80 0.39 732.90 733.00 720.00 3,873.00 718.00\n144 MFIL 799.80 -2.20 -0.27 785.00 804.80 785.00 15,660.00 802.00\n145 MHCL 362.00 -6.90 -1.87 370.00 372.00 362.00 5,159.00 368.90\n146 MHL 508.70 8.70 1.74 500.00 510.00 498.50 10,263.00 500.00\n147 MHNL 272.10 2.10 0.78 268.00 276.00 268.00 5,702.00 270.00\n148 MKCL 1,299.00 11.00 0.85 1,290.00 1,310.00 1,272.10 1,085.00 1,288.00\n149 MKHC 338.00 18.00 5.62 320.00 342.90 320.00 58,806.00 320.00\n150 MKHL 553.10 8.10 1.49 523.10 574.80 523.10 7,393.00 545.00\n151 MKJC 497.10 7.10 1.45 500.00 501.60 493.20 4,090.00 490.00\n152 MLBBL 1,189.00 -9.00 -0.75 1,220.00 1,220.00 1,183.00 2,549.00 1,198.00\n153 MLBL 370.00 4.10 1.12 369.90 370.90 367.30 14,685.00 365.90\n154 MLBS 1,270.10 -8.90 -0.70 1,250.00 1,300.00 1,250.00 190.00 1,279.00\n155 MLBSL 1,820.00 20.00 1.11 1,790.00 1,820.00 1,790.00 454.00 1,800.00\n156 MMF1 9.45 -0.14 -1.46 9.70 9.70 9.39 4,705.00 9.59\n157 MMKJL 512.40 11.40 2.28 494.00 515.00 494.00 2,234.00 501.00\n158 MNBBL 377.40 4.50 1.21 374.30 379.00 374.00 28,233.00 372.90\n159 MNMF1 10.00 0.00 0.00 9.90 10.00 9.90 22,006.00 10.00\n160 MPFL 628.00 8.50 1.37 624.90 629.00 613.00 4,951.00 619.50\n161 MSHL 707.00 12.00 1.73 695.00 707.00 686.00 703.00 695.00\n162 MSLB 1,242.00 2.00 0.16 1,272.00 1,272.00 1,235.00 1,440.00 1,240.00\n163 NABBC 957.00 7.00 0.74 930.00 968.00 930.00 4,939.00 950.00\n164 NABIL 535.10 5.10 0.96 530.00 536.00 530.00 53,893.00 530.00\n165 NABILD2089 1,095.10 -4.90 -0.45 1,125.00 1,133.00 1,095.10 335.00 1,100.00\n166 NADEP 757.00 12.00 1.61 741.00 763.20 735.40 940.00 745.00\n167 NBF2 9.92 -0.03 -0.30 9.95 10.10 9.90 5,950.00 9.95\n168 NBF3 9.96 0.01 0.10 9.95 9.96 9.95 4,700.00 9.95\n169 NBL 273.90 8.60 3.24 252.10 276.00 252.10 121,606.00 265.30\n170 NBLD85 1,081.00 28.90 2.75 1,079.50 1,081.00 1,079.50 50.00 1,052.10\n171 NBLD87 1,091.30 -33.70 -3.00 1,091.30 1,091.30 1,091.30 25.00 1,125.00\n172 NESDO 1,555.00 31.00 2.03 1,535.10 1,569.00 1,535.00 1,140.00 1,524.00\n173 NFS 577.00 7.00 1.23 584.00 584.00 570.00 9,009.00 570.00\n174 NGPL 459.20 7.70 1.71 435.00 462.00 435.00 290,990.00 451.50\n175 NHDL 644.00 7.10 1.11 636.90 646.00 636.90 144.00 636.90\n176 NHPC 297.60 2.60 0.88 309.70 309.70 295.00 385,906.00 295.00\n177 NIBD84 1,052.10 2.00 0.19 1,052.10 1,052.10 1,052.10 25.00 1,050.10\n178 NIBLGF 9.50 -0.41 -4.14 9.62 9.62 9.42 1,000.00 9.91\n179 NIBLSTF 9.21 -0.08 -0.86 9.13 9.35 9.13 2,400.00 9.29\n180 NIBSF2 9.25 -0.10 -1.07 9.14 9.41 9.14 4,710.00 9.35\n181 NICA 356.00 3.50 0.99 365.00 365.00 345.00 32,546.00 352.50\n182 NICAD2091 1,053.60 1.40 0.13 1,053.60 1,053.60 1,053.60 25.00 1,052.20\n183 NICBF 9.68 0.28 2.98 9.68 9.68 9.68 100.00 9.40\n184 NICD88 1,110.00 32.00 2.97 1,110.00 1,110.00 1,110.00 25.00 1,078.00\n185 NICFC 9.35 -0.05 -0.53 9.17 9.53 9.17 1,800.00 9.40\n186 NICGF2 9.50 -0.14 -1.45 9.92 9.92 9.40 1,600.00 9.64\n187 NICL 507.00 10.00 2.01 500.00 507.00 497.00 9,198.00 497.00\n188 NICLBSL 587.10 13.10 2.28 574.00 599.40 574.00 8,122.00 574.00\n189 NICSF 9.20 -0.09 -0.97 9.39 9.39 9.11 1,800.00 9.29\n190 NIFRA 267.00 0.20 0.07 266.10 270.00 266.00 89,532.00 266.80\n191 NIFRAGED 1,040.10 4.80 0.46 1,035.50 1,040.10 1,035.50 75.00 1,035.30\n192 NIL 625.00 11.00 1.79 610.00 625.00 610.00 4,080.00 614.00\n193 NIMB 201.00 3.00 1.52 199.00 202.00 198.00 122,308.00 198.00\n194 NIMBD90 1,245.00 -4.00 -0.32 1,245.00 1,245.00 1,245.00 25.00 1,249.00\n195 NIMBPO 152.70 1.20 0.79 151.50 152.70 151.50 218.00 151.50\n196 NLG 583.00 8.00 1.39 582.00 590.00 580.00 7,702.00 575.00\n197 NLIC 778.00 8.20 1.07 770.00 779.80 765.00 10,282.00 769.80\n198 NLICL 592.00 1.00 0.17 595.80 595.80 586.20 3,396.00 591.00\n199 NMB 249.00 0.40 0.16 248.00 251.00 247.00 16,541.00 248.60\n200 NMBD87/88 1,090.50 0.00 0.00 1,090.50 1,090.50 1,090.50 25.00 1,090.50\n201 NMBHF2 9.70 0.03 0.31 9.60 9.70 9.60 21,700.00 9.67\n202 NMBMF 653.00 21.00 3.32 633.10 655.00 633.10 2,332.00 632.00\n203 NMFBS 1,145.00 5.00 0.44 1,117.00 1,155.00 1,117.00 7,073.00 1,140.00\n204 NMIC 1,058.00 33.00 3.22 1,040.00 1,059.80 1,025.00 6,426.00 1,025.00\n205 NMLBBL 592.00 4.00 0.68 571.00 593.90 571.00 3,818.00 588.00\n206 NRIC 922.10 14.00 1.54 914.10 924.70 911.00 8,440.00 908.10\n207 NRM 383.90 19.80 5.44 345.90 388.00 345.90 34,194.00 364.10\n208 NRN 1,406.70 7.70 0.55 1,425.00 1,440.00 1,387.00 46,582.00 1,399.00\n209 NSIF2 10.72 -0.03 -0.28 10.60 10.75 10.60 3,100.00 10.75\n210 NSY 9.63 -0.05 -0.52 9.44 9.63 9.44 6,970.00 9.68\n211 NTC 898.00 7.60 0.85 890.00 899.90 888.50 14,108.00 890.40\n212 NUBL 657.10 -2.90 -0.44 665.00 665.00 656.00 2,925.00 660.00\n213 NWCL 816.00 12.00 1.49 803.00 818.90 803.00 1,160.00 804.00\n214 NYADI 400.00 8.90 2.28 399.90 401.00 391.00 4,545.00 391.10\n215 OHL 701.00 8.60 1.24 708.00 712.00 700.00 2,389.00 692.40\n216 OMPL 1,187.00 7.00 0.59 1,190.00 1,210.00 1,185.10 4,897.00 1,180.00\n217 PBD84 1,140.00 0.00 0.00 1,140.00 1,140.00 1,140.00 35.00 1,140.00\n218 PBD85 1,081.00 1.00 0.09 1,081.00 1,081.00 1,081.00 25.00 1,080.00\n219 PBLD84 1,085.10 -3.00 -0.28 1,085.10 1,085.10 1,085.10 50.00 1,088.10\n220 PCBL 243.60 3.10 1.29 240.50 244.70 239.00 49,235.00 240.50\n221 PCIL 854.00 27.00 3.26 827.00 860.00 815.00 58,524.00 827.00\n222 PFL 377.90 2.90 0.77 379.00 379.00 370.00 3,256.00 375.00\n223 PHCL 312.00 2.80 0.91 308.00 315.00 308.00 44,639.00 309.20\n224 PMHPL 350.90 8.90 2.60 343.90 352.00 343.00 15,670.00 342.00\n225 PMLI 470.20 0.20 0.04 470.00 475.00 462.50 2,651.00 470.00\n226 PPCL 392.00 12.00 3.16 380.00 393.90 378.00 9,922.00 380.00\n227 PPL 366.00 12.00 3.39 357.00 369.90 357.00 65,705.00 354.00\n228 PRIN 665.00 3.00 0.45 669.90 669.90 656.00 3,129.00 662.00\n229 PROFL 442.20 -1.80 -0.41 456.00 457.00 442.00 4,112.00 444.00\n230 PRSF 12.94 -0.01 -0.08 13.00 13.14 12.94 323,100.00 12.95\n231 PRVU 202.20 4.20 2.12 188.10 203.00 188.10 102,733.00 198.00\n232 PSF 12.17 -0.04 -0.33 12.01 12.20 12.01 56,350.00 12.21\n233 PURE 990.00 5.00 0.51 1,030.00 1,030.00 990.00 18,002.00 985.00\n234 RADHI 802.00 19.00 2.43 785.00 805.00 780.00 57,673.00 783.00\n235 RAWA 590.00 6.00 1.03 613.00 613.00 575.00 2,354.00 584.00\n236 RBBD2088 1,067.00 -18.30 -1.69 1,056.70 1,067.00 1,056.70 50.00 1,085.30\n237 RBBF40 9.41 -0.04 -0.42 9.33 9.69 9.33 2,100.00 9.45\n238 RBCL 15,292.90 361.90 2.42 14,994.00 15,292.90 14,994.00 70.00 14,931.00\n239 RFPL 381.50 5.30 1.41 360.00 382.90 360.00 24,161.00 376.20\n240 RHGCL 306.00 8.00 2.68 295.10 306.90 291.00 42,841.00 298.00\n241 RHPL 283.10 4.10 1.47 279.00 285.00 278.00 18,173.00 279.00\n242 RIDI 373.00 6.30 1.72 368.00 378.10 365.10 579,596.00 366.70\n243 RLEL 1,085.00 58.10 5.66 1,026.00 1,098.00 1,026.00 24,873.00 1,026.90\n244 RLFL 445.00 6.10 1.39 430.00 447.00 430.00 15,536.00 438.90\n245 RMF1 9.88 -0.12 -1.20 9.85 10.00 9.85 3,400.00 10.00\n246 RMF2 10.20 -0.30 -2.86 10.20 10.20 10.20 2,700.00 10.50\n247 RNLI 470.10 5.10 1.10 466.00 471.00 461.00 30,761.00 465.00\n248 RSDC 673.50 5.70 0.85 674.00 680.00 665.00 3,791.00 667.80\n249 RSML 3,830.00 100.00 2.68 3,700.00 3,850.00 3,700.00 31,065.00 3,730.00\n250 RSY 10.15 -0.20 -1.93 10.04 10.45 10.04 14,000.00 10.35\n251 RURU 663.00 3.00 0.45 670.00 670.00 655.00 5,250.00 660.00\n252 SABBL 1,279.00 32.00 2.57 1,250.00 1,285.00 1,242.10 9,055.00 1,247.00\n253 SADBL 420.90 4.90 1.18 416.00 421.50 416.00 17,364.00 416.00\n254 SAGAR 1,742.20 25.20 1.47 1,722.00 1,757.00 1,722.00 6,136.00 1,717.00\n255 SAGF 10.20 0.00 0.00 10.15 10.20 10.15 1,400.00 10.20\n256 SAHAS 676.00 12.00 1.81 664.00 679.90 664.00 186,064.00 664.00\n257 SAIL 1,158.00 10.00 0.87 1,148.00 1,173.00 1,148.00 22,164.00 1,148.00\n258 SALICO 595.00 5.00 0.85 595.00 611.00 593.00 8,584.00 590.00\n259 SAND2085 1,124.30 0.30 0.03 1,124.30 1,124.30 1,124.30 3.00 1,124.00\n260 SANIMA 368.00 2.50 0.68 370.00 387.50 365.60 127,867.00 365.50\n261 SANVI 741.00 2.00 0.27 702.10 760.00 702.10 27,219.00 739.00\n262 SAPDBL 804.00 1.10 0.14 795.00 814.90 795.00 15,724.00 802.90\n263 SARBTM 866.00 11.00 1.29 858.80 869.90 858.10 8,768.00 855.00\n264 SBCF 9.70 -0.20 -2.02 9.65 9.70 9.65 2,700.00 9.90\n265 SBI 400.00 -5.00 -1.23 396.00 404.00 396.00 8,990.00 405.00\n266 SBID83 1,064.00 -1.00 -0.09 1,065.30 1,065.40 1,063.00 911.00 1,065.00\n267 SBL 399.90 -1.00 -0.25 402.00 403.00 399.00 83,418.00 400.90\n268 SCB 657.00 3.80 0.58 664.30 664.30 653.10 10,330.00 653.20\n269 SEF 10.11 -0.29 -2.79 10.11 10.11 10.11 3,200.00 10.40\n270 SFCL 380.00 10.00 2.70 371.00 380.50 367.30 12,264.00 370.00\n271 SFEF 10.14 0.01 0.10 10.13 10.30 10.13 2,500.00 10.13\n272 SGHC 382.50 2.50 0.66 382.00 385.00 372.00 8,285.00 380.00\n273 SGIC 465.70 1.70 0.37 471.00 471.00 461.00 5,074.00 464.00\n274 SHEL 324.00 6.00 1.89 315.00 325.00 315.00 168,119.00 318.00\n275 SHINE 415.30 3.30 0.80 414.90 415.90 412.50 12,218.00 412.00\n276 SHIVM 693.00 6.10 0.89 684.00 695.00 684.00 129,127.00 686.90\n277 SHL 505.00 4.90 0.98 501.50 509.00 500.00 28,302.00 500.10\n278 SHLB 1,465.10 -4.90 -0.33 1,480.00 1,480.00 1,465.00 30.00 1,470.00\n279 SHPC 527.00 5.30 1.02 533.00 533.00 521.00 48,995.00 521.70\n280 SICL 619.00 1.20 0.19 624.00 624.00 613.00 6,661.00 617.80\n281 SIFC 546.00 5.00 0.92 540.00 548.00 535.30 3,880.00 541.00\n282 SIGS2 10.50 -0.32 -2.96 10.50 10.50 10.50 1,000.00 10.82\n283 SIGS3 10.80 -0.06 -0.55 10.66 10.80 10.66 1,200.00 10.86\n284 SIKLES 610.00 10.00 1.67 605.00 610.00 600.00 13,268.00 600.00\n285 SINDU 725.00 5.00 0.69 713.10 730.00 713.10 4,172.00 720.00\n286 SIPD 850.00 35.00 4.29 815.00 860.00 810.00 38,182.00 815.00\n287 SJCL 305.00 -1.90 -0.62 302.00 312.60 302.00 64,025.00 306.90\n288 SJLIC 435.00 4.00 0.93 429.00 438.00 429.00 11,535.00 431.00\n289 SKBBL 771.00 6.00 0.78 791.00 791.00 769.00 19,042.00 765.00\n290 SKHEL 1,315.10 37.10 2.90 1,290.00 1,348.70 1,278.00 16,592.00 1,278.00\n291 SKHL 1,030.00 80.00 8.42 970.00 1,040.30 955.00 54,192.00 950.00\n292 SLBBL 831.00 8.30 1.01 825.00 836.40 821.10 5,082.00 822.70\n293 SLBSL 1,188.00 8.00 0.68 1,180.00 1,205.00 1,180.00 1,014.00 1,180.00\n294 SLCF 10.02 0.02 0.20 10.30 10.30 10.01 3,000.00 10.00\n295 SMATA 771.00 1.00 0.13 770.00 775.00 765.00 5,467.00 770.00\n296 SMB 1,762.10 21.10 1.21 1,788.00 1,790.00 1,751.00 574.00 1,741.00\n297 SMFBS 1,514.00 -21.00 -1.37 1,513.30 1,525.10 1,502.00 1,458.00 1,535.00\n298 SMH 598.50 4.50 0.76 594.00 600.00 585.20 8,057.00 594.00\n299 SMHL 506.00 7.00 1.40 500.10 508.00 500.10 32,216.00 499.00\n300 SMJC 489.00 1.10 0.23 463.60 499.00 463.60 52,921.00 487.90\n301 SMPDA 844.00 6.00 0.72 838.00 854.00 838.00 1,606.00 838.

In [19]:
# /html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[3]/div[3]/div/div[2]/div/div/div/div/div[2]/table/thead/tr/th[9]
act_data=data.split("\n")[1:]
act_data

['1 ACLBSL 967.00 18.00 1.90 977.40 977.40 954.00 470.00 949.00',
 '2 ADBL 315.30 2.30 0.73 317.90 318.50 312.30 41,552.00 313.00',
 '3 ADBLD83 1,051.90 -18.10 -1.69 1,051.90 1,051.90 1,051.90 25.00 1,070.00',
 '4 AHL 506.00 -9.00 -1.75 505.00 518.50 504.00 14,648.00 515.00',
 '5 AHPC 289.00 5.00 1.76 275.00 289.00 275.00 83,890.00 284.00',
 '6 AKJCL 417.80 15.80 3.93 402.00 420.00 402.00 1,278,371.00 402.00',
 '7 AKPL 277.80 3.30 1.20 275.00 278.80 271.00 171,946.00 274.50',
 '8 ALBSL 1,123.00 8.00 0.72 1,086.00 1,125.00 1,086.00 6,362.00 1,115.00',
 '9 ALICL 455.30 3.00 0.66 459.90 459.90 452.00 7,840.00 452.30',
 '10 ANLB 5,996.00 95.00 1.61 5,801.00 5,996.00 5,733.00 867.00 5,901.00',
 '11 API 360.80 3.60 1.01 359.00 363.00 357.20 429,359.00 357.20',
 '12 AVYAN 1,146.00 7.00 0.61 1,082.10 1,159.00 1,082.10 4,714.00 1,139.00',
 '13 BANDIPUR 865.00 -10.90 -1.24 910.00 910.00 855.00 56,430.00 875.90',
 '14 BARUN 357.40 6.30 1.79 352.00 359.00 351.00 34,727.00 351.10',
 '15 BBC 4,822.00 22.00 0.46 4,818.90 4,832.90 4,766.10 182.00 4,800.00',
 '16 BEDC 383.60 6.70 1.78 395.70 395.70 377.30 39,932.00 376.90',
 '17 BFC 462.40 4.40 0.96 464.00 469.00 460.10 12,243.00 458.00',
 '18 BGWT 666.40 5.40 0.82 665.00 674.00 665.00 1,017.00 661.00',
 '19 BHCL 596.00 30.00 5.30 566.00 604.90 566.00 108,733.00 566.00',
 '20 BHDC 478.10 14.50 3.13 461.20 480.00 461.20 40,973.00 463.60',
 '21 BHL 228.70 2.70 1.19 237.00 237.00 225.00 161,537.00 226.00',
 '22 BHPL 533.20 3.40 0.64 530.10 537.80 530.00 4,458.00 529.80',
 '23 BJHL 989.00 36.00 3.78 952.00 1,000.00 945.00 14,617.00 953.00',
 '24 BNHC 337.10 4.00 1.20 333.10 343.00 332.00 7,278.00 333.10',
 '25 BNL 14,819.00 431.90 3.00 14,818.70 14,819.00 14,818.70 20.00 14,387.10',
 '26 BNT 11,890.00 299.40 2.58 11,590.00 11,900.00 11,590.00 50.00 11,590.60',
 '27 BPCL 705.00 6.00 0.86 699.00 709.00 680.00 51,676.00 699.00',
 '28 BUNGAL 734.00 -80.00 -9.83 773.30 773.30 706.00 78,697.00 814.00',
 '29 C30MF 10.00 0.17 1.73 9.89 10.20 9.89 11,500.00 9.83',
 '30 CBBL 923.00 6.00 0.65 924.30 924.30 918.00 14,775.00 917.00',
 '31 CFCL 504.00 1.00 0.20 510.00 510.00 496.00 5,723.00 503.00',
 '32 CGH 803.00 -0.80 -0.10 799.00 814.70 795.00 28,593.00 803.80',
 '33 CHCL 489.90 7.90 1.64 482.50 490.00 482.50 67,158.00 482.00',
 '34 CHDC 2,313.00 13.00 0.57 2,300.00 2,328.00 2,286.00 10,817.00 2,300.00',
 '35 CHL 299.00 2.00 0.67 288.10 302.00 288.10 43,600.00 297.00',
 '36 CIT 1,773.80 6.80 0.38 1,767.00 1,789.90 1,765.00 4,119.00 1,767.00',
 '37 CITY 377.00 6.00 1.62 374.00 383.90 373.00 119,087.00 371.00',
 '38 CKHL 677.50 3.60 0.53 658.00 688.00 658.00 578.00 673.90',
 '39 CLI 458.00 6.00 1.33 452.00 459.80 452.00 17,291.00 452.00',
 '40 CMF2 10.01 -0.13 -1.28 10.00 10.25 10.00 2,620.00 10.14',
 '41 CORBL 2,010.00 -56.00 -2.71 2,050.00 2,079.00 2,000.00 14,937.00 2,066.00',
 '42 CREST 1,240.00 -78.00 -5.92 1,252.10 1,260.00 1,143.00 21,491.00 1,318.00',
 '43 CSY 9.45 0.00 0.00 9.17 9.47 9.17 5,290.00 9.45',
 '44 CYCL 1,484.70 14.60 0.99 1,482.00 1,485.00 1,463.00 373.00 1,470.10',
 '45 CZBIL 209.10 1.60 0.77 197.20 210.40 197.20 46,684.00 207.50',
 '46 DDBL 855.00 2.00 0.23 859.00 870.00 853.00 6,122.00 853.00',
 '47 DHEL 672.40 4.30 0.64 650.00 684.90 650.00 44,779.00 668.10',
 '48 DHPL 304.00 2.00 0.66 303.00 311.00 303.00 3,251.00 302.00',
 '49 DLBS 1,281.10 6.10 0.48 1,271.00 1,295.00 1,271.00 258.00 1,275.00',
 '50 DOLTI 363.00 4.10 1.14 341.00 364.90 341.00 48,936.00 358.90',
 '51 DORDI 283.50 6.00 2.16 277.10 287.90 277.10 53,943.00 277.50',
 '52 EBL 711.00 1.00 0.14 719.90 719.90 710.30 26,329.00 710.00',
 '53 EBLD85 1,197.00 -1.00 -0.08 1,197.00 1,197.00 1,197.00 10.00 1,198.00',
 '54 EBLD91 1,081.00 -4.00 -0.37 1,081.10 1,081.10 1,081.00 100.00 1,085.00',
 '55 EDBL 587.10 7.10 1.22 583.00 595.00 583.00 4,358.00 580.00',
 '56 EHPL 400.20 5.70 1.44 395.00 402.50 395.00 22,372.00 394.50',
 '57 ENL 903.00 5.00 0.56 912.30 912.30 887.20 533.00 898.00',
 '58 FMDBL 797.00 9.70 1.23 792.00 799.00 792.00 11,070.00 787.30',
 '59 FOWAD 1,050.10 6.10 0.58 1,068.90 1,068.90 1,047.00 2,184.00 1,044.00',
 '60 GBBL 421.60 0.60 0.14 421.00 425.00 420.00 28,164.00 421.00',
 '61 GBILD86/87 1,086.00 5.90 0.55 1,086.00 1,086.00 1,086.00 25.00 1,080.10',
 '62 GBIME 238.90 2.10 0.89 236.00 239.00 235.20 62,203.00 236.80',
 '63 GBIMESY2 9.57 0.26 2.79 9.31 9.58 9.25 4,300.00 9.31',
 '64 GBLBS 779.00 3.10 0.40 788.00 788.00 766.00 3,269.00 775.90',
 '65 GCIL 435.00 11.00 2.59 418.20 435.00 418.00 60,458.00 424.00',
 '66 GFCL 631.10 -3.90 -0.61 635.00 643.00 630.20 5,277.00 635.00',
 '67 GHL 245.90 3.90 1.61 245.00 247.90 241.30 66,641.00 242.00',
 '68 GIBF1 11.00 0.00 0.00 10.90 11.33 10.90 6,100.00 11.00',
 '69 GILB 1,155.00 25.00 2.21 1,125.00 1,157.00 1,125.00 990.00 1,130.00',
 '70 GLBSL 1,830.00 21.00 1.16 1,830.00 1,850.00 1,805.00 232.00 1,809.00',
 '71 GLH 277.50 3.50 1.28 274.00 279.00 274.00 47,553.00 274.00',
 '72 GMFBS 1,285.10 -0.90 -0.07 1,261.00 1,315.00 1,261.00 1,237.00 1,286.00',
 '73 GMFIL 475.90 6.00 1.28 479.90 479.90 466.40 1,570.00 469.90',
 '74 GMLI 1,279.00 9.10 0.72 1,270.00 1,300.00 1,261.00 3,192.00 1,269.90',
 '75 GRDBL 1,096.50 -13.50 -1.22 1,061.10 1,129.90 1,061.10 9,289.00 1,110.00',
 '76 GSY 10.00 0.00 0.00 9.99 10.10 9.91 72,200.00 10.00',
 '77 GUFL 540.00 5.00 0.93 520.00 544.80 520.00 7,738.00 535.00',
 '78 GVL 495.50 3.60 0.73 492.00 500.00 492.00 12,681.00 491.90',
 '79 H8020 12.01 0.03 0.25 12.33 12.33 11.81 21,735.00 11.98',
 '80 HATHY 805.00 6.00 0.75 810.90 810.90 803.00 2,755.00 799.00',
 '81 HBL 206.10 3.10 1.53 202.00 207.00 200.80 53,929.00 203.00',
 '82 HBLD83 1,065.00 29.00 2.80 1,036.00 1,065.00 1,036.00 45.00 1,036.00',
 '83 HDHPC 233.50 2.80 1.21 230.70 236.00 230.70 197,364.00 230.70',
 '84 HDL 1,171.90 4.00 0.34 1,180.00 1,180.00 1,168.00 19,914.00 1,167.90',
 '85 HEI 533.20 -2.70 -0.50 535.00 583.00 533.00 8,419.00 535.90',
 '86 HEIP 326.00 6.00 1.88 328.90 328.90 326.00 599.00 320.00',
 '87 HFIN 1,024.00 24.00 2.40 985.00 1,042.00 985.00 70,467.00 1,000.00',
 '88 HHL 377.00 -1.00 -0.26 396.90 396.90 376.00 64,136.00 378.00',
 '89 HIDCL 274.90 3.40 1.25 270.00 276.80 270.00 71,736.00 271.50',
 '90 HIDCLP 210.00 2.70 1.30 209.20 210.70 207.40 169,639.00 207.30',
 '91 HIMSTAR 908.00 -10.00 -1.09 900.00 929.50 900.00 7,807.00 918.00',
 '92 HLBSL 900.00 2.00 0.22 910.00 920.00 893.00 622.00 898.00',
 '93 HLI 342.20 2.40 0.71 344.00 344.30 340.00 38,472.00 339.80',
 '94 HLICF 9.00 0.13 1.47 9.10 9.12 8.90 40,060.00 8.87',
 '95 HPPL 385.10 4.10 1.08 381.30 388.00 381.00 12,833.00 381.00',
 '96 HRL 652.10 10.70 1.67 641.00 661.00 640.50 106,053.00 641.40',
 '97 HURJA 267.90 4.90 1.86 262.00 269.00 262.00 75,441.00 263.00',
 '98 ICFC 637.00 6.00 0.95 630.90 639.50 629.00 6,510.00 631.00',
 '99 ICFCD88 1,145.00 -5.00 -0.43 1,145.00 1,145.00 1,145.00 25.00 1,150.00',
 '100 ICFCD89 1,090.00 -9.00 -0.82 1,081.00 1,095.00 1,081.00 125.00 1,099.00',
 '101 IGI 438.10 8.10 1.88 439.90 439.90 431.80 8,904.00 430.00',
 '102 IHL 443.00 1.00 0.23 442.00 451.10 425.00 112,943.00 442.00',
 '103 ILBS 940.00 0.10 0.01 935.00 947.20 920.10 3,288.00 939.90',
 '104 ILI 442.00 2.10 0.48 437.00 444.00 437.00 5,940.00 439.90',
 '105 JBBL 367.00 5.50 1.52 343.50 367.90 343.50 30,802.00 361.50',
 '106 JBLB 1,310.00 8.00 0.61 1,305.00 1,325.00 1,305.00 2,812.00 1,302.00',
 '107 JFL 414.50 6.50 1.59 409.00 414.90 409.00 2,169.00 408.00',
 '108 JHAPA 1,492.00 -7.00 -0.47 1,480.00 1,543.70 1,438.00 23,875.00 1,499.00',
 '109 JOSHI 288.00 3.50 1.23 282.10 290.00 282.10 14,635.00 284.50',
 '110 JSLBB 1,084.10 -5.00 -0.46 1,078.50 1,084.10 1,078.10 101.00 1,089.10',
 '111 KBL 223.40 4.70 2.15 220.00 224.00 219.00 259,047.00 218.70',
 '112 KBSH 1,500.00 0.00 0.00 1,470.20 1,500.20 1,470.20 280.00 1,500.00',
 '113 KDBY 11.65 0.20 1.75 11.41 11.70 11.41 278,200.00 11.45',
 '114 KDL 834.00 7.20 0.87 850.00 850.00 812.00 1,582.00 826.80',
 '115 KEF 10.81 0.06 0.56 10.75 10.81 10.72 12,900.00 10.75',
 '116 KKHC 271.50 5.40 2.03 273.50 273.50 266.00 51,459.00 266.10',
 '117 KMCDB 861.20 1.20 0.14 860.00 869.00 855.00 1,147.00 860.00',
 '118 KPCL 501.50 8.00 1.62 490.00 502.00 490.00 8,128.00 493.50',
 '119 KSBBL 489.90 7.80 1.62 484.00 490.00 484.00 35,926.00 482.10',
 '120 KSBBLD87 1,132.00 1.00 0.09 1,132.00 1,132.00 1,132.00 25.00 1,131.00',
 '121 KSBBLP 269.00 0.00 0.00 269.00 269.00 269.00 14,079.00 269.00',
 '122 KSY 9.90 0.10 1.02 9.80 9.90 9.61 21,900.00 9.80',
 '123 LBBL 495.50 4.50 0.92 498.10 498.10 491.00 32,203.00 491.00',
 '124 LEC 236.90 3.90 1.67 222.00 237.90 222.00 111,358.00 233.00',
 '125 LICN 822.00 9.00 1.11 829.00 829.00 813.00 3,955.00 813.00',
 '126 LLBS 937.20 -20.80 -2.17 958.00 965.00 937.20 820.00 958.00',
 '127 LSL 225.50 -0.40 -0.18 215.00 244.00 215.00 84,240.00 225.90',
 '128 LUK 10.00 0.05 0.50 9.95 10.20 9.95 5,825.00 9.95',
 '129 LVF2 10.19 0.19 1.90 9.80 10.19 9.80 4,600.00 10.00',
 '130 MABEL 755.00 -5.00 -0.66 760.00 782.00 747.00 30,326.00 760.00',
 '131 MAKAR 508.00 -1.70 -0.33 535.10 535.10 504.00 8,703.00 509.70',
 '132 MANDU 830.00 11.10 1.36 815.00 830.00 815.00 1,007.00 818.90',
 '133 MATRI 891.00 -4.00 -0.45 881.00 913.00 880.00 518.00 895.00',
 '134 MBJC 289.80 3.80 1.33 286.00 292.00 281.30 24,276.00 286.00',
 '135 MBL 254.90 2.00 0.79 253.70 256.80 253.70 84,848.00 252.90',
 '136 MBLD2085 1,200.00 -35.00 -2.83 1,200.00 1,200.00 1,200.00 100.00 1,235.00',
 '137 MBLEF 10.00 -0.05 -0.50 9.93 10.21 9.93 6,009.00 10.05',
 '138 MCHL 320.10 -2.80 -0.87 323.00 329.90 313.40 23,615.00 322.90',
 '139 MDB 613.20 -1.40 -0.23 615.00 618.00 612.20 12,000.00 614.60',
 '140 MEHL 385.10 5.10 1.34 379.00 390.00 379.00 2,302.00 380.00',
 '141 MEL 244.00 5.90 2.48 238.00 245.00 235.10 22,153.00 238.10',
 '142 MEN 608.00 4.00 0.66 610.00 615.00 606.50 65,116.00 604.00',
 '143 MERO 720.80 2.80 0.39 732.90 733.00 720.00 3,873.00 718.00',
 '144 MFIL 799.80 -2.20 -0.27 785.00 804.80 785.00 15,660.00 802.00',
 '145 MHCL 362.00 -6.90 -1.87 370.00 372.00 362.00 5,159.00 368.90',
 '146 MHL 508.70 8.70 1.74 500.00 510.00 498.50 10,263.00 500.00',
 '147 MHNL 272.10 2.10 0.78 268.00 276.00 268.00 5,702.00 270.00',
 '148 MKCL 1,299.00 11.00 0.85 1,290.00 1,310.00 1,272.10 1,085.00 1,288.00',
 '149 MKHC 338.00 18.00 5.62 320.00 342.90 320.00 58,806.00 320.00',
 '150 MKHL 553.10 8.10 1.49 523.10 574.80 523.10 7,393.00 545.00',
 '151 MKJC 497.10 7.10 1.45 500.00 501.60 493.20 4,090.00 490.00',
 '152 MLBBL 1,189.00 -9.00 -0.75 1,220.00 1,220.00 1,183.00 2,549.00 1,198.00',
 '153 MLBL 370.00 4.10 1.12 369.90 370.90 367.30 14,685.00 365.90',
 '154 MLBS 1,270.10 -8.90 -0.70 1,250.00 1,300.00 1,250.00 190.00 1,279.00',
 '155 MLBSL 1,820.00 20.00 1.11 1,790.00 1,820.00 1,790.00 454.00 1,800.00',
 '156 MMF1 9.45 -0.14 -1.46 9.70 9.70 9.39 4,705.00 9.59',
 '157 MMKJL 512.40 11.40 2.28 494.00 515.00 494.00 2,234.00 501.00',
 '158 MNBBL 377.40 4.50 1.21 374.30 379.00 374.00 28,233.00 372.90',
 '159 MNMF1 10.00 0.00 0.00 9.90 10.00 9.90 22,006.00 10.00',
 '160 MPFL 628.00 8.50 1.37 624.90 629.00 613.00 4,951.00 619.50',
 '161 MSHL 707.00 12.00 1.73 695.00 707.00 686.00 703.00 695.00',
 '162 MSLB 1,242.00 2.00 0.16 1,272.00 1,272.00 1,235.00 1,440.00 1,240.00',
 '163 NABBC 957.00 7.00 0.74 930.00 968.00 930.00 4,939.00 950.00',
 '164 NABIL 535.10 5.10 0.96 530.00 536.00 530.00 53,893.00 530.00',
 '165 NABILD2089 1,095.10 -4.90 -0.45 1,125.00 1,133.00 1,095.10 335.00 1,100.00',
 '166 NADEP 757.00 12.00 1.61 741.00 763.20 735.40 940.00 745.00',
 '167 NBF2 9.92 -0.03 -0.30 9.95 10.10 9.90 5,950.00 9.95',
 '168 NBF3 9.96 0.01 0.10 9.95 9.96 9.95 4,700.00 9.95',
 '169 NBL 273.90 8.60 3.24 252.10 276.00 252.10 121,606.00 265.30',
 '170 NBLD85 1,081.00 28.90 2.75 1,079.50 1,081.00 1,079.50 50.00 1,052.10',
 '171 NBLD87 1,091.30 -33.70 -3.00 1,091.30 1,091.30 1,091.30 25.00 1,125.00',
 '172 NESDO 1,555.00 31.00 2.03 1,535.10 1,569.00 1,535.00 1,140.00 1,524.00',
 '173 NFS 577.00 7.00 1.23 584.00 584.00 570.00 9,009.00 570.00',
 '174 NGPL 459.20 7.70 1.71 435.00 462.00 435.00 290,990.00 451.50',
 '175 NHDL 644.00 7.10 1.11 636.90 646.00 636.90 144.00 636.90',
 '176 NHPC 297.60 2.60 0.88 309.70 309.70 295.00 385,906.00 295.00',
 '177 NIBD84 1,052.10 2.00 0.19 1,052.10 1,052.10 1,052.10 25.00 1,050.10',
 '178 NIBLGF 9.50 -0.41 -4.14 9.62 9.62 9.42 1,000.00 9.91',
 '179 NIBLSTF 9.21 -0.08 -0.86 9.13 9.35 9.13 2,400.00 9.29',
 '180 NIBSF2 9.25 -0.10 -1.07 9.14 9.41 9.14 4,710.00 9.35',
 '181 NICA 356.00 3.50 0.99 365.00 365.00 345.00 32,546.00 352.50',
 '182 NICAD2091 1,053.60 1.40 0.13 1,053.60 1,053.60 1,053.60 25.00 1,052.20',
 '183 NICBF 9.68 0.28 2.98 9.68 9.68 9.68 100.00 9.40',
 '184 NICD88 1,110.00 32.00 2.97 1,110.00 1,110.00 1,110.00 25.00 1,078.00',
 '185 NICFC 9.35 -0.05 -0.53 9.17 9.53 9.17 1,800.00 9.40',
 '186 NICGF2 9.50 -0.14 -1.45 9.92 9.92 9.40 1,600.00 9.64',
 '187 NICL 507.00 10.00 2.01 500.00 507.00 497.00 9,198.00 497.00',
 '188 NICLBSL 587.10 13.10 2.28 574.00 599.40 574.00 8,122.00 574.00',
 '189 NICSF 9.20 -0.09 -0.97 9.39 9.39 9.11 1,800.00 9.29',
 '190 NIFRA 267.00 0.20 0.07 266.10 270.00 266.00 89,532.00 266.80',
 '191 NIFRAGED 1,040.10 4.80 0.46 1,035.50 1,040.10 1,035.50 75.00 1,035.30',
 '192 NIL 625.00 11.00 1.79 610.00 625.00 610.00 4,080.00 614.00',
 '193 NIMB 201.00 3.00 1.52 199.00 202.00 198.00 122,308.00 198.00',
 '194 NIMBD90 1,245.00 -4.00 -0.32 1,245.00 1,245.00 1,245.00 25.00 1,249.00',
 '195 NIMBPO 152.70 1.20 0.79 151.50 152.70 151.50 218.00 151.50',
 '196 NLG 583.00 8.00 1.39 582.00 590.00 580.00 7,702.00 575.00',
 '197 NLIC 778.00 8.20 1.07 770.00 779.80 765.00 10,282.00 769.80',
 '198 NLICL 592.00 1.00 0.17 595.80 595.80 586.20 3,396.00 591.00',
 '199 NMB 249.00 0.40 0.16 248.00 251.00 247.00 16,541.00 248.60',
 '200 NMBD87/88 1,090.50 0.00 0.00 1,090.50 1,090.50 1,090.50 25.00 1,090.50',
 '201 NMBHF2 9.70 0.03 0.31 9.60 9.70 9.60 21,700.00 9.67',
 '202 NMBMF 653.00 21.00 3.32 633.10 655.00 633.10 2,332.00 632.00',
 '203 NMFBS 1,145.00 5.00 0.44 1,117.00 1,155.00 1,117.00 7,073.00 1,140.00',
 '204 NMIC 1,058.00 33.00 3.22 1,040.00 1,059.80 1,025.00 6,426.00 1,025.00',
 '205 NMLBBL 592.00 4.00 0.68 571.00 593.90 571.00 3,818.00 588.00',
 '206 NRIC 922.10 14.00 1.54 914.10 924.70 911.00 8,440.00 908.10',
 '207 NRM 383.90 19.80 5.44 345.90 388.00 345.90 34,194.00 364.10',
 '208 NRN 1,406.70 7.70 0.55 1,425.00 1,440.00 1,387.00 46,582.00 1,399.00',
 '209 NSIF2 10.72 -0.03 -0.28 10.60 10.75 10.60 3,100.00 10.75',
 '210 NSY 9.63 -0.05 -0.52 9.44 9.63 9.44 6,970.00 9.68',
 '211 NTC 898.00 7.60 0.85 890.00 899.90 888.50 14,108.00 890.40',
 '212 NUBL 657.10 -2.90 -0.44 665.00 665.00 656.00 2,925.00 660.00',
 '213 NWCL 816.00 12.00 1.49 803.00 818.90 803.00 1,160.00 804.00',
 '214 NYADI 400.00 8.90 2.28 399.90 401.00 391.00 4,545.00 391.10',
 '215 OHL 701.00 8.60 1.24 708.00 712.00 700.00 2,389.00 692.40',
 '216 OMPL 1,187.00 7.00 0.59 1,190.00 1,210.00 1,185.10 4,897.00 1,180.00',
 '217 PBD84 1,140.00 0.00 0.00 1,140.00 1,140.00 1,140.00 35.00 1,140.00',
 '218 PBD85 1,081.00 1.00 0.09 1,081.00 1,081.00 1,081.00 25.00 1,080.00',
 '219 PBLD84 1,085.10 -3.00 -0.28 1,085.10 1,085.10 1,085.10 50.00 1,088.10',
 '220 PCBL 243.60 3.10 1.29 240.50 244.70 239.00 49,235.00 240.50',
 '221 PCIL 854.00 27.00 3.26 827.00 860.00 815.00 58,524.00 827.00',
 '222 PFL 377.90 2.90 0.77 379.00 379.00 370.00 3,256.00 375.00',
 '223 PHCL 312.00 2.80 0.91 308.00 315.00 308.00 44,639.00 309.20',
 '224 PMHPL 350.90 8.90 2.60 343.90 352.00 343.00 15,670.00 342.00',
 '225 PMLI 470.20 0.20 0.04 470.00 475.00 462.50 2,651.00 470.00',
 '226 PPCL 392.00 12.00 3.16 380.00 393.90 378.00 9,922.00 380.00',
 '227 PPL 366.00 12.00 3.39 357.00 369.90 357.00 65,705.00 354.00',
 '228 PRIN 665.00 3.00 0.45 669.90 669.90 656.00 3,129.00 662.00',
 '229 PROFL 442.20 -1.80 -0.41 456.00 457.00 442.00 4,112.00 444.00',
 '230 PRSF 12.94 -0.01 -0.08 13.00 13.14 12.94 323,100.00 12.95',
 '231 PRVU 202.20 4.20 2.12 188.10 203.00 188.10 102,733.00 198.00',
 '232 PSF 12.17 -0.04 -0.33 12.01 12.20 12.01 56,350.00 12.21',
 '233 PURE 990.00 5.00 0.51 1,030.00 1,030.00 990.00 18,002.00 985.00',
 '234 RADHI 802.00 19.00 2.43 785.00 805.00 780.00 57,673.00 783.00',
 '235 RAWA 590.00 6.00 1.03 613.00 613.00 575.00 2,354.00 584.00',
 '236 RBBD2088 1,067.00 -18.30 -1.69 1,056.70 1,067.00 1,056.70 50.00 1,085.30',
 '237 RBBF40 9.41 -0.04 -0.42 9.33 9.69 9.33 2,100.00 9.45',
 '238 RBCL 15,292.90 361.90 2.42 14,994.00 15,292.90 14,994.00 70.00 14,931.00',
 '239 RFPL 381.50 5.30 1.41 360.00 382.90 360.00 24,161.00 376.20',
 '240 RHGCL 306.00 8.00 2.68 295.10 306.90 291.00 42,841.00 298.00',
 '241 RHPL 283.10 4.10 1.47 279.00 285.00 278.00 18,173.00 279.00',
 '242 RIDI 373.00 6.30 1.72 368.00 378.10 365.10 579,596.00 366.70',
 '243 RLEL 1,085.00 58.10 5.66 1,026.00 1,098.00 1,026.00 24,873.00 1,026.90',
 '244 RLFL 445.00 6.10 1.39 430.00 447.00 430.00 15,536.00 438.90',
 '245 RMF1 9.88 -0.12 -1.20 9.85 10.00 9.85 3,400.00 10.00',
 '246 RMF2 10.20 -0.30 -2.86 10.20 10.20 10.20 2,700.00 10.50',
 '247 RNLI 470.10 5.10 1.10 466.00 471.00 461.00 30,761.00 465.00',
 '248 RSDC 673.50 5.70 0.85 674.00 680.00 665.00 3,791.00 667.80',
 '249 RSML 3,830.00 100.00 2.68 3,700.00 3,850.00 3,700.00 31,065.00 3,730.00',
 '250 RSY 10.15 -0.20 -1.93 10.04 10.45 10.04 14,000.00 10.35',
 '251 RURU 663.00 3.00 0.45 670.00 670.00 655.00 5,250.00 660.00',
 '252 SABBL 1,279.00 32.00 2.57 1,250.00 1,285.00 1,242.10 9,055.00 1,247.00',
 '253 SADBL 420.90 4.90 1.18 416.00 421.50 416.00 17,364.00 416.00',
 '254 SAGAR 1,742.20 25.20 1.47 1,722.00 1,757.00 1,722.00 6,136.00 1,717.00',
 '255 SAGF 10.20 0.00 0.00 10.15 10.20 10.15 1,400.00 10.20',
 '256 SAHAS 676.00 12.00 1.81 664.00 679.90 664.00 186,064.00 664.00',
 '257 SAIL 1,158.00 10.00 0.87 1,148.00 1,173.00 1,148.00 22,164.00 1,148.00',
 '258 SALICO 595.00 5.00 0.85 595.00 611.00 593.00 8,584.00 590.00',
 '259 SAND2085 1,124.30 0.30 0.03 1,124.30 1,124.30 1,124.30 3.00 1,124.00',
 '260 SANIMA 368.00 2.50 0.68 370.00 387.50 365.60 127,867.00 365.50',
 '261 SANVI 741.00 2.00 0.27 702.10 760.00 702.10 27,219.00 739.00',
 '262 SAPDBL 804.00 1.10 0.14 795.00 814.90 795.00 15,724.00 802.90',
 '263 SARBTM 866.00 11.00 1.29 858.80 869.90 858.10 8,768.00 855.00',
 '264 SBCF 9.70 -0.20 -2.02 9.65 9.70 9.65 2,700.00 9.90',
 '265 SBI 400.00 -5.00 -1.23 396.00 404.00 396.00 8,990.00 405.00',
 '266 SBID83 1,064.00 -1.00 -0.09 1,065.30 1,065.40 1,063.00 911.00 1,065.00',
 '267 SBL 399.90 -1.00 -0.25 402.00 403.00 399.00 83,418.00 400.90',
 '268 SCB 657.00 3.80 0.58 664.30 664.30 653.10 10,330.00 653.20',
 '269 SEF 10.11 -0.29 -2.79 10.11 10.11 10.11 3,200.00 10.40',
 '270 SFCL 380.00 10.00 2.70 371.00 380.50 367.30 12,264.00 370.00',
 '271 SFEF 10.14 0.01 0.10 10.13 10.30 10.13 2,500.00 10.13',
 '272 SGHC 382.50 2.50 0.66 382.00 385.00 372.00 8,285.00 380.00',
 '273 SGIC 465.70 1.70 0.37 471.00 471.00 461.00 5,074.00 464.00',
 '274 SHEL 324.00 6.00 1.89 315.00 325.00 315.00 168,119.00 318.00',
 '275 SHINE 415.30 3.30 0.80 414.90 415.90 412.50 12,218.00 412.00',
 '276 SHIVM 693.00 6.10 0.89 684.00 695.00 684.00 129,127.00 686.90',
 '277 SHL 505.00 4.90 0.98 501.50 509.00 500.00 28,302.00 500.10',
 '278 SHLB 1,465.10 -4.90 -0.33 1,480.00 1,480.00 1,465.00 30.00 1,470.00',
 '279 SHPC 527.00 5.30 1.02 533.00 533.00 521.00 48,995.00 521.70',
 '280 SICL 619.00 1.20 0.19 624.00 624.00 613.00 6,661.00 617.80',
 '281 SIFC 546.00 5.00 0.92 540.00 548.00 535.30 3,880.00 541.00',
 '282 SIGS2 10.50 -0.32 -2.96 10.50 10.50 10.50 1,000.00 10.82',
 '283 SIGS3 10.80 -0.06 -0.55 10.66 10.80 10.66 1,200.00 10.86',
 '284 SIKLES 610.00 10.00 1.67 605.00 610.00 600.00 13,268.00 600.00',
 '285 SINDU 725.00 5.00 0.69 713.10 730.00 713.10 4,172.00 720.00',
 '286 SIPD 850.00 35.00 4.29 815.00 860.00 810.00 38,182.00 815.00',
 '287 SJCL 305.00 -1.90 -0.62 302.00 312.60 302.00 64,025.00 306.90',
 '288 SJLIC 435.00 4.00 0.93 429.00 438.00 429.00 11,535.00 431.00',
 '289 SKBBL 771.00 6.00 0.78 791.00 791.00 769.00 19,042.00 765.00',

In [20]:
import pandas as pd
dfs=pd.DataFrame(act_data)
dfs

                                                     0
0    1 ACLBSL 967.00 18.00 1.90 977.40 977.40 954.0...
1    2 ADBL 315.30 2.30 0.73 317.90 318.50 312.30 4...
2    3 ADBLD83 1,051.90 -18.10 -1.69 1,051.90 1,051...
3    4 AHL 506.00 -9.00 -1.75 505.00 518.50 504.00 ...
4    5 AHPC 289.00 5.00 1.76 275.00 289.00 275.00 8...
..                                                 ...
334  335 USHL 634.00 9.00 1.44 630.00 640.00 617.20...
335  336 USLB 1,280.00 24.00 1.91 1,260.00 1,281.00...
336  337 VLBS 701.00 6.10 0.88 691.20 708.00 691.20...
337  338 VLUCL 500.00 0.00 0.00 514.70 514.70 495.0...
338  339 WNLB 1,465.00 -15.00 -1.01 1,499.00 1,499....

[339 rows x 1 columns]

In [14]:
dfs[0].str.split(expand=True)

,0,1,2,3,4,5,6,7,8,9
0,1,ACLBSL,967.00,18.00,1.90,977.40,977.40,954.00,470.00,949.00
1,2,ADBL,315.30,2.30,0.73,317.90,318.50,312.30,"41,552.00",313.00
2,3,ADBLD83,"1,051.90",-18.10,-1.69,"1,051.90","1,051.90","1,051.90",25.00,"1,070.00"
3,4,AHL,506.00,-9.00,-1.75,505.00,518.50,504.00,"14,648.00",515.00
4,5,AHPC,289.00,5.00,1.76,275.00,289.00,275.00,"83,890.00",284.00
...,...,...,...,...,...,...,...,...,...,...
334,335,USHL,634.00,9.00,1.44,630.00,640.00,617.20,538.00,625.00
335,336,USLB,"1,280.00",24.00,1.91,"1,260.00","1,281.00","1,260.00","2,614.00","1,256.00"
336,337,VLBS,701.00,6.10,0.88,691.20,708.00,691.20,"2,183.00",694.90
337,338,VLUCL,500.00,0.00,0.00,514.70,514.70,495.00,"2,523.00",500.00
338,339,WNLB,"1,465.00",-15.00,-1.01,"1,499.00","1,499.00","1,455.00",358.00,"1,480.00"

In [23]:
all_cols=[]
for i in range(1,11):
    cols=driver.find_element(By.XPATH,f"//div[2]//div//div//div//div//div[2]//table//thead//tr//th[{i}]").text
    all_cols.append(cols)
all_cols

['S.No',
 'Symbol',
 'LTP',
 'Point Change',
 '% Change',
 'Open',
 'High',
 'Low',
 'Volume',
 'Prev. Close']

In [24]:
final_dfs=dfs[0].str.split(expand=True)
final_dfs.columns=all_cols
final_dfs

,S.No,Symbol,LTP,Point Change,% Change,Open,High,Low,Volume,Prev. Close
0,1,ACLBSL,967.00,18.00,1.90,977.40,977.40,954.00,470.00,949.00
1,2,ADBL,315.30,2.30,0.73,317.90,318.50,312.30,"41,552.00",313.00
2,3,ADBLD83,"1,051.90",-18.10,-1.69,"1,051.90","1,051.90","1,051.90",25.00,"1,070.00"
3,4,AHL,506.00,-9.00,-1.75,505.00,518.50,504.00,"14,648.00",515.00
4,5,AHPC,289.00,5.00,1.76,275.00,289.00,275.00,"83,890.00",284.00
...,...,...,...,...,...,...,...,...,...,...
334,335,USHL,634.00,9.00,1.44,630.00,640.00,617.20,538.00,625.00
335,336,USLB,"1,280.00",24.00,1.91,"1,260.00","1,281.00","1,260.00","2,614.00","1,256.00"
336,337,VLBS,701.00,6.10,0.88,691.20,708.00,691.20,"2,183.00",694.90
337,338,VLUCL,500.00,0.00,0.00,514.70,514.70,495.00,"2,523.00",500.00
338,339,WNLB,"1,465.00",-15.00,-1.01,"1,499.00","1,499.00","1,455.00",358.00,"1,480.00"

In [22]:
final_dfs

,0,1,2,3,4,5,6,7,8,9
0,1,ACLBSL,967.00,18.00,1.90,977.40,977.40,954.00,470.00,949.00
1,2,ADBL,315.30,2.30,0.73,317.90,318.50,312.30,"41,552.00",313.00
2,3,ADBLD83,"1,051.90",-18.10,-1.69,"1,051.90","1,051.90","1,051.90",25.00,"1,070.00"
3,4,AHL,506.00,-9.00,-1.75,505.00,518.50,504.00,"14,648.00",515.00
4,5,AHPC,289.00,5.00,1.76,275.00,289.00,275.00,"83,890.00",284.00
...,...,...,...,...,...,...,...,...,...,...
334,335,USHL,634.00,9.00,1.44,630.00,640.00,617.20,538.00,625.00
335,336,USLB,"1,280.00",24.00,1.91,"1,260.00","1,281.00","1,260.00","2,614.00","1,256.00"
336,337,VLBS,701.00,6.10,0.88,691.20,708.00,691.20,"2,183.00",694.90
337,338,VLUCL,500.00,0.00,0.00,514.70,514.70,495.00,"2,523.00",500.00
338,339,WNLB,"1,465.00",-15.00,-1.01,"1,499.00","1,499.00","1,455.00",358.00,"1,480.00"

In [ ]:
/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[3]/div[3]/div/div[2]/div/div/div/div/div[2]/table/thead/tr/th[9]

## Creating a Functions

In [38]:
def extract_data():
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.chrome.options import Options
    import time
    from datetime import datetime
    
    options = Options()
    options.add_argument("--headless")
    driver = webdriver.Chrome(options=options)
    driver.get("https://www.sharesansar.com/live-trading")
    time.sleep(5)
    data=driver.find_element(By.ID,"headFixed").text
    act_data=data.split("\n")[1:]
    all_cols=[]
    for i in range(1,11):
        cols=driver.find_element(By.XPATH,f"//div[2]//div//div//div//div//div[2]//table//thead//tr//th[{i}]").text
        all_cols.append(cols)
    final_dfs=dfs[0].str.split(expand=True)
    final_dfs.columns=all_cols
    now =  datetime.now().strftime("%Y-%m-%d_%H-%M-%S") 
    final_dfs.to_csv(f"C:\\Users\\HP\\Desktop\\data_extractions\\seleniums\\extracted_data_pipe_lies\\{now}.csv")

## stopped after 10 Minutes

In [39]:
start_time = time.time()

while True:
    extract_data()
    time.sleep(180)   # run every 3 3 minutes 
    if time.time() - start_time > 10 * 60:
        print("Stopped after 10 minutes")
        break

Stopped after 10 minutes

In [40]:
import pandas as pd

In [41]:
all_company=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\data_fetch_of_all_comoany\cleaned\all_company_ids.csv")

In [44]:
company_share_info=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\data_fetch_of_all_comoany\cleaned\company_share_info.csv")

In [46]:
data1=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\data_fetch_of_all_comoany\cleaned\insights\Stock_Holding_Changes_all_fiscals_year.csv")

In [47]:
data1

,companyId,sectorName,companyName,companySymbol,pricePercentChange,shareNo,marketValue,growthPercent,assetPercent,isListed,fiscal_year,month,fiscalId,fiscalYear,monthName,monthId
0,13,Commercial Banks,Global IME Bank Limited,GBIME,0.68,83000.0,19754000.0,0.00,NaN,True,32,1,NaN,NaN,Baisakh,1
1,50,Commercial Banks,Standard Chartered Bank Limited,SCB,0.49,60000.0,39060000.0,0.00,NaN,True,32,1,NaN,NaN,Baisakh,1
2,44,Commercial Banks,Prime Commercial Bank Limited,PCBL,0.63,20000.0,4910000.0,0.00,NaN,True,32,1,NaN,NaN,Baisakh,1
3,11,Commercial Banks,Everest Bank Limited,EBL,0.03,62448.0,43588704.0,0.00,NaN,True,32,1,NaN,NaN,Baisakh,1
4,27,Commercial Banks,Nabil Bank Limited,NABIL,0.40,23500.0,12455000.0,9.30,NaN,True,32,1,NaN,NaN,Baisakh,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,285,Microfinance,Infinity Laghubitta Bittiya Sanstha Limited,ILBS,0.11,26500.0,25652000.0,1.92,NaN,True,37,12,37.0,2082/2083,Chaitra,12
2236,265,Microfinance,Chhimek Laghubitta Bittiya Sanstha Limited,CBBL,0.22,21000.0,19152000.0,5.00,NaN,True,37,12,37.0,2082/2083,Chaitra,12
2237,982,Mutual Fund,Muktinath Mutual Fund 1,MNMF1,0.00,1017719.0,10034709.0,0.00,NaN,True,37,12,37.0,2082/2083,Chaitra,12
2238,878,Mutual Fund,Siddhartha Investment Growth Scheme-3,SIGS3,0.93,122000.0,1281000.0,1.92,NaN,True,37,12,37.0,2082/2083,Chaitra,12
2239,949,Mutual Fund,NIC Asia Growth Fund-2,NICGF2,-0.92,2611564.0,25097130.0,0.00,NaN,True,37,12,37.0,2082/2083,Chaitra,12

In [48]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   companyId           2240 non-null   int64
 1   sectorName          2240 non-null   object
 2   companyName         2240 non-null   object
 3   companySymbol       2240 non-null   object
 4   pricePercentChange  2240 non-null   float64
 5   shareNo             2240 non-null   float64
 6   marketValue         2240 non-null   float64
 7   growthPercent       1783 non-null   float64
 8   assetPercent        0 non-null      float64
 9   isListed            2240 non-null   bool
 10  fiscal_year         2240 non-null   int64
 11  month               2240 non-null   int64
 12  fiscalId            1748 non-null   float64
 13  fiscalYear          1748 non-null   object
 14  monthName           2240 non-null   object
 15  monthId             2240 non-null   int64
dtypes: bool(1), float64(6), int64(4), object(5)
memory usage: 264.8+ KB

In [50]:
data1.sample(10)

,companyId,sectorName,companyName,companySymbol,pricePercentChange,shareNo,marketValue,growthPercent,assetPercent,isListed,fiscal_year,month,fiscalId,fiscalYear,monthName,monthId
1731,265,Microfinance,Chhimek Laghubitta Bittiya Sanstha Limited,CBBL,0.22,36880.0,31938080.0,0.00,NaN,True,36,11,36.0,2081/2082,Falgun,11
1830,180,Hydro Power,United Modi Hydropower Ltd.,UMHL,-0.35,40000.0,25560000.0,-37.50,NaN,True,37,2,37.0,2082/2083,Jestha,2
510,178,Hydro Power,Synergy Power Development Ltd.,SPDL,-0.15,1899.0,807075.0,111.23,NaN,True,34,1,34.0,2079/2080,Baisakh,1
1323,873,Non Life Insurance,Sagarmatha Lumbini Insurance Company Limited,SALICO,0.68,47873.0,31644053.0,0.00,NaN,True,35,12,35.0,2080/2081,Chaitra,12
507,938,Hydro Power,Shikhar Power Development Limited,SIPD,2.00,1276.0,438816.0,NaN,NaN,True,34,1,34.0,2079/2080,Baisakh,1
51,169,Hydro Power,Ngadi Group Power Ltd.,NGPL,1.01,10100.0,4734880.0,1136.23,NaN,True,32,2,NaN,NaN,Jestha,2
604,180,Hydro Power,United Modi Hydropower Ltd.,UMHL,-0.35,40000.0,25560000.0,-37.50,NaN,True,34,4,34.0,2079/2080,Shrawan,4
572,249,Life Insurance,National Life Insurance Co. Ltd.,NLICL,0.20,27326.0,17625270.0,4.03,NaN,True,34,3,34.0,2079/2080,Ashadh,3
2049,62,Development Banks,Garima Bikas Bank Limited,GBBL,0.48,52000.0,19656000.0,19.82,NaN,True,37,8,37.0,2082/2083,Mangsir,8
1949,1052,Non Life Insurance,Nepal Micro Insurance Company Limited,NMIC,-1.44,2461.0,2953126.0,0.00,NaN,True,37,5,37.0,2082/2083,Bhadra,5

In [51]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\data_extractions\\seleniums'