In [1]:
import requests
from bs4 import BeautifulSoup

url = "https://www.sharesansar.com/proposed-dividend"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "lxml")

title = soup.title.text

print(title)

Proposed Dividend - || ShareSansar ||

# Extract the tables datas

In [3]:
import pandas as pd

In [8]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Open Chrome
driver = webdriver.Chrome()

# Open URL
driver.get("https://www.sharesansar.com/proposed-dividend")

# Wait for loading
time.sleep(5)

# Find table
table = driver.find_element(By.TAG_NAME, "table")

# Extract rows
rows = table.find_elements(By.TAG_NAME, "tr")

data = []

for row in rows:

    cols = row.find_elements(By.TAG_NAME, "td")

    if not cols:
        cols = row.find_elements(By.TAG_NAME, "th")

    row_data = [col.text.strip() for col in cols]

    if row_data:
        data.append(row_data)

# Close browser
driver.quit()

# Create dataframe
headers = data[0]
table_data = data[1:]

df = pd.DataFrame(table_data, columns=headers)

print(df)

# # Save CSV
# df.to_csv("proposed_dividend.csv", index=False)

   S.N.    Symbol                                            Company  \
0     1      ANLB    Aatmanirbhar Laghubitta Bittiya Sanstha Limited
1     2      CIGL               Chandragiri Investment Group Limited
2     3     PHLTD                      Professional Holdings Limited
3     4  UNIGLOBE  Uniglobe Higher Secondary School Kathmandu Lim...
4     5      SGIC                       Sanima GIC Insurance Limited
5     6      PRIN                   Prabhu Insurance Company Limited
6     7     SMFBS      Swabhimaan Laghubitta Bittiya Sanstha Limited
7     8      UMHL                     United Modi Hydropower Limited
8     9       STC                   Salt Trading Corporation Limited
9    10       SMH                        Supermai Hydropower Limited
10   11    SUMERU                            Sumeru Polymers Limited
11   12  HIGHLAND                        Highland Distillery Limited
12   13       NIL                             Neco Insurance Limited
13   14     ALICL               Asian Life Insurance Company Limited
14   15       HEI                Himalayan Everest Insurance Limited
15   16      CHCL                Chilime Hydro power Company Limited
16   17       NTC                  Nepal Doorsanchar Company Limited
17   18       API                          Api Power Company Limited
18   19       NLG                      NLG Insurance Company Limited
19   20      BHDC  Bindhyabasini Hydropower Development Company L...

   Bonus (%) Cash (%) Total (%) Announcement Date    Book Closure Date  \
0      14.25     0.75     15.00        2026-03-26  2026-04-09 [Closed]
1                4.00      4.00        2026-03-22
2     2.6316    50.00   52.6316        2026-03-19
3     0.2632     5.00    5.2632        2026-03-19
4       5.00   0.2632    5.2632        2026-03-15  2026-05-06 [Closed]
5        8.7   0.4579    9.1579        2026-03-03  2026-04-09 [Closed]
6        9.5      0.5     10.00        2026-03-01
7       7.00   0.3684    7.3684        2026-02-22  2026-04-17 [Closed]
8        9.5      0.5     10.00        2026-02-12           2026-05-27
9      20.00     1.11     21.11        2026-02-04  2026-02-25 [Closed]
10      9.00   0.0237    9.0237        2026-01-30  2026-02-05 [Closed]
11     25.00   1.3158   25.3158        2026-01-21
12      3.00  12.7894   13.7894        2026-01-16  2026-02-08 [Closed]
13      5.00   5.5263   10.5263        2026-01-14  2026-02-12 [Closed]
14      0.00     8.00      8.00        2025-12-28  2026-01-05 [Closed]
15      8.00     4.00     12.00        2025-12-24  2026-01-01 [Closed]
16      0.00    30.00     30.00        2025-12-24  2026-01-04 [Closed]
17      5.00   0.2632    5.2632        2025-12-23  2026-01-02 [Closed]
18      4.00   3.3684    7.3684        2025-12-23  2026-01-06 [Closed]
19      5.00   0.2632    5.2632        2025-12-23  2026-01-06 [Closed]

   Distribution Date Bonus Listing Date Fiscal Year      LTP      As Of:
0                                         2081/2082  5901.00  2026-05-22
1                                         2081/2082
2                                         2081/2082
3                                         2081/2082
4                                         2081/2082   464.00  2026-05-22
5                                         2081/2082   662.00  2026-05-22
6                                         2081/2082  1535.00  2026-05-22
7                                         2081/2082   564.00  2026-05-22
8                                         2081/2082  5930.00  2026-05-22
9                                         2081/2082   594.00  2026-05-22
10                                        2081/2082
11                                        2081/2082
12                                        2081/2082   614.00  2026-05-22
13                                        2081/2082   452.30  2026-05-22
14                                        2081/2082   535.90  2026-05-22
15                                        2081/2082   482.00  2026-05-22
16                                        2081/2082   890.40  2026-05-22
17                           2026-03-01   2081/2082   357.20  2026-05-22
18                           2026-03-30   2081/2082   575.00  2026-05-22
19                           2026-03-30   2081/2082   463.60  2026-05-22

In [9]:
df

,S.N.,Symbol,Company,Bonus (%),Cash (%),Total (%),Announcement Date,Book Closure Date,Distribution Date,Bonus Listing Date,Fiscal Year,LTP,As Of:
0,1,ANLB,Aatmanirbhar Laghubitta Bittiya Sanstha Limited,14.25,0.75,15.00,2026-03-26,2026-04-09 [Closed],,,2081/2082,5901.00,2026-05-22
1,2,CIGL,Chandragiri Investment Group Limited,,4.00,4.00,2026-03-22,,,,2081/2082,,
2,3,PHLTD,Professional Holdings Limited,2.6316,50.00,52.6316,2026-03-19,,,,2081/2082,,
3,4,UNIGLOBE,Uniglobe Higher Secondary School Kathmandu Lim...,0.2632,5.00,5.2632,2026-03-19,,,,2081/2082,,
4,5,SGIC,Sanima GIC Insurance Limited,5.00,0.2632,5.2632,2026-03-15,2026-05-06 [Closed],,,2081/2082,464.00,2026-05-22
5,6,PRIN,Prabhu Insurance Company Limited,8.7,0.4579,9.1579,2026-03-03,2026-04-09 [Closed],,,2081/2082,662.00,2026-05-22
6,7,SMFBS,Swabhimaan Laghubitta Bittiya Sanstha Limited,9.5,0.5,10.00,2026-03-01,,,,2081/2082,1535.00,2026-05-22
7,8,UMHL,United Modi Hydropower Limited,7.00,0.3684,7.3684,2026-02-22,2026-04-17 [Closed],,,2081/2082,564.00,2026-05-22
8,9,STC,Salt Trading Corporation Limited,9.5,0.5,10.00,2026-02-12,2026-05-27,,,2081/2082,5930.00,2026-05-22
9,10,SMH,Supermai Hydropower Limited,20.00,1.11,21.11,2026-02-04,2026-02-25 [Closed],,,2081/2082,594.00,2026-05-22
10,11,SUMERU,Sumeru Polymers Limited,9.00,0.0237,9.0237,2026-01-30,2026-02-05 [Closed],,,2081/2082,,
11,12,HIGHLAND,Highland Distillery Limited,25.00,1.3158,25.3158,2026-01-21,,,,2081/2082,,
12,13,NIL,Neco Insurance Limited,3.00,12.7894,13.7894,2026-01-16,2026-02-08 [Closed],,,2081/2082,614.00,2026-05-22
13,14,ALICL,Asian Life Insurance Company Limited,5.00,5.5263,10.5263,2026-01-14,2026-02-12 [Closed],,,2081/2082,452.30,2026-05-22
14,15,HEI,Himalayan Everest Insurance Limited,0.00,8.00,8.00,2025-12-28,2026-01-05 [Closed],,,2081/2082,535.90,2026-05-22
15,16,CHCL,Chilime Hydro power Company Limited,8.00,4.00,12.00,2025-12-24,2026-01-01 [Closed],,,2081/2082,482.00,2026-05-22
16,17,NTC,Nepal Doorsanchar Company Limited,0.00,30.00,30.00,2025-12-24,2026-01-04 [Closed],,,2081/2082,890.40,2026-05-22
17,18,API,Api Power Company Limited,5.00,0.2632,5.2632,2025-12-23,2026-01-02 [Closed],,2026-03-01,2081/2082,357.20,2026-05-22
18,19,NLG,NLG Insurance Company Limited,4.00,3.3684,7.3684,2025-12-23,2026-01-06 [Closed],,2026-03-30,2081/2082,575.00,2026-05-22
19,20,BHDC,Bindhyabasini Hydropower Development Company L...,5.00,0.2632,5.2632,2025-12-23,2026-01-06 [Closed],,2026-03-30,2081/2082,463.60,2026-05-22

## Selenioyum Without Headless Modes

In [10]:
# Chrome options
options = Options()
# Run browser in background
options.add_argument("--headless")

# Optional performance settings
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

# Start browser
driver = webdriver.Chrome(options=options)

# Open page
driver.get("https://www.sharesansar.com/proposed-dividend")

# Wait for JS rendering
time.sleep(5)

# Extract table
table = driver.find_element(By.TAG_NAME, "table")

rows = table.find_elements(By.TAG_NAME, "tr")

data = []

for row in rows:

    cols = row.find_elements(By.TAG_NAME, "td")

    if not cols:
        cols = row.find_elements(By.TAG_NAME, "th")

    row_data = [col.text.strip() for col in cols]

    if row_data:
        data.append(row_data)

# Close browser
driver.quit()

# Convert to DataFrame
headers = data[0]
table_data = data[1:]

temps = pd.DataFrame(table_data, columns=headers)

print("extraced sucessfully ")

extraced sucessfully

In [11]:
temps

,S.N.,Symbol,Company,Bonus (%),Cash (%),Total (%),Announcement Date,Book Closure Date,Distribution Date,Bonus Listing Date,Fiscal Year,LTP,As Of:
0,1,ANLB,Aatmanirbhar Laghubitta Bittiya Sanstha Limited,14.25,0.75,15.00,2026-03-26,2026-04-09 [Closed],,,2081/2082,5901.00,2026-05-22
1,2,CIGL,Chandragiri Investment Group Limited,,4.00,4.00,2026-03-22,,,,2081/2082,,
2,3,PHLTD,Professional Holdings Limited,2.6316,50.00,52.6316,2026-03-19,,,,2081/2082,,
3,4,UNIGLOBE,Uniglobe Higher Secondary School Kathmandu Lim...,0.2632,5.00,5.2632,2026-03-19,,,,2081/2082,,
4,5,SGIC,Sanima GIC Insurance Limited,5.00,0.2632,5.2632,2026-03-15,2026-05-06 [Closed],,,2081/2082,464.00,2026-05-22
5,6,PRIN,Prabhu Insurance Company Limited,8.7,0.4579,9.1579,2026-03-03,2026-04-09 [Closed],,,2081/2082,662.00,2026-05-22
6,7,SMFBS,Swabhimaan Laghubitta Bittiya Sanstha Limited,9.5,0.5,10.00,2026-03-01,,,,2081/2082,1535.00,2026-05-22
7,8,UMHL,United Modi Hydropower Limited,7.00,0.3684,7.3684,2026-02-22,2026-04-17 [Closed],,,2081/2082,564.00,2026-05-22
8,9,STC,Salt Trading Corporation Limited,9.5,0.5,10.00,2026-02-12,2026-05-27,,,2081/2082,5930.00,2026-05-22
9,10,SMH,Supermai Hydropower Limited,20.00,1.11,21.11,2026-02-04,2026-02-25 [Closed],,,2081/2082,594.00,2026-05-22
10,11,SUMERU,Sumeru Polymers Limited,9.00,0.0237,9.0237,2026-01-30,2026-02-05 [Closed],,,2081/2082,,
11,12,HIGHLAND,Highland Distillery Limited,25.00,1.3158,25.3158,2026-01-21,,,,2081/2082,,
12,13,NIL,Neco Insurance Limited,3.00,12.7894,13.7894,2026-01-16,2026-02-08 [Closed],,,2081/2082,614.00,2026-05-22
13,14,ALICL,Asian Life Insurance Company Limited,5.00,5.5263,10.5263,2026-01-14,2026-02-12 [Closed],,,2081/2082,452.30,2026-05-22
14,15,HEI,Himalayan Everest Insurance Limited,0.00,8.00,8.00,2025-12-28,2026-01-05 [Closed],,,2081/2082,535.90,2026-05-22
15,16,CHCL,Chilime Hydro power Company Limited,8.00,4.00,12.00,2025-12-24,2026-01-01 [Closed],,,2081/2082,482.00,2026-05-22
16,17,NTC,Nepal Doorsanchar Company Limited,0.00,30.00,30.00,2025-12-24,2026-01-04 [Closed],,,2081/2082,890.40,2026-05-22
17,18,API,Api Power Company Limited,5.00,0.2632,5.2632,2025-12-23,2026-01-02 [Closed],,2026-03-01,2081/2082,357.20,2026-05-22
18,19,NLG,NLG Insurance Company Limited,4.00,3.3684,7.3684,2025-12-23,2026-01-06 [Closed],,2026-03-30,2081/2082,575.00,2026-05-22
19,20,BHDC,Bindhyabasini Hydropower Development Company L...,5.00,0.2632,5.2632,2025-12-23,2026-01-06 [Closed],,2026-03-30,2081/2082,463.60,2026-05-22

## Extract the data to make a complete website fully dymanics

In [12]:
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")

tables = driver.find_elements(By.TAG_NAME, "table")

print("Total tables:", len(tables))



for i, table in enumerate(tables):
    print(f"\nTABLE {i+1}")
    print(table.text)

Total tables: 2

TABLE 1
S.N. Symbol Company Bonus (%) Cash (%) Total (%) Announcement Date Book Closure Date Distribution Date Bonus Listing Date Fiscal Year LTP As Of:
1 ANLB Aatmanirbhar Laghubitta Bittiya Sanstha Limited 14.25 0.75 15.00 2026-03-26 2026-04-09 [Closed] 2081/2082 5901.00 2026-05-22
2 CIGL Chandragiri Investment Group Limited 4.00 4.00 2026-03-22 2081/2082
3 PHLTD Professional Holdings Limited 2.6316 50.00 52.6316 2026-03-19 2081/2082
4 UNIGLOBE Uniglobe Higher Secondary School Kathmandu Limited 0.2632 5.00 5.2632 2026-03-19 2081/2082
5 SGIC Sanima GIC Insurance Limited 5.00 0.2632 5.2632 2026-03-15 2026-05-06 [Closed] 2081/2082 464.00 2026-05-22
6 PRIN Prabhu Insurance Company Limited 8.7 0.4579 9.1579 2026-03-03 2026-04-09 [Closed] 2081/2082 662.00 2026-05-22
7 UMHL United Modi Hydropower Limited 7.00 0.3684 7.3684 2026-02-22 2026-04-17 [Closed] 2081/2082 564.00 2026-05-22
8 STC Salt Trading Corporation Limited 9.5 0.5 10.00 2026-02-12 2026-05-27 2081/2082 5930.00 2026-05-22
9 SMH Supermai Hydropower Limited 20.00 1.11 21.11 2026-02-04 2026-02-25 [Closed] 2081/2082 594.00 2026-05-22
10 SUMERU Sumeru Polymers Limited 9.00 0.0237 9.0237 2026-01-30 2026-02-05 [Closed] 2081/2082
11 HIGHLAND Highland Distillery Limited 25.00 1.3158 25.3158 2026-01-21 2081/2082
12 NIL Neco Insurance Limited 3.00 12.7894 13.7894 2026-01-16 2026-02-08 [Closed] 2081/2082 614.00 2026-05-22
13 ALICL Asian Life Insurance Company Limited 5.00 5.5263 10.5263 2026-01-14 2026-02-12 [Closed] 2081/2082 452.30 2026-05-22
14 HEI Himalayan Everest Insurance Limited 0.00 8.00 8.00 2025-12-28 2026-01-05 [Closed] 2081/2082 535.90 2026-05-22
15 CHCL Chilime Hydro power Company Limited 8.00 4.00 12.00 2025-12-24 2026-01-01 [Closed] 2081/2082 482.00 2026-05-22
16 NTC Nepal Doorsanchar Company Limited 0.00 30.00 30.00 2025-12-24 2026-01-04 [Closed] 2081/2082 890.40 2026-05-22
17 API Api Power Company Limited 5.00 0.2632 5.2632 2025-12-23 2026-01-02 [Closed] 2026-03-01 2081/2082 357.20 2026-05-22
18 NLG NLG Insurance Company Limited 4.00 3.3684 7.3684 2025-12-23 2026-01-06 [Closed] 2026-03-30 2081/2082 575.00 2026-05-22
19 BHDC Bindhyabasini Hydropower Development Company Limited 5.00 0.2632 5.2632 2025-12-23 2026-01-06 [Closed] 2026-03-30 2081/2082 463.60 2026-05-22
20 UHEWA Upper Hewakhola Hydropower Company Limited 15.00 0.789 15.789 2025-12-23 2026-01-01 [Closed] 2026-03-26 2081/2082 583.60 2026-05-22

TABLE 2

## anpothjer methods

In [ ]:
# loczate the element from the clas snames 

# paginate_button next

In [14]:
driver = webdriver.Chrome()

driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(2)
button = driver.find_element(By.CLASS_NAME, "paginate_button.next")
time.sleep(2)
button.click()

## fins how many oages are there

In [25]:
import re
import json
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")

html = driver.page_source

# Extract cmpjson array
match = re.search(r"var cmpjson = (\[.*?\]);", html, re.DOTALL)

if match:
    json_text = match.group(1)
    data = json.loads(json_text)

    for item in data:
        print(item)

else:
    print("cmpjson not found")

driver.quit()

{'id': 1414, 'symbol': '101', 'companyname': 'One O One Company Limited'}
{'id': 1035, 'symbol': '1025BOKL86', 'companyname': '10.25% BOK Debenture 2086'}
{'id': 1026, 'symbol': '1025EBLD83', 'companyname': '10.25% Everest Bank Limited Debenture 2083'}
{'id': 1028, 'symbol': '1025SANID86', 'companyname': '10.25%  Sanima Debenture 2086'}
{'id': 863, 'symbol': '105global2080', 'companyname': '10.5% Global IME Debenture 2080'}
{'id': 870, 'symbol': '10NICD208586', 'companyname': '10% NIC ASIA Debenture 2085/86'}
{'id': 1036, 'symbol': '10PRVU84', 'companyname': '10% Prabhu Bank Debenture 2084'}
{'id': 1072, 'symbol': '4ADBLKR', 'companyname': '4% ADBL Krishi Rinpatra'}
{'id': 1077, 'symbol': '4NMBUR', 'companyname': '4% NMB Urja Rinpatra 2092/93'}
{'id': 981, 'symbol': '79SBI2080', 'companyname': '7.9% Nepal SBI Bank Debenture 2080'}
{'id': 1457, 'symbol': '8.5CIZBD90', 'companyname': '8.5% Citizens Bank Debenture 2090'}
{'id': 1064, 'symbol': '85SANIMAD86', 'companyname': '8.5% Sanima Debenture 2086'}
{'id': 532, 'symbol': '8NIB2078', 'companyname': '8% NIB Debenture 2078'}
{'id': 1542, 'symbol': '8NICAD91', 'companyname': '8% NIC Asia Debenture 2091'}
{'id': 1070, 'symbol': '8NMBR8485', 'companyname': '8% NMB Rinpatra 2084/85'}
{'id': 1084, 'symbol': '9%CSB82', 'companyname': '9% Citizen Saving Bond 2082'}
{'id': 1091, 'symbol': '9JBBB87', 'companyname': '9% Jyoti Bikas Bank Bond 2087'}
{'id': 1421, 'symbol': 'AADHYANTA', 'companyname': 'Aadhyanta Fund Management Limited'}
{'id': 1649, 'symbol': 'AAYU', 'companyname': 'Aayu Molung Hydropower Limited'}
{'id': 175, 'symbol': 'ABBL', 'companyname': 'Annapurna Bikash Bank Limited'}
{'id': 1689, 'symbol': 'ABIRAL', 'companyname': 'Abiral Hydropower Company Limited'}
{'id': 1659, 'symbol': 'ABL', 'companyname': 'Asian Batteries Limited'}
{'id': 1340, 'symbol': 'ABSL', 'companyname': 'Aakash Bhairab Securities Limited'}
{'id': 785, 'symbol': 'ACAL', 'companyname': 'Arks Capital Advisors Limited'}
{'id': 1277, 'symbol': 'ACCL', 'companyname': 'Annapurna Cable Car Limited'}
{'id': 373, 'symbol': 'ACECAP', 'companyname': 'Ace Capital Limited'}
{'id': 177, 'symbol': 'ACEDBL', 'companyname': 'Ace Development Bank Limited'}
{'id': 247, 'symbol': 'ACEDPO', 'companyname': 'ACE Development Bank Limited Promoter Share'}
{'id': 759, 'symbol': 'ACL', 'companyname': 'Aakash Capital Limited'}
{'id': 1039, 'symbol': 'ACLBSL', 'companyname': 'Aarambha Chautari Laghubitta Bittiya Sanstha Limited'}
{'id': 1253, 'symbol': 'ACLBSLP', 'companyname': 'Aarambha Chautari Laghubitta Bittiya Sanstha Limited Promoter Share'}
{'id': 1350, 'symbol': 'ACLTD', 'companyname': 'Asian Capital Limited'}
{'id': 1241, 'symbol': 'ACPL', 'companyname': 'Accord Pharmaceuticals limited'}
{'id': 924, 'symbol': 'ADB', 'companyname': 'Asian Development Bank Limited'}
{'id': 24, 'symbol': 'ADBL', 'companyname': 'Agricultural Development Bank Limited'}
{'id': 1105, 'symbol': 'ADBLB86', 'companyname': '4% Agricultural Bond 2086'}
{'id': 1131, 'symbol': 'ADBLB87', 'companyname': '4% Agricultural Bond 2087'}
{'id': 996, 'symbol': 'ADBLD83', 'companyname': '10.35% Agricultural Bank Debenture 2083'}
{'id': 943, 'symbol': 'ADLB', 'companyname': 'Adarsha Laghubitta Bittiya Sanstha Limited'}
{'id': 50, 'symbol': 'AEFL', 'companyname': 'Alpic Everest Finance Company Limited'}
{'id': 258, 'symbol': 'AEFLPO', 'companyname': 'Alpic Everest Finance Company Limited Promotor Share'}
{'id': 1270, 'symbol': 'AEL', 'companyname': 'Avasar Equity Limited'}
{'id': 1363, 'symbol': 'AELTD', 'companyname': 'Aashutosh Energy Limited'}
{'id': 1563, 'symbol': 'AERO', 'companyname': 'Aero Pharmaceuticals Limited'}
{'id': 249, 'symbol': 'AFCPO', 'companyname': 'Annapurna Finance Company Limited Promoter Share'}
{'id': 87, 'symbol': 'AFL', 'companyname': 'Api Finance Limtied'}
{'id': 1137, 'symbol': 'AGCL', 'companyname': 'Arghakhanchi Cement Limited'}
{'id': 1473, 'symbol': 'AGNI', 'companyname': 'Agni Cement Industries Limited'}
{'id': 892, 'symbol': 'AGROP', 'companyname': 'Nepal Agro Laghubitta Bittiya Sanstha Limited Promoter Share'}
{'id': 1617, 'symbol': 'AHCL', 'companyname': 'Api Holdings Company Limited'}
{'id': 1010, 'symbol': 'AHL', 'companyname': 'Asian Hydropower Limited'}
{'id': 1632, 'symbol': 'AHLTD', 'companyname': 'Asian Hotel Limited'}
{'id': 121, 'symbol': 'AHPC', 'companyname': 'Arun Valley Hydropower Development Company Limited'}
{'id': 134, 'symbol': 'AIC', 'companyname': 'Alliance Insurance Company Limited'}
{'id': 1500, 'symbol': 'AICL', 'companyname': 'Aadishakti Investment Company Limited'}
{'id': 483, 'symbol': 'AICPO', 'companyname': 'Alliance Insurance Company Limited Promoter'}
{'id': 831, 'symbol': 'AIL', 'companyname': 'Ajod Insurance Limited'}
{'id': 1378, 'symbol': 'AKAMA', 'companyname': 'Akama Hotel Limited'}
{'id': 897, 'symbol': 'AKBSL', 'companyname': 'Adhikhola Laghubitta Bittiya Sanstha Limited'}
{'id': 1058, 'symbol': 'AKBSLP', 'companyname': 'Adhikhola Laghubitta Bittiya Sanstha Limited promoter'}
{'id': 590, 'symbol': 'AKJCL', 'companyname': 'Ankhukhola Hydropower Company Limited'}
{'id': 514, 'symbol': 'AKPL', 'companyname': 'Arun Kabeli Power Limited'}
{'id': 670, 'symbol': 'ALBSL', 'companyname': 'Asha Laghubitta Bittiya Sanstha Limited'}
{'id': 893, 'symbol': 'ALBSLP', 'companyname': 'Asha Laghubitta Bittiya Sanstha Limited Promoter Share'}
{'id': 195, 'symbol': 'ALDBL', 'companyname': 'Alpine Development Bank Limited'}
{'id': 1370, 'symbol': 'ALICE', 'companyname': 'Hotel Alice the Wonder Inn Limited'}
{'id': 143, 'symbol': 'ALICL', 'companyname': 'Asian Life Insurance Company Limited'}
{'id': 486, 'symbol': 'ALICLP', 'companyname': 'Asian Life Insurance company Limited Promoter Share'}
{'id': 466, 'symbol': 'ALICO', 'companyname': 'Metlife - American Life Insurance Company Limited'}
{'id': 1368, 'symbol': 'ALPHA', 'companyname': 'Alpha Capital Limited'}
{'id': 886, 'symbol': 'AMBE', 'companyname': 'Ambe Cement Private Limited'}
{'id': 608, 'symbol': 'AMFI', 'companyname': 'Aarambha Laghubitta Bittiya Sanstha Limited'}
{'id': 787, 'symbol': 'AMFIPO', 'companyname': 'Aarambha Laghubitta Bittiya Sanstha Limited Promoter Share'}
{'id': 1135, 'symbol': 'AMHL', 'companyname': 'Apex Makalu Hydropower Limited'}
{'id': 1409, 'symbol': 'AMILCL', 'companyname': 'Aadar Multi Investment Company Limited'}
{'id': 1291, 'symbol': 'ANIDCL', 'companyname': 'All Nepal Infrastructure Development Company Limited'}
{'id': 997, 'symbol': 'ANLB', 'companyname': 'Aatmanirbhar Laghubitta Bittiya Sanstha Limited'}
{'id': 1312, 'symbol': 'ANLBP', 'companyname': 'Aatmanirbhar Laghubitta Bittiya Sanstha Limited Promoter Share'}
{'id': 906, 'symbol': 'ANMACL', 'companyname': 'Aarabha Nepal Modern Agriculture Company Limited'}
{'id': 456, 'symbol': 'APEX', 'companyname': 'Apex Development Bank Limited'}
{'id': 1353, 'symbol': 'APHL', 'companyname': 'Apex Hospitality Limited'}
{'id': 527, 'symbol': 'API', 'companyname': 'Api Power Company Limited'}
{'id': 1275, 'symbol': 'APL', 'companyname': 'Alliance Pharmaceuticals Limited.'}
{'id': 1548, 'symbol': 'APPOLO', 'companyname': 'Appolo Hydropower Limited'}
{'id': 303, 'symbol': 'ARDBL', 'companyname': 'Araniko Development Bank Limited'}
{'id': 517, 'symbol': 'ARDBLP', 'companyname': 'Araniko Development Bank Limited Promoter Share'}
{'id': 368, 'symbol': 'Arniko', 'companyname': 'Arniko Capital Management Company Limited'}
{'id': 953, 'symbol': 'ARPCL', 'companyname': 'Aarati Power Company Limited'}
{'id': 1634, 'symbol': 'ARPL', 'companyname': 'Atithi Resort & Spa Limited'}
{'id': 843, 'symbol': 'ARTHIK', 'companyname': 'Aarthik Samriddhi Laghubitta Bittiya Sanstha Limited'}
{'id': 1564, 'symbol': 'ASICL', 'companyname': 'Asian Concreto Limited'}
{'id': 1403, 'symbol': 'ASL', 'companyname': 'Ambe Steels Limited'}
{'id': 895, 'symbol': 'ASTPL', 'companyname': 'AST Private Limited'}
{'id': 105, 'symbol': 'AVU', 'companyname': 'Arun Vanaspati Udhyog Limited'}
{'id': 1033, 'symbol': 'AVYAN', 'companyname': 'Aviyan Laghubitta Bittiya Sanstha Limited'}
{'id': 406, 'symbol': 'AXIS', 'companyname': 'Axis Development Bank Limited'}
{'id': 332, 'symbol': 'Baibhava', 'companyname': 'Baibhava Finance Limited'}
{'id': 1687, 'symbol': 'BAIDIK', 'companyname': 'Baidik Investment Company Limited'}
{'id': 1616, 'symbol': 'BAJEKO', 'companyname': 'Bajeko Sekuwa Limited'}
{'id': 1387, 'symbol': 'BANDIPUR', 'companyname': 'Bandipur Cable Car and Tourism Limited'}
{'id': 493, 'symbol': 'BARUN', 'companyname': 'Barun Hydropower Company Limited'}
{'id': 931, 'symbol': 'BATAS', 'companyname': 'Batas Investment Company Private Limited'}
{'id': 165, 'symbol': 'BBBL', 'companyname': 'Bhrikuti Vikash Bank Limited'}
{'id': 172, 'symbol': 'BBBLN', 'companyname': 'Bageshowori Dev.elopment  Bank Limited'}
{'id': 391, 'symbol': 'BBBLNP', 'companyname': 'Bagheshowari Development Bank Limited Promoer Share'}
{'id': 274, 'symbol': 'BBBLPO', 'companyname': 'Bhrikuti Bikash Bank Limited Promoter Share'}
{'id': 123, 'symbol': 'BBC', 'companyname': 'Bishal Bazar Company Limited'}
{'id': 921, 'symbol': 'BCIPL', 'companyname': 'Balaji Cement Industries Private Limited'}
{'id': 1339, 'symbol': 'BCSL', 'companyname': 'Blue Chip Securities Limited'}
{'id': 164, 'symbol': 'BDBL', 'companyname': 'Business Development Bank Limited'}
{'id': 851, 'symbol': 'BEDC', 'companyname': 'Bhugol Energy Development Company Limited'}
{'id': 1352, 'symbol': 'BENI', 'companyname': 'Beni Hydropower Project Limited'}
{'id': 776, 'symbol': 'BETAN', 'companyname': 'Betan Karnali Sanchayakarta Hydropower Company Limited'}
{'id': 40, 'symbol': 'BFC', 'companyname': 'Best Finance Company Limited'}
{'id': 340, 'symbol': 'BFCL', 'companyname': 'Bhaktapur Finance Company Limited'}
{'id': 726, 'symbol': 'BFCPO', 'companyname': 'Best Finance Company Limited Promoter Share'}
{'id': 1013, 'symbol': 'BFIINL', 'companyname': 'Banking Finance and Insurance Institute of Nepal Limited'}
{'id': 73, 'symbol': 'BFIL', 'companyname': 'Bhajuratna Finance & Saving Company Limited'}
{'id': 58, 'symbol': 'BFL', 'companyname': 'Butwal Finance Limited'}
{'id': 329, 'symbol': 'BGDBL', 'companyname': 'Bagmati Development Bank Limited'}
{'id': 569, 'symbol': 'BGDBLP', 'companyname': 'Bagmati Development Bank Limited Promoter Share'}
{'id': 1138, 'symbol': 'BGWT', 'companyname': 'Bhagawati Hydropower Development Company Limited'}
{'id': 661, 'symbol': 'BHAIRAB', 'companyname': 'Bhairabkunda Hydropower Limited'}
{'id': 293, 'symbol': 'BHBL', 'companyname': 'Bhargav Bikash Bank Limited'}
{'id': 547, 'symbol': 'BHBLPO', 'companyname': 'Bhargav Bikash Bank Limited Promoter Share'}
{'id': 1397, 'symbol': 'BHCL', 'companyname': 'Bikash Hydropower Company Limited'}
{'id': 766, 'symbol': 'BHDC', 'companyname': 'Bindhyabasini Hydropower Development Company Limited'}
{'id': 1422, 'symbol': 'BHHL', 'companyname': 'Budhanilkantha Heritage Hotel Limited'}
{'id': 969, 'symbol': 'BHL', 'companyname': 'Balephi Hydropower Limited'}
{'id': 674, 'symbol': 'BHPL', 'companyname': 'Barahi Hydropower Public Limited'}
{'id': 845, 'symbol': 'BHRIKUTIPU', 'companyname': 'Bhrikuti Pulp & Paper Nepal Limited'}
{'id': 1496, 'symbol': 'BHUGARBHA', 'companyname': 'Bhugarbha Cement Limited'}
{'id': 1408, 'symbol': 'BIGIL', 'companyname': 'Business Interest Group of Industries Limited'}
{'id': 710, 'symbol': 'BIL', 'companyname': 'Beed Invest Limited'}
{'id': 1217, 'symbol': 'BIML', 'companyname': 'Barun Investment Limited'}
{'id': 385, 'symbol': 'Biratnagar', 'companyname': 'Biratnagar Jute Mills Limited'}
{'id': 1582, 'symbol': 'BIZWELL', 'companyname': 'Bizwell Limited'}
{'id': 1498, 'symbol': 'BJCL', 'companyname': 'Budhigandaki Jalbidhyut Company Limited'}
{'id': 65, 'symbol': 'BJFL', 'companyname': 'Birgunj Finance Limited'}
{'id': 1222, 'symbol': 'BJHL', 'companyname': 'Bhujung Hydropower Limited'}
{'id': 939, 'symbol': 'BJLBSL', 'companyname': 'Buddha Jyoti Laghubitta Bittiya Sanstha Limited'}
{'id': 181, 'symbol': 'BLDBL', 'companyname': 'Biratlaxmi Bikash Bank Limited'}
{'id': 377, 'symbol': 'BLDBLP', 'companyname': 'Biratlaxmi Development Bank Limited Promoter Share'}
{'id': 1006, 'symbol': 'BMHL', 'companyname': 'BomKhola Mini Hydropower Limited'}
{'id': 782, 'symbol': 'BNHC', 'companyname': 'Buddha Bhumi Nepal Hydropower Company Limited'}
{'id': 98, 'symbol': 'BNL', 'companyname': 'Bottlers Nepal Limited (Balaju)'}
{'id': 106, 'symbol': 'BNT', 'companyname': 'Bottlers Nepal (Terai) Limited'}
{'id': 17, 'symbol': 'BOAN', 'companyname': 'Bank of Asia Nepal Limited'}
{'id': 9, 'symbol': 'BOK', 'companyname': '(Former) Bank of Kathmandu Limited'}
{'id': 216, 'symbol': 'BOKB2069', 'companyname': 'Bank of Kathmandu Rinpatra 2069'}
{'id': 649, 'symbol': 'BOKCML', 'companyname': 'BOK Capital Market Limited'}
{'id': 1063, 'symbol': 'BOKD86', 'companyname': '8.5% BOK Debenture 2086'}
{'id': 1169, 'symbol': 'BOKD86KA', 'companyname': '10.5% BOK Debenture 2086'}
{'id': 634, 'symbol': 'BOKL', 'companyname': 'Bank of Kathmandu Limited'}
{'id': 253, 'symbol': 'BOKLPO', 'companyname': 'Bank of Kathmandu Limited Promoter Share'}
{'id': 119, 'symbol': 'BPCL', 'companyname': 'Butwal Power Company Limited'}
{'id': 1095, 'symbol': 'BPW', 'companyname': 'BPW Laghubitta Bittiya Sanstha Limited'}
{'id': 1177, 'symbol': 'BRR84', 'companyname': '12.50% Baidesik Rojgaar Bachatpatra 2084'}
{'id': 351, 'symbol': 'BRTBL', 'companyname': 'Bright Development Bank Limited'}
{'id': 153, 'symbol': 'BSBL', 'companyname': 'Bishwa Bikas Bank Limited'}
{'id': 533, 'symbol': 'BSBLPO', 'companyname': 'Bishwa Bikas Bank Limited Promoter Share'}
{'id': 1693, 'symbol': 'BSIL', 'companyname': 'Bhagawati Steel Industries Limited'}
{'id': 108, 'symbol': 'BSL', 'companyname': 'Birat Shoe Limited'}
{'id': 102, 'symbol': 'BSM', 'companyname': 'Butwal Spinning Mills Limited'}
{'id': 403, 'symbol': 'BUDBL', 'companyname': 'Business Universal Development Bank Limited'}
{'id': 555, 'symbol': 'BUDBLP', 'companyname': 'Business Universal Development Bank Limited Promoter Share'}
{'id': 1179, 'symbol': 'BUNGAL', 'companyname': 'Bungal Hydro Limited'}
{'id': 1123, 'symbol': 'C30MF', 'companyname': 'Citizens Super 30 Mutual Fund'}
{'id': 1695, 'symbol': 'C50MF', 'companyname': 'Citizens Super 50'}
{'id': 1375, 'symbol': 'CAPMAX', 'companyname': 'Capital Max Securities Limited'}
{'id': 1423, 'symbol': 'CAPOL', 'companyname': 'Capital One Limited'}
{'id': 769, 'symbol': 'CARE', 'companyname': 'Care Ratings Nepal Limited'}
{'id': 159, 'symbol': 'CBBL', 'companyname': 'Chhimek Laghubitta Bittiya Sanstha Limited'}
{'id': 768, 'symbol': 'CBBLPO', 'companyname': 'Chhimek Laghubitta Bikas Bank Limited Promoter Share'}
{'id': 1301, 'symbol': 'CBFIN', 'companyname': 'Confederation of Banks and Financial Institutions Nepal'}
{'id': 691, 'symbol': 'CBIL', 'companyname': 'Citizens Capital Ltd. (Former CBIL Capital )'}
{'id': 1434, 'symbol': 'CBILSL', 'companyname': 'Citizens Share Broker Limited'}
{'id': 325, 'symbol': 'CBL', 'companyname': 'Civil Bank Limited'}
{'id': 1195, 'symbol': 'CBL2084', 'companyname': '11% Civil Bank Debenture 2084'}
{'id': 1130, 'symbol': 'CBLD88', 'companyname': '10.25% Civil Bank Debenture 2088'}
{'id': 536, 'symbol': 'CBLPO', 'companyname': 'Civil Bank Limited Promoter Share'}
{'id': 709, 'symbol': 'CCAIL', 'companyname': 'Chartered Capital and Investment Limited'}
{'id': 1164, 'symbol': 'CCBD88', 'companyname': '10.50% Century Debenture 2088'}
{'id': 335, 'symbol': 'CCBL', 'companyname': 'Century Commercial Bank Limited'}
{'id': 700, 'symbol': 'CCBLPO', 'companyname': 'Century Commercial Bank Limited Promoter Share'}
{'id': 1641, 'symbol': 'CCLTD', 'companyname': 'Club Chaulani Limited'}
{'id': 908, 'symbol': 'CCML', 'companyname': 'Century Capital Markets Limited'}
{'id': 192, 'symbol': 'CDBL', 'companyname': 'City Development Bank Limited'}
{'id': 470, 'symbol': 'CDBLPO', 'companyname': 'City Development Bank Limited promoter Share'}
{'id': 1158, 'symbol': 'CDCL', 'companyname': 'Chhaya Devi Complex Limited'}
{'id': 460, 'symbol': 'CDS', 'companyname': 'CDS & Clearing Limited'}
{'id': 168, 'symbol': 'CEDBL', 'companyname': 'Clean Energy Development Bank Limited'}
{'id': 379, 'symbol': 'CEDBLP', 'companyname': 'Clean Energy Development Bank Limited Promoter Share'}
{'id': 835, 'symbol': 'CEDBPO', 'companyname': 'CEDB Hydropower Development Company Limited Promoter Share'}
{'id': 85, 'symbol': 'CEFL', 'companyname': 'City Express Finance Limited (former Kuber Merchant Finance)'}
{'id': 679, 'symbol': 'CEFLPO', 'companyname': 'City Express Finance Limited Promoter Share'}
{'id': 1388, 'symbol': 'CEL', 'companyname': 'Century Energy Limited'}
{'id': 54, 'symbol': 'CFCL', 'companyname': 'Central Finance Limited'}
{'id': 562, 'symbol': 'CFCLPO', 'companyname': 'Central Finance Limited Promoter Share'}
{'id': 88, 'symbol': 'CFL', 'companyname': 'Crystal Finance Limited'}
{'id': 872, 'symbol': 'CGH', 'companyname': 'Chandragiri Hills Limited'}
{'id': 1319, 'symbol': 'CHANDESWARI', 'companyname': 'Chandeswari Mahadev Khola Micro Hydro Company Limited'}
{'id': 120, 'symbol': 'CHCL', 'companyname': 'Chilime Hydro power Company Limited'}
{'id': 518, 'symbol': 'CHDC', 'companyname': 'CEDB Holdings Limited'}
{'id': 628, 'symbol': 'CHL', 'companyname': 'Chhyangdi Hydropower Company Limited'}
{'id': 644, 'symbol': 'CHLBS', 'companyname': 'Chautari Laghubitta Bittiya Sanstha Limited'}
{'id': 1676, 'symbol': 'CIGL', 'companyname': 'Chandragiri Investment Group Limited'}
{'id': 33, 'symbol': 'CIT', 'companyname': 'Citizen Investment Trust'}
{'id': 572, 'symbol': 'CITIZEN_UN', 'companyname': 'Citizen Units Scheme 2052'}
{'id': 1389, 'symbol': 'CITPO', 'companyname': 'Citizen Investment Trust Promoter Share'}
{'id': 1166, 'symbol': 'CITY', 'companyname': 'City Hotel Limited'}
{'id': 315, 'symbol': 'CIVIC', 'companyname': 'Civic Development Bank Limited'}
{'id': 1465, 'symbol': 'CIVIL', 'companyname': 'Civil Hydropower Limited'}
{'id': 356, 'symbol': 'Civil-Capital', 'companyname': 'Civil Capital Market Limited'}
{'id': 1002, 'symbol': 'CIZBD86', 'companyname': '10.25% Citizens Bank Debenture 2086'}
{'id': 1303, 'symbol': 'CIZBD90', 'companyname': '10% Citizens Bank Debenture 2090'}
{'id': 1229, 'symbol': 'CKHL', 'companyname': 'Chirkhwa Hydro Power Limited'}
{'id': 923, 'symbol': 'CKSPL', 'companyname': 'Crystal Kanchanjungha Securities Pvt. Ltd'}
{'id': 765, 'symbol': 'CLI', 'companyname': 'Citizen Life Insurance Company Limited'}
{'id': 66, 'symbol': 'CMB', 'companyname': 'Capital Merchant Banking & Finance Limited'}
{'id': 62, 'symbol': 'CMBF', 'companyname': 'CMB Finance Limited'}
{'id': 231, 'symbol': 'CMBFLP', 'companyname': 'Capital Merchant Banking & Finance Limited Promotor Share'}
{'id': 235, 'symbol': 'CMBFPO', 'companyname': 'Cosmic Merchant Bank & Finance Company Limited Promoter Share'}
{'id': 76, 'symbol': 'CMBSL', 'companyname': 'Civil Merchant Bittiya Santha Limited'}
{'id': 695, 'symbol': 'CMF1', 'companyname': 'Citizens Mutual Fund-1'}
{'id': 890, 'symbol': 'CMF2', 'companyname': 'Citizens Mutual Fund - 2'}
{'id': 294, 'symbol': 'CNDBL', 'companyname': 'Country Development Bank Limited'}
{'id': 554, 'symbol': 'CNDBLP', 'companyname': 'Country Development Bank Limited Promoter Share'}
{'id': 309, 'symbol': 'CORBL', 'companyname': 'Corporate Development Bank Limited'}
{'id': 727, 'symbol': 'CORBLP', 'companyname': 'Corporate Development Bank Limited Promoter Share'}
{'id': 1519, 'symbol': 'COSMIC', 'companyname': 'Cosmic Electrical Limited'}
{'id': 1235, 'symbol': 'CPPL', 'companyname': 'Champawati Hydropower Limited'}
{'id': 1316, 'symbol': 'CREST', 'companyname': 'Crest Micro Life Insurance Limited'}
{'id': 937, 'symbol': 'CRLBSL', 'companyname': 'Creative Laghubitta Bittiya Sanstha Limited'}
{'id': 1254, 'symbol': 'CSB2084', 'companyname': "11.50% Citizens Saving Bond 2084 'Ka'"}
{'id': 1151, 'symbol': 'CSBK', 'companyname': "10% Citizen Saving Bond 2083 'Ka'"}

In [26]:
pd.DataFrame(data)

        id         symbol                                  companyname
0     1414            101                    One O One Company Limited
1     1035     1025BOKL86                    10.25% BOK Debenture 2086
2     1026     1025EBLD83   10.25% Everest Bank Limited Debenture 2083
3     1028    1025SANID86                10.25%  Sanima Debenture 2086
4      863  105global2080              10.5% Global IME Debenture 2080
...    ...            ...                                          ...
1610   263          YFLPO  Yeti Finance Company Limited Promoter Share
1611    94            YHL                     Yak & Yeti Hotel Limited
1612  1320           YMHL                 Yambaling Hydropower Limited
1613  1653       YUWARANI             Yuwarani Agro Industries Limited
1614    90            ZFL                       Zenith Finance Limited

[1615 rows x 3 columns]

# again generate a code again

In [27]:
driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")

## find all the avai;lable apis on this sites

In [ ]:
/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/div[3]/div/table/tbody/tr[10]/td[11]

## another codes

In [ ]:
<span><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="1" tabindex="0">1</a><a class="paginate_button current" aria-controls="myTableFD" data-dt-idx="2" tabindex="0">2</a><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="3" tabindex="0">3</a><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="4" tabindex="0">4</a></span>

In [ ]:
# <span><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="1" tabindex="0">1</a><span class="ellipsis">…</span><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="2" tabindex="0">5</a><a class="paginate_button current" aria-controls="myTableFD" data-dt-idx="3" tabindex="0">6</a><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="4" tabindex="0">7</a><span class="ellipsis">…</span><a class="paginate_button " aria-controls="myTableFD" data-dt-idx="5" tabindex="0">17</a></span>

In [ ]:
/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/div[3]/div/div[5]/span

In [38]:
driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(5)
data=driver.find_element(By.XPATH,"//div[2]//div//div[3]//div//div[5]//span").text
data

'12345…10'

## select all the dropdown oprtions

In [ ]:
//div//div[3]//div//div[1]//label//select

In [39]:
from selenium.webdriver.support.ui import Select

driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(5)
dropdown_element=driver.find_element(By.XPATH,"//div//div[3]//div//div[1]//label//select")

select = Select(dropdown_element)

# get all options
options = select.options

for opt in options:
    print(opt.text)

10
20
50

## get  another drop down menus values

In [ ]:
# /html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[1]/span/span[1]

In [44]:
from selenium.webdriver.support.ui import Select

driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(10)
years = driver.execute_script("""
    return Array.from(document.querySelectorAll('.select2-results__option'))
        .map(e => e.innerText.trim())
        .filter(e => e.length > 0);
""")
print(years)

[]

In [48]:
driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(10)

DROPDOWN=driver.find_element(By.XPATH,"/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[1]/span/span[1]/span/span[1]")
DROPDOWN.click()

# 2. Wait for options to appear
options = driver.find_elements(By.XPATH, "//li | //div[@role='option'] | //option")

# 3. Extract text
values = []
for opt in options:
    text = opt.text.strip()
    if text:
        values.append(text)

print(values)

['Login', 'Register', 'Contact Us', 'FAQ', 'Write For Us', 'Home', 'News', 'Economy', 'Market', 'IPO/FPO', 'Company', 'Investment', 'Training', 'Forum', 'Knowledge', 'Analysis', 'Tools', 'Share Kheladi', '⬈ SS Pro', 'Latest Dividend', 'Fiscal Year Wise', '2081/2082', '2080/2081', '2079/2080', '2078/2079', '2077/2078', '2076/2077', '2075/2076', '2074/2075', '2073/2074', '2072/2073', '2071/2072', '2070/2071', '2069/2070', '2068/2069', '2067/2068', '2066/2067', '2065/2066', '2064/2065', '2063/2064', '2062/2063', '2061/2062', '2060/2061', '2059/2060', '2058/2059', '2057/2058', 'All Sector', 'Commercial Bank', 'Corporate Debentures', 'Development Bank', 'Finance', 'Government Bonds', 'Hotel & Tourism', 'Hydropower', 'Investment', 'Life Insurance', 'Manufacturing and Processing', 'Merchant Bank', 'Merged', 'Microfinance', 'Mutual Fund', 'Non Category', 'Non-Life Insurance', 'Others', 'Preference Share', 'Promoter Share', 'Trading', '10', '20', '50', 'Technical Analysis', 'Moving Average', '180 Days Avg Prices', 'Pivot Analysis', 'Weekly Market Analysis', 'Top Companies in Nepal', 'IPO/FPO News', 'Dividend, Right & Bonus', 'Exclusive', 'Company Analysis', 'Share Listing', 'Write For Us', 'Share Registrar (RTS)', 'Broker List', 'Merchant Bankers', 'C-ASBA BFIs', 'DP Members', 'IPO Results', 'Existing Issues', 'Upcoming Issues', 'Ongoing Auctions', "Today's Share Price", 'Floorsheet', 'Indices/Sub-indices', 'Top Transactions', 'Top Turnovers', 'Top Traded Shares', 'Top Losers', 'Top Gainers', 'Top Brokers', 'IMS Investment Management Services Pvt. Ltd.', 'Dhalko Linkroad -17, Kathmandu', 'sharesansar@gmail.com', '977-\u202a01-5359786\u202c, 5365399', 'Editor: Usha Shakya', 'Regd No (Dept. of Information) : 669/074-75', 'Home', 'ShareSansar Forum', 'Create Free Account', 'Careers', 'Advertise With Us', 'Go To SS Pro', 'Terms & Conditions', '2081/2082', '2080/2081', '2079/2080', '2078/2079', '2077/2078', '2076/2077', '2075/2076', '2074/2075', '2073/2074', '2072/2073', '2071/2072', '2070/2071', '2069/2070', '2068/2069', '2067/2068', '2066/2067', '2065/2066', '2064/2065', '2063/2064', '2062/2063', '2061/2062', '2060/2061', '2059/2060', '2058/2059', '2057/2058']

In [ ]:
select2-results__option

In [50]:
driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(10)

DROPDOWN=driver.find_element(By.XPATH,"/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[1]/span/span[1]/span/span[1]")
DROPDOWN.click()

time.sleep(2)

al_ele=driver.find_elements(By.CLASS_NAME,"select2-results__option")

for item in al_ele:
    print(item.text)

2081/2082
2080/2081
2079/2080
2078/2079
2077/2078
2076/2077
2075/2076
2074/2075
2073/2074
2072/2073
2071/2072
2070/2071
2069/2070
2068/2069
2067/2068
2066/2067
2065/2066
2064/2065
2063/2064
2062/2063
2061/2062
2060/2061
2059/2060
2058/2059
2057/2058

## ALL the Companys Na,es

In [58]:
time.sleep(5)
all_companys_names=driver.find_element(By.XPATH,"/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[2]/span/span[1]/span/span[1]")
all_companys_names.click()

time.sleep(5)

textboxes = driver.find_elements(By.CLASS_NAME, "select2-selection__rendered")

for item in textboxes:
    print(item.text)

2079/2080
Finance

In [54]:

DROPDOWN=driver.find_element(By.XPATH,"/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[1]/span/span[1]/span/span[1]")
DROPDOWN.click()

time.sleep(2)

al_ele=driver.find_elements(By.CLASS_NAME,"select2-results__option")

for item in al_ele:
    print(item.text)

2081/2082
2080/2081
2079/2080
2078/2079
2077/2078
2076/2077
2075/2076
2074/2075
2073/2074
2072/2073
2071/2072
2070/2071
2069/2070
2068/2069
2067/2068
2066/2067
2065/2066
2064/2065
2063/2064
2062/2063
2061/2062
2060/2061
2059/2060
2058/2059
2057/2058

In [ ]:
/html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[2]/span/span[1]/span/span[1]

In [60]:
driver = webdriver.Chrome()
driver.get("https://www.sharesansar.com/proposed-dividend")
time.sleep(10)


all_companys_names=driver.find_element(By.XPATH,"//html//body//span//span//span[1]//input")
all_companys_names.click()

time.sleep(5)

textboxes = driver.find_elements(By.CLASS_NAME, "select2-selection__rendered")

for item in textboxes:
    print(item.text)

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=148.0.7778.179)
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7c2307de5+14895]
	chromedriver!GetHandleVerifier [0x7ff7c2307e50+14900]
	chromedriver!(No symbol) [0x7ff7c206d5ad]
	chromedriver!(No symbol) [0x7ff7c2058a92]
	chromedriver!(No symbol) [0x7ff7c207ee6c]
	chromedriver!(No symbol) [0x7ff7c20f71b0]
	chromedriver!(No symbol) [0x7ff7c2114172]
	chromedriver!(No symbol) [0x7ff7c20b9df8]
	chromedriver!(No symbol) [0x7ff7c20bace3]
	chromedriver!GetHandleVerifier [0x7ff7c261cc49+3296f9]
	chromedriver!GetHandleVerifier [0x7ff7c2617375+323e25]
	chromedriver!GetHandleVerifier [0x7ff7c263bc82+348732]
	chromedriver!GetHandleVerifier [0x7ff7c2326045+32af5]
	chromedriver!GetHandleVerifier [0x7ff7c232ecec+3b79c]
	chromedriver!GetHandleVerifier [0x7ff7c2311bc4+1e674]
	chromedriver!GetHandleVerifier [0x7ff7c2311d54+1e804]
	chromedriver!GetHandleVerifier [0x7ff7c22f60e7+2b97]
	KERNEL32!BaseThreadInitThunk [0x7ff8103fe957+17]
	ntdll!RtlUserThreadStart [0x7ff810d8427c+2c]

In [ ]:
# /html/body/div[2]/div/section[2]/div[3]/div/div/div/div/div[1]/div[2]/div[2]/div/form/div[2]/span/span[1]