In [ ]:
Problems

1) Find The Total Revenue Generated

2) Find The Total Revenue Genretaed by the course in each Month (jan, feb)

3)- Find The Most demand Course (higher frequency of persons join the same course is most demanding) 


4)Find The Student who never enrolled in any course
Find The course that does not enrolled by any student


5) find the Most loayal student (highest enrolled person is most loay student)

6) find the students who enrolled in both Month

## read lla the datasets

In [1]:
import pandas as pd

In [2]:
courses=pd.read_csv("courses.csv")
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [3]:
students=pd.read_csv(r"students.csv")
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [4]:
jan=pd.read_csv(r"reg-month1.csv")
jan

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [6]:
feb=pd.read_csv(r"reg-month2.csv")
feb

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

# 1) Find The Total Revenue Generated : jan , feb

In [15]:
temp=pd.concat([jan,feb],keys=["jan",'feb'])
temp=temp.reset_index()

temp.merge(courses,on='course_id',how='inner')['price'].sum()

np.int64(154247)

# 2) Find The Total Revenue Genretaed by the course in each Month (jan, feb)

In [23]:
temp=pd.concat([jan,feb],keys=["jan",'feb']).reset_index()
temp.merge(courses,on="course_id",how="inner").groupby('level_0')['price'].sum()

level_0
feb    65072
jan    89175
Name: price, dtype: int64

In [24]:
 65072+ 89175

154247

# m3)- Find The Most demand Course (higher frequency of persons join the same course is most demanding)

In [32]:
temp=pd.DataFrame(pd.concat([jan,feb])['course_id'].value_counts()).reset_index()
temp.merge(courses,on="course_id")[['course_name','count']]

        course_name  count
0            python      9
1           tableau      7
2          power bi      6
3           pyspark      6
4     data analysis      5
5            plotly      5
6          ms sxcel      5
7  machine learning      4
8            pandas      4
9               sql      2

In [35]:
pd.concat([jan,feb]).merge(courses,on="course_id")['course_name'].value_counts()

course_name
python              9
tableau             7
power bi            6
pyspark             6
data analysis       5
plotly              5
ms sxcel            5
machine learning    4
pandas              4
sql                 2
Name: count, dtype: int64

In [ ]:
# aggreate + join
# join + aggrgate :

In [38]:
pd.concat([jan,feb])['course_id'].value_counts()

course_id
1     9
5     7
6     6
10    6
3     5
9     5
7     5
4     4
8     4
2     2
Name: count, dtype: int64

In [39]:
pd.concat([jan,feb]).merge(courses,on="course_id")['course_name'].value_counts()

course_name
python              9
tableau             7
power bi            6
pyspark             6
data analysis       5
plotly              5
ms sxcel            5
machine learning    4
pandas              4
sql                 2
Name: count, dtype: int64

In [41]:
pd.concat([jan,feb]).shape

(53, 2)

In [42]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

## 4)Find The Student who never enrolled in any course
# Find The course that does not enrolled by any student

In [52]:
students.merge(pd.concat([jan,feb]),on="student_id",how="left")

    student_id                name  partner  course_id
0            1       Kailash Harjo       23        1.0
1            1       Kailash Harjo       23        6.0
2            1       Kailash Harjo       23       10.0
3            1       Kailash Harjo       23        9.0
4            2         Esha Butala        1        5.0
5            3      Parveen Bhalla        3        3.0
6            3      Parveen Bhalla        3        5.0
7            4         Marlo Dugal       14        NaN
8            5         Kusum Bahri        6        NaN
9            6  Lakshmi Contractor       10        NaN
10           7        Tarun Thaker        9        8.0
11           7        Tarun Thaker        9       10.0
12           7        Tarun Thaker        9        7.0
13           7        Tarun Thaker        9        2.0
14           7        Tarun Thaker        9        6.0
15           8      Radheshyam Dey        5        NaN
16           9   Nitika Chatterjee        4        NaN
17          10      Aayushman Sant        8        NaN
18          11  David Mukhopadhyay       20        7.0
19          11  David Mukhopadhyay       20        8.0
20          11  David Mukhopadhyay       20       10.0
21          12          Radha Dutt       19       10.0
22          12          Radha Dutt       19        1.0
23          12          Radha Dutt       19        5.0
24          12          Radha Dutt       19        7.0
25          13      Munni Varghese       24        3.0
26          14    Pranab Natarajan       22        9.0
27          14    Pranab Natarajan       22        6.0
28          14    Pranab Natarajan       22        4.0
29          14    Pranab Natarajan       22        1.0
30          15           Preet Sha       16        5.0
31          15           Preet Sha       16        1.0
32          16        Elias Dodiya       25        9.0
33          16        Elias Dodiya       25        5.0
34          16        Elias Dodiya       25        7.0
35          16        Elias Dodiya       25        3.0
36          17        Yasmin Palan        7        7.0
37          17        Yasmin Palan        7       10.0
38          18     Fardeen Mahabir       13        6.0
39          18     Fardeen Mahabir       13        1.0
40          18     Fardeen Mahabir       13        8.0
41          19        Qabeel Raman       12        4.0
42          19        Qabeel Raman       12        2.0
43          20       Hanuman Hegde       11        NaN
44          21          Seema Kota       15        1.0
45          22          Yash Sethi       21        3.0
46          22          Yash Sethi       21        5.0
47          22          Yash Sethi       21        6.0
48          23      Chhavi Lachman       18        1.0
49          23      Chhavi Lachman       18        4.0
50          23      Chhavi Lachman       18        3.0
51          23      Chhavi Lachman       18        6.0
52          23      Chhavi Lachman       18        9.0
53          23      Chhavi Lachman       18        5.0
54          24        Radhika Suri       17        4.0
55          25     Shashank D’Alia        2        1.0
56          25     Shashank D’Alia        2       10.0

### numpy , set , is  not in

In [53]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [61]:
enrolled_stu=pd.concat([jan,feb])['student_id'].unique()
enrolled_stu

array([23, 15, 18, 16,  1,  7, 22, 19, 11, 13, 24, 21, 17, 25,  3, 12, 14,
        2, 42, 50, 38])

In [67]:
students[~ students['student_id'].isin(enrolled_stu)]

    student_id                name  partner
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
19          20       Hanuman Hegde       11

In [64]:
students[students['student_id'].isin(enrolled_stu)]

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

# 6) find the students who enrolled in both Month

In [68]:
jan

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [69]:
feb

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [73]:
both_month=jan.merge(feb,on='student_id')['student_id'].unique()
both_month

array([23, 18, 16,  1,  7, 22, 11, 17,  3])

In [74]:
students[students['student_id'].isin(both_month)]

    student_id                name  partner
0            1       Kailash Harjo       23
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18

In [75]:
jan

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [76]:
feb

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1