In [1]:
from IPython.display import Image
# Image(filename='path_to_your_image.jpg') 
Image(url=r"https://dk81.github.io/dkmathstats_site/images/sql-joins.jpg")

In [2]:
import pandas as pd
import numpy as np


np.random.seed(42)

customers = pd.DataFrame({
    "customer_id": range(1001, 1016),
    "customer_name": [
        "Aarav Sharma", "Emma Johnson", "Liam Brown",
        "Olivia Wilson", "Noah Davis", "Sophia Miller",
        "William Moore", "Isabella Taylor", "James Anderson",
        "Mia Thomas", "Benjamin Jackson", "Charlotte White",
        "Lucas Harris", "Amelia Martin", "Henry Thompson"
    ],
    "city": [
        "Kathmandu", "London", "New York", "Sydney", "Toronto",
        "Berlin", "Paris", "Tokyo", "Dubai", "Singapore",
        "Mumbai", "Bangkok", "Seoul", "Chicago", "Madrid"
    ],
    "membership": [
        "Gold", "Silver", "Gold", "Bronze", "Silver",
        "Gold", "Bronze", "Silver", "Gold", "Silver",
        "Bronze", "Gold", "Silver", "Gold", "Bronze"
    ]
})




products = pd.DataFrame({
    "product_id": [201,202,203,204,205,206,207,208],
    "product_name": [
        "iPhone 15", "Samsung S24", "MacBook Air",
        "Gaming Mouse", "Mechanical Keyboard",
        "Smart Watch", "Bluetooth Speaker", "Monitor"
    ],
    "category": [
        "Mobile", "Mobile", "Laptop",
        "Accessories", "Accessories",
        "Wearable", "Audio", "Display"
    ],
    "price": [1400, 1200, 1800, 60, 120, 350, 90, 450]
})



orders = pd.DataFrame({
    "order_id": range(5001, 5021),
    "customer_id": np.random.choice(customers["customer_id"], 20),
    "product_id": np.random.choice(products["product_id"], 20),
    "quantity": np.random.randint(1, 5, 20),
    "order_date": pd.date_range(start="2025-01-01", periods=20, freq="D")
})




payments = pd.DataFrame({
    "payment_id": range(9001, 9016),
    "order_id": np.random.choice(orders["order_id"], 15, replace=False),
    "payment_method": np.random.choice(
        ["Credit Card", "PayPal", "eSewa", "Khalti"],
        15
    ),
    "payment_status": np.random.choice(
        ["Completed", "Pending", "Failed"],
        15
    )
})

In [12]:
customers.head(14)  # customer_id , customer_name , city , membership

    customer_id     customer_name       city membership
0          1001      Aarav Sharma  Kathmandu       Gold
1          1002      Emma Johnson     London     Silver
2          1003        Liam Brown   New York       Gold
3          1004     Olivia Wilson     Sydney     Bronze
4          1005        Noah Davis    Toronto     Silver
5          1006     Sophia Miller     Berlin       Gold
6          1007     William Moore      Paris     Bronze
7          1008   Isabella Taylor      Tokyo     Silver
8          1009    James Anderson      Dubai       Gold
9          1010        Mia Thomas  Singapore     Silver
10         1011  Benjamin Jackson     Mumbai     Bronze
11         1012   Charlotte White    Bangkok       Gold
12         1013      Lucas Harris      Seoul     Silver
13         1014     Amelia Martin    Chicago       Gold

In [10]:
products.head(10) # product_id ,product_name , category , price

   product_id         product_name     category  price
0         201            iPhone 15       Mobile   1400
1         202          Samsung S24       Mobile   1200
2         203          MacBook Air       Laptop   1800
3         204         Gaming Mouse  Accessories     60
4         205  Mechanical Keyboard  Accessories    120
5         206          Smart Watch     Wearable    350
6         207    Bluetooth Speaker        Audio     90
7         208              Monitor      Display    450

In [8]:
orders

    order_id  customer_id  product_id  quantity order_date
0       5001         1007         206         3 2025-01-01
1       5002         1004         205         3 2025-01-02
2       5003         1013         202         2 2025-01-03
3       5004         1015         208         4 2025-01-04
4       5005         1011         204         4 2025-01-05
5       5006         1008         206         4 2025-01-06
6       5007         1013         206         4 2025-01-07
7       5008         1005         202         3 2025-01-08
8       5009         1007         208         2 2025-01-09
9       5010         1010         204         2 2025-01-10
10      5011         1003         205         3 2025-01-11
11      5012         1007         201         2 2025-01-12
12      5013         1011         204         3 2025-01-13
13      5014         1011         202         4 2025-01-14
14      5015         1008         206         3 2025-01-15
15      5016         1005         205         4 2025-01-16
16      5017         1004         204         4 2025-01-17
17      5018         1008         201         1 2025-01-18
18      5019         1008         201         3 2025-01-19
19      5020         1003         203         1 2025-01-20

In [13]:
payments

    payment_id  order_id payment_method payment_status
0         9001      5011          eSewa      Completed
1         9002      5008          eSewa         Failed
2         9003      5001         PayPal        Pending
3         9004      5003    Credit Card        Pending
4         9005      5006         Khalti        Pending
5         9006      5017         PayPal        Pending
6         9007      5015         Khalti        Pending
7         9008      5013         Khalti        Pending
8         9009      5005         PayPal         Failed
9         9010      5014         PayPal         Failed
10        9011      5010         PayPal        Pending
11        9012      5016         PayPal         Failed
12        9013      5012         PayPal      Completed
13        9014      5018         Khalti        Pending
14        9015      5004         PayPal      Completed

## merge

In [ ]:
pd.merge(df1,df2,on=common_col, how="inner","outer","left","right")

In [14]:
customers

    customer_id     customer_name       city membership
0          1001      Aarav Sharma  Kathmandu       Gold
1          1002      Emma Johnson     London     Silver
2          1003        Liam Brown   New York       Gold
3          1004     Olivia Wilson     Sydney     Bronze
4          1005        Noah Davis    Toronto     Silver
5          1006     Sophia Miller     Berlin       Gold
6          1007     William Moore      Paris     Bronze
7          1008   Isabella Taylor      Tokyo     Silver
8          1009    James Anderson      Dubai       Gold
9          1010        Mia Thomas  Singapore     Silver
10         1011  Benjamin Jackson     Mumbai     Bronze
11         1012   Charlotte White    Bangkok       Gold
12         1013      Lucas Harris      Seoul     Silver
13         1014     Amelia Martin    Chicago       Gold
14         1015    Henry Thompson     Madrid     Bronze

In [15]:
orders

    order_id  customer_id  product_id  quantity order_date
0       5001         1007         206         3 2025-01-01
1       5002         1004         205         3 2025-01-02
2       5003         1013         202         2 2025-01-03
3       5004         1015         208         4 2025-01-04
4       5005         1011         204         4 2025-01-05
5       5006         1008         206         4 2025-01-06
6       5007         1013         206         4 2025-01-07
7       5008         1005         202         3 2025-01-08
8       5009         1007         208         2 2025-01-09
9       5010         1010         204         2 2025-01-10
10      5011         1003         205         3 2025-01-11
11      5012         1007         201         2 2025-01-12
12      5013         1011         204         3 2025-01-13
13      5014         1011         202         4 2025-01-14
14      5015         1008         206         3 2025-01-15
15      5016         1005         205         4 2025-01-16
16      5017         1004         204         4 2025-01-17
17      5018         1008         201         1 2025-01-18
18      5019         1008         201         3 2025-01-19
19      5020         1003         203         1 2025-01-20

## Extract all the ionformation frpm gthe left table common from right

In [20]:
pd.merge(customers,orders,on="customer_id",how='left').head(3)

,customer_id,customer_name,city,membership,order_id,product_id,quantity,order_date
0,1001,Aarav Sharma,Kathmandu,Gold,NaN,NaN,NaN,NaT
1,1002,Emma Johnson,London,Silver,NaN,NaN,NaN,NaT
2,1003,Liam Brown,New York,Gold,5011.0,205.0,3.0,2025-01-11

In [21]:
pd.merge(orders,customers,on="customer_id",how='right').head(3)

,order_id,customer_id,product_id,quantity,order_date,customer_name,city,membership
0,NaN,1001,NaN,NaN,NaT,Aarav Sharma,Kathmandu,Gold
1,NaN,1002,NaN,NaN,NaT,Emma Johnson,London,Silver
2,5011.0,1003,205.0,3.0,2025-01-11,Liam Brown,New York,Gold

In [22]:
pd.merge(customers,orders,on="customer_id",how='inner')

,customer_id,customer_name,city,membership,order_id,product_id,quantity,order_date
0,1003,Liam Brown,New York,Gold,5011,205,3,2025-01-11
1,1003,Liam Brown,New York,Gold,5020,203,1,2025-01-20
2,1004,Olivia Wilson,Sydney,Bronze,5002,205,3,2025-01-02
3,1004,Olivia Wilson,Sydney,Bronze,5017,204,4,2025-01-17
4,1005,Noah Davis,Toronto,Silver,5008,202,3,2025-01-08
5,1005,Noah Davis,Toronto,Silver,5016,205,4,2025-01-16
6,1007,William Moore,Paris,Bronze,5001,206,3,2025-01-01
7,1007,William Moore,Paris,Bronze,5009,208,2,2025-01-09
8,1007,William Moore,Paris,Bronze,5012,201,2,2025-01-12
9,1008,Isabella Taylor,Tokyo,Silver,5006,206,4,2025-01-06
10,1008,Isabella Taylor,Tokyo,Silver,5015,206,3,2025-01-15
11,1008,Isabella Taylor,Tokyo,Silver,5018,201,1,2025-01-18
12,1008,Isabella Taylor,Tokyo,Silver,5019,201,3,2025-01-19
13,1010,Mia Thomas,Singapore,Silver,5010,204,2,2025-01-10
14,1011,Benjamin Jackson,Mumbai,Bronze,5005,204,4,2025-01-05
15,1011,Benjamin Jackson,Mumbai,Bronze,5013,204,3,2025-01-13
16,1011,Benjamin Jackson,Mumbai,Bronze,5014,202,4,2025-01-14
17,1013,Lucas Harris,Seoul,Silver,5003,202,2,2025-01-03
18,1013,Lucas Harris,Seoul,Silver,5007,206,4,2025-01-07
19,1015,Henry Thompson,Madrid,Bronze,5004,208,4,2025-01-04

In [26]:
cust= pd.DataFrame({
    "customer_id": [1, 2, 3, 4,100],
    "customer_name": ["Alice", "Bob", "Charlie", "David","ram"]
})


ordr = pd.DataFrame({
    "customer_id": [1, 2, 2, 5,200],
    "order_amount": [250, 120, 300, 500,700]
})

In [27]:
cust  #  1 2 3 4 100 | 1 2 5 200

   customer_id customer_name
0            1         Alice
1            2           Bob
2            3       Charlie
3            4         David
4          100           ram

In [28]:
ordr

   customer_id  order_amount
0            1           250
1            2           120
2            2           300
3            5           500
4          200           700

In [30]:
pd.merge(cust,ordr ,on="customer_id",how="left")

   customer_id customer_name  order_amount
0            1         Alice         250.0
1            2           Bob         120.0
2            2           Bob         300.0
3            3       Charlie           NaN
4            4         David           NaN
5          100           ram           NaN

In [31]:
pd.merge(cust,ordr ,on="customer_id",how="right")

   customer_id customer_name  order_amount
0            1         Alice           250
1            2           Bob           120
2            2           Bob           300
3            5           NaN           500
4          200           NaN           700

In [32]:
pd.merge(cust,ordr ,on="customer_id",how="inner")

   customer_id customer_name  order_amount
0            1         Alice           250
1            2           Bob           120
2            2           Bob           300

In [ ]:
 #  1 2 3 4 100 | 1 2 5 200

In [33]:
pd.merge(cust,ordr ,on="customer_id",how="outer")

   customer_id customer_name  order_amount
0            1         Alice         250.0
1            2           Bob         120.0
2            2           Bob         300.0
3            3       Charlie           NaN
4            4         David           NaN
5            5           NaN         500.0
6          100           ram           NaN
7          200           NaN         700.0

#### merges examples

In [35]:
df1=pd.DataFrame({"ID":[1,2,3,4],"pname":['mouse',"keyboard","laptop","speaker"]})
df1

   ID     pname
0   1     mouse
1   2  keyboard
2   3    laptop
3   4   speaker

In [36]:
df2=pd.DataFrame({"ID":[5,6],"pname":["speaker","headphone"]})
df2

   ID      pname
0   5    speaker
1   6  headphone

## concat tge data

In [38]:
pd.concat([df1,df2],axis=0)

   ID      pname
0   1      mouse
1   2   keyboard
2   3     laptop
3   4    speaker
0   5    speaker
1   6  headphone

In [39]:
pd.concat([df1,df2],axis=1)

   ID     pname   ID      pname
0   1     mouse  5.0    speaker
1   2  keyboard  6.0  headphone
2   3    laptop  NaN        NaN
3   4   speaker  NaN        NaN

In [40]:
pd.concat([df1,df2])

   ID      pname
0   1      mouse
1   2   keyboard
2   3     laptop
3   4    speaker
0   5    speaker
1   6  headphone

In [41]:
pd.concat([df1,df2],ignore_index=True)

   ID      pname
0   1      mouse
1   2   keyboard
2   3     laptop
3   4    speaker
4   5    speaker
5   6  headphone

In [42]:
pd.concat([df1,df2],keys=["data1","data2"])

         ID      pname
data1 0   1      mouse
      1   2   keyboard
      2   3     laptop
      3   4    speaker
data2 0   5    speaker
      1   6  headphone

In [44]:
import os
os.getcwd()

'R:\\adarsha\\evening_class'

In [ ]:


# =========================================================
# INNER MERGE
# =========================================================
# Merge Orders with Customers

inner_merge = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="inner"
)

print("\nINNER MERGE")
print(inner_merge.head())


# =========================================================
# LEFT MERGE
# =========================================================
# Merge Orders with Payments

left_merge = pd.merge(
    orders,
    payments,
    on="order_id",
    how="left"
)

print("\nLEFT MERGE")
print(left_merge.head())


# =========================================================
# MULTIPLE TABLE MERGE
# =========================================================

full_data = (
    orders
    .merge(customers, on="customer_id", how="left")
    .merge(products, on="product_id", how="left")
    .merge(payments, on="order_id", how="left")
)

print("\nFULL MERGED DATASET")
print(full_data.head())


# =========================================================
# CALCULATE TOTAL SALES
# =========================================================

full_data["total_sales"] = (
    full_data["quantity"] * full_data["price"]
)

print("\nFINAL DATASET WITH SALES")
print(full_data.head())


# =========================================================
# BUSINESS ANALYSIS
# =========================================================

sales_summary = (
    full_data.groupby("category")["total_sales"]
    .sum()
    .reset_index()
    .sort_values(by="total_sales", ascending=False)
)

print("\nSALES SUMMARY")
print(sales_summary)