In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\HP\Desktop\New folder (2)\tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## fins the total Bill Generated by Sunday and friday and thursday

In [4]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
df[df['day']=="Sun"]['total_bill'].sum()

np.float64(1627.16)

In [8]:
df[df['day']=="Sat"]['total_bill'].sum()

np.float64(1778.3999999999999)

In [11]:
df[(df['day']=="Sun") & (df['sex']=="Female")]['total_bill'].sum()

np.float64(357.69999999999993)

In [12]:
df[(df['day']=="Sun") & (df['sex']=="Male")]['total_bill'].sum()

np.float64(1269.46)

## group by

In [13]:
from IPython.display import Image, display
# For local files
display(Image(url=r'https://www.simplilearn.com/ice9/free_resources_article_thumb/group_by_strategy-SQL_group_by.PNG'))

In [14]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## find the Total sales across the gender wise

In [15]:
df.groupby('sex')['total_bill'].sum()

sex
Female    1570.95
Male      3256.82
Name: total_bill, dtype: float64

In [18]:
df[df['sex']=="Female"]['total_bill'].sum()

np.float64(1570.9499999999996)

In [19]:
df[df['sex']=="Male"]['total_bill'].sum()

np.float64(3256.8199999999997)

### fins the total Bill actross the day wise

In [22]:
df.groupby('day')['total_bill'].sum()

day
Fri      325.88
Sat     1778.40
Sun     1627.16
Thur    1096.33
Name: total_bill, dtype: float64

In [24]:
df.groupby(['day','sex'])['total_bill'].sum()

day   sex
Fri   Female     127.31
      Male       198.57
Sat   Female     551.05
      Male      1227.35
Sun   Female     357.70
      Male      1269.46
Thur  Female     534.89
      Male       561.44
Name: total_bill, dtype: float64

In [25]:
df.groupby(['day','sex'])['total_bill'].mean()

day   sex
Fri   Female    14.145556
      Male      19.857000
Sat   Female    19.680357
      Male      20.802542
Sun   Female    19.872222
      Male      21.887241
Thur  Female    16.715312
      Male      18.714667
Name: total_bill, dtype: float64

In [26]:
df.groupby(['day','sex'])['total_bill'].std()

day   sex
Fri   Female     4.788547
      Male      10.015847
Sat   Female     8.806470
      Male       9.836306
Sun   Female     7.837513
      Male       9.129142
Thur  Female     7.759764
      Male       8.019728
Name: total_bill, dtype: float64

In [27]:
df.groupby(['day','sex'])['total_bill'].median()

day   sex
Fri   Female    15.380
      Male      17.215
Sat   Female    18.360
      Male      18.240
Sun   Female    17.410
      Male      20.725
Thur  Female    13.785
      Male      16.975
Name: total_bill, dtype: float64

In [29]:
df.groupby(['day','sex'])['total_bill'].std()

day   sex
Fri   Female     4.788547
      Male      10.015847
Sat   Female     8.806470
      Male       9.836306
Sun   Female     7.837513
      Male       9.129142
Thur  Female     7.759764
      Male       8.019728
Name: total_bill, dtype: float64

## Grouping with Multiple column

In [30]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
df.groupby('sex').agg({'total_bill':['sum','min','max'],'tip':['sum','mean'],'size':'sum'})

       total_bill                  tip           size
              sum   min    max     sum      mean  sum
sex
Female    1570.95  3.07  44.30  246.51  2.833448  214
Male      3256.82  7.25  50.81  485.07  3.089618  413

In [36]:
df[df['sex']=="Female"]['total_bill'].max()

np.float64(44.3)

In [39]:
df[df['sex']=="Female"]['size'].sum()

np.int64(214)

In [40]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\New folder (2)'