In [1]:
import pandas as pd

In [2]:
all_company_ids=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\data_fetch_of_all_comoany\all_company_ids.csv")

In [6]:
all_company_ids[all_company_ids["companyId"].isin([885,1096,1082,747])]

,companyId,nepseCompanyId,companyName,stockSymbol,sector,type
55,1082,0,Citizens Sadabahar Yojana,CSBY,Mutual Fund,Mutual Fund
56,1096,0,Citizens Santulit Yojana,CSY,Mutual Fund,Mutual Fund
421,747,0,Siddhartha Systematic Investment Scheme,SSIS,Mutual Fund,Mutual Fund
465,885,0,Citizens Super 30 Mutual Fund,C30MF,Mutual Fund,Mutual Fund

## Extract all the datasets

In [3]:
data=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\open_ended.csv")

# open ended

In [9]:
data

,Company,Fund Size,Units,Fund Managers,Weekly NAV\n(Rs),Weekly NAV\nDate,type
0,CSBY,50.00 Cr,5.00 Cr,Citizens Capital Limited,10.33,2083-01-25 BS,Open-Ended
1,ELIS,1.00 Arb,10.00 Cr,NIC Asia Capital Limited,9.84,2083-02-01 BS,Open-Ended
2,KSLY,1.00 Arb,10.00 Cr,Kumari Capital Limited,12.13,2083-02-01 BS,Open-Ended
3,NADDF,2.00 Arb,20.00 Cr,NIC Asia Capital Limited,10.00,2083-02-01 BS,Open-Ended
4,NFCF,2.25 Arb,22.50 Cr,Nabil Investment Banking Limited,10.45,2083-02-01 BS,Open-Ended
5,NI31,25.00 Cr,2.50 Cr,Nabil Investment Banking Limited,10.34,2083-02-01 BS,Open-Ended
6,NIBLSF,6.00 Arb,60.00 Cr,NIMB Ace Capital Limited,10.25,2083-01-25 BS,Open-Ended
7,NMBSBF,1.00 Arb,10.00 Cr,NMB Capital Limited,10.72,2083-02-01 BS,Open-Ended
8,SFF,1.00 Arb,10.00 Cr,Sanima Capital Limited,10.48,2083-02-01 BS,Open-Ended
9,SLK,1.00 Arb,10.00 Cr,Laxmi Capital Market Limited,10.40,2083-01-25 BS,Open-Ended
10,SSIS,2.80 Arb,28.00 Cr,Siddhartha Capital Limited,11.01,2083-02-01 BS,Open-Ended

In [13]:
data['Company'].tolist()

['CSBY',
 'ELIS',
 'KSLY',
 'NADDF',
 'NFCF',
 'NI31',
 'NIBLSF',
 'NMBSBF',
 'SFF',
 'SLK',
 'SSIS']

In [ ]:
https://app.smartwealthpro.com/MutualFund/Overview/Siddhartha-Systematic-Investment-Scheme/SSIS?c=747

In [10]:
all_listed_companys=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\data_fetch_of_all_comoany\all_company_ids.csv")

In [11]:
all_listed_companys

,companyId,nepseCompanyId,companyName,stockSymbol,sector,type
0,596,0,Aarambha Chautari Laghubitta Bittiya Sanstha L...,ACLBSL,Microfinance,Ordinary Share
1,947,0,Aarambha Chautari Laghubitta Bittiya Sanstha L...,ACLBSLP,Microfinance,Ordinary Share
2,2,0,Agricultural Development Bank Limited,ADBL,Commercial Banks,Ordinary Share
3,950,0,4% AGRICULTURAL BOND,ADBLB,Corporate Debenture,Bond and Debenture
4,969,0,Agricultural Development Bank Limited Promoter...,ADBLP,Commercial Banks,Promoter Share
...,...,...,...,...,...,...
557,1102,0,Siddhartha Equity Fund 2,SEF2,Mutual Fund,Mutual Fund
558,521,0,Siddhartha Investment Growth Scheme-1,SIGS1,Mutual Fund,Mutual Fund
559,199,0,Siddhartha Investment Growth Scheme - 2,SIGS2,Mutual Fund,Mutual Fund
560,878,0,Siddhartha Investment Growth Scheme-3,SIGS3,Mutual Fund,Mutual Fund
561,363,0,10.25% Sunrise Bank Debenture 2083,SRBLD83,Corporate Debenture,Bond and Debenture

In [14]:
all_listed_companys[all_listed_companys['stockSymbol'].isin(data['Company'].tolist())]

,companyId,nepseCompanyId,companyName,stockSymbol,sector,type
55,1082,0,Citizens Sadabahar Yojana,CSBY,Mutual Fund,Mutual Fund
74,1087,0,NIC Asia Equity Linked Investment Scheme,ELIS,Mutual Fund,Mutual Fund
226,622,0,NIC Asia Dynamic Debt Fund,NADDF,Mutual Fund,Mutual Fund
235,836,0,Nabil Flexi Cap Fund,NFCF,Mutual Fund,Mutual Fund
243,601,0,NIBL Sahabhagita Fund,NIBLSF,Mutual Fund,Mutual Fund
273,737,0,NMB Saral Bachat Fund - E (Open End),NMBSBF,Mutual Fund,Mutual Fund
361,1067,0,Sanima Flexi Fund,SFF,Mutual Fund,Mutual Fund
395,821,0,Subha Laxmi Kosh,SLK,Mutual Fund,Mutual Fund
421,747,0,Siddhartha Systematic Investment Scheme,SSIS,Mutual Fund,Mutual Fund
514,1088,0,NI 31,NI31,Mutual Fund,Mutual Fund

In [17]:
open_listed=all_listed_companys[all_listed_companys['stockSymbol'].isin(data['Company'].tolist())][['companyId','companyName','stockSymbol']]

In [18]:
open_listed

     companyId                               companyName stockSymbol
55        1082                 Citizens Sadabahar Yojana        CSBY
74        1087  NIC Asia Equity Linked Investment Scheme        ELIS
226        622                NIC Asia Dynamic Debt Fund       NADDF
235        836                      Nabil Flexi Cap Fund        NFCF
243        601                     NIBL Sahabhagita Fund      NIBLSF
273        737      NMB Saral Bachat Fund - E (Open End)      NMBSBF
361       1067                         Sanima Flexi Fund         SFF
395        821                          Subha Laxmi Kosh         SLK
421        747   Siddhartha Systematic Investment Scheme        SSIS
514       1088                                     NI 31        NI31

In [ ]:
https://app.smartwealthpro.com/MutualFund/Overview/NMB-Saral-Bachat-Fund---E-(Open-End)/NMBSBF?c=737
https://app.smartwealthpro.com/MutualFund/Overview/Citizens-Sadabahar-Yojana/CSBY?c=1082


https://app.smartwealthpro.com/MutualFund/Overview/NI-31/NI31?c=1088
https://app.smartwealthpro.com/MutualFund/Overview/NMB-Saral-Bachat-Fund---E-(Open-End)/NMBSBF?c=737

## Extract all the urls

In [4]:
from selenium import webdriver

driver = webdriver.Chrome()
from selenium.webdriver.common.by import By
driver.get("https://app.smartwealthpro.com/MutualFund/Overview")

In [5]:
# /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[44]/td[1]/a[1]
from selenium.webdriver.common.by import By

closed_ended=[]

for i in range(1,45):
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a[1]").get_attribute("href")
    closed_ended.append(url_links)

In [6]:
open_ended=[]

for i in range(1,12):
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    open_ended.append(url_links)

In [7]:
open_ended

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956']

# matured

In [8]:
matured=[]
for i in range(1,11):
    # /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[1]/a
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    matured.append(url_links)

In [27]:
matured

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729']

In [28]:
## Trades info  : close ended 

# weekly nav
# /html/body/div[7]/div[1]/div/div/div[1]/div[1]/div[3]


# schema profiles
# /html/body/div[7]/div[1]/div/div/div[1]/div[2]/div/button/div


# corporate acgtions
# /html/body/div[7]/div[1]/div/div/div[2]/div[3]/div


# market summary
# /html/body/div[7]/div[1]/div/div/div[3]/div[1]/div[2]


# performance
# /html/body/div[7]/div[1]/div/div/div[3]/div[2]/div/table


# financials
# /html/body/div[7]/div[1]/div/div/div[3]/div[3]/div/table


# assets allocations
# /html/body/div[7]/div[2]/div/div/div[2]/div


# sectorwise allocations 
# /html/body/div[7]/div[2]/div/div/div[3]/div/div[3]

In [29]:
weekly_nav=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[1]/div[1]/div[3]").text
schema_profiles=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[1]/div[2]/div/button/div").text
corporate_actions=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[2]/div[3]/div").text
market_summary=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[1]/div[2]").text
performance=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[2]/div/table").text


financials=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[3]/div/table").text
assets_allocations=driver.find_element(By.XPATH,"/html/body/div[7]/div[2]/div/div/div[2]/div").text
sectorwise_allocations=driver.find_element(By.XPATH,"/html/body/div[7]/div[2]/div/div/div[3]/div/div[3]").text

In [30]:
weekly_nav

'10.00\n0.00 (0.00%)\nWeekly NAV\n10.76\nTrade Day Range\nL\n9.92 - 10.00\nH\nVolume\n1,500\n180 Days Avg Price\n9.77\n52 Weeks Range\nL\n8.70 - 10.71\nH\nAs of Wed, 27 May 2026 | 02:32 PM'

In [31]:
schema_profiles

'Mutual Fund Name\nC30MF\nFund Manager / Depository\nCitizens Capital Limited\nSponsor\nCitizens Bank International Ltd.\nFund Size\nNPR 750,723,900\nType\nClose-End Scheme\nLaunch Date\n2079-12-08 BS\nMaturity Date\n2090-02-01 BS\nPeriod\n10 yrs\nPrice per Unit\nNPR 10.00\nTotal Units\n75,072,390 units'

In [32]:
corporate_actions

'Corporate Action\nDividend (Bonus/Cash)\nFiscal Year\n2081/2082\nTotal Dividend (12.75%)\nBonus (0%), Cash (12.75%)\nBook Close Date\n2025-08-29 AD (2082-05-13 BS)\nRight\nFiscal Year\n-\nRatio\n-\nBook Close Date\n-\nAGM/SGM\nLast AGM\n-\nNext AGM\n-\nView More'

In [33]:
market_summary

'Last Trade Price\n10.00\nTurnover *\n14,992.00\nChg (% Chg)\n0.00 (0.00%)\nVolume\n1,500\nTrade Day Open\n9.92\n3M Avg Vol\n35,369.65\nPrevious Close\n10.00\nTransaction *\n0\n120 Days VWAP\n10.07\n180 Days VWAP\n9.92\nO/S Shares\n75,072,390\nMarket Cap\n750,723,900.00\nBeta (Daily)\n0.30\nDividend Yield\n0.00%\nVar @ 5% 1M\n-8.41%\nVol Wt Avg Price\n9.99\n% Below 52 Wk High\n11.72%\n% Above 52 Wk Low\n11.44%\nTrade Day Range\n9.92\n10.00\nLow\nHigh\n52 Wk Range\n8.70\n10.71\nLow\nHigh\n5 Days Performance'

In [34]:
performance

'Date Value 1M 3M 6M YTD 1Y\nLatest Price 2026-05-27 10.00 -0.99% 4.93% 12.49% 0.00% 0.00%\nMonthly NAV Chaitra 2082 10.99 -0.09% 4.96% 13.53% -7.56% 1.47%'

In [35]:
financials

'Particulars Amount M-to-M % Change\nTotal Assets 828,773,634.00 0.06%\nTotal Liabilities 17,296,691.00 31.81%\nNet Assets 825,276,302.00 0.08%\nNet Assets Value per Share 10.99 0.09%\nExpenses & Fees 11,005,744.00 13.04%\nNet Income/(Expenses) 74,507,950.00 0.91%'

In [36]:
assets_allocations

"Assets Allocation\nAs of Chaitra 2082\n(Figures are in '000 except for ratio, price and % change.)\nBy Asset Class Amount % of Total Assets\nEquity Stocks 635,630.54 76.70%\nBonds & Debentures - -\nIPO/FPO/Rights/Bonus - -\nBanks Fixed Deposits 40,000.00 4.83%\nCash & Others 153,143.09 18.48%\n\nTotal Assets: 828,773.63\n76.7 %76.7 %\n0 %0 %\n0 %0 %\n4.83 %4.83 %\n18.48 %18.48 %\nEquity Stocks\nBonds & Debentures\nIPO/FPO/Rights/Bonus\nBanks Fixed Deposits\nCash & Others"

In [38]:
sectorwise_allocations

'By Sectorwise Amount % Sectorwise % of Total Assets\nCommercial Banks 151,267,704.00 23.92% 18.25%\nDevelopment Banks 35,831,163.00 5.67% 4.32%\nHotels and Tourism 21,531,279.00 3.40% 2.60%\nHydro Power 109,196,332.00 17.27% 13.18%\nInvestment 3,592,000.00 0.57% 0.43%\nLife Insurance 54,116,694.00 8.56% 6.53%\nManufacturing and Processing 35,346,207.00 5.59% 4.26%\nMicrofinance 44,804,000.00 7.08% 5.41%\nMutual Fund 36,412,839.00 5.76% 4.39%\nNon Life Insurance 101,720,869.00 16.08% 12.27%\nOthers 38,584,000.00 6.10% 4.66%'

In [39]:
driver.title

'Overview | Smart Wealth Pro'

In [42]:
matured[0].split("=")[1]

'885'

In [15]:
all_dicts={}

In [17]:
import time


for url in closed_ended[40:]:
    driver.get(url)
    time.sleep(5)
    weekly_nav=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[1]/div[1]/div[3]").text
    schema_profiles=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[1]/div[2]/div/button/div").text
    corporate_actions=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[2]/div[3]/div").text
    market_summary=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[1]/div[2]").text
    performance=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[2]/div/table").text
    financials=driver.find_element(By.XPATH,"/html/body/div[7]/div[1]/div/div/div[3]/div[3]/div/table").text
    assets_allocations=driver.find_element(By.XPATH,"/html/body/div[7]/div[2]/div/div/div[2]/div").text
    sectorwise_allocations=driver.find_element(By.XPATH,"/html/body/div[7]/div[2]/div/div/div[3]/div/div[3]").text
    company_id=url.split("=")[1]   

    info_dicts={"weekly_nav":weekly_nav,"schema_profiles":schema_profiles,"corporate_actions":corporate_actions,
     "market_summary":market_summary,"performance":performance,"financials":financials,
      "assets_allocations":assets_allocations,"sectorwise_allocations":sectorwise_allocations}
    all_dicts[company_id]=info_dicts

In [18]:
len(all_dicts)

42

In [12]:
len(closed_ended)

44

In [46]:
closed_ended

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
 'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
 'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
 'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
 'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
 'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
 'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
 'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629']

# closed ended

In [50]:
all_dicts.keys()

dict_keys(['885', '184', '1096', '1092', '815', '1049', '935', '1091', '797', '729', '956', '598', '923', '1070', '764', '982', '188', '768', '849', '954', '728', '192', '798', '949', '735', '597', '1066', '824', '1097', '881', '734', '1090', '736', '884', '1072', '833', '720', '197', '850', '200', '199', '878', '629'])

## data cleanings

In [55]:
all_dicts['885']['weekly_nav'].split("\n")[:2]

['10.00', '0.00 (0.00%)']

In [56]:
all_dicts['885']['weekly_nav'].split("\n")

['10.00',
 '0.00 (0.00%)',
 'Weekly NAV',
 '10.76',
 'Trade Day Range',
 'L',
 '9.92 - 10.00',
 'H',
 'Volume',
 '1,500',
 '180 Days Avg Price',
 '9.77',
 '52 Weeks Range',
 'L',
 '8.70 - 10.71',
 'H',
 'As of Wednesday, 27 May 2026 02:40 PM']

In [59]:
len(all_dicts['885']['weekly_nav'].split("\n"))

17

In [62]:
pd.Series(all_dicts['885']['weekly_nav'].split("\n"))

0                                     10.00
1                              0.00 (0.00%)
2                                Weekly NAV
3                                     10.76
4                           Trade Day Range
5                                         L
6                              9.92 - 10.00
7                                         H
8                                    Volume
9                                     1,500
10                       180 Days Avg Price
11                                     9.77
12                           52 Weeks Range
13                                        L
14                             8.70 - 10.71
15                                        H
16    As of Wednesday, 27 May 2026 02:40 PM
dtype: object

In [20]:
ser_cols=['Current_Price','Price_change/price_change_%','Weekly NAV','Trade_Day_Range','Volume','180 Days Avg Price','52 Weeks Range',"time_stamps"]

## weekly nav

In [19]:
ser=pd.DataFrame(all_dicts['885']['weekly_nav'].split("\n"))
ser_final=ser.iloc[[0,1,3,6,9,11,14,16]]
ser_final.index=ser_cols

NameError: name 'ser_cols' is not defined

In [74]:
ser_final.rename(columns={0:"Data"})

                                                     Data
percentage                                          10.00
percentage_2                                 0.00 (0.00%)
Weekly NAV                                          10.76
Trade_Day_Range                              9.92 - 10.00
Volume                                              1,500
180 Days Avg Price                                   9.77
52 Weeks Range                               8.70 - 10.71
time                As of Wednesday, 27 May 2026 02:40 PM

In [76]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [77]:
all_dicts['885']['schema_profiles']

'Mutual Fund Name\nC30MF\nFund Manager / Depository\nCitizens Capital Limited\nSponsor\nCitizens Bank International Ltd.\nFund Size\nNPR 750,723,900\nType\nClose-End Scheme\nLaunch Date\n2079-12-08 BS\nMaturity Date\n2090-02-01 BS\nPeriod\n10 yrs\nPrice per Unit\nNPR 10.00\nTotal Units\n75,072,390 units'

In [79]:
all_dicts['885']['schema_profiles'].split('\n')[::2]

['Mutual Fund Name',
 'Fund Manager / Depository',
 'Sponsor',
 'Fund Size',
 'Type',
 'Launch Date',
 'Maturity Date',
 'Period',
 'Price per Unit',
 'Total Units']

# schema prifiles

In [85]:
sp=pd.DataFrame(all_dicts['885']['schema_profiles'].split('\n')[1::2])
sp.index=all_dicts['885']['schema_profiles'].split('\n')[::2]
sp.rename(columns={0:"Data"})

                                                       Data
Mutual Fund Name                                      C30MF
Fund Manager / Depository          Citizens Capital Limited
Sponsor                    Citizens Bank International Ltd.
Fund Size                                   NPR 750,723,900
Type                                       Close-End Scheme
Launch Date                                   2079-12-08 BS
Maturity Date                                 2090-02-01 BS
Period                                               10 yrs
Price per Unit                                    NPR 10.00
Total Units                                75,072,390 units

In [91]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [92]:
all_dicts['885']['corporate_actions']

'Corporate Action\nDividend (Bonus/Cash)\nFiscal Year\n2081/2082\nTotal Dividend (12.75%)\nBonus (0%), Cash (12.75%)\nBook Close Date\n2025-08-29 AD (2082-05-13 BS)\nRight\nFiscal Year\n-\nRatio\n-\nBook Close Date\n-\nAGM/SGM\nLast AGM\n-\nNext AGM\n-\nView More'

In [96]:
all_dicts['885']['market_summary'].split("\n")[::2]

['Last Trade Price',
 'Turnover *',
 'Chg (% Chg)',
 'Volume',
 'Trade Day Open',
 '3M Avg Vol',
 'Previous Close',
 'Transaction *',
 '120 Days VWAP',
 '180 Days VWAP',
 'O/S Shares',
 'Market Cap',
 'Beta (Daily)',
 'Dividend Yield',
 'Var @ 5% 1M',
 'Vol Wt Avg Price',
 '% Below 52 Wk High',
 '% Above 52 Wk Low',
 'Trade Day Range',
 '10.00',
 'High',
 '8.70',
 'Low',
 '5 Days Performance']

In [97]:
all_dicts['885']['market_summary'].split("\n")[1::2]

['10.00',
 '14,992.00',
 '0.00 (0.00%)',
 '1,500',
 '9.92',
 '35,369.65',
 '10.00',
 '0',
 '10.07',
 '9.92',
 '75,072,390',
 '750,723,900.00',
 '0.30',
 '0.00%',
 '-8.41%',
 '9.99',
 '11.72%',
 '11.44%',
 '9.92',
 'Low',
 '52 Wk Range',
 '10.71',
 'High']

In [102]:
all_dicts['885']['market_summary'].split("\n")[:-3]

['Last Trade Price',
 '10.00',
 'Turnover *',
 '14,992.00',
 'Chg (% Chg)',
 '0.00 (0.00%)',
 'Volume',
 '1,500',
 'Trade Day Open',
 '9.92',
 '3M Avg Vol',
 '35,369.65',
 'Previous Close',
 '10.00',
 'Transaction *',
 '0',
 '120 Days VWAP',
 '10.07',
 '180 Days VWAP',
 '9.92',
 'O/S Shares',
 '75,072,390',
 'Market Cap',
 '750,723,900.00',
 'Beta (Daily)',
 '0.30',
 'Dividend Yield',
 '0.00%',
 'Var @ 5% 1M',
 '-8.41%',
 'Vol Wt Avg Price',
 '9.99',
 '% Below 52 Wk High',
 '11.72%',
 '% Above 52 Wk Low',
 '11.44%',
 'Trade Day Range',
 '9.92',
 '10.00',
 'Low',
 'High',
 '52 Wk Range',
 '8.70',
 '10.71']

In [126]:
td=all_di cts['885']['market_summary'].split("\n")[-11:]
td[1]+"-"+td[2]

wk_52_range=td[-5] + '-'+td[-4]
td_range=td[1]+"-"+td[2]

rem=["Trade Day Range",td_range,"wk_52_range",wk_52_range]
td+rem

['Trade Day Range',
 '9.92',
 '10.00',
 'Low',
 'High',
 '52 Wk Range',
 '8.70',
 '10.71',
 'Low',
 'High',
 '5 Days Performance',
 'Trade Day Range',
 '9.92-10.00',
 'wk_52_range',
 '8.70-10.71']

In [119]:
wk_52_range=td[-5] + '-'+td[-4]
td_range=td[1]+"-"+td[2]

'8.70-10.71'

In [120]:
td

['Trade Day Range',
 '9.92',
 '10.00',
 'Low',
 'High',
 '52 Wk Range',
 '8.70',
 '10.71',
 'Low',
 'High',
 '5 Days Performance']

In [123]:
last_11=all_dicts['885']['market_summary'].split("\n")[:-11]

['Last Trade Price',
 '10.00',
 'Turnover *',
 '14,992.00',
 'Chg (% Chg)',
 '0.00 (0.00%)',
 'Volume',
 '1,500',
 'Trade Day Open',
 '9.92',
 '3M Avg Vol',
 '35,369.65',
 'Previous Close',
 '10.00',
 'Transaction *',
 '0',
 '120 Days VWAP',
 '10.07',
 '180 Days VWAP',
 '9.92',
 'O/S Shares',
 '75,072,390',
 'Market Cap',
 '750,723,900.00',
 'Beta (Daily)',
 '0.30',
 'Dividend Yield',
 '0.00%',
 'Var @ 5% 1M',
 '-8.41%',
 'Vol Wt Avg Price',
 '9.99',
 '% Below 52 Wk High',
 '11.72%',
 '% Above 52 Wk Low',
 '11.44%']

In [124]:
all_dicts['885']['market_summary'].split("\n")

['Last Trade Price',
 '10.00',
 'Turnover *',
 '14,992.00',
 'Chg (% Chg)',
 '0.00 (0.00%)',
 'Volume',
 '1,500',
 'Trade Day Open',
 '9.92',
 '3M Avg Vol',
 '35,369.65',
 'Previous Close',
 '10.00',
 'Transaction *',
 '0',
 '120 Days VWAP',
 '10.07',
 '180 Days VWAP',
 '9.92',
 'O/S Shares',
 '75,072,390',
 'Market Cap',
 '750,723,900.00',
 'Beta (Daily)',
 '0.30',
 'Dividend Yield',
 '0.00%',
 'Var @ 5% 1M',
 '-8.41%',
 'Vol Wt Avg Price',
 '9.99',
 '% Below 52 Wk High',
 '11.72%',
 '% Above 52 Wk Low',
 '11.44%',
 'Trade Day Range',
 '9.92',
 '10.00',
 'Low',
 'High',
 '52 Wk Range',
 '8.70',
 '10.71',
 'Low',
 'High',
 '5 Days Performance']

In [132]:
temps=all_dicts['885']['market_summary'].split("\n")[:-11] 

td=all_dicts['885']['market_summary'].split("\n")[-11:]
wk_52_range=td[-5] + '-'+td[-4]
td_range=td[1]+"-"+td[2]

rem=["Trade Day Range",td_range,"wk_52_range",wk_52_range]
final=temps+rem
final

['Last Trade Price',
 '10.00',
 'Turnover *',
 '14,992.00',
 'Chg (% Chg)',
 '0.00 (0.00%)',
 'Volume',
 '1,500',
 'Trade Day Open',
 '9.92',
 '3M Avg Vol',
 '35,369.65',
 'Previous Close',
 '10.00',
 'Transaction *',
 '0',
 '120 Days VWAP',
 '10.07',
 '180 Days VWAP',
 '9.92',
 'O/S Shares',
 '75,072,390',
 'Market Cap',
 '750,723,900.00',
 'Beta (Daily)',
 '0.30',
 'Dividend Yield',
 '0.00%',
 'Var @ 5% 1M',
 '-8.41%',
 'Vol Wt Avg Price',
 '9.99',
 '% Below 52 Wk High',
 '11.72%',
 '% Above 52 Wk Low',
 '11.44%',
 'Trade Day Range',
 '9.92-10.00',
 'wk_52_range',
 '8.70-10.71']

In [133]:
final[::2]

['Last Trade Price',
 'Turnover *',
 'Chg (% Chg)',
 'Volume',
 'Trade Day Open',
 '3M Avg Vol',
 'Previous Close',
 'Transaction *',
 '120 Days VWAP',
 '180 Days VWAP',
 'O/S Shares',
 'Market Cap',
 'Beta (Daily)',
 'Dividend Yield',
 'Var @ 5% 1M',
 'Vol Wt Avg Price',
 '% Below 52 Wk High',
 '% Above 52 Wk Low',
 'Trade Day Range',
 'wk_52_range']

# Market Summary

In [139]:
temps=all_dicts['885']['market_summary'].split("\n")[:-11] 

td=all_dicts['885']['market_summary'].split("\n")[-11:]
wk_52_range=td[-5] + '-'+td[-4]
td_range=td[1]+"-"+td[2]

rem=["Trade Day Range",td_range,"wk_52_range",wk_52_range]
final=temps+rem


series=pd.DataFrame((final[1::2]))
series.index=final[::2]
series.rename(columns={0:"data"})

                              data
Last Trade Price             10.00
Turnover *               14,992.00
Chg (% Chg)           0.00 (0.00%)
Volume                       1,500
Trade Day Open                9.92
3M Avg Vol               35,369.65
Previous Close               10.00
Transaction *                    0
120 Days VWAP                10.07
180 Days VWAP                 9.92
O/S Shares              75,072,390
Market Cap          750,723,900.00
Beta (Daily)                  0.30
Dividend Yield               0.00%
Var @ 5% 1M                 -8.41%
Vol Wt Avg Price              9.99
% Below 52 Wk High          11.72%
% Above 52 Wk Low           11.44%
Trade Day Range         9.92-10.00
wk_52_range             8.70-10.71

In [141]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [155]:
per=all_dicts['885']['performance'].split("\n")
per

['Date Value 1M 3M 6M YTD 1Y',
 'Latest Price 2026-05-27 10.00 -0.99% 4.93% 12.49% 0.00% 0.00%',
 'Monthly NAV Chaitra 2082 10.99 -0.09% 4.96% 13.53% -7.56% 1.47%']

In [156]:
headers=per[0]
headers

'Date Value 1M 3M 6M YTD 1Y'

In [170]:
['-']+headers.split()

['-', 'Date', 'Value', '1M', '3M', '6M', 'YTD', '1Y']

In [175]:
all_data=[]
for item in per[1:]:
    firsts=item.split()[0]+'_'+item.split()[1]
    # print(item.split()[2:])
    all_data.append([firsts]+item.split()[2:])
    
temps=pd.DataFrame(all_data)
temps.iloc[1]

0    Monthly_NAV
1        Chaitra
2           2082
3          10.99
4         -0.09%
5          4.96%
6         13.53%
7         -7.56%
8          1.47%
Name: 1, dtype: object

In [180]:
temps.iloc[1][1]+"-"+temps.iloc[1][2]

'Chaitra-2082'

In [187]:
temps.iloc[1].iloc[[1,2]]=temps.iloc[1][1]+"-"+temps.iloc[1][2]

C:\Users\HP\AppData\Local\Temp\ipykernel_1416\2304556239.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  temps.iloc[1].iloc[[1,2]]=temps.iloc[1][1]+"-"+temps.iloc[1][2]

In [194]:
temps.loc[1]=temps.iloc[1].drop_duplicates()
temps

,0,1,2,3,4,5,6,7,8
0,Latest_Price,2026-05-27,10.00,-0.99%,4.93%,12.49%,0.00%,0.00%,None
1,Monthly_NAV,Chaitra-2082,NaN,10.99,-0.09%,4.96%,13.53%,-7.56%,1.47%

#### aniother

In [198]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [199]:
all_dicts['885']['financials']

'Particulars Amount M-to-M % Change\nTotal Assets 828,773,634.00 0.06%\nTotal Liabilities 17,296,691.00 31.81%\nNet Assets 825,276,302.00 0.08%\nNet Assets Value per Share 10.99 0.09%\nExpenses & Fees 11,005,744.00 13.04%\nNet Income/(Expenses) 74,507,950.00 0.91%'

# financials

In [267]:
temps=pd.DataFrame(all_dicts['885']['financials'].split("\n"))
temps3=pd.DataFrame(temps.iloc[1:][0].str.split(" ").str[-2:].apply(lambda x : '|'.join(x)))
temps3=temps3[0].str.split("|",expand=True)

index=['Total Assets',"Total  Liabilities","Net Assets","Net Assets Value per Share","Expenses & Fees","Net, Income/(Expenses)"]
temps3["particulars"]=index
temps3=temps3[['particulars',0,1]]
temps3.columns=["Particulars", "Amount" ,"M-to-M%, Change"]

temps3

                  Particulars          Amount M-to-M%, Change
1                Total Assets  828,773,634.00           0.06%
2          Total  Liabilities   17,296,691.00          31.81%
3                  Net Assets  825,276,302.00           0.08%
4  Net Assets Value per Share           10.99           0.09%
5             Expenses & Fees   11,005,744.00          13.04%
6      Net, Income/(Expenses)   74,507,950.00           0.91%

In [253]:
temps3=pd.DataFrame(temps.iloc[1:][0].str.split(" ").str[-2:].apply(lambda x : '|'.join(x)))
temps3

                      0
1  828,773,634.00|0.06%
2  17,296,691.00|31.81%
3  825,276,302.00|0.08%
4           10.99|0.09%
5  11,005,744.00|13.04%
6   74,507,950.00|0.91%

In [257]:
temps3=temps3[0].str.split("|",expand=True)
temps3

                0       1
1  828,773,634.00   0.06%
2   17,296,691.00  31.81%
3  825,276,302.00   0.08%
4           10.99   0.09%
5   11,005,744.00  13.04%
6   74,507,950.00   0.91%

In [261]:
temps3["particulars"]=index

In [265]:
index=['Total Assets',"Total  Liabilities","Net Assets","Net Assets Value per Share","Expenses & Fees","Net, Income/(Expenses)"]
temps3["particulars"]=index
temps3=temps3[['particulars',0,1]]
temps3.columns=["Particulars", "Amount" ,"M-to-M%, Change"]

temps3

                  Particulars          Amount M-to-M%, Change
1                Total Assets  828,773,634.00           0.06%
2          Total  Liabilities   17,296,691.00          31.81%
3                  Net Assets  825,276,302.00           0.08%
4  Net Assets Value per Share           10.99           0.09%
5             Expenses & Fees   11,005,744.00          13.04%
6      Net, Income/(Expenses)   74,507,950.00           0.91%

In [ ]:
##

In [270]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [278]:
temps=pd.DataFrame(all_dicts['885']['assets_allocations'].split("\n")[4:4+5])

In [285]:
temps=temps[0].str.split(" ").str[-2:]

0    [635,630.54, 76.70%]
1                  [-, -]
2                  [-, -]
3      [40,000.00, 4.83%]
4    [153,143.09, 18.48%]
Name: 0, dtype: object

## Assets Allocations

In [286]:
index=['Equity Stocks',"Bonds & Debentures","IPO/FPO/Rights/Bonus","Banks Fixed Deposits","Cash & Others"]
temps3=pd.DataFrame(temps[0].str.split(" ").str[-2:].apply(lambda x : '|'.join(x)))
temps3=temps3[0].str.split("|",expand=True)

temps3["By Asset Class"]=index
temps3=temps3[['By Asset Class',0,1]]
temps3.columns=["By Asset Class", "Amount" ,"% of Total Assets"]

temps3

         By Asset Class      Amount % of Total Assets
0         Equity Stocks  635,630.54            76.70%
1    Bonds & Debentures           -                 -
2  IPO/FPO/Rights/Bonus           -                 -
3  Banks Fixed Deposits   40,000.00             4.83%
4         Cash & Others  153,143.09            18.48%

## sector wise allocations

In [291]:
all_dicts['885']['sectorwise_allocations']

'By Sectorwise Amount % Sectorwise % of Total Assets\nCommercial Banks 151,267,704.00 23.92% 18.25%\nDevelopment Banks 35,831,163.00 5.67% 4.32%\nHotels and Tourism 21,531,279.00 3.40% 2.60%\nHydro Power 109,196,332.00 17.27% 13.18%\nInvestment 3,592,000.00 0.57% 0.43%\nLife Insurance 54,116,694.00 8.56% 6.53%\nManufacturing and Processing 35,346,207.00 5.59% 4.26%\nMicrofinance 44,804,000.00 7.08% 5.41%\nMutual Fund 36,412,839.00 5.76% 4.39%\nNon Life Insurance 101,720,869.00 16.08% 12.27%\nOthers 38,584,000.00 6.10% 4.66%'

In [293]:
all_dicts['885']['sectorwise_allocations'].split("\n")

['By Sectorwise Amount % Sectorwise % of Total Assets',
 'Commercial Banks 151,267,704.00 23.92% 18.25%',
 'Development Banks 35,831,163.00 5.67% 4.32%',
 'Hotels and Tourism 21,531,279.00 3.40% 2.60%',
 'Hydro Power 109,196,332.00 17.27% 13.18%',
 'Investment 3,592,000.00 0.57% 0.43%',
 'Life Insurance 54,116,694.00 8.56% 6.53%',
 'Manufacturing and Processing 35,346,207.00 5.59% 4.26%',
 'Microfinance 44,804,000.00 7.08% 5.41%',
 'Mutual Fund 36,412,839.00 5.76% 4.39%',
 'Non Life Insurance 101,720,869.00 16.08% 12.27%',
 'Others 38,584,000.00 6.10% 4.66%']

In [296]:
temps=pd.DataFrame(all_dicts['885']['sectorwise_allocations'].split("\n"))[1:]
temps

                                                    0
1       Commercial Banks 151,267,704.00 23.92% 18.25%
2         Development Banks 35,831,163.00 5.67% 4.32%
3        Hotels and Tourism 21,531,279.00 3.40% 2.60%
4            Hydro Power 109,196,332.00 17.27% 13.18%
5                 Investment 3,592,000.00 0.57% 0.43%
6            Life Insurance 54,116,694.00 8.56% 6.53%
7   Manufacturing and Processing 35,346,207.00 5.5...
8              Microfinance 44,804,000.00 7.08% 5.41%
9               Mutual Fund 36,412,839.00 5.76% 4.39%
10    Non Life Insurance 101,720,869.00 16.08% 12.27%
11                   Others 38,584,000.00 6.10% 4.66%

In [305]:
temps=pd.DataFrame((temps[0].str.split(" ").str[-3:]).apply(lambda x : '|'.join(x)))
temps

                               0
1   151,267,704.00|23.92%|18.25%
2      35,831,163.00|5.67%|4.32%
3      21,531,279.00|3.40%|2.60%
4   109,196,332.00|17.27%|13.18%
5       3,592,000.00|0.57%|0.43%
6      54,116,694.00|8.56%|6.53%
7      35,346,207.00|5.59%|4.26%
8      44,804,000.00|7.08%|5.41%
9      36,412,839.00|5.76%|4.39%
10  101,720,869.00|16.08%|12.27%
11     38,584,000.00|6.10%|4.66%

In [307]:
index=["Commercial Banks","Development Banks","Hotels and Tourism",
 "Hydro Power","Investment","Life Insurance","Manufacturing and Processing","Microfinance"
 ,"Mutual Fund","Non Life Insurance","Others"]

index

['Commercial Banks',
 'Development Banks',
 'Hotels and Tourism',
 'Hydro Power',
 'Investment',
 'Life Insurance',
 'Manufacturing and Processing',
 'Microfinance',
 'Mutual Fund',
 'Non Life Insurance',
 'Others']

# Sector allocatuions

In [2]:
import pandas as pd

In [3]:
index=["Commercial Banks","Development Banks","Hotels and Tourism",
 "Hydro Power","Investment","Life Insurance","Manufacturing and Processing","Microfinance"
 ,"Mutual Fund","Non Life Insurance","Others"]

temps=pd.DataFrame(all_dicts['885']['sectorwise_allocations'].split("\n"))[1:]
temps=pd.DataFrame((temps[0].str.split(" ").str[-3:]).apply(lambda x : '|'.join(x)))

temps['By Sectorwise']=index

temps[['Amount',"Sector wise","% of total Assets"]]=temps[0].str.split("|",expand=True)
final=temps.iloc[:,1:]
final

NameError: name 'all_dicts' is not defined

In [318]:
all_dicts['885'].keys()

dict_keys(['weekly_nav', 'schema_profiles', 'corporate_actions', 'market_summary', 'performance', 'financials', 'assets_allocations', 'sectorwise_allocations'])

In [321]:
all_dicts['885']['weekly_nav']

'10.00\n0.00 (0.00%)\nWeekly NAV\n10.76\nTrade Day Range\nL\n9.92 - 10.00\nH\nVolume\n1,500\n180 Days Avg Price\n9.77\n52 Weeks Range\nL\n8.70 - 10.71\nH\nAs of Wednesday, 27 May 2026 02:40 PM'

In [322]:
all_dicts['885']['sectorwise_allocations']

'By Sectorwise Amount % Sectorwise % of Total Assets\nCommercial Banks 151,267,704.00 23.92% 18.25%\nDevelopment Banks 35,831,163.00 5.67% 4.32%\nHotels and Tourism 21,531,279.00 3.40% 2.60%\nHydro Power 109,196,332.00 17.27% 13.18%\nInvestment 3,592,000.00 0.57% 0.43%\nLife Insurance 54,116,694.00 8.56% 6.53%\nManufacturing and Processing 35,346,207.00 5.59% 4.26%\nMicrofinance 44,804,000.00 7.08% 5.41%\nMutual Fund 36,412,839.00 5.76% 4.39%\nNon Life Insurance 101,720,869.00 16.08% 12.27%\nOthers 38,584,000.00 6.10% 4.66%'

In [7]:
all_company_ids['stockSymbol'].apply(present)

0      False
1      False
2      False
3      False
4      False
       ...
557    False
558    False
559    False
560    False
561    False
Name: stockSymbol, Length: 562, dtype: bool

In [6]:
def present(data):
    if 'NBL' in data:
        return True
    else:
        return False

In [24]:
with open('my_data.pkl', 'wb') as f:
    pickle.dump(all_dicts, f)

In [23]:
import pickle