In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\open_ended.csv")

# open ended

In [3]:
from selenium import webdriver

driver = webdriver.Chrome()
from selenium.webdriver.common.by import By
driver.get("https://app.smartwealthpro.com/MutualFund/Overview")

In [4]:
# /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[44]/td[1]/a[1]
from selenium.webdriver.common.by import By

closed_ended=[]

for i in range(1,45):
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a[1]").get_attribute("href")
    closed_ended.append(url_links)

In [5]:
open_ended=[]

for i in range(1,12):
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    open_ended.append(url_links)

In [6]:
matured=[]
for i in range(1,11):
    # /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[1]/a
    url_links=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    matured.append(url_links)

In [7]:
open_ended

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956']

In [8]:
closed_ended

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
 'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
 'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
 'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
 'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
 'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
 'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
 'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629']

In [9]:
matured

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729']

In [10]:
all_companys_url={'open_ended':open_ended,"closed_ended":closed_ended,"matured":matured}
all_companys_url

{'open_ended': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956'],
 'closed_ended': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
  'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
  'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
  'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
  'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
  'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
  'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
  'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629'],
 'matured': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729']}

In [11]:
import pickle

with open("all_company_url.pkl","wb") as file:
    pickle.dump(all_companys_url,file)

In [12]:
with open("all_company_url.pkl","rb") as file:
    loaded=pickle.load(file)

loaded

{'open_ended': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956'],
 'closed_ended': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
  'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
  'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
  'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
  'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
  'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
  'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
  'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629'],
 'matured': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729']}

## now wxtractt he urls

In [13]:
loaded['open_ended'][0]

'https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885'

## Nav statements

In [ ]:
# https://app.smartwealthpro.com/MutualFund/NavStatement/Himalayan-80-20/H8020?c=935
#

# Income statements

In [ ]:
# https://app.smartwealthpro.com/MutualFund/IncomeStatement/Citizens-Mutual-Fund-2/CMF2?c=184

In [14]:
# /html/body/div[7]/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/table

# NAV statements

In [15]:
# /html/body/div[7]/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/table

In [67]:
from selenium import webdriver

driver = webdriver.Chrome()
from selenium.webdriver.common.by import By
driver.get("https://app.smartwealthpro.com/MutualFund/Overview")

In [68]:
driver.get("https://app.smartwealthpro.com/MutualFund/IncomeStatement/Citizens-Mutual-Fund-2/CMF2?c=184")

In [71]:
income_state=driver.find_element(By.XPATH,"/html/body/div[7]/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/table").text

In [22]:
driver.get("https://app.smartwealthpro.com/MutualFund/NavStatement/Himalayan-80-20/H8020?c=935")

In [23]:
NAV_statement=driver.find_element(By.XPATH,"/html/body/div[7]/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[3]/table").text

# data cleanings

In [25]:
print(income_state)

Particulars
Baisakh 2083
Chaitra 2082
Falgun 2082
Magh 2082
Poush 2082
Income
          Realized Income
2,414,466.00
10,083,322.00
20,404,591.00
20,036,586.00
4,512,031.00
Unrealized Income/(Expense) & Capital Gains
3,452,799.00
26,604,011.00
41,755,811.00
21,243,258.00
8,306,223.00
Total Income
1,038,333.00
16,520,689.00
21,351,220.00
1,206,672.00
12,818,254.00
Expenses
          Publication, Listing & Other Expenses
346,759.00
317,461.00
288,034.00
257,793.00
225,676.00
Audit Fee
112,196.00
100,679.00
89,534.00
78,388.00
67,614.00
Scheme Manager & Depository Fee
8,051,540.00
7,223,300.00
6,352,038.00
5,519,592.00
4,740,960.00
Fund Supervisor Fee
243,750.00
223,750.00
210,000.00
183,750.00
157,500.00
Total Expenses
8,754,245.00
7,865,190.00
6,939,606.00
6,039,523.00
5,191,750.00
Net Income/(Expenses)
7,715,912.00
8,655,499.00
14,411,614.00
4,832,851.00
18,010,004.00
Net Cost Price of Investments till Date
460,348,964.00
441,899,412.00
458,145,892.00
469,591,230.00
487,847,216.00

In [62]:
all_cols=income_state.split("\n")[:6]

In [53]:
al_datas=income_state.split("\n")[6:]
al_datas

['Income',
 '          Realized Income',
 '2,414,466.00',
 '10,083,322.00',
 '20,404,591.00',
 '20,036,586.00',
 '4,512,031.00',
 'Unrealized Income/(Expense) & Capital Gains',
 '3,452,799.00',
 '26,604,011.00',
 '41,755,811.00',
 '21,243,258.00',
 '8,306,223.00',
 'Total Income',
 '1,038,333.00',
 '16,520,689.00',
 '21,351,220.00',
 '1,206,672.00',
 '12,818,254.00',
 'Expenses',
 '          Publication, Listing & Other Expenses',
 '346,759.00',
 '317,461.00',
 '288,034.00',
 '257,793.00',
 '225,676.00',
 'Audit Fee',
 '112,196.00',
 '100,679.00',
 '89,534.00',
 '78,388.00',
 '67,614.00',
 'Scheme Manager & Depository Fee',
 '8,051,540.00',
 '7,223,300.00',
 '6,352,038.00',
 '5,519,592.00',
 '4,740,960.00',
 'Fund Supervisor Fee',
 '243,750.00',
 '223,750.00',
 '210,000.00',
 '183,750.00',
 '157,500.00',
 'Total Expenses',
 '8,754,245.00',
 '7,865,190.00',
 '6,939,606.00',
 '6,039,523.00',
 '5,191,750.00',
 'Net Income/(Expenses)',
 '7,715,912.00',
 '8,655,499.00',
 '14,411,614.00',
 '4,832,851.00',
 '18,010,004.00',
 'Net Cost Price of Investments till Date',
 '460,348,964.00',
 '441,899,412.00',
 '458,145,892.00',
 '469,591,230.00',
 '487,847,216.00']

In [34]:
[10,20,30].index(20)

1

In [36]:
index_pos={}
for item in al_datas:
    if item=="Income" or item=="Expenses":
        index_pos[item]=al_datas.index(item)
    else:
        pass

In [65]:
def cleaned_income(income_state,cid):
    all_cols=income_state.split("\n")[:6]
    al_datas=income_state.split("\n")[6:]
    for _ in range(5):
        al_datas.insert(20, "0")
    for _ in range(5):
        al_datas.insert(1, "0")
    al_arrays=np.array(al_datas).reshape(int(len(np.array(al_datas))/6),6)
    data=pd.DataFrame(al_arrays)
    data.columns=all_cols
    data['company_id']=cid
    return data

In [72]:
cleaned_income(income_state,1001)

,Particulars,Baisakh 2083,Chaitra 2082,Falgun 2082,Magh 2082,Poush 2082,company_id
0,Income,0,0,0,0,0,1001
1,Realized Income,"2,414,466.00","10,083,322.00","20,404,591.00","20,036,586.00","4,512,031.00",1001
2,Unrealized Income/(Expense) & Capital Gains,"3,452,799.00","26,604,011.00","41,755,811.00","21,243,258.00","8,306,223.00",1001
3,Total Income,"1,038,333.00","16,520,689.00","21,351,220.00","1,206,672.00","12,818,254.00",1001
4,Expenses,0,0,0,0,0,1001
5,"Publication, Listing & Other Expenses","346,759.00","317,461.00","288,034.00","257,793.00","225,676.00",1001
6,Audit Fee,"112,196.00","100,679.00","89,534.00","78,388.00","67,614.00",1001
7,Scheme Manager & Depository Fee,"8,051,540.00","7,223,300.00","6,352,038.00","5,519,592.00","4,740,960.00",1001
8,Fund Supervisor Fee,"243,750.00","223,750.00","210,000.00","183,750.00","157,500.00",1001
9,Total Expenses,"8,754,245.00","7,865,190.00","6,939,606.00","6,039,523.00","5,191,750.00",1001
10,Net Income/(Expenses),"7,715,912.00","8,655,499.00","14,411,614.00","4,832,851.00","18,010,004.00",1001
11,Net Cost Price of Investments till Date,"460,348,964.00","441,899,412.00","458,145,892.00","469,591,230.00","487,847,216.00",1001

In [54]:
for _ in range(5):
    al_datas.insert(20, "0")

for _ in range(5):
    al_datas.insert(1, "0")

In [48]:
import numpy as np

In [55]:
len(np.array(al_datas))

72

In [56]:
72/6

12.0

In [63]:
al_arrays=np.array(al_datas).reshape(int(len(np.array(al_datas))/6),6)
data=pd.DataFrame(al_arrays)
data.columns=all_cols
data

,Particulars,Baisakh 2083,Chaitra 2082,Falgun 2082,Magh 2082,Poush 2082
0,Income,0,0,0,0,0
1,Realized Income,"2,414,466.00","10,083,322.00","20,404,591.00","20,036,586.00","4,512,031.00"
2,Unrealized Income/(Expense) & Capital Gains,"3,452,799.00","26,604,011.00","41,755,811.00","21,243,258.00","8,306,223.00"
3,Total Income,"1,038,333.00","16,520,689.00","21,351,220.00","1,206,672.00","12,818,254.00"
4,Expenses,0,0,0,0,0
5,"Publication, Listing & Other Expenses","346,759.00","317,461.00","288,034.00","257,793.00","225,676.00"
6,Audit Fee,"112,196.00","100,679.00","89,534.00","78,388.00","67,614.00"
7,Scheme Manager & Depository Fee,"8,051,540.00","7,223,300.00","6,352,038.00","5,519,592.00","4,740,960.00"
8,Fund Supervisor Fee,"243,750.00","223,750.00","210,000.00","183,750.00","157,500.00"
9,Total Expenses,"8,754,245.00","7,865,190.00","6,939,606.00","6,039,523.00","5,191,750.00"
10,Net Income/(Expenses),"7,715,912.00","8,655,499.00","14,411,614.00","4,832,851.00","18,010,004.00"
11,Net Cost Price of Investments till Date,"460,348,964.00","441,899,412.00","458,145,892.00","469,591,230.00","487,847,216.00"

## Nav sttements

In [100]:
print(NAV_statement)

Particulars
Baisakh 2083
Chaitra 2082
Falgun 2082
Magh 2082
Poush 2082
Investments
          Investment in Listed/Non-Listed Shares
763,970,169.50
809,884,541.40
899,265,417.46
817,662,386.20
796,053,062.80
Debentures & Bonds
91,784,244.58
91,784,244.58
91,778,557.57
91,778,557.57
91,222,557.47
Investment in IPO/FPO/Right/Bonus
13,899,455.05
8,947,559.80
26,278,840.66
42,843,702.65
32,995,696.02
Fixed Income Instruments
115,000,000.00
115,000,000.00
115,000,000.00
115,000,000.00
115,000,000.00
Total Investments
984,653,869.13
1,025,616,345.78
1,132,322,815.69
1,067,284,646.42
1,035,271,316.29
Current Assets
          Bank Balance
240,595,220.93
251,586,421.55
140,158,437.29
139,505,825.66
150,743,518.81
Other Assets
39,249,145.50
10,079,379.78
22,767,107.90
14,340,123.38
17,214,810.16
Total Current Assets
279,844,366.43
261,665,801.33
162,925,545.19
153,845,949.04
167,958,328.97
Current Liabilities
          Other Liabilities
0.00
6,385,948.42
33,371,587.08
7,682,492.05
13,545,696.64
Total Current Liabilities
41,359.54
6,385,948.42
33,371,587.08
7,682,492.05
13,545,696.64
Total Assets
1,264,456,876.02
1,280,896,198.69
1,261,876,773.80
1,213,448,103.41
1,189,683,948.62
Scheme Manager and Depository Fee
1,825,523.49
0.00
3,399,451.93
1,638,851.00
0.00
Fund Supervisor Fee
100,000.00
0.00
200,000.00
100,000.00
0.00
Net Assets
1,262,531,352.53
1,280,896,198.69
1,258,277,321.87
1,211,709,252.41
1,189,683,948.62
Total Issued Units
100,000,000.00
100,000,000.00
100,000,000.00
100,000,000.00
100,000,000.00
Net Assets Value (NAV)
12.63
12.81
12.58
12.12
11.90

In [ ]:
Investments
Current Assets
Current Liabilities

In [ ]:


for _ in range(5):
    al_datas.insert(20, "0")

for _ in range(5):
    al_datas.insert(1, "0")

In [86]:
index_pos

{'Investments': 6, 'Current Assets': 37, 'Current Liabilities': 56}

In [89]:
index_pos={}
listed=NAV_statement.split("\n")
for item in listed:
    if item in ["Investments","Current Assets","Current Liabilities"]:
        index_pos[item]=listed.index(item)

for _ in range(5):
    listed.insert(57,"0")

for _ in range(5):
    listed.insert(38,"0")

for _ in range(5):
    listed.insert(7,"0")

In [93]:
all_datas=np.array(listed)
all_datas

array(['Particulars', 'Baisakh 2083', 'Chaitra 2082', 'Falgun 2082',
       'Magh 2082', 'Poush 2082', 'Investments', '0', '0', '0', '0', '0',
       '          Investment in Listed/Non-Listed Shares',
       '763,970,169.50', '809,884,541.40', '899,265,417.46',
       '817,662,386.20', '796,053,062.80', 'Debentures & Bonds',
       '91,784,244.58', '91,784,244.58', '91,778,557.57', '91,778,557.57',
       '91,222,557.47', 'Investment in IPO/FPO/Right/Bonus',
       '13,899,455.05', '8,947,559.80', '26,278,840.66', '42,843,702.65',
       '32,995,696.02', 'Fixed Income Instruments', '115,000,000.00',
       '115,000,000.00', '115,000,000.00', '115,000,000.00',
       '115,000,000.00', 'Total Investments', '984,653,869.13',
       '1,025,616,345.78', '1,132,322,815.69', '1,067,284,646.42',
       '1,035,271,316.29', 'Current Assets', '0', '0', '0', '0', '0',
       '          Bank Balance', '240,595,220.93', '251,586,421.55',
       '140,158,437.29', '139,505,825.66', '150,743,518.81',
       'Other Assets', '39,249,145.50', '10,079,379.78', '22,767,107.90',
       '14,340,123.38', '17,214,810.16', 'Total Current Assets',
       '279,844,366.43', '261,665,801.33', '162,925,545.19',
       '153,845,949.04', '167,958,328.97', 'Current Liabilities', '0',
       '0', '0', '0', '0', '          Other Liabilities', '0.00',
       '6,385,948.42', '33,371,587.08', '7,682,492.05', '13,545,696.64',
       'Total Current Liabilities', '41,359.54', '6,385,948.42',
       '33,371,587.08', '7,682,492.05', '13,545,696.64', 'Total Assets',
       '1,264,456,876.02', '1,280,896,198.69', '1,261,876,773.80',
       '1,213,448,103.41', '1,189,683,948.62',
       'Scheme Manager and Depository Fee', '1,825,523.49', '0.00',
       '3,399,451.93', '1,638,851.00', '0.00', 'Fund Supervisor Fee',
       '100,000.00', '0.00', '200,000.00', '100,000.00', '0.00',
       'Net Assets', '1,262,531,352.53', '1,280,896,198.69',
       '1,258,277,321.87', '1,211,709,252.41', '1,189,683,948.62',
       'Total Issued Units', '100,000,000.00', '100,000,000.00',
       '100,000,000.00', '100,000,000.00', '100,000,000.00',
       'Net Assets Value (NAV)', '12.63', '12.81', '12.58', '12.12',
       '11.90'], dtype='<U48')

In [105]:
def cleaned_nav_statements(NAV_statement,cid):
    index_pos={}
    listed=NAV_statement.split("\n")
    for _ in range(5):
        listed.insert(57,"0")
    for _ in range(5):
        listed.insert(38,"0")
    for _ in range(5):
        listed.insert(7,"0")
    all_datas=np.array(listed)
    dfs=pd.DataFrame(all_datas.reshape(int(len(all_datas)/6),6))
    dfs.columns=dfs.iloc[0]
    finals=dfs.iloc[1:,:]
    finals['company_id']=cid
    return finals

In [109]:
cleaned_nav_statements(NAV_statement,1003)

,Particulars,Baisakh 2083,Chaitra 2082,Falgun 2082,Magh 2082,Poush 2082,company_id
1,Investments,0,0,0,0,0,1003
2,Investment in Listed/Non-Listed Shares,"763,970,169.50","809,884,541.40","899,265,417.46","817,662,386.20","796,053,062.80",1003
3,Debentures & Bonds,"91,784,244.58","91,784,244.58","91,778,557.57","91,778,557.57","91,222,557.47",1003
4,Investment in IPO/FPO/Right/Bonus,"13,899,455.05","8,947,559.80","26,278,840.66","42,843,702.65","32,995,696.02",1003
5,Fixed Income Instruments,"115,000,000.00","115,000,000.00","115,000,000.00","115,000,000.00","115,000,000.00",1003
6,Total Investments,"984,653,869.13","1,025,616,345.78","1,132,322,815.69","1,067,284,646.42","1,035,271,316.29",1003
7,Current Assets,0,0,0,0,0,1003
8,Bank Balance,"240,595,220.93","251,586,421.55","140,158,437.29","139,505,825.66","150,743,518.81",1003
9,Other Assets,"39,249,145.50","10,079,379.78","22,767,107.90","14,340,123.38","17,214,810.16",1003
10,Total Current Assets,"279,844,366.43","261,665,801.33","162,925,545.19","153,845,949.04","167,958,328.97",1003
11,Current Liabilities,0,0,0,0,0,1003
12,Other Liabilities,0.00,"6,385,948.42","33,371,587.08","7,682,492.05","13,545,696.64",1003
13,Total Current Liabilities,"41,359.54","6,385,948.42","33,371,587.08","7,682,492.05","13,545,696.64",1003
14,Total Assets,"1,264,456,876.02","1,280,896,198.69","1,261,876,773.80","1,213,448,103.41","1,189,683,948.62",1003
15,Scheme Manager and Depository Fee,"1,825,523.49",0.00,"3,399,451.93","1,638,851.00",0.00,1003
16,Fund Supervisor Fee,"100,000.00",0.00,"200,000.00","100,000.00",0.00,1003
17,Net Assets,"1,262,531,352.53","1,280,896,198.69","1,258,277,321.87","1,211,709,252.41","1,189,683,948.62",1003
18,Total Issued Units,"100,000,000.00","100,000,000.00","100,000,000.00","100,000,000.00","100,000,000.00",1003
19,Net Assets Value (NAV),12.63,12.81,12.58,12.12,11.90,1003

In [98]:
dfs=pd.DataFrame(all_datas.reshape(int(len(all_datas)/6),6))
dfs.columns=dfs.iloc[0]
finals=dfs.iloc[1:,:]
finals

,Particulars,Baisakh 2083,Chaitra 2082,Falgun 2082,Magh 2082,Poush 2082
1,Investments,0,0,0,0,0
2,Investment in Listed/Non-Listed Shares,"763,970,169.50","809,884,541.40","899,265,417.46","817,662,386.20","796,053,062.80"
3,Debentures & Bonds,"91,784,244.58","91,784,244.58","91,778,557.57","91,778,557.57","91,222,557.47"
4,Investment in IPO/FPO/Right/Bonus,"13,899,455.05","8,947,559.80","26,278,840.66","42,843,702.65","32,995,696.02"
5,Fixed Income Instruments,"115,000,000.00","115,000,000.00","115,000,000.00","115,000,000.00","115,000,000.00"
6,Total Investments,"984,653,869.13","1,025,616,345.78","1,132,322,815.69","1,067,284,646.42","1,035,271,316.29"
7,Current Assets,0,0,0,0,0
8,Bank Balance,"240,595,220.93","251,586,421.55","140,158,437.29","139,505,825.66","150,743,518.81"
9,Other Assets,"39,249,145.50","10,079,379.78","22,767,107.90","14,340,123.38","17,214,810.16"
10,Total Current Assets,"279,844,366.43","261,665,801.33","162,925,545.19","153,845,949.04","167,958,328.97"
11,Current Liabilities,0,0,0,0,0
12,Other Liabilities,0.00,"6,385,948.42","33,371,587.08","7,682,492.05","13,545,696.64"
13,Total Current Liabilities,"41,359.54","6,385,948.42","33,371,587.08","7,682,492.05","13,545,696.64"
14,Total Assets,"1,264,456,876.02","1,280,896,198.69","1,261,876,773.80","1,213,448,103.41","1,189,683,948.62"
15,Scheme Manager and Depository Fee,"1,825,523.49",0.00,"3,399,451.93","1,638,851.00",0.00
16,Fund Supervisor Fee,"100,000.00",0.00,"200,000.00","100,000.00",0.00
17,Net Assets,"1,262,531,352.53","1,280,896,198.69","1,258,277,321.87","1,211,709,252.41","1,189,683,948.62"
18,Total Issued Units,"100,000,000.00","100,000,000.00","100,000,000.00","100,000,000.00","100,000,000.00"
19,Net Assets Value (NAV),12.63,12.81,12.58,12.12,11.90

In [104]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\data_extractions\\tables_csv\\nav_statements_income+statements'