## matrix multiplication or Dot Products

In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(1,100,size=(3,4))
arr1

array([[66, 49, 26, 38],
       [20, 68,  8, 41],
       [ 2, 47, 96,  8]], dtype=int32)

In [3]:
np.transpose(arr1)

array([[66, 20,  2],
       [49, 68, 47],
       [26,  8, 96],
       [38, 41,  8]], dtype=int32)

In [6]:
arr1=np.random.randint(1,100,size=(3,3))
arr1

array([[86, 40, 38],
       [50, 67, 97],
       [75, 55, 60]], dtype=int32)

In [7]:
np.linalg.inv(arr1)

array([[ 0.04607568,  0.01086195, -0.04674142],
       [-0.14978977, -0.08093903,  0.22571829],
       [ 0.07971268,  0.06061668, -0.131815  ]])

In [11]:
np.linalg.inv(np.linalg.inv(arr1))

array([[86., 40., 38.],
       [50., 67., 97.],
       [75., 55., 60.]])

In [8]:
arr1

array([[86, 40, 38],
       [50, 67, 97],
       [75, 55, 60]], dtype=int32)

In [10]:
arr1.T.T

array([[86, 40, 38],
       [50, 67, 97],
       [75, 55, 60]], dtype=int32)

### solve

In [ ]:
2x-4y+5z=36
x+1.5y-7Z=-7
5x+3y-8z=-31

In [13]:
coef=np.array([[2,-4,5],[1,1.5,-7],[5,3,-8]])
coef

array([[ 2. , -4. ,  5. ],
       [ 1. ,  1.5, -7. ],
       [ 5. ,  3. , -8. ]])

In [14]:
soln=[36,-7,-31]

In [15]:
np.linalg.solve(coef,soln)

array([ -1.85990338, -12.30917874,  -1.90338164])

In [18]:
5*(-1.85990338 )+3*(-12.30917874) -8*(-1.90338164)

-31.0

#### dot product : matrix MultiicATION

In [19]:
# 4X5  5X3

In [21]:
mat1=np.random.randint(1,100,size=(4,5))

In [22]:
mat2=np.random.randint(1,100,size=(5,4))

In [23]:
mat1

array([[57, 32, 73,  5, 48],
       [77,  9, 41, 34, 63],
       [46, 95, 75, 26, 19],
       [44, 37, 77, 97, 47]], dtype=int32)

In [24]:
mat2

array([[59, 61, 63, 62],
       [52, 13, 20, 71],
       [59, 23, 19, 98],
       [15, 73, 70, 81],
       [89, 29, 64, 10]], dtype=int32)

In [26]:
57*59 +32*52 + 73*59 + 5*15 +48*89

13681

In [25]:
mat1.dot(mat2)

array([[13681,  7329,  9040, 13845],
       [13547, 10066, 12222, 12815],
       [14160,  8215,  9259, 19243],
       [14701, 13380, 14773, 21228]], dtype=int32)

In [27]:
mat1@mat2

array([[13681,  7329,  9040, 13845],
       [13547, 10066, 12222, 12815],
       [14160,  8215,  9259, 19243],
       [14701, 13380, 14773, 21228]], dtype=int32)

In [28]:
mat1

array([[57, 32, 73,  5, 48],
       [77,  9, 41, 34, 63],
       [46, 95, 75, 26, 19],
       [44, 37, 77, 97, 47]], dtype=int32)

In [29]:
mat1.T

array([[57, 77, 46, 44],
       [32,  9, 95, 37],
       [73, 41, 75, 77],
       [ 5, 34, 26, 97],
       [48, 63, 19, 47]], dtype=int32)

### split , join

In [31]:
arr1=np.random.randint(1,100,size=(6,8))
arr1

array([[34, 56, 94, 24, 67, 65, 86,  9],
       [85, 43, 23, 84, 39, 30, 10, 92],
       [24, 70, 18, 64, 98, 30, 89, 98],
       [73, 45, 22,  1, 84, 83, 42, 67],
       [43, 77, 59, 72, 71, 37, 32,  3],
       [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)

In [32]:
np.vsplit(arr1,2)  # List of arrays

[array([[34, 56, 94, 24, 67, 65, 86,  9],
        [85, 43, 23, 84, 39, 30, 10, 92],
        [24, 70, 18, 64, 98, 30, 89, 98]], dtype=int32),
 array([[73, 45, 22,  1, 84, 83, 42, 67],
        [43, 77, 59, 72, 71, 37, 32,  3],
        [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)]

In [33]:
np.vsplit(arr1,3)

[array([[34, 56, 94, 24, 67, 65, 86,  9],
        [85, 43, 23, 84, 39, 30, 10, 92]], dtype=int32),
 array([[24, 70, 18, 64, 98, 30, 89, 98],
        [73, 45, 22,  1, 84, 83, 42, 67]], dtype=int32),
 array([[43, 77, 59, 72, 71, 37, 32,  3],
        [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)]

## h split : horizontally split

In [34]:
arr1

array([[34, 56, 94, 24, 67, 65, 86,  9],
       [85, 43, 23, 84, 39, 30, 10, 92],
       [24, 70, 18, 64, 98, 30, 89, 98],
       [73, 45, 22,  1, 84, 83, 42, 67],
       [43, 77, 59, 72, 71, 37, 32,  3],
       [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)

In [35]:
np.hsplit(arr1,2)

[array([[34, 56, 94, 24],
        [85, 43, 23, 84],
        [24, 70, 18, 64],
        [73, 45, 22,  1],
        [43, 77, 59, 72],
        [99, 63, 30, 23]], dtype=int32),
 array([[67, 65, 86,  9],
        [39, 30, 10, 92],
        [98, 30, 89, 98],
        [84, 83, 42, 67],
        [71, 37, 32,  3],
        [ 1, 55, 22, 34]], dtype=int32)]

In [37]:
np.hsplit(arr1,4)

[array([[34, 56],
        [85, 43],
        [24, 70],
        [73, 45],
        [43, 77],
        [99, 63]], dtype=int32),
 array([[94, 24],
        [23, 84],
        [18, 64],
        [22,  1],
        [59, 72],
        [30, 23]], dtype=int32),
 array([[67, 65],
        [39, 30],
        [98, 30],
        [84, 83],
        [71, 37],
        [ 1, 55]], dtype=int32),
 array([[86,  9],
        [10, 92],
        [89, 98],
        [42, 67],
        [32,  3],
        [22, 34]], dtype=int32)]

In [39]:
np.hsplit(arr1,2)

[array([[34, 56, 94, 24],
        [85, 43, 23, 84],
        [24, 70, 18, 64],
        [73, 45, 22,  1],
        [43, 77, 59, 72],
        [99, 63, 30, 23]], dtype=int32),
 array([[67, 65, 86,  9],
        [39, 30, 10, 92],
        [98, 30, 89, 98],
        [84, 83, 42, 67],
        [71, 37, 32,  3],
        [ 1, 55, 22, 34]], dtype=int32)]

In [40]:
arr1

array([[34, 56, 94, 24, 67, 65, 86,  9],
       [85, 43, 23, 84, 39, 30, 10, 92],
       [24, 70, 18, 64, 98, 30, 89, 98],
       [73, 45, 22,  1, 84, 83, 42, 67],
       [43, 77, 59, 72, 71, 37, 32,  3],
       [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)

In [ ]:
______________________________________ :  Horizontal


|
|    ----> Veritical
|

In [41]:
np.vsplit(arr1,3)

[array([[34, 56, 94, 24, 67, 65, 86,  9],
        [85, 43, 23, 84, 39, 30, 10, 92]], dtype=int32),
 array([[24, 70, 18, 64, 98, 30, 89, 98],
        [73, 45, 22,  1, 84, 83, 42, 67]], dtype=int32),
 array([[43, 77, 59, 72, 71, 37, 32,  3],
        [99, 63, 30, 23,  1, 55, 22, 34]], dtype=int32)]

### concat

In [44]:
arr1=np.random.randint(1,100,size=(4,5))
arr1

array([[56, 71, 27, 17, 57],
       [98, 21, 17, 40, 27],
       [58, 29, 65, 17, 66],
       [92, 89, 24, 52, 97]], dtype=int32)

In [45]:
arr2=np.random.randint(1,100,size=(4,8))
arr2

array([[62, 41, 20, 99, 80, 89, 93,  4],
       [11, 61, 20, 57, 84, 33, 25, 47],
       [32, 27, 82, 96, 70, 96, 11, 90],
       [31, 80, 81, 93, 38, 87, 45, 10]], dtype=int32)

In [48]:
np.concat([arr1,arr2],axis=1)  # row wise concat

array([[56, 71, 27, 17, 57, 62, 41, 20, 99, 80, 89, 93,  4],
       [98, 21, 17, 40, 27, 11, 61, 20, 57, 84, 33, 25, 47],
       [58, 29, 65, 17, 66, 32, 27, 82, 96, 70, 96, 11, 90],
       [92, 89, 24, 52, 97, 31, 80, 81, 93, 38, 87, 45, 10]], dtype=int32)

In [49]:
arr1=np.random.randint(1,100,size=(4,5))
arr1

array([[80, 41, 55, 42, 70],
       [61,  3, 30,  8,  5],
       [65, 95, 49, 86, 47],
       [14, 29,  9, 47, 38]], dtype=int32)

In [50]:
arr2=np.random.randint(1,100,size=(6,5))
arr2

array([[13, 38, 62, 53, 72],
       [92, 37, 92, 15, 71],
       [10, 74, 16, 80, 33],
       [29, 32, 42, 19, 76],
       [70, 33, 60, 11,  4],
       [20, 72,  2, 44, 70]], dtype=int32)

In [51]:
np.concat([arr1,arr2])

array([[80, 41, 55, 42, 70],
       [61,  3, 30,  8,  5],
       [65, 95, 49, 86, 47],
       [14, 29,  9, 47, 38],
       [13, 38, 62, 53, 72],
       [92, 37, 92, 15, 71],
       [10, 74, 16, 80, 33],
       [29, 32, 42, 19, 76],
       [70, 33, 60, 11,  4],
       [20, 72,  2, 44, 70]], dtype=int32)

In [52]:
import pandas as pd

In [83]:
df=pd.read_excel(r"C:\Users\HP\Desktop\adva.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,C1,C2,C3,C4,C5,C6,NaN,NaN,SalesRep,Value,Date
1,NaN,SalesRep,A,B,C,D,E,NaN,NaN,A,18,2015-02-13 00:00:00
2,NaN,Value,18,14,19,17,13,NaN,NaN,B,14,2015-01-13 00:00:00
3,NaN,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00,NaN,NaN,C,19,2015-04-01 00:00:00
4,NaN,SalesRep,A,B,C,D,E,NaN,NaN,D,17,2015-03-04 00:00:00
5,NaN,Value,19,10,11,11,20,NaN,NaN,E,13,2015-02-05 00:00:00
6,NaN,Date,2015-03-27 00:00:00,2015-04-06 00:00:00,2015-03-18 00:00:00,2015-02-28 00:00:00,2014-12-31 00:00:00,NaN,NaN,A,19,2015-03-27 00:00:00
7,NaN,SalesRep,A,B,C,D,E,NaN,NaN,B,10,2015-04-06 00:00:00
8,NaN,Value,15,20,11,15,10,NaN,NaN,C,11,2015-03-18 00:00:00
9,NaN,Date,2015-02-03 00:00:00,2015-02-06 00:00:00,2015-04-06 00:00:00,2015-01-03 00:00:00,2015-01-05 00:00:00,NaN,NaN,D,11,2015-02-28 00:00:00
10,NaN,SalesRep,A,B,C,D,E,NaN,NaN,E,20,2014-12-31 00:00:00
11,NaN,Value,18,14,19,17,13,NaN,NaN,A,15,2015-02-03 00:00:00
12,NaN,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00,NaN,NaN,B,20,2015-02-06 00:00:00
13,NaN,SalesRep,A,B,C,D,E,NaN,NaN,C,11,2015-04-06 00:00:00
14,NaN,Value,18,14,19,17,13,NaN,NaN,D,15,2015-01-03 00:00:00
15,NaN,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00,NaN,NaN,E,10,2015-01-05 00:00:00

In [96]:
temp=df.iloc[1:,1:7]
temp

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
1,SalesRep,A,B,C,D,E
2,Value,18,14,19,17,13
3,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00
4,SalesRep,A,B,C,D,E
5,Value,19,10,11,11,20
6,Date,2015-03-27 00:00:00,2015-04-06 00:00:00,2015-03-18 00:00:00,2015-02-28 00:00:00,2014-12-31 00:00:00
7,SalesRep,A,B,C,D,E
8,Value,15,20,11,15,10
9,Date,2015-02-03 00:00:00,2015-02-06 00:00:00,2015-04-06 00:00:00,2015-01-03 00:00:00,2015-01-05 00:00:00
10,SalesRep,A,B,C,D,E
11,Value,18,14,19,17,13
12,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00
13,SalesRep,A,B,C,D,E
14,Value,18,14,19,17,13
15,Date,2015-02-13 00:00:00,2015-01-13 00:00:00,2015-04-01 00:00:00,2015-03-04 00:00:00,2015-02-05 00:00:00

In [97]:
def transform(temp):
    temp=np.array(temp)
    cols=np.unique(temp[:,0:1])
    final_arr=[]
    for arr in np.vsplit(temp[:,1:],temp.shape[0]//3):
        final_arr.append(arr.T)
    final_dfs=pd.DataFrame(np.concat(final_arr),columns=cols)
    return final_dfs

In [98]:
transform(temp)

   Date SalesRep      Value
0     A       18 2015-02-13
1     B       14 2015-01-13
2     C       19 2015-04-01
3     D       17 2015-03-04
4     E       13 2015-02-05
5     A       19 2015-03-27
6     B       10 2015-04-06
7     C       11 2015-03-18
8     D       11 2015-02-28
9     E       20 2014-12-31
10    A       15 2015-02-03
11    B       20 2015-02-06
12    C       11 2015-04-06
13    D       15 2015-01-03
14    E       10 2015-01-05
15    A       18 2015-02-13
16    B       14 2015-01-13
17    C       19 2015-04-01
18    D       17 2015-03-04
19    E       13 2015-02-05
20    A       18 2015-02-13
21    B       14 2015-01-13
22    C       19 2015-04-01
23    D       17 2015-03-04
24    E       13 2015-02-05

In [61]:
temp=np.array(temp)
temp

array([['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 19, 10, 11, 11, 20],
       ['Date', datetime.datetime(2015, 3, 27, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 3, 18, 0, 0),
        datetime.datetime(2015, 2, 28, 0, 0),
        datetime.datetime(2014, 12, 31, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 15, 20, 11, 15, 10],
       ['Date', datetime.datetime(2015, 2, 3, 0, 0),
        datetime.datetime(2015, 2, 6, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 1, 3, 0, 0),
        datetime.datetime(2015, 1, 5, 0, 0)]], dtype=object)

In [65]:
cols=np.unique(temp[:,0:1])
cols

array(['Date', 'SalesRep', 'Value'], dtype=object)

In [78]:
final_arr=[]
for arr in np.vsplit(temp[:,1:],3):
    final_arr.append(arr.T)
    
np.concat(final_arr)

array([['A', 18, datetime.datetime(2015, 2, 13, 0, 0)],
       ['B', 14, datetime.datetime(2015, 1, 13, 0, 0)],
       ['C', 19, datetime.datetime(2015, 4, 1, 0, 0)],
       ['D', 17, datetime.datetime(2015, 3, 4, 0, 0)],
       ['E', 13, datetime.datetime(2015, 2, 5, 0, 0)],
       ['A', 19, datetime.datetime(2015, 3, 27, 0, 0)],
       ['B', 10, datetime.datetime(2015, 4, 6, 0, 0)],
       ['C', 11, datetime.datetime(2015, 3, 18, 0, 0)],
       ['D', 11, datetime.datetime(2015, 2, 28, 0, 0)],
       ['E', 20, datetime.datetime(2014, 12, 31, 0, 0)],
       ['A', 15, datetime.datetime(2015, 2, 3, 0, 0)],
       ['B', 20, datetime.datetime(2015, 2, 6, 0, 0)],
       ['C', 11, datetime.datetime(2015, 4, 6, 0, 0)],
       ['D', 15, datetime.datetime(2015, 1, 3, 0, 0)],
       ['E', 10, datetime.datetime(2015, 1, 5, 0, 0)]], dtype=object)

In [81]:
pd.DataFrame(np.concat(final_arr),columns=cols)

   Date SalesRep      Value
0     A       18 2015-02-13
1     B       14 2015-01-13
2     C       19 2015-04-01
3     D       17 2015-03-04
4     E       13 2015-02-05
5     A       19 2015-03-27
6     B       10 2015-04-06
7     C       11 2015-03-18
8     D       11 2015-02-28
9     E       20 2014-12-31
10    A       15 2015-02-03
11    B       20 2015-02-06
12    C       11 2015-04-06
13    D       15 2015-01-03
14    E       10 2015-01-05

In [91]:
temp=np.array(temp)
temp

array([['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 19, 10, 11, 11, 20],
       ['Date', datetime.datetime(2015, 3, 27, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 3, 18, 0, 0),
        datetime.datetime(2015, 2, 28, 0, 0),
        datetime.datetime(2014, 12, 31, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 15, 20, 11, 15, 10],
       ['Date', datetime.datetime(2015, 2, 3, 0, 0),
        datetime.datetime(2015, 2, 6, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 1, 3, 0, 0),
        datetime.datetime(2015, 1, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)]], dtype=object)

In [94]:
temp.shape[0]//3

5

In [100]:
np.array(temp)

array([['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 19, 10, 11, 11, 20],
       ['Date', datetime.datetime(2015, 3, 27, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 3, 18, 0, 0),
        datetime.datetime(2015, 2, 28, 0, 0),
        datetime.datetime(2014, 12, 31, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 15, 20, 11, 15, 10],
       ['Date', datetime.datetime(2015, 2, 3, 0, 0),
        datetime.datetime(2015, 2, 6, 0, 0),
        datetime.datetime(2015, 4, 6, 0, 0),
        datetime.datetime(2015, 1, 3, 0, 0),
        datetime.datetime(2015, 1, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)],
       ['SalesRep', 'A', 'B', 'C', 'D', 'E'],
       ['Value', 18, 14, 19, 17, 13],
       ['Date', datetime.datetime(2015, 2, 13, 0, 0),
        datetime.datetime(2015, 1, 13, 0, 0),
        datetime.datetime(2015, 4, 1, 0, 0),
        datetime.datetime(2015, 3, 4, 0, 0),
        datetime.datetime(2015, 2, 5, 0, 0)]], dtype=object)

In [92]:
np.vsplit(temp[:,1:],5)

[array([['A', 'B', 'C', 'D', 'E'],
        [18, 14, 19, 17, 13],
        [datetime.datetime(2015, 2, 13, 0, 0),
         datetime.datetime(2015, 1, 13, 0, 0),
         datetime.datetime(2015, 4, 1, 0, 0),
         datetime.datetime(2015, 3, 4, 0, 0),
         datetime.datetime(2015, 2, 5, 0, 0)]], dtype=object),
 array([['A', 'B', 'C', 'D', 'E'],
        [19, 10, 11, 11, 20],
        [datetime.datetime(2015, 3, 27, 0, 0),
         datetime.datetime(2015, 4, 6, 0, 0),
         datetime.datetime(2015, 3, 18, 0, 0),
         datetime.datetime(2015, 2, 28, 0, 0),
         datetime.datetime(2014, 12, 31, 0, 0)]], dtype=object),
 array([['A', 'B', 'C', 'D', 'E'],
        [15, 20, 11, 15, 10],
        [datetime.datetime(2015, 2, 3, 0, 0),
         datetime.datetime(2015, 2, 6, 0, 0),
         datetime.datetime(2015, 4, 6, 0, 0),
         datetime.datetime(2015, 1, 3, 0, 0),
         datetime.datetime(2015, 1, 5, 0, 0)]], dtype=object),
 array([['A', 'B', 'C', 'D', 'E'],
        [18, 14, 19, 17, 13],
        [datetime.datetime(2015, 2, 13, 0, 0),
         datetime.datetime(2015, 1, 13, 0, 0),
         datetime.datetime(2015, 4, 1, 0, 0),
         datetime.datetime(2015, 3, 4, 0, 0),
         datetime.datetime(2015, 2, 5, 0, 0)]], dtype=object),
 array([['A', 'B', 'C', 'D', 'E'],
        [18, 14, 19, 17, 13],
        [datetime.datetime(2015, 2, 13, 0, 0),
         datetime.datetime(2015, 1, 13, 0, 0),
         datetime.datetime(2015, 4, 1, 0, 0),
         datetime.datetime(2015, 3, 4, 0, 0),
         datetime.datetime(2015, 2, 5, 0, 0)]], dtype=object)]

In [101]:
import pickle

with open("data1.pkl","wb") as file:
    pickle.dump(np.array(temp),file)

In [102]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\New folder'