In [ ]:
https://nepalytix.com/dashboard/broker-analysis/daily-snapshot?date=2026-06-11

In [1]:
import pandas as pd

In [ ]:
# table-container

In [ ]:
pd.date_range(start='2024-01-01', end='2024-01-10')

In [ ]:
# /html/body/app-root/div/main/div/app-dashboard/div[1]/div[1]/div/div[1]/div[4]

In [5]:
from selenium import webdriver

driver = webdriver.Chrome()

driver.get("https://www.nepalstock.com/")

data=driver.find_element(By.XPATH,"/html/body/app-root/div/main/div/app-dashboard/div[1]/div[1]/div/div[1]/div[4]").text
data

'ADVANCED\n96\nDECLINED\n158\nUNCHANGED\n16\nTechnical Charts'

In [6]:
print(data)

ADVANCED
96
DECLINED
158
UNCHANGED
16
Technical Charts

## All Sdectors

In [60]:
sectors = [
    "Banking",
    "Trading",
    "Hotels And Tourism",
    "Development Banks",
    "Hydropower",
    "Finance",
    "Microfinance",
    "Non-Life Insurance",
    "Life Insurance",
    "Manu.and.Pro",
    "Others",
    "Mutual Fund",
    "Investment"
]


# june 8 to june 11

In [ ]:
# /html/body/form/div[4]/div[4]/div/div/div[1]/div[1]/select/option[6]


# /html/body/form/div[4]/div[4]/div/div/div[1]/div[1]/select/option[18]

In [ ]:
# /html/body/form/div[4]/div[4]/div/div/div[1]/div[1]/select


# start_date : /html/body/form/div[4]/div[4]/div/div/div[1]/div[2]/div/input[1]  # 06/08/2026
# end_date : /html/body/form/div[4]/div[4]/div/div/div[1]/div[2]/div/input[2]    # 06/11/2026

In [52]:
driver = webdriver.Chrome()

driver.get("https://merolagani.com/Indices.aspx")

In [61]:
all_sector_data = {}
counter = 6
for i in range(len(sectors)):
    try:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(3)
        driver.find_element(By.XPATH,f"/html/body/form/div[4]/div[4]/div/div/div[1]/div[1]/select/option[{counter}]"
        ).click()
        time.sleep(2)
        driver.find_element(By.XPATH,"/html/body/form/div[4]/div[4]/div/div/div[2]/a[1]").click()
        time.sleep(2)
        datasets = driver.find_element(By.XPATH,"/html/body/form/div[4]/div[5]/div/div[3]/table").text
        all_sector_data[sectors[i]] = data_converter(datasets,sectors[i])
        print(f"{sectors[i]} Data Extracted Successfully")
        counter += 1
    except Exception as e:
        print(f"{sectors[i]} Failed: {e}")

dfs = pd.concat(all_sector_data.values(),ignore_index=True)
final = dfs.pivot_table(index="sector",columns="Date",values="pct_changes",aggfunc="first")
final

Banking Data Extracted Successfully
Trading Data Extracted Successfully
Hotels And Tourism Data Extracted Successfully
Development Banks Data Extracted Successfully
Hydropower Data Extracted Successfully
Finance Data Extracted Successfully
Microfinance Data Extracted Successfully
Non-Life Insurance Data Extracted Successfully
Life Insurance Data Extracted Successfully
Manu.and.Pro Data Extracted Successfully
Others Data Extracted Successfully
Mutual Fund Data Extracted Successfully
Investment Data Extracted Successfully

Date               2026/06/08 2026/06/09 2026/06/10 2026/06/11 2026/06/12
sector
Banking                -0.45%         0%         0%     -0.25%     -0.12%
Development Banks      -0.98%     -0.06%      0.21%     -0.51%     -0.13%
Finance                 0.26%     -1.01%      0.08%     -1.45%     -0.38%
Hotels And Tourism     -0.71%      0.13%      0.54%      0.47%     -0.42%
Hydropower             -0.95%      0.01%      0.65%     -0.18%     -0.25%
Investment             -0.38%     -0.12%     -0.08%      -0.2%     -0.03%
Life Insurance         -0.54%     -0.37%     -0.32%     -0.21%     -0.19%
Manu.and.Pro           -0.44%      0.26%      0.18%      0.26%     -0.49%
Microfinance           -0.52%     -0.18%         0%     -0.28%     -0.38%
Mutual Fund            -0.59%     -0.15%      0.01%      -0.2%      0.38%
Non-Life Insurance     -0.83%     -0.41%     -0.24%     -0.17%      0.35%
Others                 -1.49%      0.29%     -0.03%     -0.91%      0.18%
Trading                -1.77%     -0.38%     -0.43%     -1.23%      0.37%

In [11]:
data=driver.find_element(By.XPATH,"/html/body/form/div[4]/div[5]/div/div[3]/table").text

In [57]:
dfs = pd.concat(all_sector_data.values(),ignore_index=True)

final = dfs.pivot_table(index="sector",columns="Date",values="pct_changes",aggfunc="first")

final

Date               2026/06/08 2026/06/09 2026/06/10 2026/06/11 2026/06/12
sector
Banking                -0.45%         0%         0%     -0.25%     -0.12%
Development Banks      -0.98%     -0.06%      0.21%     -0.51%     -0.13%
Finance                 0.26%     -1.01%      0.08%     -1.45%     -0.38%
Hotels And Tourism     -0.71%      0.13%      0.54%      0.47%     -0.42%
Hydropower             -0.95%      0.01%      0.65%     -0.18%     -0.25%
Investment             -0.38%     -0.12%     -0.08%      -0.2%     -0.03%
Life Insurance         -0.54%     -0.37%     -0.32%     -0.21%     -0.19%
Manu.and.Pro           -0.44%      0.26%      0.18%      0.26%     -0.49%
Microfinance           -0.52%     -0.18%         0%     -0.28%     -0.38%
Mutual Fund            -0.59%     -0.15%      0.01%      -0.2%      0.38%
Non-Life Insurance     -0.83%     -0.41%     -0.24%     -0.17%      0.35%
Others                 -1.49%      0.29%     -0.03%     -0.91%      0.18%
Trading                -1.77%     -0.38%     -0.43%     -1.23%      0.37%

In [55]:
def data_converter(data, sector):
    rows = []
    for item in data.split("\n")[1:]:
        date = item.split()[1]
        pct_changes = item.split()[-1]

        rows.append([date, pct_changes])

    df = pd.DataFrame(rows, columns=["Date", "pct_changes"])
    df["sector"] = sector
    return df

In [23]:
data_converter(data)

          Date pct_changes
0   2026/06/11      -0.29%
1   2026/06/10       0.09%
2   2026/06/09      -0.05%
3   2026/06/08      -0.73%
4   2026/06/05      -0.41%
..         ...         ...
95  2026/01/08       0.17%
96  2026/01/07       -0.5%
97  2026/01/06       0.37%
98  2026/01/05        1.1%
99  2026/01/04      -0.39%

[100 rows x 2 columns]

In [ ]:
dfs=pd.concat(list(all_datas.values()),ignore_index=True)
    final=dfs.pivot(index="sector",columns="Date",values="pct_changes")
    final

In [29]:
 all_datas["Banking"]

         Date pct_changes   sector
0  2026/06/11       -0.2%  Banking
1  2026/06/10      -0.08%  Banking
2  2026/06/09      -0.12%  Banking
3  2026/06/08      -0.38%  Banking

In [49]:
dfs=pd.concat(list(all_datas.values()),ignore_index=True)
final=dfs.pivot(index="sector",columns="Date",values="pct_changes")
final

Date,2026/01/05,2026/01/06,2026/01/07,2026/01/08,2026/01/12,2026/01/13,2026/01/14,2026/01/18,2026/01/20,2026/01/21,...,2026/06/01,2026/06/02,2026/06/03,2026/06/04,2026/06/05,2026/06/08,2026/06/09,2026/06/10,2026/06/11,2026/06/12
sector,,,,,,,,,,,,,,,,,,,,,
Development Banks,2.53%,-0.23%,-1.39%,0.4%,0.1%,-0.48%,0.31%,2.02%,3.36%,-1.88%,...,-1.4%,0.12%,0.18%,-1.07%,0.05%,-0.71%,0.13%,0.54%,0.47%,-0.37%
Finance,1.44%,0.14%,-0.79%,0.32%,-0.11%,1.02%,0.07%,0.7%,1.77%,-0.03%,...,-1.97%,0.61%,-0.11%,-0.51%,-0.74%,-0.95%,0.01%,0.65%,-0.18%,-0.25%
Hotels And Tourism,0.22%,0.54%,0%,-0.22%,-1.16%,0.98%,0.67%,0.54%,0.37%,-1.36%,...,-6.14%,1.32%,-0.24%,-1.71%,-0.23%,-1.77%,-0.38%,-0.43%,-1.23%,0.37%
Hydropower,2.7%,0.79%,-0.84%,0.18%,0.02%,0%,0.01%,3.03%,1.45%,-0.59%,...,-0.81%,0.59%,0.66%,-0.44%,-0.16%,-0.98%,-0.06%,0.21%,-0.51%,-0.15%
Investment,0.73%,0.77%,-0.53%,-0.07%,-0.29%,0.78%,-0.13%,0.45%,1.44%,0.26%,...,3.36%,3.84%,-2.36%,-0.75%,-0.74%,-1.49%,0.29%,-0.03%,-0.91%,0.18%
Manu.and.Pro,0.57%,0.07%,-0.6%,0.26%,-0.14%,0.07%,0.38%,0.68%,1.65%,-0.3%,...,1.37%,1.02%,3.37%,-1.21%,0.06%,-0.83%,-0.41%,-0.24%,-0.17%,0.33%
Microfinance,0.83%,2.87%,0.21%,-0.44%,-0.53%,-0.29%,2.55%,5.73%,0.97%,-1.67%,...,-0.5%,6.03%,-1.16%,-0.22%,2.77%,0.26%,-1.01%,0.08%,-1.45%,-0.36%
Mutual Fund,3.05%,-0.51%,-1.16%,0.49%,1.02%,-0.23%,-0.41%,2.42%,1.4%,-0.46%,...,-1.42%,-0.42%,0.42%,-0.53%,-0.79%,-0.44%,0.26%,0.18%,0.26%,-0.49%
Non-Life Insurance,0.53%,0.83%,-0.4%,-0.04%,-0.66%,-0.2%,-0.05%,1.31%,1.54%,-0.25%,...,-0.9%,0.4%,0.45%,-0.18%,-0.16%,-0.52%,-0.18%,0%,-0.28%,-0.34%
Others,0.49%,0.04%,-0.07%,0.33%,-0.18%,-0.17%,-0.01%,1.25%,1.86%,-0.36%,...,-0.79%,0.27%,1.73%,-0.46%,-0.44%,-0.54%,-0.37%,-0.32%,-0.21%,-0.19%
Trading,0.67%,0.43%,-0.24%,0.3%,-0.25%,-0.14%,-0.08%,0.85%,1.24%,-0.16%,...,-0.99%,0.41%,-0.13%,-0.03%,-0.44%,-0.45%,0%,0%,-0.25%,-0.12%

In [65]:
final.to_csv("sectorwise.csv",index=True)

In [63]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\New folder\\nepalytix_broker_analysis_data'