In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## loc and iloc

In [ ]:
   0  1  2  3  4  5 
0 0,0 
1
2
3

## iloc

In [ ]:
df.iloc[row_slicing , column_slicing]

row_slicing :    start_row:ending_row:step_size
column_slicing :  start_col : ending_col : step_size

In [6]:
df.iloc[0:5,:]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
df.iloc[-5::,:]      # -1 bottom to up : 1 : top to bottom
                      # -1 : right to left , 1: left to right

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [9]:
df.iloc[:,0:3]

     total_bill   tip     sex
0         16.99  1.01  Female
1         10.34  1.66    Male
2         21.01  3.50    Male
3         23.68  3.31    Male
4         24.59  3.61  Female
..          ...   ...     ...
239       29.03  5.92    Male
240       27.18  2.00  Female
241       22.67  2.00    Male
242       17.82  1.75    Male
243       18.78  3.00  Female

[244 rows x 3 columns]

In [11]:
df.iloc[:,-3::]

      day    time  size
0     Sun  Dinner     2
1     Sun  Dinner     3
2     Sun  Dinner     3
3     Sun  Dinner     2
4     Sun  Dinner     4
..    ...     ...   ...
239   Sat  Dinner     3
240   Sat  Dinner     2
241   Sat  Dinner     2
242   Sat  Dinner     2
243  Thur  Dinner     2

[244 rows x 3 columns]

## set index and reset_index

In [13]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
df.set_index("time")

        total_bill   tip     sex smoker   day  size
time
Dinner       16.99  1.01  Female     No   Sun     2
Dinner       10.34  1.66    Male     No   Sun     3
Dinner       21.01  3.50    Male     No   Sun     3
Dinner       23.68  3.31    Male     No   Sun     2
Dinner       24.59  3.61  Female     No   Sun     4
...            ...   ...     ...    ...   ...   ...
Dinner       29.03  5.92    Male     No   Sat     3
Dinner       27.18  2.00  Female    Yes   Sat     2
Dinner       22.67  2.00    Male    Yes   Sat     2
Dinner       17.82  1.75    Male     No   Sat     2
Dinner       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [15]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
df.set_index(["sex","time"])

               total_bill   tip smoker   day  size
sex    time
Female Dinner       16.99  1.01     No   Sun     2
Male   Dinner       10.34  1.66     No   Sun     3
       Dinner       21.01  3.50     No   Sun     3
       Dinner       23.68  3.31     No   Sun     2
Female Dinner       24.59  3.61     No   Sun     4
...                   ...   ...    ...   ...   ...
Male   Dinner       29.03  5.92     No   Sat     3
Female Dinner       27.18  2.00    Yes   Sat     2
Male   Dinner       22.67  2.00    Yes   Sat     2
       Dinner       17.82  1.75     No   Sat     2
Female Dinner       18.78  3.00     No  Thur     2

[244 rows x 5 columns]

In [26]:
df.sort_values(['day','sex',"time"]).set_index(['day','sex',"time"])

                    total_bill    tip smoker  size
day  sex    time
Fri  Female Dinner        5.75   1.00    Yes     2
            Dinner       16.32   4.30    Yes     2
            Dinner       22.75   3.25     No     2
            Dinner       11.35   2.50    Yes     2
            Dinner       15.38   3.00    Yes     2
            Lunch        13.42   3.48    Yes     2
            Lunch        15.98   3.00     No     3
            Lunch        16.27   2.50    Yes     2
            Lunch        10.09   2.00    Yes     2
     Male   Dinner       28.97   3.00    Yes     2
            Dinner       22.49   3.50     No     2
            Dinner       40.17   4.73    Yes     4
            Dinner       27.28   4.00    Yes     2
            Dinner       12.03   1.50    Yes     2
            Dinner       21.01   3.00    Yes     2
            Dinner       12.46   1.50     No     2
            Lunch        12.16   2.20    Yes     2
            Lunch         8.58   1.92    Yes     1
            Lunch        13.42   1.58    Yes     2
Sat  Female Dinner       20.29   2.75     No     2
            Dinner       15.77   2.23     No     2
            Dinner       19.65   3.00     No     2
            Dinner       15.06   3.00     No     2
            Dinner       20.69   2.45     No     4
            Dinner       16.93   3.07     No     3
            Dinner       26.41   1.50     No     2
            Dinner       16.45   2.47     No     2
            Dinner        3.07   1.00    Yes     1
            Dinner       17.07   3.00     No     3
            Dinner       26.86   3.14    Yes     2
            Dinner       25.28   5.00    Yes     2
            Dinner       14.73   2.20     No     2
            Dinner       44.30   2.50    Yes     3
            Dinner       22.42   3.48    Yes     2
            Dinner       20.92   4.08     No     2
            Dinner       14.31   4.00    Yes     2
            Dinner        7.25   1.00     No     1
            Dinner       10.59   1.61    Yes     2
            Dinner       10.63   2.00    Yes     2
            Dinner       12.76   2.23    Yes     2
            Dinner       13.27   2.50    Yes     2
            Dinner       28.17   6.50    Yes     3
            Dinner       12.90   1.10    Yes     2
            Dinner       30.14   3.09    Yes     4
            Dinner       22.12   2.88    Yes     2
            Dinner       35.83   4.67     No     3
            Dinner       27.18   2.00    Yes     2
     Male   Dinner       20.65   3.35     No     3
            Dinner       17.92   4.08     No     2
            Dinner       39.42   7.58     No     4
            Dinner       19.82   3.18     No     2
            Dinner       17.81   2.34     No     4
            Dinner       13.37   2.00     No     2
            Dinner       12.69   2.00     No     2
            Dinner       21.70   4.30     No     2
            Dinner        9.55   1.45     No     2
            Dinner       18.35   2.50     No     4
            Dinner       17.78   3.27     No     2
            Dinner       24.06   3.60     No     3
            Dinner       16.31   2.00     No     3
            Dinner       18.69   2.31     No     3
            Dinner       31.27   5.00     No     3
            Dinner       16.04   2.24     No     3
            Dinner       38.01   3.00    Yes     4
            Dinner       11.24   1.76    Yes     2
            Dinner       48.27   6.73     No     4
            Dinner       20.29   3.21    Yes     2
            Dinner       13.81   2.00    Yes     2
            Dinner       11.02   1.98    Yes     2
            Dinner       18.29   3.76    Yes     4
            Dinner       17.59   2.64     No     3
            Dinner       20.08   3.15     No     3
            Dinner       20.23   2.01     No     2
            Dinner       15.01   2.09    Yes     2
            Dinner       12.02   1.97     No     2
            Dinner       10.51   1.25     No     2
            Dinner       17.92   3.08    Yes     2
            Dinner       15.36   1.64    Yes     2
            Dinner       20.49   4.06    Yes     2
            Dinner       25.21   4.29    Yes     2
            Dinner       18.24   3.76     No     2
            Dinner       14.00   3.00     No     2
            Dinner       50.81  10.00    Yes     3
            Dinner       15.81   3.16    Yes     2
            Dinner       26.59   3.41    Yes     3
            Dinner       38.73   3.00    Yes     4
            Dinner       24.27   2.03    Yes     2
            Dinner       30.06   2.00    Yes     3
            Dinner       25.89   5.16    Yes     4
            Dinner       48.33   9.00     No     4
            Dinner       28.15   3.00    Yes     5
            Dinner       11.59   1.50    Yes     2
            Dinner        7.74   1.44    Yes     2
            Dinner       20.45   3.00     No     4
            Dinner       13.28   2.72     No     2
            Dinner       24.01   2.00    Yes     4
            Dinner       15.69   3.00    Yes     3
            Dinner       11.61   3.39     No     2
            Dinner       10.77   1.47     No     2
            Dinner       15.53   3.00    Yes     2
            Dinner       10.07   1.25     No     2
            Dinner       12.60   1.00    Yes     2
            Dinner       32.83   1.17    Yes     2
            Dinner       29.03   5.92     No     3
            Dinner       22.67   2.00    Yes     2
            Dinner       17.82   1.75     No     2
Sun  Female Dinner       16.99   1.01     No     2
            Dinner       24.59   3.61     No     4
            Dinner       35.26   5.00     No     4
            Dinner       14.83   3.02     No     2
            Dinner       10.33   1.67     No     3
            Dinner       16.97   3.50     No     3
            Dinner       10.29   2.60     No     2
            Dinner       34.81   5.20     No     4
            Dinner       25.71   4.00     No     3
            Dinner       17.31   3.50     No     2
            Dinner       29.85   5.14     No     5
            Dinner       25.00   3.75     No     4
            Dinner       13.39   2.61     No     2
            Dinner       16.21   2.00     No     3
            Dinner       17.51   3.00    Yes     2
            Dinner        9.60   4.00    Yes     2
            Dinner       20.90   3.50    Yes     3
            Dinner       18.15   3.50    Yes     3
     Male   Dinner       10.34   1.66     No     3
            Dinner       21.01   3.50     No     3
            Dinner       23.68   3.31     No     2
            Dinner       25.29   4.71     No     4
            Dinner        8.77   2.00     No     2
            Dinner       26.88   3.12     No     4
            Dinner       15.04   1.96     No     2
            Dinner       14.78   3.23     No     2
            Dinner       10.27   1.71     No     2
            Dinner       15.42   1.57     No     2
            Dinner       18.43   3.00     No     4
            Dinner       21.58   3.92     No     2
            Dinner       16.29   3.71     No     3
            Dinner       17.46   2.54     No     2
            Dinner       13.94   3.06     No     2
            Dinner        9.68   1.32     No     2
            Dinner       30.40   5.60     No     4
            Dinner       18.29   3.00     No     2
            Dinner       22.23   5.00     No     2
            Dinner       32.40   6.00     No     4
            Dinner       28.55   2.05     No     3
            Dinner       18.04   3.00     No     2
            Dinner       12.54   2.50     No     2
            Dinner        9.94   1.56     No     2
            Dinner       25.56   4.34     No     4
            Dinner       19.49   3.51     No     2
            Dinner       38.07   4.00     No     3
            Dinner       23.95   2.55     No     2
            Dinner       29.93   5.07     No     4
            Dinner       14.07   2.50     No     2
            Dinner       13.13   2.00     No     2
            Dinner       17.26   2.74     No     3
            Dinner       24.55   2.00     No     4
            Dinner       19.77   2.00     No     4
            Dinner       48.17   5.00     No     6
            Dinner       16.49   2.00     No     4
            Dinner       21.50   3.50     No     4
            Dinner       12.66   2.50     No     2
            Dinner       13.81   2.00     No     2
            Dinner       24.52   3.48     No     3
            Dinner       20.76   2.24     No     2
            Dinner       31.71   4.50     No     4
            Dinner        7.25   5.15    Yes     2
            Dinner       31.85   3.18    Yes     2
            Dinner       16.82   4.00    Yes     2
            Dinner       32.90   3.11    Yes     2
            Dinner       17.89   2.00    Yes     2
            Dinner       14.48   2.00    Yes     2
            Dinner       34.63   3.55    Yes     2
            Dinner       34.65   3.68    Yes     4
            Dinner       23.33   5.65    Yes     2
            Dinner       45.35   3.50    Yes     3
            Dinner       23.17   6.50    Yes     4
            Dinner       40.55   3.00    Yes     2
            Dinner       20.69   5.00     No     5
            Dinner       30.46   2.00    Yes     5
            Dinner       23.10   4.00    Yes     3
            Dinner       15.69   1.50    Yes     2
Thur Female Dinner       18.78   3.00     No     2
            Lunch        10.07   1.83     No     1
            Lunch        34.83   5.17     No     4
            Lunch        10.65   1.50     No     2
            Lunch        12.43   1.80     No     2
            Lunch        24.08   2.92     No     4
            Lunch        13.42   1.68     No     2
            Lunch        12.48   2.52     No     2
            Lunch        29.80   4.20     No     6
            Lunch        14.52   2.00     No     2
            Lunch        11.38   2.00     No     2
            Lunch        20.27   2.83     No     2
            Lunch        11.17   1.50     No     2
            Lunch        12.26   2.00     No     2
            Lunch        18.26   3.25     No     2
            Lunch         8.51   1.25     No     2
            Lunch        10.33   2.00     No     2
            Lunch        14.15   2.00     No     2
            Lunch        13.16   2.75     No     2
            Lunch        17.47   3.50     No     2
            Lunch        27.05   5.00     No     6
            Lunch        16.43   2.30     No     2
            Lunch         8.35   1.50     No     2
            Lunch        18.64   1.36     No     3
            Lunch        11.87   1.63     No     2
            Lunch        19.81   4.19    Yes     2
            Lunch        43.11   5.00    Yes     4
            Lunch        13.00   2.00    Yes     2
            Lunch        12.74   2.01    Yes     2
            Lunch        13.00   2.00    Yes     2
            Lunch        16.40   2.50    Yes     2
            Lunch        16.47   3.23    Yes     3
     Male   Lunch        27.20   4.00     No     4
            Lunch        22.76   3.00     No     2
            Lunch        17.29   2.71     No     2
            Lunch        19.44   3.00    Yes     2
            Lunch        16.66   3.40     No     2
            Lunch        32.68   5.00    Yes     2
            Lunch        15.98   2.03     No     2
            Lunch        13.03   2.00     No     2
            Lunch        18.28   4.00     No     2
            Lunch        24.71   5.85     No     2
            Lunch        21.16   3.00     No     2
            Lunch        11.69   2.31     No     2
            Lunch        14.26   2.50     No     2
            Lunch        15.95   2.00     No     2
            Lunch         8.52   1.48     No     2
            Lunch        22.82   2.18     No     3
            Lunch        19.08   1.50     No     2
            Lunch        16.00   2.00    Yes     2
            Lunch        34.30   6.70     No     6
            Lunch        41.19   5.00     No     5
            Lunch         9.78   1.73     No     2
            Lunch         7.51   2.00     No     2
            Lunch        28.44   2.56    Yes     2
            Lunch        15.48   2.02    Yes     2
            Lunch        16.58   4.00    Yes     2
            Lunch         7.56   1.44     No     2
            Lunch        10.34   2.00    Yes     2
            Lunch        13.51   2.00    Yes     2
            Lunch        18.71   4.00    Yes     3
            Lunch        20.53   4.00    Yes     4

In [28]:
pd.reset_option('display.max_rows',None)

In [29]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
pd.set_option('display.max_rows',None)

### iloc

In [32]:
temp=df.set_index("smoker")
temp

        total_bill   tip     sex   day    time  size
smoker
No           16.99  1.01  Female   Sun  Dinner     2
No           10.34  1.66    Male   Sun  Dinner     3
No           21.01  3.50    Male   Sun  Dinner     3
No           23.68  3.31    Male   Sun  Dinner     2
No           24.59  3.61  Female   Sun  Dinner     4
...            ...   ...     ...   ...     ...   ...
No           29.03  5.92    Male   Sat  Dinner     3
Yes          27.18  2.00  Female   Sat  Dinner     2
Yes          22.67  2.00    Male   Sat  Dinner     2
No           17.82  1.75    Male   Sat  Dinner     2
No           18.78  3.00  Female  Thur  Dinner     2

[244 rows x 6 columns]

In [33]:
temp.iloc[0:5,:]

        total_bill   tip     sex  day    time  size
smoker
No           16.99  1.01  Female  Sun  Dinner     2
No           10.34  1.66    Male  Sun  Dinner     3
No           21.01  3.50    Male  Sun  Dinner     3
No           23.68  3.31    Male  Sun  Dinner     2
No           24.59  3.61  Female  Sun  Dinner     4

In [34]:
temp=df.set_index(["sex","time"])
temp

               total_bill   tip smoker   day  size
sex    time
Female Dinner       16.99  1.01     No   Sun     2
Male   Dinner       10.34  1.66     No   Sun     3
       Dinner       21.01  3.50     No   Sun     3
       Dinner       23.68  3.31     No   Sun     2
Female Dinner       24.59  3.61     No   Sun     4
...                   ...   ...    ...   ...   ...
Male   Dinner       29.03  5.92     No   Sat     3
Female Dinner       27.18  2.00    Yes   Sat     2
Male   Dinner       22.67  2.00    Yes   Sat     2
       Dinner       17.82  1.75     No   Sat     2
Female Dinner       18.78  3.00     No  Thur     2

[244 rows x 5 columns]

In [35]:
temp.iloc[0:5,:]  # i means index position

               total_bill   tip smoker  day  size
sex    time
Female Dinner       16.99  1.01     No  Sun     2
Male   Dinner       10.34  1.66     No  Sun     3
       Dinner       21.01  3.50     No  Sun     3
       Dinner       23.68  3.31     No  Sun     2
Female Dinner       24.59  3.61     No  Sun     4

In [38]:
temp.iloc[[0,1,10,12]]

               total_bill   tip smoker  day  size
sex    time
Female Dinner       16.99  1.01     No  Sun     2
Male   Dinner       10.34  1.66     No  Sun     3
       Dinner       10.27  1.71     No  Sun     2
       Dinner       15.42  1.57     No  Sun     2

In [40]:
temp.iloc[[0,1,10,12],[0,1,-1]]

               total_bill   tip  size
sex    time
Female Dinner       16.99  1.01     2
Male   Dinner       10.34  1.66     3
       Dinner       10.27  1.71     2
       Dinner       15.42  1.57     2

## fins the top 5 rows

In [45]:
df.nlargest(5,"total_bill").columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [47]:
df.nlargest(5,"total_bill").index

Index([170, 212, 59, 156, 182], dtype='int64')

In [48]:
df.iloc[df.nlargest(5,"total_bill").index]

     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

## Loc : value basis

In [51]:
temps=df.set_index('sex')
temps

        total_bill   tip smoker   day    time  size
sex
Female       16.99  1.01     No   Sun  Dinner     2
Male         10.34  1.66     No   Sun  Dinner     3
Male         21.01  3.50     No   Sun  Dinner     3
Male         23.68  3.31     No   Sun  Dinner     2
Female       24.59  3.61     No   Sun  Dinner     4
...            ...   ...    ...   ...     ...   ...
Male         29.03  5.92     No   Sat  Dinner     3
Female       27.18  2.00    Yes   Sat  Dinner     2
Male         22.67  2.00    Yes   Sat  Dinner     2
Male         17.82  1.75     No   Sat  Dinner     2
Female       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [52]:
temps.loc["Female"]

        total_bill   tip smoker   day    time  size
sex
Female       16.99  1.01     No   Sun  Dinner     2
Female       24.59  3.61     No   Sun  Dinner     4
Female       35.26  5.00     No   Sun  Dinner     4
Female       14.83  3.02     No   Sun  Dinner     2
Female       10.33  1.67     No   Sun  Dinner     3
...            ...   ...    ...   ...     ...   ...
Female       10.09  2.00    Yes   Fri   Lunch     2
Female       22.12  2.88    Yes   Sat  Dinner     2
Female       35.83  4.67     No   Sat  Dinner     3
Female       27.18  2.00    Yes   Sat  Dinner     2
Female       18.78  3.00     No  Thur  Dinner     2

[87 rows x 6 columns]

In [54]:
temps.loc[["Female"],["smoker","day","time"]]

       smoker   day    time
sex
Female     No   Sun  Dinner
Female     No   Sun  Dinner
Female     No   Sun  Dinner
Female     No   Sun  Dinner
Female     No   Sun  Dinner
...       ...   ...     ...
Female    Yes   Fri   Lunch
Female    Yes   Sat  Dinner
Female     No   Sat  Dinner
Female    Yes   Sat  Dinner
Female     No  Thur  Dinner

[87 rows x 3 columns]

In [59]:
temp=df.set_index("sex")
temp

        total_bill   tip smoker   day    time  size
sex
Female       16.99  1.01     No   Sun  Dinner     2
Male         10.34  1.66     No   Sun  Dinner     3
Male         21.01  3.50     No   Sun  Dinner     3
Male         23.68  3.31     No   Sun  Dinner     2
Female       24.59  3.61     No   Sun  Dinner     4
...            ...   ...    ...   ...     ...   ...
Male         29.03  5.92     No   Sat  Dinner     3
Female       27.18  2.00    Yes   Sat  Dinner     2
Male         22.67  2.00    Yes   Sat  Dinner     2
Male         17.82  1.75     No   Sat  Dinner     2
Female       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [60]:
temp.index

Index(['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male',
       'Male', 'Male',
       ...
       'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Male', 'Female'],
      dtype='object', name='sex', length=244)

In [62]:
temp[temp.index=="Female"]

        total_bill   tip smoker   day    time  size
sex
Female       16.99  1.01     No   Sun  Dinner     2
Female       24.59  3.61     No   Sun  Dinner     4
Female       35.26  5.00     No   Sun  Dinner     4
Female       14.83  3.02     No   Sun  Dinner     2
Female       10.33  1.67     No   Sun  Dinner     3
...            ...   ...    ...   ...     ...   ...
Female       10.09  2.00    Yes   Fri   Lunch     2
Female       22.12  2.88    Yes   Sat  Dinner     2
Female       35.83  4.67     No   Sat  Dinner     3
Female       27.18  2.00    Yes   Sat  Dinner     2
Female       18.78  3.00     No  Thur  Dinner     2

[87 rows x 6 columns]

In [66]:
temp.loc[:,"total_bill":"smoker"]

        total_bill   tip smoker
sex
Female       16.99  1.01     No
Male         10.34  1.66     No
Male         21.01  3.50     No
Male         23.68  3.31     No
Female       24.59  3.61     No
...            ...   ...    ...
Male         29.03  5.92     No
Female       27.18  2.00    Yes
Male         22.67  2.00    Yes
Male         17.82  1.75     No
Female       18.78  3.00     No

[244 rows x 3 columns]

### multi index data extractions

In [69]:
temp.loc[:,["total_bill","smoker"]]

        total_bill smoker
sex
Female       16.99     No
Male         10.34     No
Male         21.01     No
Male         23.68     No
Female       24.59     No
...            ...    ...
Male         29.03     No
Female       27.18    Yes
Male         22.67    Yes
Male         17.82     No
Female       18.78     No

[244 rows x 2 columns]

## Creating a Multi Index

In [82]:
temp=df.sort_values(['day',"smoker"]).set_index(["day","smoker"])
temp

             total_bill   tip     sex    time  size
day  smoker
Fri  No           22.49  3.50    Male  Dinner     2
     No           22.75  3.25  Female  Dinner     2
     No           12.46  1.50    Male  Dinner     2
     No           15.98  3.00  Female   Lunch     3
     Yes          28.97  3.00    Male  Dinner     2
...                 ...   ...     ...     ...   ...
Thur Yes          12.74  2.01  Female   Lunch     2
     Yes          13.00  2.00  Female   Lunch     2
     Yes          16.40  2.50  Female   Lunch     2
     Yes          20.53  4.00    Male   Lunch     4
     Yes          16.47  3.23  Female   Lunch     3

[244 rows x 5 columns]

In [83]:
conds=[("Fri","No"),("Thur","No"),("Sat","Yes")]
temp.loc[conds]

             total_bill   tip     sex    time  size
day  smoker
Fri  No           22.49  3.50    Male  Dinner     2
     No           22.75  3.25  Female  Dinner     2
     No           12.46  1.50    Male  Dinner     2
     No           15.98  3.00  Female   Lunch     3
Thur No           27.20  4.00    Male   Lunch     4
...                 ...   ...     ...     ...   ...
Sat  Yes          15.53  3.00    Male  Dinner     2
     Yes          12.60  1.00    Male  Dinner     2
     Yes          32.83  1.17    Male  Dinner     2
     Yes          27.18  2.00  Female  Dinner     2
     Yes          22.67  2.00    Male  Dinner     2

[91 rows x 5 columns]

## Cresting a 3 index columns

In [105]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [102]:
df.set_index(["day","sex","smoker"])

                    total_bill   tip    time  size
day  sex    smoker
Sun  Female No           16.99  1.01  Dinner     2
     Male   No           10.34  1.66  Dinner     3
            No           21.01  3.50  Dinner     3
            No           23.68  3.31  Dinner     2
     Female No           24.59  3.61  Dinner     4
...                        ...   ...     ...   ...
Sat  Male   No           29.03  5.92  Dinner     3
     Female Yes          27.18  2.00  Dinner     2
     Male   Yes          22.67  2.00  Dinner     2
            No           17.82  1.75  Dinner     2
Thur Female No           18.78  3.00  Dinner     2

[244 rows x 4 columns]

In [85]:
temp=df.sort_values(['day',"sex","smoker"]).set_index(["day","sex","smoker"])
temp

                    total_bill   tip    time  size
day  sex    smoker
Fri  Female No           22.75  3.25  Dinner     2
            No           15.98  3.00   Lunch     3
            Yes           5.75  1.00  Dinner     2
            Yes          16.32  4.30  Dinner     2
            Yes          11.35  2.50  Dinner     2
...                        ...   ...     ...   ...
Thur Male   Yes          16.58  4.00   Lunch     2
            Yes          10.34  2.00   Lunch     2
            Yes          13.51  2.00   Lunch     2
            Yes          18.71  4.00   Lunch     3
            Yes          20.53  4.00   Lunch     4

[244 rows x 4 columns]

In [91]:
cond=[("Fri","Male","No"),("Sat","Female","Yes"),("Fri","Female","Yes")]
temp.loc[cond]

                   total_bill   tip    time  size
day sex    smoker
Fri Male   No           22.49  3.50  Dinner     2
           No           12.46  1.50  Dinner     2
Sat Female Yes           3.07  1.00  Dinner     1
           Yes          26.86  3.14  Dinner     2
           Yes          25.28  5.00  Dinner     2
           Yes          44.30  2.50  Dinner     3
           Yes          22.42  3.48  Dinner     2
           Yes          14.31  4.00  Dinner     2
           Yes          10.59  1.61  Dinner     2
           Yes          10.63  2.00  Dinner     2
           Yes          12.76  2.23  Dinner     2
           Yes          13.27  2.50  Dinner     2
           Yes          28.17  6.50  Dinner     3
           Yes          12.90  1.10  Dinner     2
           Yes          30.14  3.09  Dinner     4
           Yes          22.12  2.88  Dinner     2
           Yes          27.18  2.00  Dinner     2
Fri Female Yes           5.75  1.00  Dinner     2
           Yes          16.32  4.30  Dinner     2
           Yes          11.35  2.50  Dinner     2
           Yes          15.38  3.00  Dinner     2
           Yes          13.42  3.48   Lunch     2
           Yes          16.27  2.50   Lunch     2
           Yes          10.09  2.00   Lunch     2

In [101]:
summary=(df.groupby(['sex',"day","smoker"]).
           agg({"total_bill":['sum','mean','max',"min"],
                'tip':['sum','mean','max',"min"]}))
summary

                   total_bill                              tip            \
                          sum       mean    max    min     sum      mean
sex    day  smoker
Female Fri  No          38.73  19.365000  22.75  15.98    6.25  3.125000
            Yes         88.58  12.654286  16.32   5.75   18.78  2.682857
       Sat  No         247.05  19.003846  35.83   7.25   35.42  2.724615
            Yes        304.00  20.266667  44.30   3.07   43.03  2.868667
       Sun  No         291.54  20.824286  35.26  10.29   46.61  3.329286
            Yes         66.16  16.540000  20.90   9.60   14.00  3.500000
       Thur No         400.36  16.014400  34.83   8.35   61.49  2.459600
            Yes        134.53  19.218571  43.11  12.74   20.93  2.990000
Male   Fri  No          34.95  17.475000  22.49  12.46    5.00  2.500000
            Yes        163.62  20.452500  40.17   8.58   21.93  2.741250
       Sat  No         637.73  19.929063  48.33   9.55  104.21  3.256563
            Yes        589.62  21.837778  50.81   7.74   77.74  2.879259
       Sun  No         877.34  20.403256  48.17   8.77  133.96  3.115349
            Yes        392.12  26.141333  45.35   7.25   52.82  3.521333
       Thur No         369.73  18.486500  41.19   7.51   58.83  2.941500
            Yes        191.71  19.171000  32.68  10.34   30.58  3.058000


                      max   min
sex    day  smoker
Female Fri  No       3.25  3.00
            Yes      4.30  1.00
       Sat  No       4.67  1.00
            Yes      6.50  1.00
       Sun  No       5.20  1.01
            Yes      4.00  3.00
       Thur No       5.17  1.25
            Yes      5.00  2.00
Male   Fri  No       3.50  1.50
            Yes      4.73  1.50
       Sat  No       9.00  1.25
            Yes     10.00  1.00
       Sun  No       6.00  1.32
            Yes      6.50  1.50
       Thur No       6.70  1.44
            Yes      5.00  2.00

In [125]:
summary=(df.groupby(["day","smoker","sex"]).
           agg({"total_bill":['sum','mean','max',"min"],
                'tip':['sum','mean','max',"min"]}))
summary

                   total_bill                              tip            \
                          sum       mean    max    min     sum      mean
day  smoker sex
Fri  No     Female      38.73  19.365000  22.75  15.98    6.25  3.125000
            Male        34.95  17.475000  22.49  12.46    5.00  2.500000
     Yes    Female      88.58  12.654286  16.32   5.75   18.78  2.682857
            Male       163.62  20.452500  40.17   8.58   21.93  2.741250
Sat  No     Female     247.05  19.003846  35.83   7.25   35.42  2.724615
            Male       637.73  19.929063  48.33   9.55  104.21  3.256563
     Yes    Female     304.00  20.266667  44.30   3.07   43.03  2.868667
            Male       589.62  21.837778  50.81   7.74   77.74  2.879259
Sun  No     Female     291.54  20.824286  35.26  10.29   46.61  3.329286
            Male       877.34  20.403256  48.17   8.77  133.96  3.115349
     Yes    Female      66.16  16.540000  20.90   9.60   14.00  3.500000
            Male       392.12  26.141333  45.35   7.25   52.82  3.521333
Thur No     Female     400.36  16.014400  34.83   8.35   61.49  2.459600
            Male       369.73  18.486500  41.19   7.51   58.83  2.941500
     Yes    Female     134.53  19.218571  43.11  12.74   20.93  2.990000
            Male       191.71  19.171000  32.68  10.34   30.58  3.058000


                      max   min
day  smoker sex
Fri  No     Female   3.25  3.00
            Male     3.50  1.50
     Yes    Female   4.30  1.00
            Male     4.73  1.50
Sat  No     Female   4.67  1.00
            Male     9.00  1.25
     Yes    Female   6.50  1.00
            Male    10.00  1.00
Sun  No     Female   5.20  1.01
            Male     6.00  1.32
     Yes    Female   4.00  3.00
            Male     6.50  1.50
Thur No     Female   5.17  1.25
            Male     6.70  1.44
     Yes    Female   5.00  2.00
            Male     5.00  2.00

In [107]:
row_filter=[("Fri")]
col_filter=[("total_bill")]

summary.loc[row_filter,col_filter]

                  total_bill
                         sum       mean    max    min
day smoker sex
Fri No     Female      38.73  19.365000  22.75  15.98
           Male        34.95  17.475000  22.49  12.46
    Yes    Female      88.58  12.654286  16.32   5.75
           Male       163.62  20.452500  40.17   8.58

In [112]:
summary.columns

MultiIndex([('total_bill',  'sum'),
            ('total_bill', 'mean'),
            ('total_bill',  'max'),
            ('total_bill',  'min'),
            (       'tip',  'sum'),
            (       'tip', 'mean'),
            (       'tip',  'max'),
            (       'tip',  'min')],
           )

## Multi index

In [115]:
sales = pd.DataFrame({
    "city": ["Kathmandu", "Kathmandu", "Pokhara", "Pokhara"],
    "year": [2024, 2025, 2024, 2025],
    "sales": [100, 150, 120, 180],
    "profit": [20, 35, 25, 40]
})

sales

        city  year  sales  profit
0  Kathmandu  2024    100      20
1  Kathmandu  2025    150      35
2    Pokhara  2024    120      25
3    Pokhara  2025    180      40

In [120]:
summary = sales.groupby("city").agg({
    "sales": ["sum", "mean"],
    "profit": ["sum", "mean","max"]
})

summary

          sales        profit
            sum   mean    sum  mean max
city
Kathmandu   250  125.0     55  27.5  35
Pokhara     300  150.0     65  32.5  40

In [121]:
summary.columns

MultiIndex([( 'sales',  'sum'),
            ( 'sales', 'mean'),
            ('profit',  'sum'),
            ('profit', 'mean'),
            ('profit',  'max')],
           )

In [119]:
summary.index

Index(['Kathmandu', 'Pokhara'], dtype='object', name='city')

In [122]:
summary

          sales        profit
            sum   mean    sum  mean max
city
Kathmandu   250  125.0     55  27.5  35
Pokhara     300  150.0     65  32.5  40

In [123]:
summary[("sales", "sum")]

city
Kathmandu    250
Pokhara      300
Name: (sales, sum), dtype: int64

In [124]:
summary.loc[
    :,
    [("sales", "sum"), ("profit", "mean")]
]

          sales profit
            sum   mean
city
Kathmandu   250   27.5
Pokhara     300   32.5

In [126]:
summary

                   total_bill                              tip            \
                          sum       mean    max    min     sum      mean
day  smoker sex
Fri  No     Female      38.73  19.365000  22.75  15.98    6.25  3.125000
            Male        34.95  17.475000  22.49  12.46    5.00  2.500000
     Yes    Female      88.58  12.654286  16.32   5.75   18.78  2.682857
            Male       163.62  20.452500  40.17   8.58   21.93  2.741250
Sat  No     Female     247.05  19.003846  35.83   7.25   35.42  2.724615
            Male       637.73  19.929063  48.33   9.55  104.21  3.256563
     Yes    Female     304.00  20.266667  44.30   3.07   43.03  2.868667
            Male       589.62  21.837778  50.81   7.74   77.74  2.879259
Sun  No     Female     291.54  20.824286  35.26  10.29   46.61  3.329286
            Male       877.34  20.403256  48.17   8.77  133.96  3.115349
     Yes    Female      66.16  16.540000  20.90   9.60   14.00  3.500000
            Male       392.12  26.141333  45.35   7.25   52.82  3.521333
Thur No     Female     400.36  16.014400  34.83   8.35   61.49  2.459600
            Male       369.73  18.486500  41.19   7.51   58.83  2.941500
     Yes    Female     134.53  19.218571  43.11  12.74   20.93  2.990000
            Male       191.71  19.171000  32.68  10.34   30.58  3.058000


                      max   min
day  smoker sex
Fri  No     Female   3.25  3.00
            Male     3.50  1.50
     Yes    Female   4.30  1.00
            Male     4.73  1.50
Sat  No     Female   4.67  1.00
            Male     9.00  1.25
     Yes    Female   6.50  1.00
            Male    10.00  1.00
Sun  No     Female   5.20  1.01
            Male     6.00  1.32
     Yes    Female   4.00  3.00
            Male     6.50  1.50
Thur No     Female   5.17  1.25
            Male     6.70  1.44
     Yes    Female   5.00  2.00
            Male     5.00  2.00

In [143]:
cols=[("total_bill","sum"),("total_bill","mean"),("tip","sum"),("tip","mean")]
rows=[("Fri","No","Male"),("Sat","Yes","Female"),("Fri","No","Female")]

In [144]:
summary.loc[rows,cols]

                  total_bill               tip
                         sum       mean    sum      mean
day smoker sex
Fri No     Male        34.95  17.475000   5.00  2.500000
Sat Yes    Female     304.00  20.266667  43.03  2.868667
Fri No     Female      38.73  19.365000   6.25  3.125000

### gap

In [201]:
df=pd.read_csv("gap.csv")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [151]:
temps=df.sort_values(['year',"continent","country"]).set_index(['year',"continent","country"])
temps

                               lifeExp       pop     gdpPercap iso_alpha  \
year continent country
1952 Africa    Algeria          43.077   9279525   2449.008185       DZA
               Angola           30.015   4232095   3520.610273       AGO
               Benin            38.223   1738315   1062.752200       BEN
               Botswana         47.622    442308    851.241141       BWA
               Burkina Faso     31.975   4469979    543.255241       BFA
...                                ...       ...           ...       ...
2007 Europe    Switzerland      81.701   7554661  37506.419070       CHE
               Turkey           71.777  71158647   8458.276384       TUR
               United Kingdom   79.425  60776238  33203.261280       GBR
     Oceania   Australia        81.235  20434176  34435.367440       AUS
               New Zealand      80.204   4115771  25185.009110       NZL

                               iso_num
year continent country
1952 Africa    Algeria              12
               Angola               24
               Benin               204
               Botswana             72
               Burkina Faso        854
...                                ...
2007 Europe    Switzerland         756
               Turkey              792
               United Kingdom      826
     Oceania   Australia            36
               New Zealand         554

[1704 rows x 5 columns]

In [154]:
temps.loc[(2007,"Asia"),:]

                    lifeExp         pop     gdpPercap iso_alpha  iso_num
country
Afghanistan          43.828    31889923    974.580338       AFG        4
Bahrain              75.635      708573  29796.048340       BHR       48
Bangladesh           64.062   150448339   1391.253792       BGD       50
Cambodia             59.723    14131858   1713.778686       KHM      116
China                72.961  1318683096   4959.114854       CHN      156
Hong Kong, China     82.208     6980412  39724.978670       HKG      344
India                64.698  1110396331   2452.210407       IND      356
Indonesia            70.650   223547000   3540.651564       IDN      360
Iran                 70.964    69453570  11605.714490       IRN      364
Iraq                 59.545    27499638   4471.061906       IRQ      368
Israel               80.745     6426679  25523.277100       ISR      376
Japan                82.603   127467972  31656.068060       JPN      392
Jordan               72.535     6053193   4519.461171       JOR      400
Korea, Dem. Rep.     67.297    23301725   1593.065480       KOR      410
Korea, Rep.          78.623    49044790  23348.139730       KOR      410
Kuwait               77.588     2505559  47306.989780       KWT      414
Lebanon              71.993     3921278  10461.058680       LBN      422
Malaysia             74.241    24821286  12451.655800       MYS      458
Mongolia             66.803     2874127   3095.772271       MNG      496
Myanmar              62.069    47761980    944.000000       MMR      104
Nepal                63.785    28901790   1091.359778       NPL      524
Oman                 75.640     3204897  22316.192870       OMN      512
Pakistan             65.483   169270617   2605.947580       PAK      586
Philippines          71.688    91077287   3190.481016       PHL      608
Saudi Arabia         72.777    27601038  21654.831940       SAU      682
Singapore            79.972     4553009  47143.179640       SGP      702
Sri Lanka            72.396    20378239   3970.095407       LKA      144
Syria                74.143    19314747   4184.548089       SYR      760
Taiwan               78.400    23174294  28718.276840       TWN      158
Thailand             70.616    65068149   7458.396327       THA      764
Vietnam              74.249    85262356   2441.576404       VNM      704
West Bank and Gaza   73.422     4018332   3025.349798       PSE      275
Yemen, Rep.          62.698    22211743   2280.769906       YEM      887

In [160]:
comb=[(1952,"Asia","Nepal"),(1952,"Asia","India"),(2007,"Asia","Nepal"),(2007,"Asia","India")]

In [159]:
df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [ ]:
(1957, "Asia","Nepal")

In [161]:
temps.loc[comb,:]

                        lifeExp         pop    gdpPercap iso_alpha  iso_num
year continent country
1952 Asia      Nepal     36.157     9182536   545.865723       NPL      524
               India     37.373   372000000   546.565749       IND      356
2007 Asia      Nepal     63.785    28901790  1091.359778       NPL      524
               India     64.698  1110396331  2452.210407       IND      356

## Reset index

In [165]:
temps.loc[comb,:].reset_index()

   year continent country  lifeExp         pop    gdpPercap iso_alpha  iso_num
0  1952      Asia   Nepal   36.157     9182536   545.865723       NPL      524
1  1952      Asia   India   37.373   372000000   546.565749       IND      356
2  2007      Asia   Nepal   63.785    28901790  1091.359778       NPL      524
3  2007      Asia   India   64.698  1110396331  2452.210407       IND      356

## Pivot

In [202]:
temps=df[df['country'].isin(["Nepal","India","China","Canada"])]
temps

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
240,Canada,Americas,1952,68.75000,14785584,11367.161120,CAN,124
241,Canada,Americas,1957,69.96000,17010154,12489.950060,CAN,124
242,Canada,Americas,1962,71.30000,18985849,13462.485550,CAN,124
243,Canada,Americas,1967,72.13000,20819767,16076.588030,CAN,124
244,Canada,Americas,1972,72.88000,22284500,18970.570860,CAN,124
245,Canada,Americas,1977,74.21000,23796400,22090.883060,CAN,124
246,Canada,Americas,1982,75.76000,25201900,22898.792140,CAN,124
247,Canada,Americas,1987,76.86000,26549700,26626.515030,CAN,124
248,Canada,Americas,1992,77.95000,28523502,26342.884260,CAN,124
249,Canada,Americas,1997,78.61000,30305843,28954.925890,CAN,124
250,Canada,Americas,2002,79.77000,31902268,33328.965070,CAN,124
251,Canada,Americas,2007,80.65300,33390141,36319.235010,CAN,124
288,China,Asia,1952,44.00000,556263527,400.448611,CHN,156
289,China,Asia,1957,50.54896,637408000,575.987001,CHN,156
290,China,Asia,1962,44.50136,665770000,487.674018,CHN,156
291,China,Asia,1967,58.38112,754550000,612.705693,CHN,156
292,China,Asia,1972,63.11888,862030000,676.900092,CHN,156
293,China,Asia,1977,63.96736,943455000,741.237470,CHN,156
294,China,Asia,1982,65.52500,1000281000,962.421381,CHN,156
295,China,Asia,1987,67.27400,1084035000,1378.904018,CHN,156
296,China,Asia,1992,68.69000,1164970000,1655.784158,CHN,156
297,China,Asia,1997,70.42600,1230075000,2289.234136,CHN,156
298,China,Asia,2002,72.02800,1280400000,3119.280896,CHN,156
299,China,Asia,2007,72.96100,1318683096,4959.114854,CHN,156
696,India,Asia,1952,37.37300,372000000,546.565749,IND,356
697,India,Asia,1957,40.24900,409000000,590.061996,IND,356
698,India,Asia,1962,43.60500,454000000,658.347151,IND,356
699,India,Asia,1967,47.19300,506000000,700.770611,IND,356
700,India,Asia,1972,50.65100,567000000,724.032527,IND,356
701,India,Asia,1977,54.20800,634000000,813.337323,IND,356
702,India,Asia,1982,56.59600,708000000,855.723538,IND,356
703,India,Asia,1987,58.55300,788000000,976.512676,IND,356
704,India,Asia,1992,60.22300,872000000,1164.406809,IND,356
705,India,Asia,1997,61.76500,959000000,1458.817442,IND,356
706,India,Asia,2002,62.87900,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.69800,1110396331,2452.210407,IND,356
1068,Nepal,Asia,1952,36.15700,9182536,545.865723,NPL,524
1069,Nepal,Asia,1957,37.68600,9682338,597.936356,NPL,524
1070,Nepal,Asia,1962,39.39300,10332057,652.396859,NPL,524
1071,Nepal,Asia,1967,41.47200,11261690,676.442225,NPL,524
1072,Nepal,Asia,1972,43.97100,12412593,674.788130,NPL,524
1073,Nepal,Asia,1977,46.74800,13933198,694.112440,NPL,524
1074,Nepal,Asia,1982,49.59400,15796314,718.373095,NPL,524
1075,Nepal,Asia,1987,52.53700,17917180,775.632450,NPL,524
1076,Nepal,Asia,1992,55.72700,20326209,897.740360,NPL,524
1077,Nepal,Asia,1997,59.42600,23001113,1010.892138,NPL,524
1078,Nepal,Asia,2002,61.34000,25873917,1057.206311,NPL,524
1079,Nepal,Asia,2007,63.78500,28901790,1091.359778,NPL,524

In [204]:
temps=temps[['country',"year","lifeExp","gdpPercap","pop"]]  # Long format 
temps

     country  year   lifeExp     gdpPercap         pop
240   Canada  1952  68.75000  11367.161120    14785584
241   Canada  1957  69.96000  12489.950060    17010154
242   Canada  1962  71.30000  13462.485550    18985849
243   Canada  1967  72.13000  16076.588030    20819767
244   Canada  1972  72.88000  18970.570860    22284500
245   Canada  1977  74.21000  22090.883060    23796400
246   Canada  1982  75.76000  22898.792140    25201900
247   Canada  1987  76.86000  26626.515030    26549700
248   Canada  1992  77.95000  26342.884260    28523502
249   Canada  1997  78.61000  28954.925890    30305843
250   Canada  2002  79.77000  33328.965070    31902268
251   Canada  2007  80.65300  36319.235010    33390141
288    China  1952  44.00000    400.448611   556263527
289    China  1957  50.54896    575.987001   637408000
290    China  1962  44.50136    487.674018   665770000
291    China  1967  58.38112    612.705693   754550000
292    China  1972  63.11888    676.900092   862030000
293    China  1977  63.96736    741.237470   943455000
294    China  1982  65.52500    962.421381  1000281000
295    China  1987  67.27400   1378.904018  1084035000
296    China  1992  68.69000   1655.784158  1164970000
297    China  1997  70.42600   2289.234136  1230075000
298    China  2002  72.02800   3119.280896  1280400000
299    China  2007  72.96100   4959.114854  1318683096
696    India  1952  37.37300    546.565749   372000000
697    India  1957  40.24900    590.061996   409000000
698    India  1962  43.60500    658.347151   454000000
699    India  1967  47.19300    700.770611   506000000
700    India  1972  50.65100    724.032527   567000000
701    India  1977  54.20800    813.337323   634000000
702    India  1982  56.59600    855.723538   708000000
703    India  1987  58.55300    976.512676   788000000
704    India  1992  60.22300   1164.406809   872000000
705    India  1997  61.76500   1458.817442   959000000
706    India  2002  62.87900   1746.769454  1034172547
707    India  2007  64.69800   2452.210407  1110396331
1068   Nepal  1952  36.15700    545.865723     9182536
1069   Nepal  1957  37.68600    597.936356     9682338
1070   Nepal  1962  39.39300    652.396859    10332057
1071   Nepal  1967  41.47200    676.442225    11261690
1072   Nepal  1972  43.97100    674.788130    12412593
1073   Nepal  1977  46.74800    694.112440    13933198
1074   Nepal  1982  49.59400    718.373095    15796314
1075   Nepal  1987  52.53700    775.632450    17917180
1076   Nepal  1992  55.72700    897.740360    20326209
1077   Nepal  1997  59.42600   1010.892138    23001113
1078   Nepal  2002  61.34000   1057.206311    25873917
1079   Nepal  2007  63.78500   1091.359778    28901790

In [171]:
pd.pivot(temps,index="country",columns="year",values="lifeExp")

year,1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007
country,,,,,,,,,,,,
Canada,68.750,69.96000,71.30000,72.13000,72.88000,74.21000,75.760,76.860,77.950,78.610,79.770,80.653
China,44.000,50.54896,44.50136,58.38112,63.11888,63.96736,65.525,67.274,68.690,70.426,72.028,72.961
India,37.373,40.24900,43.60500,47.19300,50.65100,54.20800,56.596,58.553,60.223,61.765,62.879,64.698
Nepal,36.157,37.68600,39.39300,41.47200,43.97100,46.74800,49.594,52.537,55.727,59.426,61.340,63.785

### multi index columns

### Datasets

In [206]:
temps=temps[['country',"year","lifeExp","pop","gdpPercap"]] # Long format 
temps

     country  year   lifeExp         pop     gdpPercap
240   Canada  1952  68.75000    14785584  11367.161120
241   Canada  1957  69.96000    17010154  12489.950060
242   Canada  1962  71.30000    18985849  13462.485550
243   Canada  1967  72.13000    20819767  16076.588030
244   Canada  1972  72.88000    22284500  18970.570860
245   Canada  1977  74.21000    23796400  22090.883060
246   Canada  1982  75.76000    25201900  22898.792140
247   Canada  1987  76.86000    26549700  26626.515030
248   Canada  1992  77.95000    28523502  26342.884260
249   Canada  1997  78.61000    30305843  28954.925890
250   Canada  2002  79.77000    31902268  33328.965070
251   Canada  2007  80.65300    33390141  36319.235010
288    China  1952  44.00000   556263527    400.448611
289    China  1957  50.54896   637408000    575.987001
290    China  1962  44.50136   665770000    487.674018
291    China  1967  58.38112   754550000    612.705693
292    China  1972  63.11888   862030000    676.900092
293    China  1977  63.96736   943455000    741.237470
294    China  1982  65.52500  1000281000    962.421381
295    China  1987  67.27400  1084035000   1378.904018
296    China  1992  68.69000  1164970000   1655.784158
297    China  1997  70.42600  1230075000   2289.234136
298    China  2002  72.02800  1280400000   3119.280896
299    China  2007  72.96100  1318683096   4959.114854
696    India  1952  37.37300   372000000    546.565749
697    India  1957  40.24900   409000000    590.061996
698    India  1962  43.60500   454000000    658.347151
699    India  1967  47.19300   506000000    700.770611
700    India  1972  50.65100   567000000    724.032527
701    India  1977  54.20800   634000000    813.337323
702    India  1982  56.59600   708000000    855.723538
703    India  1987  58.55300   788000000    976.512676
704    India  1992  60.22300   872000000   1164.406809
705    India  1997  61.76500   959000000   1458.817442
706    India  2002  62.87900  1034172547   1746.769454
707    India  2007  64.69800  1110396331   2452.210407
1068   Nepal  1952  36.15700     9182536    545.865723
1069   Nepal  1957  37.68600     9682338    597.936356
1070   Nepal  1962  39.39300    10332057    652.396859
1071   Nepal  1967  41.47200    11261690    676.442225
1072   Nepal  1972  43.97100    12412593    674.788130
1073   Nepal  1977  46.74800    13933198    694.112440
1074   Nepal  1982  49.59400    15796314    718.373095
1075   Nepal  1987  52.53700    17917180    775.632450
1076   Nepal  1992  55.72700    20326209    897.740360
1077   Nepal  1997  59.42600    23001113   1010.892138
1078   Nepal  2002  61.34000    25873917   1057.206311
1079   Nepal  2007  63.78500    28901790   1091.359778

## Pivot

In [215]:
temp=pd.pivot(temps,index="country",columns="year",values=["lifeExp","pop","gdpPercap"])
temp

        lifeExp                                                            \
year       1952      1957      1962      1967      1972      1977    1982
country
Canada   68.750  69.96000  71.30000  72.13000  72.88000  74.21000  75.760
China    44.000  50.54896  44.50136  58.38112  63.11888  63.96736  65.525
India    37.373  40.24900  43.60500  47.19300  50.65100  54.20800  56.596
Nepal    36.157  37.68600  39.39300  41.47200  43.97100  46.74800  49.594

                                                         pop               \
year       1987    1992    1997    2002    2007         1952         1957
country
Canada   76.860  77.950  78.610  79.770  80.653   14785584.0   17010154.0
China    67.274  68.690  70.426  72.028  72.961  556263527.0  637408000.0
India    58.553  60.223  61.765  62.879  64.698  372000000.0  409000000.0
Nepal    52.537  55.727  59.426  61.340  63.785    9182536.0    9682338.0

                                                                           \
year            1962         1967         1972         1977          1982
country
Canada    18985849.0   20819767.0   22284500.0   23796400.0  2.520190e+07
China    665770000.0  754550000.0  862030000.0  943455000.0  1.000281e+09
India    454000000.0  506000000.0  567000000.0  634000000.0  7.080000e+08
Nepal     10332057.0   11261690.0   12412593.0   13933198.0  1.579631e+07

                                                                               \
year             1987          1992          1997          2002          2007
country
Canada   2.654970e+07  2.852350e+07  3.030584e+07  3.190227e+07  3.339014e+07
China    1.084035e+09  1.164970e+09  1.230075e+09  1.280400e+09  1.318683e+09
India    7.880000e+08  8.720000e+08  9.590000e+08  1.034173e+09  1.110396e+09
Nepal    1.791718e+07  2.032621e+07  2.300111e+07  2.587392e+07  2.890179e+07

            gdpPercap                                                          \
year             1952          1957          1962          1967          1972
country
Canada   11367.161120  12489.950060  13462.485550  16076.588030  18970.570860
China      400.448611    575.987001    487.674018    612.705693    676.900092
India      546.565749    590.061996    658.347151    700.770611    724.032527
Nepal      545.865723    597.936356    652.396859    676.442225    674.788130

                                                                               \
year             1977          1982          1987          1992          1997
country
Canada   22090.883060  22898.792140  26626.515030  26342.884260  28954.925890
China      741.237470    962.421381   1378.904018   1655.784158   2289.234136
India      813.337323    855.723538    976.512676   1164.406809   1458.817442
Nepal      694.112440    718.373095    775.632450    897.740360   1010.892138


year             2002          2007
country
Canada   33328.965070  36319.235010
China     3119.280896   4959.114854
India     1746.769454   2452.210407
Nepal     1057.206311   1091.359778

In [180]:
temp.loc[:,["lifeExp"]]

        lifeExp                                                            \
year       1952      1957      1962      1967      1972      1977    1982
country
Canada   68.750  69.96000  71.30000  72.13000  72.88000  74.21000  75.760
China    44.000  50.54896  44.50136  58.38112  63.11888  63.96736  65.525
India    37.373  40.24900  43.60500  47.19300  50.65100  54.20800  56.596
Nepal    36.157  37.68600  39.39300  41.47200  43.97100  46.74800  49.594


year       1987    1992    1997    2002    2007
country
Canada   76.860  77.950  78.610  79.770  80.653
China    67.274  68.690  70.426  72.028  72.961
India    58.553  60.223  61.765  62.879  64.698
Nepal    52.537  55.727  59.426  61.340  63.785

In [181]:
temp.loc[:,("lifeExp")]

year,1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007
country,,,,,,,,,,,,
Canada,68.750,69.96000,71.30000,72.13000,72.88000,74.21000,75.760,76.860,77.950,78.610,79.770,80.653
China,44.000,50.54896,44.50136,58.38112,63.11888,63.96736,65.525,67.274,68.690,70.426,72.028,72.961
India,37.373,40.24900,43.60500,47.19300,50.65100,54.20800,56.596,58.553,60.223,61.765,62.879,64.698
Nepal,36.157,37.68600,39.39300,41.47200,43.97100,46.74800,49.594,52.537,55.727,59.426,61.340,63.785

In [182]:
temp.loc[:,("pop")]

year,1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007
country,,,,,,,,,,,,
Canada,14785584.0,17010154.0,18985849.0,20819767.0,22284500.0,23796400.0,2.520190e+07,2.654970e+07,2.852350e+07,3.030584e+07,3.190227e+07,3.339014e+07
China,556263527.0,637408000.0,665770000.0,754550000.0,862030000.0,943455000.0,1.000281e+09,1.084035e+09,1.164970e+09,1.230075e+09,1.280400e+09,1.318683e+09
India,372000000.0,409000000.0,454000000.0,506000000.0,567000000.0,634000000.0,7.080000e+08,7.880000e+08,8.720000e+08,9.590000e+08,1.034173e+09,1.110396e+09
Nepal,9182536.0,9682338.0,10332057.0,11261690.0,12412593.0,13933198.0,1.579631e+07,1.791718e+07,2.032621e+07,2.300111e+07,2.587392e+07,2.890179e+07

In [186]:
temp.loc[:,[("lifeExp",2002),("lifeExp",2007),("pop",2002),("pop",2007)]]

        lifeExp                   pop
year       2002    2007          2002          2007
country
Canada   79.770  80.653  3.190227e+07  3.339014e+07
China    72.028  72.961  1.280400e+09  1.318683e+09
India    62.879  64.698  1.034173e+09  1.110396e+09
Nepal    61.340  63.785  2.587392e+07  2.890179e+07

In [175]:
pd.set_option("display.max_columns",None)

## creating a Dynamic

In [188]:
years = [2002, 2007]
metrics = ["lifeExp", "pop"]

col_filter = [(metric, year) for metric in metrics for year in years]
col_filter

[('lifeExp', 2002), ('lifeExp', 2007), ('pop', 2002), ('pop', 2007)]

In [192]:
def select_data(col_data):
    return temp.loc[:,col_data]

In [190]:
years = [2002, 2007,1957,1962]
metrics = ["lifeExp", "pop"]

col_filter = [(metric, year) for metric in metrics for year in years]
col_filter

[('lifeExp', 2002),
 ('lifeExp', 2007),
 ('lifeExp', 1957),
 ('lifeExp', 1962),
 ('pop', 2002),
 ('pop', 2007),
 ('pop', 1957),
 ('pop', 1962)]

In [191]:
select_data(col_filter)

        lifeExp                                       pop                \
year       2002    2007      1957      1962          2002          2007
country
Canada   79.770  80.653  69.96000  71.30000  3.190227e+07  3.339014e+07
China    72.028  72.961  50.54896  44.50136  1.280400e+09  1.318683e+09
India    62.879  64.698  40.24900  43.60500  1.034173e+09  1.110396e+09
Nepal    61.340  63.785  37.68600  39.39300  2.587392e+07  2.890179e+07


year            1957         1962
country
Canada    17010154.0   18985849.0
China    637408000.0  665770000.0
India    409000000.0  454000000.0
Nepal      9682338.0   10332057.0

#### logic

In [197]:
years = [2002, 2007,1957,1962]
metrics = ["lifeExp", "pop"]
cols=[]


for item in metrics:
    for year in years:
        cols.append((item,year))
cols

[('lifeExp', 2002),
 ('lifeExp', 2007),
 ('lifeExp', 1957),
 ('lifeExp', 1962),
 ('pop', 2002),
 ('pop', 2007),
 ('pop', 1957),
 ('pop', 1962)]

In [219]:
def extract_data(years,metric):
    cols=[]
    for item in metric:
        for year in years:
            cols.append((item,year))
    return temp.loc[:,cols]

In [221]:
extract_data([1952,2002,2007],["pop","lifeExp"])

                 pop                             lifeExp
year            1952          2002          2007    1952    2002    2007
country
Canada    14785584.0  3.190227e+07  3.339014e+07  68.750  79.770  80.653
China    556263527.0  1.280400e+09  1.318683e+09  44.000  72.028  72.961
India    372000000.0  1.034173e+09  1.110396e+09  37.373  62.879  64.698
Nepal      9182536.0  2.587392e+07  2.890179e+07  36.157  61.340  63.785

In [ ]:
  year   1952     1957    1962 ..     2007
canada   68.75
nepal
india
china

### final

In [222]:
df=pd.read_csv("gap.csv")
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [223]:
temps=df[df['country'].isin(["Nepal","India","China","Canada"])]
temps

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
240,Canada,Americas,1952,68.75000,14785584,11367.161120,CAN,124
241,Canada,Americas,1957,69.96000,17010154,12489.950060,CAN,124
242,Canada,Americas,1962,71.30000,18985849,13462.485550,CAN,124
243,Canada,Americas,1967,72.13000,20819767,16076.588030,CAN,124
244,Canada,Americas,1972,72.88000,22284500,18970.570860,CAN,124
245,Canada,Americas,1977,74.21000,23796400,22090.883060,CAN,124
246,Canada,Americas,1982,75.76000,25201900,22898.792140,CAN,124
247,Canada,Americas,1987,76.86000,26549700,26626.515030,CAN,124
248,Canada,Americas,1992,77.95000,28523502,26342.884260,CAN,124
249,Canada,Americas,1997,78.61000,30305843,28954.925890,CAN,124
250,Canada,Americas,2002,79.77000,31902268,33328.965070,CAN,124
251,Canada,Americas,2007,80.65300,33390141,36319.235010,CAN,124
288,China,Asia,1952,44.00000,556263527,400.448611,CHN,156
289,China,Asia,1957,50.54896,637408000,575.987001,CHN,156
290,China,Asia,1962,44.50136,665770000,487.674018,CHN,156
291,China,Asia,1967,58.38112,754550000,612.705693,CHN,156
292,China,Asia,1972,63.11888,862030000,676.900092,CHN,156
293,China,Asia,1977,63.96736,943455000,741.237470,CHN,156
294,China,Asia,1982,65.52500,1000281000,962.421381,CHN,156
295,China,Asia,1987,67.27400,1084035000,1378.904018,CHN,156
296,China,Asia,1992,68.69000,1164970000,1655.784158,CHN,156
297,China,Asia,1997,70.42600,1230075000,2289.234136,CHN,156
298,China,Asia,2002,72.02800,1280400000,3119.280896,CHN,156
299,China,Asia,2007,72.96100,1318683096,4959.114854,CHN,156
696,India,Asia,1952,37.37300,372000000,546.565749,IND,356
697,India,Asia,1957,40.24900,409000000,590.061996,IND,356
698,India,Asia,1962,43.60500,454000000,658.347151,IND,356
699,India,Asia,1967,47.19300,506000000,700.770611,IND,356
700,India,Asia,1972,50.65100,567000000,724.032527,IND,356
701,India,Asia,1977,54.20800,634000000,813.337323,IND,356
702,India,Asia,1982,56.59600,708000000,855.723538,IND,356
703,India,Asia,1987,58.55300,788000000,976.512676,IND,356
704,India,Asia,1992,60.22300,872000000,1164.406809,IND,356
705,India,Asia,1997,61.76500,959000000,1458.817442,IND,356
706,India,Asia,2002,62.87900,1034172547,1746.769454,IND,356
707,India,Asia,2007,64.69800,1110396331,2452.210407,IND,356
1068,Nepal,Asia,1952,36.15700,9182536,545.865723,NPL,524
1069,Nepal,Asia,1957,37.68600,9682338,597.936356,NPL,524
1070,Nepal,Asia,1962,39.39300,10332057,652.396859,NPL,524
1071,Nepal,Asia,1967,41.47200,11261690,676.442225,NPL,524
1072,Nepal,Asia,1972,43.97100,12412593,674.788130,NPL,524
1073,Nepal,Asia,1977,46.74800,13933198,694.112440,NPL,524
1074,Nepal,Asia,1982,49.59400,15796314,718.373095,NPL,524
1075,Nepal,Asia,1987,52.53700,17917180,775.632450,NPL,524
1076,Nepal,Asia,1992,55.72700,20326209,897.740360,NPL,524
1077,Nepal,Asia,1997,59.42600,23001113,1010.892138,NPL,524
1078,Nepal,Asia,2002,61.34000,25873917,1057.206311,NPL,524
1079,Nepal,Asia,2007,63.78500,28901790,1091.359778,NPL,524

In [224]:
temps=temps[['country',"year","lifeExp","pop","gdpPercap"]] # Long format 
temps

     country  year   lifeExp         pop     gdpPercap
240   Canada  1952  68.75000    14785584  11367.161120
241   Canada  1957  69.96000    17010154  12489.950060
242   Canada  1962  71.30000    18985849  13462.485550
243   Canada  1967  72.13000    20819767  16076.588030
244   Canada  1972  72.88000    22284500  18970.570860
245   Canada  1977  74.21000    23796400  22090.883060
246   Canada  1982  75.76000    25201900  22898.792140
247   Canada  1987  76.86000    26549700  26626.515030
248   Canada  1992  77.95000    28523502  26342.884260
249   Canada  1997  78.61000    30305843  28954.925890
250   Canada  2002  79.77000    31902268  33328.965070
251   Canada  2007  80.65300    33390141  36319.235010
288    China  1952  44.00000   556263527    400.448611
289    China  1957  50.54896   637408000    575.987001
290    China  1962  44.50136   665770000    487.674018
291    China  1967  58.38112   754550000    612.705693
292    China  1972  63.11888   862030000    676.900092
293    China  1977  63.96736   943455000    741.237470
294    China  1982  65.52500  1000281000    962.421381
295    China  1987  67.27400  1084035000   1378.904018
296    China  1992  68.69000  1164970000   1655.784158
297    China  1997  70.42600  1230075000   2289.234136
298    China  2002  72.02800  1280400000   3119.280896
299    China  2007  72.96100  1318683096   4959.114854
696    India  1952  37.37300   372000000    546.565749
697    India  1957  40.24900   409000000    590.061996
698    India  1962  43.60500   454000000    658.347151
699    India  1967  47.19300   506000000    700.770611
700    India  1972  50.65100   567000000    724.032527
701    India  1977  54.20800   634000000    813.337323
702    India  1982  56.59600   708000000    855.723538
703    India  1987  58.55300   788000000    976.512676
704    India  1992  60.22300   872000000   1164.406809
705    India  1997  61.76500   959000000   1458.817442
706    India  2002  62.87900  1034172547   1746.769454
707    India  2007  64.69800  1110396331   2452.210407
1068   Nepal  1952  36.15700     9182536    545.865723
1069   Nepal  1957  37.68600     9682338    597.936356
1070   Nepal  1962  39.39300    10332057    652.396859
1071   Nepal  1967  41.47200    11261690    676.442225
1072   Nepal  1972  43.97100    12412593    674.788130
1073   Nepal  1977  46.74800    13933198    694.112440
1074   Nepal  1982  49.59400    15796314    718.373095
1075   Nepal  1987  52.53700    17917180    775.632450
1076   Nepal  1992  55.72700    20326209    897.740360
1077   Nepal  1997  59.42600    23001113   1010.892138
1078   Nepal  2002  61.34000    25873917   1057.206311
1079   Nepal  2007  63.78500    28901790   1091.359778

In [225]:
temp=pd.pivot(temps,index="country",columns="year",values=["lifeExp","pop","gdpPercap"])
temp

        lifeExp                                                            \
year       1952      1957      1962      1967      1972      1977    1982
country
Canada   68.750  69.96000  71.30000  72.13000  72.88000  74.21000  75.760
China    44.000  50.54896  44.50136  58.38112  63.11888  63.96736  65.525
India    37.373  40.24900  43.60500  47.19300  50.65100  54.20800  56.596
Nepal    36.157  37.68600  39.39300  41.47200  43.97100  46.74800  49.594

                                                         pop               \
year       1987    1992    1997    2002    2007         1952         1957
country
Canada   76.860  77.950  78.610  79.770  80.653   14785584.0   17010154.0
China    67.274  68.690  70.426  72.028  72.961  556263527.0  637408000.0
India    58.553  60.223  61.765  62.879  64.698  372000000.0  409000000.0
Nepal    52.537  55.727  59.426  61.340  63.785    9182536.0    9682338.0

                                                                           \
year            1962         1967         1972         1977          1982
country
Canada    18985849.0   20819767.0   22284500.0   23796400.0  2.520190e+07
China    665770000.0  754550000.0  862030000.0  943455000.0  1.000281e+09
India    454000000.0  506000000.0  567000000.0  634000000.0  7.080000e+08
Nepal     10332057.0   11261690.0   12412593.0   13933198.0  1.579631e+07

                                                                               \
year             1987          1992          1997          2002          2007
country
Canada   2.654970e+07  2.852350e+07  3.030584e+07  3.190227e+07  3.339014e+07
China    1.084035e+09  1.164970e+09  1.230075e+09  1.280400e+09  1.318683e+09
India    7.880000e+08  8.720000e+08  9.590000e+08  1.034173e+09  1.110396e+09
Nepal    1.791718e+07  2.032621e+07  2.300111e+07  2.587392e+07  2.890179e+07

            gdpPercap                                                          \
year             1952          1957          1962          1967          1972
country
Canada   11367.161120  12489.950060  13462.485550  16076.588030  18970.570860
China      400.448611    575.987001    487.674018    612.705693    676.900092
India      546.565749    590.061996    658.347151    700.770611    724.032527
Nepal      545.865723    597.936356    652.396859    676.442225    674.788130

                                                                               \
year             1977          1982          1987          1992          1997
country
Canada   22090.883060  22898.792140  26626.515030  26342.884260  28954.925890
China      741.237470    962.421381   1378.904018   1655.784158   2289.234136
India      813.337323    855.723538    976.512676   1164.406809   1458.817442
Nepal      694.112440    718.373095    775.632450    897.740360   1010.892138


year             2002          2007
country
Canada   33328.965070  36319.235010
China     3119.280896   4959.114854
India     1746.769454   2452.210407
Nepal     1057.206311   1091.359778

# Internal Logic

In [226]:
years = [2002, 2007,1957,1962]
metrics = ["lifeExp", "pop"]
cols=[]


for item in metrics:
    for year in years:
        cols.append((item,year))
cols

[('lifeExp', 2002),
 ('lifeExp', 2007),
 ('lifeExp', 1957),
 ('lifeExp', 1962),
 ('pop', 2002),
 ('pop', 2007),
 ('pop', 1957),
 ('pop', 1962)]

In [228]:
def extract_data(years,metric):
    cols=[]
    for item in metric:
        for year in years:
            cols.append((item,year))
    print(cols)
    return temp.loc[:,cols]

In [235]:
extract_data([1952,2007,2002],["pop","gdpPercap"])

[('pop', 1952), ('pop', 2007), ('pop', 2002), ('gdpPercap', 1952), ('gdpPercap', 2007), ('gdpPercap', 2002)]

                 pop                                 gdpPercap                \
year            1952          2007          2002          1952          2007
country
Canada    14785584.0  3.339014e+07  3.190227e+07  11367.161120  36319.235010
China    556263527.0  1.318683e+09  1.280400e+09    400.448611   4959.114854
India    372000000.0  1.110396e+09  1.034173e+09    546.565749   2452.210407
Nepal      9182536.0  2.890179e+07  2.587392e+07    545.865723   1091.359778


year             2002
country
Canada   33328.965070
China     3119.280896
India     1746.769454
Nepal     1057.206311

In [234]:
temps.columns

Index(['country', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [236]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\New folder (4)'