In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

np.random.seed(42)

In [2]:
n = 50000

df = pd.DataFrame({

    "order_id": np.arange(1, n+1),

    "customer_id": np.random.randint(1000, 10000, n),

    "customer_name": np.random.choice(
        ["Ram", "Hari", "Sita", "John", "Emily", "David"],
        n
    ),

    "gender": np.random.choice(
        ["Male", "Female"],
        n
    ),

    "city": np.random.choice(
        ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"],
        n
    ),

    "department": np.random.choice(
        ["Electronics", "Fashion", "Food", "Furniture"],
        n
    ),

    "sales_channel": np.random.choice(
        ["Online", "Retail", "Distributor"],
        n
    ),

    "payment_method": np.random.choice(
        ["Cash", "Card", "eSewa", "Khalti"],
        n
    ),

    "quantity": np.random.randint(1, 10, n),

    "unit_price": np.random.randint(100, 5000, n),

    "discount": np.random.uniform(0, 0.40, n),

    "rating": np.random.uniform(1, 5, n),

    "delivery_days": np.random.randint(1, 15, n),

    "website_visits": np.random.randint(1, 500, n),

    "ad_spend": np.random.randint(1000, 50000, n),

    "join_date": pd.to_datetime("2020-01-01") +
                 pd.to_timedelta(
                     np.random.randint(0, 1500, n),
                     unit="D"
                 ),

    "order_date": pd.to_datetime("2023-01-01") +
                  pd.to_timedelta(
                      np.random.randint(0, 730, n),
                      unit="D"
                  )
})

df["sales"] = (
    df["quantity"] *
    df["unit_price"] *
    (1 - df["discount"])
)

df["profit"] = (
    df["sales"] *
    np.random.uniform(0.05, 0.30, n)
)

df.head()

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850

In [3]:
df.shape

(50000, 19)

# STEP 3 — BASIC EXPLORATION

df.head()
df.tail()
df.sample(5)
df.shape
df.columns
df.dtypes
df.info()
df.describe()

In [4]:
df.dtypes

order_id                   int64
customer_id                int32
customer_name             object
gender                    object
city                      object
department                object
sales_channel             object
payment_method            object
quantity                   int32
unit_price                 int32
discount                 float64
rating                   float64
delivery_days              int32
website_visits             int32
ad_spend                   int32
join_date         datetime64[ns]
order_date        datetime64[ns]
sales                    float64
profit                   float64
dtype: object

# STEP 4 — MEMORY OPTIMIZATIO

In [5]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50000 non-null  int64
 1   customer_id     50000 non-null  int32
 2   customer_name   50000 non-null  object
 3   gender          50000 non-null  object
 4   city            50000 non-null  object
 5   department      50000 non-null  object
 6   sales_channel   50000 non-null  object
 7   payment_method  50000 non-null  object
 8   quantity        50000 non-null  int32
 9   unit_price      50000 non-null  int32
 10  discount        50000 non-null  float64
 11  rating          50000 non-null  float64
 12  delivery_days   50000 non-null  int32
 13  website_visits  50000 non-null  int32
 14  ad_spend        50000 non-null  int32
 15  join_date       50000 non-null  datetime64[ns]
 16  order_date      50000 non-null  datetime64[ns]
 17  sales           50000 non-null  float64
 18  profit          50000 non-null  float64
dtypes: datetime64[ns](2), float64(4), int32(6), int64(1), object(6)
memory usage: 19.6 MB

# Convert to category

In [6]:
cat_cols = [
    "gender",
    "city",
    "department",
    "sales_channel",
    "payment_method"
]

for col in cat_cols:
    df[col] = df[col].astype("category")

# Downcasting

In [7]:
df["quantity"] = pd.to_numeric(
    df["quantity"],
    downcast="integer"
)

df["unit_price"] = pd.to_numeric(
    df["unit_price"],
    downcast="integer"
)

In [8]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50000 non-null  int64
 1   customer_id     50000 non-null  int32
 2   customer_name   50000 non-null  object
 3   gender          50000 non-null  category
 4   city            50000 non-null  category
 5   department      50000 non-null  category
 6   sales_channel   50000 non-null  category
 7   payment_method  50000 non-null  category
 8   quantity        50000 non-null  int8
 9   unit_price      50000 non-null  int16
 10  discount        50000 non-null  float64
 11  rating          50000 non-null  float64
 12  delivery_days   50000 non-null  int32
 13  website_visits  50000 non-null  int32
 14  ad_spend        50000 non-null  int32
 15  join_date       50000 non-null  datetime64[ns]
 16  order_date      50000 non-null  datetime64[ns]
 17  sales           50000 non-null  float64
 18  profit          50000 non-null  float64
dtypes: category(5), datetime64[ns](2), float64(4), int16(1), int32(4), int64(1), int8(1), object(1)
memory usage: 6.4 MB

# STEP 5 — CREATE MISSING VALUES

In [9]:
df.loc[
    df.sample(frac=0.02).index,
    "rating"
] = np.nan

In [10]:
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242

# CHECK MISSING VALUES

In [11]:
df.isnull().sum()

order_id             0
customer_id          0
customer_name        0
gender               0
city                 0
department           0
sales_channel        0
payment_method       0
quantity             0
unit_price           0
discount             0
rating            1000
delivery_days        0
website_visits       0
ad_spend             0
join_date            0
order_date           0
sales                0
profit               0
dtype: int64

## HANDLE MISSING VALUES
## Fill using department average

In [14]:
df["rating"] = (
    df.groupby("department")["rating"]
    .transform(
        lambda x: x.fillna(x.mean())
    )
)

In [13]:
import warnings
warnings.filterwarnings("ignore")

# STEP 6 — DUPLICATES

In [15]:
df.duplicated().sum()

np.int64(0)

### Remove duplicates

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated()  # Subset parameters , keepo parameters

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool

In [18]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, city, department, sales_channel, payment_method, quantity, unit_price, discount, rating, delivery_days, website_visits, ad_spend, join_date, order_date, sales, profit]
Index: []

### STEP 7 — loc[]
### High sales customers

In [24]:
df.loc[
    df["sales"] > 43000
]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit
1605,1606,6342,John,Female,Lalitpur,Food,Online,Card,9,4883,0.006094,1.276490,8,175,15726,2020-03-01,2024-12-28,43679.176446,10725.326645
1878,1879,8340,Emily,Male,Kathmandu,Food,Online,Cash,9,4950,0.000639,4.633253,4,376,38619,2020-12-30,2024-04-09,44521.553784,12917.881168
17935,17936,4345,Emily,Female,Pokhara,Electronics,Retail,Card,9,4986,0.028461,4.339383,1,320,43756,2021-01-31,2024-03-25,43596.854815,12290.031598
19564,19565,3919,Sita,Female,Kathmandu,Electronics,Retail,Cash,9,4912,0.010764,1.658942,6,55,37924,2022-09-17,2023-12-14,43732.127241,7247.961767
24286,24287,9294,Ram,Male,Lalitpur,Furniture,Retail,Khalti,9,4944,0.018972,1.176913,4,335,6221,2023-03-19,2024-08-18,43651.840188,12026.875764
26287,26288,7005,Emily,Male,Lalitpur,Food,Retail,eSewa,9,4838,0.000764,2.332359,10,386,48633,2020-09-07,2023-12-11,43508.730510,4740.018888
28922,28923,8318,John,Male,Kathmandu,Fashion,Retail,Khalti,9,4886,0.011349,4.007296,5,258,1055,2020-10-02,2024-02-14,43474.933657,10272.426316
29907,29908,7167,David,Female,Kathmandu,Electronics,Distributor,Khalti,9,4865,0.001364,2.703915,2,129,35164,2020-10-27,2024-06-15,43725.255548,12781.680753
33051,33052,8676,Sita,Female,Lalitpur,Electronics,Distributor,Khalti,9,4997,0.002439,4.949496,10,197,18155,2021-10-18,2023-01-18,44863.316319,9383.347713
33651,33652,4944,Sita,Male,Pokhara,Furniture,Online,Card,9,4961,0.015243,4.211626,7,234,45737,2023-01-24,2023-09-30,43968.418041,12715.528577
37457,37458,9625,Sita,Male,Kathmandu,Fashion,Online,Cash,9,4902,0.024045,1.311656,10,264,24367,2023-10-03,2023-05-11,43057.167493,4381.858948
38132,38133,4869,David,Male,Biratnagar,Furniture,Distributor,Khalti,9,4958,0.008128,3.845116,10,269,47367,2022-11-22,2023-08-23,44259.309127,2373.210384
41369,41370,2445,John,Female,Kathmandu,Fashion,Online,Card,9,4898,0.004430,4.746230,12,155,5491,2023-08-12,2023-08-08,43886.715644,6795.677952
41405,41406,7502,Emily,Male,Pokhara,Furniture,Distributor,Cash,9,4870,0.017477,3.094241,6,209,30874,2020-11-26,2023-09-17,43063.985126,9609.242121

In [26]:
df[df["sales"] > 43000]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit
1605,1606,6342,John,Female,Lalitpur,Food,Online,Card,9,4883,0.006094,1.276490,8,175,15726,2020-03-01,2024-12-28,43679.176446,10725.326645
1878,1879,8340,Emily,Male,Kathmandu,Food,Online,Cash,9,4950,0.000639,4.633253,4,376,38619,2020-12-30,2024-04-09,44521.553784,12917.881168
17935,17936,4345,Emily,Female,Pokhara,Electronics,Retail,Card,9,4986,0.028461,4.339383,1,320,43756,2021-01-31,2024-03-25,43596.854815,12290.031598
19564,19565,3919,Sita,Female,Kathmandu,Electronics,Retail,Cash,9,4912,0.010764,1.658942,6,55,37924,2022-09-17,2023-12-14,43732.127241,7247.961767
24286,24287,9294,Ram,Male,Lalitpur,Furniture,Retail,Khalti,9,4944,0.018972,1.176913,4,335,6221,2023-03-19,2024-08-18,43651.840188,12026.875764
26287,26288,7005,Emily,Male,Lalitpur,Food,Retail,eSewa,9,4838,0.000764,2.332359,10,386,48633,2020-09-07,2023-12-11,43508.730510,4740.018888
28922,28923,8318,John,Male,Kathmandu,Fashion,Retail,Khalti,9,4886,0.011349,4.007296,5,258,1055,2020-10-02,2024-02-14,43474.933657,10272.426316
29907,29908,7167,David,Female,Kathmandu,Electronics,Distributor,Khalti,9,4865,0.001364,2.703915,2,129,35164,2020-10-27,2024-06-15,43725.255548,12781.680753
33051,33052,8676,Sita,Female,Lalitpur,Electronics,Distributor,Khalti,9,4997,0.002439,4.949496,10,197,18155,2021-10-18,2023-01-18,44863.316319,9383.347713
33651,33652,4944,Sita,Male,Pokhara,Furniture,Online,Card,9,4961,0.015243,4.211626,7,234,45737,2023-01-24,2023-09-30,43968.418041,12715.528577
37457,37458,9625,Sita,Male,Kathmandu,Fashion,Online,Cash,9,4902,0.024045,1.311656,10,264,24367,2023-10-03,2023-05-11,43057.167493,4381.858948
38132,38133,4869,David,Male,Biratnagar,Furniture,Distributor,Khalti,9,4958,0.008128,3.845116,10,269,47367,2022-11-22,2023-08-23,44259.309127,2373.210384
41369,41370,2445,John,Female,Kathmandu,Fashion,Online,Card,9,4898,0.004430,4.746230,12,155,5491,2023-08-12,2023-08-08,43886.715644,6795.677952
41405,41406,7502,Emily,Male,Pokhara,Furniture,Distributor,Cash,9,4870,0.017477,3.094241,6,209,30874,2020-11-26,2023-09-17,43063.985126,9609.242121

### Multiple conditions

In [27]:
df.loc[
    (df["sales"] > 15000) &
    (df["city"] == "Kathmandu")
]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit
15,16,6051,Hari,Male,Kathmandu,Furniture,Distributor,Card,6,4490,0.195535,1.112833,12,364,10561,2021-01-02,2024-10-31,21672.296414,3506.782928
53,54,2021,Emily,Female,Kathmandu,Fashion,Retail,Khalti,8,4740,0.159684,2.968061,9,164,12518,2022-11-22,2023-02-24,31864.792033,6164.745272
64,65,7439,Ram,Male,Kathmandu,Electronics,Distributor,eSewa,9,4506,0.341628,1.663476,6,481,18370,2022-10-02,2023-01-20,26699.624187,4089.534617
94,95,4104,David,Female,Kathmandu,Food,Online,Card,9,4647,0.360567,2.298020,2,495,31450,2022-06-30,2023-04-21,26743.015132,5309.656658
98,99,3731,Emily,Male,Kathmandu,Furniture,Distributor,eSewa,6,4497,0.263118,3.034755,2,117,19924,2020-08-23,2024-02-01,19882.555434,3990.271051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49942,49943,2878,Ram,Male,Kathmandu,Food,Online,eSewa,7,2899,0.077198,4.338134,3,484,31856,2020-03-12,2024-08-13,18726.419723,2799.740891
49944,49945,5755,Hari,Female,Kathmandu,Fashion,Retail,Card,6,4771,0.081534,2.982397,7,399,37015,2023-07-28,2023-04-02,26291.994481,2955.455738
49975,49976,8793,Ram,Female,Kathmandu,Electronics,Online,Card,7,3587,0.262947,4.147571,13,495,11113,2022-08-16,2023-07-27,18506.670204,5528.062121
49993,49994,5929,Ram,Male,Kathmandu,Furniture,Online,eSewa,8,3423,0.248231,1.446514,12,146,40140,2022-01-24,2023-01-22,20586.428906,4956.872643
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902

### Select columns

In [28]:
df.loc[
    df["sales"] > 10000,
    ["customer_name", "city", "sales"]
]

      customer_name        city         sales
1             Emily     Pokhara  21971.302557
2               Ram  Biratnagar  16723.058813
3             David  Biratnagar  15069.108079
4              Sita     Pokhara  10961.898690
12             Hari     Pokhara  10867.976831
...             ...         ...           ...
49989          John  Biratnagar  20754.204477
49991         Emily     Pokhara  14960.187964
49993           Ram   Kathmandu  20586.428906
49996          Sita   Kathmandu  25940.993460
49998           Ram    Lalitpur  26844.609895

[20260 rows x 3 columns]

### Update values

In [29]:
df.loc[
    df["department"] == "Electronics",
    "updated_profit"
] = 10000

df.loc[
    df["department"] == "Electronics",
    "profit"
] *= 1.10

In [31]:
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN

### STEP 8 — iloc[]
### First 10 rows

In [32]:
df.iloc[:10]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN
5,6,7265,Sita,Female,Pokhara,Furniture,Online,Cash,4,382,0.032178,4.730542,6,297,20301,2021-01-09,2023-02-12,1478.831650,234.924836,NaN
6,7,1466,Ram,Female,Biratnagar,Furniture,Retail,Khalti,3,2740,0.031833,3.560220,13,144,30636,2023-10-06,2024-11-06,7958.330157,655.121890,NaN
7,8,5426,Sita,Male,Biratnagar,Furniture,Online,Khalti,1,3723,0.074466,1.396870,13,274,3850,2022-06-07,2023-12-02,3445.764171,825.003557,NaN
8,9,6578,John,Male,Biratnagar,Electronics,Distributor,Cash,6,1790,0.145977,4.945986,7,226,1925,2020-02-06,2024-10-08,9172.202711,2567.575074,10000.0
9,10,9322,John,Female,Biratnagar,Electronics,Distributor,Khalti,1,2606,0.197732,2.475587,7,453,40794,2021-09-25,2023-08-24,2090.710609,422.946883,10000.0

### Specific rows + cols

In [33]:
df.iloc[
    [1,5,10],
    [0,2,5]
]

    order_id customer_name department
1          2         Emily  Furniture
5          6          Sita  Furniture
10        11         David    Fashion

## Last row

In [34]:
df.iloc[-1]

order_id                        50000
customer_id                      8309
customer_name                    John
gender                         Female
city                         Lalitpur
department                    Fashion
sales_channel             Distributor
payment_method                   Cash
quantity                            9
unit_price                       1087
discount                     0.228972
rating                       3.115385
delivery_days                      14
website_visits                    228
ad_spend                        18338
join_date         2023-02-26 00:00:00
order_date        2024-01-19 00:00:00
sales                     7542.965433
profit                     714.591242
updated_profit                    NaN
Name: 49999, dtype: object

### STEP 9 — at[] and iat[]

In [35]:
df.at[0, "sales"]

np.float64(9312.938773294007)

In [37]:
df.iat[0, 5]

'Electronics'

In [38]:
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN

### STEP 10 — FILTERING
### BETWEEN

In [39]:
df[
    df["sales"].between(40000, 50000)
]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
95,96,8215,John,Male,Lalitpur,Fashion,Retail,eSewa,9,4574,0.014978,4.084867,12,448,16960,2022-03-31,2024-07-14,40549.432126,11476.040454,NaN
661,662,8648,Ram,Male,Lalitpur,Food,Distributor,Cash,9,4963,0.072332,3.722995,9,26,5775,2021-03-05,2023-08-03,41436.165593,2298.589168,NaN
1523,1524,1955,Sita,Female,Pokhara,Electronics,Retail,Card,9,4877,0.069991,2.271683,14,143,34782,2023-07-12,2023-11-29,40820.900867,5444.473535,10000.0
1605,1606,6342,John,Female,Lalitpur,Food,Online,Card,9,4883,0.006094,1.276490,8,175,15726,2020-03-01,2024-12-28,43679.176446,10725.326645,NaN
1800,1801,3493,Ram,Male,Biratnagar,Furniture,Retail,eSewa,9,4966,0.039693,3.006058,8,349,13975,2020-07-05,2024-10-30,42919.941860,2224.336180,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43272,43273,9822,John,Female,Pokhara,Furniture,Retail,Cash,9,4661,0.044860,4.519796,11,118,27654,2022-01-25,2024-05-30,40067.153244,7597.030575,NaN
44854,44855,9612,Ram,Male,Pokhara,Fashion,Retail,Khalti,9,4628,0.011120,4.748959,6,422,1124,2021-08-03,2024-01-13,41188.832897,12251.940780,NaN
45555,45556,9916,David,Male,Lalitpur,Food,Online,eSewa,9,4889,0.062547,3.043478,2,350,7312,2021-04-20,2023-07-06,41248.867365,10510.380044,NaN
45840,45841,4187,John,Male,Lalitpur,Food,Distributor,Khalti,9,4539,0.011309,1.119531,13,204,22492,2021-04-21,2024-01-15,40389.027970,10876.564668,NaN
47780,47781,9919,Emily,Male,Biratnagar,Food,Online,Card,9,4742,0.039212,1.579676,3,293,45087,2022-12-05,2023-06-10,41004.520190,4827.107269,NaN

## ISIN

In [40]:
df[
    df["city"].isin(
        ["Kathmandu", "Pokhara"]
    )
]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN
5,6,7265,Sita,Female,Pokhara,Furniture,Online,Cash,4,382,0.032178,4.730542,6,297,20301,2021-01-09,2023-02-12,1478.831650,234.924836,NaN
10,11,2685,David,Female,Pokhara,Fashion,Retail,Card,2,2057,0.343812,3.626962,6,154,46206,2022-10-10,2023-05-28,2699.555383,337.489310,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49991,49992,5222,Emily,Male,Pokhara,Electronics,Online,Cash,8,2177,0.141009,4.629262,11,482,19926,2020-05-15,2024-01-28,14960.187964,1336.504633,10000.0
49993,49994,5929,Ram,Male,Kathmandu,Furniture,Online,eSewa,8,3423,0.248231,1.446514,12,146,40140,2022-01-24,2023-01-22,20586.428906,4956.872643,NaN
49994,49995,8661,Emily,Male,Kathmandu,Food,Distributor,Card,7,601,0.009228,3.097691,8,367,17946,2021-04-23,2024-11-29,4168.177395,1061.945254,NaN
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0

## QUERY

In [41]:
df.query(
    "sales > 10000 and city == 'Kathmandu'"
)

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
15,16,6051,Hari,Male,Kathmandu,Furniture,Distributor,Card,6,4490,0.195535,1.112833,12,364,10561,2021-01-02,2024-10-31,21672.296414,3506.782928,NaN
38,39,9792,Emily,Male,Kathmandu,Fashion,Distributor,eSewa,6,2283,0.041576,3.235913,10,173,37060,2020-09-07,2024-12-20,13128.494742,3338.624195,NaN
53,54,2021,Emily,Female,Kathmandu,Fashion,Retail,Khalti,8,4740,0.159684,2.968061,9,164,12518,2022-11-22,2023-02-24,31864.792033,6164.745272,NaN
59,60,5297,John,Female,Kathmandu,Electronics,Retail,Khalti,5,4047,0.297904,1.832936,3,357,14771,2023-08-09,2023-10-21,14206.921087,4136.663083,10000.0
64,65,7439,Ram,Male,Kathmandu,Electronics,Distributor,eSewa,9,4506,0.341628,1.663476,6,481,18370,2022-10-02,2023-01-20,26699.624187,4089.534617,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49942,49943,2878,Ram,Male,Kathmandu,Food,Online,eSewa,7,2899,0.077198,4.338134,3,484,31856,2020-03-12,2024-08-13,18726.419723,2799.740891,NaN
49944,49945,5755,Hari,Female,Kathmandu,Fashion,Retail,Card,6,4771,0.081534,2.982397,7,399,37015,2023-07-28,2023-04-02,26291.994481,2955.455738,NaN
49975,49976,8793,Ram,Female,Kathmandu,Electronics,Online,Card,7,3587,0.262947,4.147571,13,495,11113,2022-08-16,2023-07-27,18506.670204,5528.062121,10000.0
49993,49994,5929,Ram,Male,Kathmandu,Furniture,Online,eSewa,8,3423,0.248231,1.446514,12,146,40140,2022-01-24,2023-01-22,20586.428906,4956.872643,NaN
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN

### STRING FILTER

In [45]:
df[
    df["customer_name"]
    .str.contains("ra", case=False)
]

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN
6,7,1466,Ram,Female,Biratnagar,Furniture,Retail,Khalti,3,2740,0.031833,3.560220,13,144,30636,2023-10-06,2024-11-06,7958.330157,655.121890,NaN
11,12,1769,Ram,Male,Biratnagar,Furniture,Online,Cash,2,3357,0.035721,4.597909,14,481,39071,2020-08-19,2023-05-31,6474.170780,817.189850,NaN
22,23,3558,Ram,Male,Biratnagar,Electronics,Retail,eSewa,6,2739,0.374027,3.160920,13,62,22494,2020-05-25,2023-05-11,10287.248113,834.875158,10000.0
27,28,3734,Ram,Male,Kathmandu,Food,Online,Cash,1,4239,0.299864,4.850696,14,103,44889,2023-09-29,2023-06-30,2967.877126,382.932138,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49986,49987,1676,Ram,Male,Lalitpur,Fashion,Online,Cash,4,639,0.139181,1.114574,6,21,25504,2022-11-19,2023-02-17,2200.253663,136.211745,NaN
49987,49988,2124,Ram,Female,Pokhara,Furniture,Online,eSewa,2,1415,0.177761,1.857000,11,206,49776,2020-12-13,2023-11-27,2326.936802,136.306532,NaN
49993,49994,5929,Ram,Male,Kathmandu,Furniture,Online,eSewa,8,3423,0.248231,1.446514,12,146,40140,2022-01-24,2023-01-22,20586.428906,4956.872643,NaN
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN

## STEP 11 — FEATURE ENGINEERING
## Profit Margin

In [46]:
df["profit_margin"] = (
    df["profit"] / df["sales"]
) * 100

## Customer Segment

In [47]:
df["customer_segment"] = np.where(
    df["sales"] > 20000,
    "Premium",
    "Regular"
)

### Multiple conditions

In [48]:
df["risk"] = np.select(

    [
        df["profit_margin"] < 10,
        df["profit_margin"] < 20
    ],

    [
        "High Risk",
        "Medium Risk"
    ],

    default="Low Risk"
)

## STEP 12 — GROUPBY
## Total sales by city

In [49]:
df.groupby("city")["sales"].sum()

city
Biratnagar    1.276469e+08
Kathmandu     1.262160e+08
Lalitpur      1.274642e+08
Pokhara       1.273557e+08
Name: sales, dtype: float64

In [50]:
df.groupby("department").agg({

    "sales": ["sum", "mean", "max"],

    "profit": ["sum", "mean"],

    "quantity": ["sum"]
})

                    sales                                    profit  \
                      sum          mean           max           sum
department
Electronics  1.273313e+08  10225.770171  44863.316319  2.232712e+07
Fashion      1.277184e+08  10066.076270  43886.715644  2.236243e+07
Food         1.263628e+08  10192.194379  44521.553784  2.223401e+07
Furniture    1.272702e+08  10212.664900  44259.309127  2.224756e+07

                         quantity
                    mean      sum
department
Electronics  1793.055014    62339
Fashion      1762.486335    63317
Food         1793.354384    62139
Furniture    1785.232271    62313

## Named aggregation

In [51]:
df.groupby("city").agg(

    total_sales=("sales", "sum"),

    avg_sales=("sales", "mean"),

    total_orders=("order_id", "count")
)

             total_sales     avg_sales  total_orders
city
Biratnagar  1.276469e+08  10059.649444         12689
Kathmandu   1.262160e+08  10139.459730         12448
Lalitpur    1.274642e+08  10301.800025         12373
Pokhara     1.273557e+08  10196.610374         12490

## Lambda aggregation

In [52]:
df.groupby("city").agg({

    "sales": lambda x: x.max() - x.min()
})

                   sales
city
Biratnagar  44188.676781
Kathmandu   44440.242527
Lalitpur    44787.727825
Pokhara     43889.649679

## STEP 13 — TRANSFORM()
## City total sales

In [53]:
df["city_sales"] = (
    df.groupby("city")["sales"]
    .transform("sum")
)

## Percentage contribution

In [54]:
df["sales_pct"] = (
    df["sales"] /
    df["city_sales"]
) * 100

## STEP 14 — RANKING

In [55]:
df["rank_in_city"] = (

    df.groupby("city")["sales"]
    .rank(ascending=False)
)

## STEP 15 — WINDOW FUNCTIONS
## Rolling average

In [56]:
df["rolling_sales"] = (
    df["sales"]
    .rolling(7)
    .mean()
)

### Expanding sum

In [58]:
df[["sales"]]

              sales
0       9312.938773
1      21971.302557
2      16723.058813
3      15069.108079
4      10961.898690
...             ...
49995   1391.508330
49996  25940.993460
49997   2524.886995
49998  26844.609895
49999   7542.965433

[50000 rows x 1 columns]

In [59]:
df["expanding_sales"] = (
    df["sales"]
    .expanding()
    .sum()
)

In [60]:
df[["sales","expanding_sales"]]

              sales  expanding_sales
0       9312.938773     9.312939e+03
1      21971.302557     3.128424e+04
2      16723.058813     4.800730e+04
3      15069.108079     6.307641e+04
4      10961.898690     7.403831e+04
...             ...              ...
49995   1391.508330     5.086199e+08
49996  25940.993460     5.086458e+08
49997   2524.886995     5.086483e+08
49998  26844.609895     5.086752e+08
49999   7542.965433     5.086827e+08

[50000 rows x 2 columns]

## Shift

In [61]:
df["previous_sales"] = (
    df["sales"]
    .shift(1)
)
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895

## sales Difference

In [62]:
df["sales_diff"] = (
    df["sales"] -
    df["previous_sales"]
)

### STEP 16 — TIME SERIES
### Extract feature

In [63]:
df["year"] = (
    df["order_date"]
    .dt.year
)

df["month"] = (
    df["order_date"]
    .dt.month
)

df["quarter"] = (
    df["order_date"]
    .dt.quarter
)

df["weekday"] = (
    df["order_date"]
    .dt.day_name()
)

## Monthly sales trend

In [64]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("M")
    .sum()
)
monthly_sales

order_date
2023-01-31    2.188594e+07
2023-02-28    1.913025e+07
2023-03-31    2.172485e+07
2023-04-30    1.958840e+07
2023-05-31    2.079054e+07
2023-06-30    1.981893e+07
2023-07-31    2.247026e+07
2023-08-31    2.238257e+07
2023-09-30    2.047711e+07
2023-10-31    2.258785e+07
2023-11-30    2.147097e+07
2023-12-31    2.090333e+07
2024-01-31    2.159702e+07
2024-02-29    2.053086e+07
2024-03-31    2.179480e+07
2024-04-30    2.035634e+07
2024-05-31    2.166113e+07
2024-06-30    2.165668e+07
2024-07-31    2.116552e+07
2024-08-31    2.159529e+07
2024-09-30    2.039027e+07
2024-10-31    2.292052e+07
2024-11-30    2.099907e+07
2024-12-31    2.078422e+07
Freq: ME, Name: sales, dtype: float64

In [65]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("M")
    .min()
)
monthly_sales

order_date
2023-01-31    122.169136
2023-02-28    103.199756
2023-03-31    123.126661
2023-04-30     96.882142
2023-05-31     77.478504
2023-06-30    117.105597
2023-07-31    161.780660
2023-08-31     81.311258
2023-09-30    113.403564
2023-10-31     99.657673
2023-11-30     75.588494
2023-12-31     81.352862
2024-01-31     90.129092
2024-02-29     92.053162
2024-03-31     70.632346
2024-04-30     91.675503
2024-05-31    102.333808
2024-06-30     81.583190
2024-07-31     96.143315
2024-08-31     78.768362
2024-09-30     80.520907
2024-10-31     89.680680
2024-11-30     83.752609
2024-12-31     96.110663
Freq: ME, Name: sales, dtype: float64

In [66]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("Y")
    .min()
)
monthly_sales

order_date
2023-12-31    75.588494
2024-12-31    70.632346
Freq: YE-DEC, Name: sales, dtype: float64

In [67]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("Q")
    .min()
)
monthly_sales

order_date
2023-03-31    103.199756
2023-06-30     77.478504
2023-09-30     81.311258
2023-12-31     75.588494
2024-03-31     70.632346
2024-06-30     81.583190
2024-09-30     78.768362
2024-12-31     83.752609
Freq: QE-DEC, Name: sales, dtype: float64

In [68]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("W")
    .min()
)
monthly_sales

order_date
2023-01-01    476.150436
2023-01-08    216.980662
2023-01-15    211.105771
2023-01-22    122.169136
2023-01-29    138.613323
                 ...
2024-12-08    153.343547
2024-12-15     97.714542
2024-12-22    124.972351
2024-12-29     96.110663
2025-01-05    332.211219
Freq: W-SUN, Name: sales, Length: 106, dtype: float64

In [69]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("D")
    .min()
)
monthly_sales

order_date
2023-01-01    476.150436
2023-01-02    381.853221
2023-01-03    248.200982
2023-01-04    359.725175
2023-01-05    318.278010
                 ...
2024-12-26    256.114045
2024-12-27    282.355022
2024-12-28    157.552570
2024-12-29    343.525122
2024-12-30    332.211219
Freq: D, Name: sales, Length: 730, dtype: float64

In [73]:
monthly_sales = (

    df
    .set_index("order_date")
    ["sales"]

    .resample("YS")  # s hour min , 
    .min()
)
monthly_sales

order_date
2023-01-01    75.588494
2024-01-01    70.632346
Freq: YS-JAN, Name: sales, dtype: float64

Time Frequency Aliases
Alias	Meaning
"S"	Seconds
"min" or "T"	Minutes
"H"	Hour
"D"	Day
"W"	Week
"M"	Month end
"MS"	Month start
"Q"	Quarter end
"QS"	Quarter start
"Y" or "A"	Year end
"YS"	Year star

### STEP 17 — PIVOT TABLES

In [74]:
pd.pivot_table(

    df,
    values="sales",
    index="city",
    columns="department",
    aggfunc="sum",
    fill_value=0
)

department   Electronics       Fashion          Food     Furniture
city
Biratnagar  3.244236e+07  3.140071e+07  3.184653e+07  3.195729e+07
Kathmandu   3.135224e+07  3.181032e+07  3.120040e+07  3.185303e+07
Lalitpur    3.153126e+07  3.234772e+07  3.103456e+07  3.255062e+07
Pokhara     3.200542e+07  3.215962e+07  3.228133e+07  3.090929e+07

### STEP 18 — CROSSTAB

In [76]:
pd.crosstab(   # agg func and all the methiods 
    df["city"],
    df["payment_method"]
)

payment_method  Card  Cash  Khalti  eSewa
city
Biratnagar      3076  3142    3249   3222
Kathmandu       3105  3175    3043   3125
Lalitpur        3089  3080    3112   3092
Pokhara         3069  3117    3178   3126

### STEP 19 — MELT

In [77]:
pd.melt(
    df,
    id_vars=["order_id"],

    value_vars=["sales", "profit"]
)

       order_id variable         value
0             1    sales   9312.938773
1             2    sales  21971.302557
2             3    sales  16723.058813
3             4    sales  15069.108079
4             5    sales  10961.898690
...         ...      ...           ...
99995     49996   profit    305.051442
99996     49997   profit   1576.344902
99997     49998   profit    478.473774
99998     49999   profit   7927.025576
99999     50000   profit    714.591242

[100000 rows x 3 columns]

## STEP 20 — MULTIINDEX

In [78]:
multi = (
    df.groupby(
        ["city", "department"]
    )["sales"]
    .sum()
)
multi

city        department
Biratnagar  Electronics    3.244236e+07
            Fashion        3.140071e+07
            Food           3.184653e+07
            Furniture      3.195729e+07
Kathmandu   Electronics    3.135224e+07
            Fashion        3.181032e+07
            Food           3.120040e+07
            Furniture      3.185303e+07
Lalitpur    Electronics    3.153126e+07
            Fashion        3.234772e+07
            Food           3.103456e+07
            Furniture      3.255062e+07
Pokhara     Electronics    3.200542e+07
            Fashion        3.215962e+07
            Food           3.228133e+07
            Furniture      3.090929e+07
Name: sales, dtype: float64

### STEP 21 — JSON NORMALIZE
### Nested JSON

In [79]:
data = [

    {
        "id": 1,

        "name": "Ram",

        "address": {
            "city": "Kathmandu",
            "country": "Nepal"
        },

        "skills": [
            "Python",
            "SQL"
        ]
    },

    {
        "id": 2,

        "name": "Hari",

        "address": {
            "city": "Pokhara",
            "country": "Nepal"
        },

        "skills": [
            "Power BI",
            "Excel"
        ]
    }
]

In [80]:
data

[{'id': 1,
  'name': 'Ram',
  'address': {'city': 'Kathmandu', 'country': 'Nepal'},
  'skills': ['Python', 'SQL']},
 {'id': 2,
  'name': 'Hari',
  'address': {'city': 'Pokhara', 'country': 'Nepal'},
  'skills': ['Power BI', 'Excel']}]

In [81]:
json_df = pd.json_normalize(data)

json_df

   id  name             skills address.city address.country
0   1   Ram      [Python, SQL]    Kathmandu           Nepal
1   2  Hari  [Power BI, Excel]      Pokhara           Nepal

In [82]:
json_df.explode("skills")

   id  name    skills address.city address.country
0   1   Ram    Python    Kathmandu           Nepal
0   1   Ram       SQL    Kathmandu           Nepal
1   2  Hari  Power BI      Pokhara           Nepal
1   2  Hari     Excel      Pokhara           Nepal

## STEP 22 — APPLY + LAMBDA

In [83]:
df["grade"] = df.apply(

    lambda row:

    "A"
    if row["sales"] > 20000

    else "B",

    axis=1
)

In [84]:
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Card,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN,NaN,2024,6,2,Tuesday,B
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557,-5248.243744,2024,11,4,Sunday,B
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813,-1653.950734,2023,5,2,Wednesday,B
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395,-2776.669065,2023,3,1,Monday,B
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330,24549.485130,2024,7,3,Sunday,A
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460,-23416.106465,2023,2,1,Friday,B
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995,24319.722900,2024,8,3,Thursday,A
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895,-19301.644462,2024,1,1,Friday,B

### STEP 23 — MAP

In [85]:
province_map = {

    "Kathmandu": "Bagmati",

    "Pokhara": "Gandaki"
}

df["province"] = (
    df["city"]
    .map(province_map)
)

In [90]:
df['city']

0           Pokhara
1           Pokhara
2        Biratnagar
3        Biratnagar
4           Pokhara
            ...
49995      Lalitpur
49996     Kathmandu
49997       Pokhara
49998      Lalitpur
49999      Lalitpur
Name: city, Length: 50000, dtype: category
Categories (4, object): ['Biratnagar', 'Kathmandu', 'Lalitpur', 'Pokhara']

### STEP 24 — REPLACE

In [91]:
df["payment_method"] = (

    df["payment_method"]

    .replace({
        "Card": "Debit/Credit"
    })
)

### STEP 26 — METHOD CHAINING

In [93]:
result = (

    df

    .query("sales > 10000")

    .assign(

        tax=lambda x:
        x["sales"] * 0.13

    )

    .groupby("city")

    .agg(

        total_sales=("sales", "sum"),

        avg_profit=("profit", "mean"),
        tax_sum=("tax","sum")
    )

    .sort_values(
        "total_sales",
        ascending=False
    )
)
result

             total_sales   avg_profit       tax_sum
city
Pokhara     9.506295e+07  3253.309607  1.235818e+07
Lalitpur    9.505287e+07  3291.038352  1.235687e+07
Biratnagar  9.381032e+07  3221.395588  1.219534e+07
Kathmandu   9.296065e+07  3277.947163  1.208488e+07

## STEP 27 — ADVANCED FUNCTIONS
## factorize

In [95]:
df['city']

0           Pokhara
1           Pokhara
2        Biratnagar
3        Biratnagar
4           Pokhara
            ...
49995      Lalitpur
49996     Kathmandu
49997       Pokhara
49998      Lalitpur
49999      Lalitpur
Name: city, Length: 50000, dtype: category
Categories (4, object): ['Biratnagar', 'Kathmandu', 'Lalitpur', 'Pokhara']

In [96]:
df["city_id"] = (
    pd.factorize(df["city"])[0]
)

In [97]:
df[['city','city_id']]

             city  city_id
0         Pokhara        0
1         Pokhara        0
2      Biratnagar        1
3      Biratnagar        1
4         Pokhara        0
...           ...      ...
49995    Lalitpur        2
49996   Kathmandu        3
49997     Pokhara        0
49998    Lalitpur        2
49999    Lalitpur        2

[50000 rows x 2 columns]

## cut

In [98]:
df["sales_band"] = pd.cut(

    df["sales"],

    bins=[0,5000,10000,20000,100000],

    labels=[
        "Low",
        "Medium",
        "High",
        "Ultra"
    ]
)
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Debit/Credit,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN,NaN,2024,6,2,Tuesday,B,Gandaki,0,Medium
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557,-5248.243744,2024,11,4,Sunday,B,NaN,1,High
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813,-1653.950734,2023,5,2,Wednesday,B,NaN,1,High
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395,-2776.669065,2023,3,1,Monday,B,NaN,2,Low
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330,24549.485130,2024,7,3,Sunday,A,Bagmati,3,Ultra
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460,-23416.106465,2023,2,1,Friday,B,Gandaki,0,Low
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995,24319.722900,2024,8,3,Thursday,A,NaN,2,Ultra
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895,-19301.644462,2024,1,1,Friday,B,NaN,2,Medium

## qcut

In [99]:
df["quantile_band"] = pd.qcut(
    df["sales"],
    q=4
)
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band,quantile_band
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Debit/Credit,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN,NaN,2024,6,2,Tuesday,B,Gandaki,0,Medium,"(7797.481, 15047.316]"
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]"
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557,-5248.243744,2024,11,4,Sunday,B,NaN,1,High,"(15047.316, 44863.316]"
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813,-1653.950734,2023,5,2,Wednesday,B,NaN,1,High,"(15047.316, 44863.316]"
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395,-2776.669065,2023,3,1,Monday,B,NaN,2,Low,"(70.631, 3332.509]"
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330,24549.485130,2024,7,3,Sunday,A,Bagmati,3,Ultra,"(15047.316, 44863.316]"
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460,-23416.106465,2023,2,1,Friday,B,Gandaki,0,Low,"(70.631, 3332.509]"
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995,24319.722900,2024,8,3,Thursday,A,NaN,2,Ultra,"(15047.316, 44863.316]"
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895,-19301.644462,2024,1,1,Friday,B,NaN,2,Medium,"(3332.509, 7797.481]"

## STEP 28 — TOP N ANALYSIS
## Top 5 sales per city

In [100]:
df.groupby("city").apply(
    lambda x:
    x.nlargest(5, "sales")
)

                  order_id  customer_id customer_name  gender        city  \
city
Biratnagar 38132     38133         4869         David    Male  Biratnagar
           8871       8872         2203           Ram    Male  Biratnagar
           1800       1801         3493           Ram    Male  Biratnagar
           22571     22572         4956           Ram    Male  Biratnagar
           41195     41196         3339         Emily    Male  Biratnagar
Kathmandu  1878       1879         8340         Emily    Male   Kathmandu
           41369     41370         2445          John  Female   Kathmandu
           19564     19565         3919          Sita  Female   Kathmandu
           29907     29908         7167         David  Female   Kathmandu
           28922     28923         8318          John    Male   Kathmandu
Lalitpur   33051     33052         8676          Sita  Female    Lalitpur
           1605       1606         6342          John  Female    Lalitpur
           24286     24287         9294           Ram    Male    Lalitpur
           26287     26288         7005         Emily    Male    Lalitpur
           8027       8028         1246         David    Male    Lalitpur
Pokhara    33651     33652         4944          Sita    Male     Pokhara
           17935     17936         4345         Emily  Female     Pokhara
           41405     41406         7502         Emily    Male     Pokhara
           15141     15142         6617          Sita    Male     Pokhara
           6542       6543         2906           Ram    Male     Pokhara

                   department sales_channel payment_method  quantity  \
city
Biratnagar 38132    Furniture   Distributor         Khalti         9
           8871       Fashion   Distributor         Khalti         9
           1800     Furniture        Retail          eSewa         9
           22571         Food   Distributor   Debit/Credit         9
           41195    Furniture        Retail         Khalti         9
Kathmandu  1878          Food        Online           Cash         9
           41369      Fashion        Online   Debit/Credit         9
           19564  Electronics        Retail           Cash         9
           29907  Electronics   Distributor         Khalti         9
           28922      Fashion        Retail         Khalti         9
Lalitpur   33051  Electronics   Distributor         Khalti         9
           1605          Food        Online   Debit/Credit         9
           24286    Furniture        Retail         Khalti         9
           26287         Food        Retail          eSewa         9
           8027       Fashion   Distributor          eSewa         9
Pokhara    33651    Furniture        Online   Debit/Credit         9
           17935  Electronics        Retail   Debit/Credit         9
           41405    Furniture   Distributor           Cash         9
           15141    Furniture        Online          eSewa         9
           6542   Electronics        Online          eSewa         9

                  unit_price  discount    rating  delivery_days  \
city
Biratnagar 38132        4958  0.008128  3.845116             10
           8871         4929  0.031209  3.224564             11
           1800         4966  0.039693  3.006058              8
           22571        4925  0.038403  1.194101              7
           41195        4809  0.029457  3.815371              1
Kathmandu  1878         4950  0.000639  4.633253              4
           41369        4898  0.004430  4.746230             12
           19564        4912  0.010764  1.658942              6
           29907        4865  0.001364  2.703915              2
           28922        4886  0.011349  4.007296              5
Lalitpur   33051        4997  0.002439  4.949496             10
           1605         4883  0.006094  1.276490              8
           24286        4944  0.018972  1.176913              4
           26287        4838  0.000764  2.332359             10
           8027         4805  0.011882  1.049156             14
Pokhara    33651        4961  0.015243  4.211626              7
           17935        4986  0.028461  4.339383              1
           41405        4870  0.017477  3.094241              6
           15141        4986  0.052243  3.559664              2
           6542         4988  0.057607  1.425549             11

                  website_visits  ad_spend  join_date order_date  \
city
Biratnagar 38132             269     47367 2022-11-22 2023-08-23
           8871               74      2528 2023-07-04 2024-07-10
           1800              349     13975 2020-07-05 2024-10-30
           22571             179     30219 2021-02-12 2023-09-16
           41195             469     16541 2024-01-15 2024-04-24
Kathmandu  1878              376     38619 2020-12-30 2024-04-09
           41369             155      5491 2023-08-12 2023-08-08
           19564              55     37924 2022-09-17 2023-12-14
           29907             129     35164 2020-10-27 2024-06-15
           28922             258      1055 2020-10-02 2024-02-14
Lalitpur   33051             197     18155 2021-10-18 2023-01-18
           1605              175     15726 2020-03-01 2024-12-28
           24286             335      6221 2023-03-19 2024-08-18
           26287             386     48633 2020-09-07 2023-12-11
           8027               74     31367 2023-02-24 2023-10-30
Pokhara    33651             234     45737 2023-01-24 2023-09-30
           17935             320     43756 2021-01-31 2024-03-25
           41405             209     30874 2020-11-26 2023-09-17
           15141             392     41735 2020-02-05 2024-01-20
           6542              461     47535 2020-04-15 2024-02-14

                         sales        profit  updated_profit  profit_margin  \
city
Biratnagar 38132  44259.309127   2373.210384             NaN       5.362059
           8871   42976.518101   8059.796390             NaN      18.753954
           1800   42919.941860   2224.336180             NaN       5.182524
           22571  42622.787018   5212.250632             NaN      12.228789
           41195  42006.087706   8220.763906             NaN      19.570411
Kathmandu  1878   44521.553784  12917.881168             NaN      29.014893
           41369  43886.715644   6795.677952             NaN      15.484590
           19564  43732.127241   7247.961767         10000.0      16.573540
           29907  43725.255548  12781.680753         10000.0      29.231803
           28922  43474.933657  10272.426316             NaN      23.628389
Lalitpur   33051  44863.316319   9383.347713         10000.0      20.915413
           1605   43679.176446  10725.326645             NaN      24.554782
           24286  43651.840188  12026.875764             NaN      27.551818
           26287  43508.730510   4740.018888             NaN      10.894409
           8027   42731.159976   5865.212108             NaN      13.725843
Pokhara    33651  43968.418041  12715.528577             NaN      28.919686
           17935  43596.854815  12290.031598         10000.0      28.190179
           41405  43063.985126   9609.242121             NaN      22.313871
           15141  42529.643601  12646.781639             NaN      29.736392
           6542   42305.924523  12026.767917         10000.0      28.428094

                 customer_segment         risk    city_sales  sales_pct  \
city
Biratnagar 38132          Premium    High Risk  1.276469e+08   0.034673
           8871           Premium  Medium Risk  1.276469e+08   0.033668
           1800           Premium    High Risk  1.276469e+08   0.033624
           22571          Premium  Medium Risk  1.276469e+08   0.033391
           41195          Premium  Medium Risk  1.276469e+08   0.032908
Kathmandu  1878           Premium     Low Risk  1.262160e+08   0.035274
           41369          Premium  Medium Risk  1.262160e+08   0.034771
           19564          Premium  Medium Risk  1.262160e+08   0.034649
           29907          Premium     Low Risk  1.262160e+08   0.034643
           28922          Premium     Low Risk  1.262160e+08   0.034445
Lalitpur   33051          Premium     Low Risk  1.274642e+08   0.035197
           1605           Premium     Low Risk  1.274642e+08   0.034268
           24286          Premium     Low Risk  1.274642e+08   0.034246
           26287          Premium  Medium Risk  1.274642e+08   0.034134
           8027           Premium  Medium Risk  1.274642e+08   0.033524
Pokhara    33651          Premium     Low Risk  1.273557e+08   0.034524
           17935          Premium     Low Risk  1.273557e+08   0.034232
           41405          Premium     Low Risk  1.273557e+08   0.033814
           15141          Premium     Low Risk  1.273557e+08   0.033394
           6542           Premium     Low Risk  1.273557e+08   0.033219

                  rank_in_city  rolling_sales  expanding_sales  \
city
Biratnagar 38132           1.0   11227.517494     3.887160e+08
           8871            2.0   20577.313089     9.123678e+07
           1800            3.0   13500.070816     1.897154e+07
           22571           4.0   16381.249579     2.303426e+08
           41195           5.0   12673.957661     4.196602e+08
Kathmandu  1878            1.0   13325.837446     1.983544e+07
           41369           2.0   17359.394156     4.212617e+08
           19564           3.0   19744.928971     1.990916e+08
           29907           4.0   13818.797647     3.053769e+08
           28922           5.0   14276.734390     2.952430e+08
Lalitpur   33051           1.0   15635.081979     3.373141e+08
           1605            2.0   11114.607649     1.698482e+07
           24286           3.0   20775.790173     2.476598e+08
           26287           4.0   12262.110506     2.677892e+08
           8027            5.0   16350.357810     8.266450e+07
Pokhara    33651           1.0   13667.938439     3.433932e+08
           17935           2.0   12555.040887     1.820536e+08
           41405           3.0   18201.556860     4.217400e+08
           15141           4.0   11968.967902     1.542463e+08
           6542            5.0   17216.306103     6.784368e+07

                  previous_sales    sales_diff  year  month  quarter  \
city
Biratnagar 38132      943.721658  43315.587469  2023      8        3
           8871     26656.648292  16319.869809  2024      7        3
           1800      3526.378194  39393.563666  2024     10        4
           22571     4507.691960  38115.095058  2023      9        3
           41195    12215.580912  29790.506794  2024      4        2
Kathmandu  1878      7903.603320  36617.950464  2024      4        2
           41369     8377.272619  35509.443025  2023      8        3
           19564    11386.802177  32345.325064  2023     12        4
           29907     4554.461606  39170.793942  2024      6        2
           28922    18226.979040  25247.954617  2024      2        1
Lalitpur   33051     6566.286818  38297.029501  2023      1        1
           1605      3306.611758  40372.564688  2024     12        4
           24286    20393.799797  23258.040391  2024      8        3
           26287     2441.103555  41067.626955  2023     12        4
           8027     10146.398706  32584.761270  2023     10        4
Pokhara    33651     1394.420916  42573.997125  2023      9        3
           17935     2732.539428  40864.315386  2024      3        1
           41405     7663.726563  35400.258563  2023      9        3
           15141     1024.055248  41505.588354  2024      1        1
           6542     24519.686414  17786.238110  2024      2        1

                    weekday grade province  city_id sales_band  \
city
Biratnagar 38132  Wednesday     A      NaN        1      Ultra
           8871   Wednesday     A      NaN        1      Ultra
           1800   Wednesday     A      NaN        1      Ultra
           22571   Saturday     A      NaN        1      Ultra
           41195  Wednesday     A      NaN        1      Ultra
Kathmandu  1878     Tuesday     A  Bagmati        3      Ultra
           41369    Tuesday     A  Bagmati        3      Ultra
           19564   Thursday     A  Bagmati        3      Ultra
           29907   Saturday     A  Bagmati        3      Ultra
           28922  Wednesday     A  Bagmati        3      Ultra
Lalitpur   33051  Wednesday     A      NaN        2      Ultra
           1605    Saturday     A      NaN        2      Ultra
           24286     Sunday     A      NaN        2      Ultra
           26287     Monday     A      NaN        2      Ultra
           8027      Monday     A      NaN        2      Ultra
Pokhara    33651   Saturday     A  Gandaki        0      Ultra
           17935     Monday     A  Gandaki        0      Ultra
           41405     Sunday     A  Gandaki        0      Ultra
           15141   Saturday     A  Gandaki        0      Ultra
           6542   Wednesday     A  Gandaki        0      Ultra

                           quantile_band
city
Biratnagar 38132  (15047.316, 44863.316]
           8871   (15047.316, 44863.316]
           1800   (15047.316, 44863.316]
           22571  (15047.316, 44863.316]
           41195  (15047.316, 44863.316]
Kathmandu  1878   (15047.316, 44863.316]
           41369  (15047.316, 44863.316]
           19564  (15047.316, 44863.316]
           29907  (15047.316, 44863.316]
           28922  (15047.316, 44863.316]
Lalitpur   33051  (15047.316, 44863.316]
           1605   (15047.316, 44863.316]
           24286  (15047.316, 44863.316]
           26287  (15047.316, 44863.316]
           8027   (15047.316, 44863.316]
Pokhara    33651  (15047.316, 44863.316]
           17935  (15047.316, 44863.316]
           41405  (15047.316, 44863.316]
           15141  (15047.316, 44863.316]
           6542   (15047.316, 44863.316]

## STEP 29 — SQL INSIDE PANDA

In [101]:
import pandasql

In [102]:
query = """

SELECT city,
SUM(sales) AS total_sales

FROM df

GROUP BY city

"""
query

'\n\nSELECT city,\nSUM(sales) AS total_sales\n\nFROM df\n\nGROUP BY city\n\n'

In [103]:
df.head()

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band,quantile_band
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Debit/Credit,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9312.938773,NaN,NaN,2024,6,2,Tuesday,B,Gandaki,0,Medium,"(7797.481, 15047.316]"
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,31284.241331,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]"
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,48007.300144,21971.302557,-5248.243744,2024,11,4,Sunday,B,NaN,1,High,"(15047.316, 44863.316]"
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,63076.408223,16723.058813,-1653.950734,2023,5,2,Wednesday,B,NaN,1,High,"(15047.316, 44863.316]"
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,74038.306913,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]"

In [104]:
def high_sales(data):
    return data[(data["sales"] > 10000) & (data["city"]=="Pokhara")]

df.pipe(high_sales)

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band,quantile_band
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]"
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]"
12,13,7949,Hari,Male,Pokhara,Food,Distributor,Cash,6,1878,0.035501,3.693694,14,464,42402,2021-02-22,2023-11-17,10867.976831,3203.705458,NaN,29.478398,Regular,Low Risk,1.273557e+08,0.008534,4755.0,6101.244377,1.182258e+05,6474.170780,4393.806051,2023,11,4,Friday,B,Gandaki,0,High,"(7797.481, 15047.316]"
18,19,5555,Sita,Male,Pokhara,Furniture,Online,Cash,8,3681,0.086278,2.915930,7,404,40864,2022-12-20,2024-12-08,26907.297606,1727.678210,NaN,6.420854,Premium,High Risk,1.273557e+08,0.021128,646.0,13661.497262,2.029884e+05,2135.332629,24771.964976,2024,12,4,Sunday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]"
40,41,8513,David,Male,Pokhara,Electronics,Online,Cash,8,2168,0.136076,4.397969,13,231,43758,2023-10-18,2023-07-10,14983.903993,1731.474303,10000.0,11.555562,Regular,Medium Risk,1.273557e+08,0.011765,3170.0,6291.163869,3.367315e+05,1839.017472,13144.886521,2023,7,3,Monday,B,Gandaki,0,High,"(7797.481, 15047.316]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49948,49949,3129,David,Female,Pokhara,Electronics,Retail,Khalti,7,3580,0.002728,2.157545,8,466,46504,2021-03-13,2023-08-01,24991.628778,5647.789053,10000.0,22.598723,Premium,Low Risk,1.273557e+08,0.019623,870.0,11848.410632,5.081986e+08,9247.706866,15743.921912,2023,8,3,Tuesday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]"
49949,49950,6132,Emily,Male,Pokhara,Furniture,Distributor,Cash,3,4115,0.149203,1.951136,8,154,15026,2020-06-04,2023-12-04,10503.086493,3129.764959,NaN,29.798526,Regular,Low Risk,1.273557e+08,0.008247,4918.0,10673.648742,5.082091e+08,24991.628778,-14488.542286,2023,12,4,Monday,B,Gandaki,0,High,"(7797.481, 15047.316]"
49958,49959,8579,Sita,Male,Pokhara,Fashion,Distributor,Khalti,8,2645,0.345860,1.831907,11,268,12257,2024-01-09,2024-06-23,13841.604953,881.241855,NaN,6.366616,Regular,High Risk,1.273557e+08,0.010868,3560.0,10696.156132,5.082948e+08,21897.084377,-8055.479424,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]"
49967,49968,7178,John,Female,Pokhara,Food,Distributor,Cash,6,2631,0.309969,2.178829,10,61,44816,2020-06-10,2023-09-15,10892.837157,2970.915991,NaN,27.274033,Regular,Low Risk,1.273557e+08,0.008553,4747.0,6822.373812,5.083769e+08,20772.224077,-9879.386921,2023,9,3,Friday,B,Gandaki,0,High,"(7797.481, 15047.316]"
49991,49992,5222,Emily,Male,Pokhara,Electronics,Online,Cash,8,2177,0.141009,4.629262,11,482,19926,2020-05-15,2024-01-28,14960.187964,1336.504633,10000.0,8.933742,Regular,High Risk,1.273557e+08,0.011747,3179.0,9082.955985,5.085892e+08,485.779782,14474.408182,2024,1,1,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]"

## apply

In [108]:
df["risk_level123"] = df.apply(
    lambda row:
    "High" if row["profit"] < 1000 and row["city"] == "Pokhara"
    else "Low",
    axis=1
    
)
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band,quantile_band,risk_level123
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Debit/Credit,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.938773,1732.455190,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN,NaN,2024,6,2,Tuesday,B,Gandaki,0,Medium,"(7797.481, 15047.316]",Low
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.302557,4924.999781,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]",Low
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.058813,1554.307750,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557,-5248.243744,2024,11,4,Sunday,B,NaN,1,High,"(15047.316, 44863.316]",Low
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.108079,2618.179110,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813,-1653.950734,2023,5,2,Wednesday,B,NaN,1,High,"(15047.316, 44863.316]",Low
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.898690,1988.133850,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]",Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.508330,305.051442,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395,-2776.669065,2023,3,1,Monday,B,NaN,2,Low,"(70.631, 3332.509]",Low
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.993460,1576.344902,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330,24549.485130,2024,7,3,Sunday,A,Bagmati,3,Ultra,"(15047.316, 44863.316]",Low
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.886995,478.473774,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460,-23416.106465,2023,2,1,Friday,B,Gandaki,0,Low,"(70.631, 3332.509]",High
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.609895,7927.025576,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995,24319.722900,2024,8,3,Thursday,A,NaN,2,Ultra,"(15047.316, 44863.316]",Low
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.965433,714.591242,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895,-19301.644462,2024,1,1,Friday,B,NaN,2,Medium,"(3332.509, 7797.481]",Low

## Applymap()

In [109]:
df[["sales", "profit"]] = (
    df[["sales", "profit"]]
    .applymap(lambda x: round(x, 2))
)
df

,order_id,customer_id,customer_name,gender,city,department,sales_channel,payment_method,quantity,unit_price,discount,rating,delivery_days,website_visits,ad_spend,join_date,order_date,sales,profit,updated_profit,profit_margin,customer_segment,risk,city_sales,sales_pct,rank_in_city,rolling_sales,expanding_sales,previous_sales,sales_diff,year,month,quarter,weekday,grade,province,city_id,sales_band,quantile_band,risk_level123
0,1,8270,Emily,Male,Pokhara,Electronics,Retail,Debit/Credit,2,4912,0.052022,4.791408,1,54,17909,2023-12-05,2024-06-18,9312.94,1732.46,10000.0,18.602669,Regular,Medium Risk,1.273557e+08,0.007313,5480.0,NaN,9.312939e+03,NaN,NaN,2024,6,2,Tuesday,B,Gandaki,0,Medium,"(7797.481, 15047.316]",Low
1,2,1860,Emily,Female,Pokhara,Furniture,Online,Khalti,7,4500,0.302498,1.798061,2,109,5738,2021-03-25,2024-07-26,21971.30,4925.00,NaN,22.415602,Premium,Low Risk,1.273557e+08,0.017252,1396.0,NaN,3.128424e+04,9312.938773,12658.363784,2024,7,3,Friday,A,Gandaki,0,Ultra,"(15047.316, 44863.316]",Low
2,3,6390,Ram,Male,Biratnagar,Food,Online,eSewa,8,2109,0.008828,3.687034,10,263,47758,2020-12-30,2024-11-03,16723.06,1554.31,NaN,9.294399,Regular,High Risk,1.276469e+08,0.013101,2633.0,NaN,4.800730e+04,21971.302557,-5248.243744,2024,11,4,Sunday,B,NaN,1,High,"(15047.316, 44863.316]",Low
3,4,6191,David,Female,Biratnagar,Furniture,Online,Cash,9,2771,0.395761,3.028401,4,377,30723,2022-02-21,2023-05-10,15069.11,2618.18,NaN,17.374480,Regular,Medium Risk,1.276469e+08,0.011805,3104.0,NaN,6.307641e+04,16723.058813,-1653.950734,2023,5,2,Wednesday,B,NaN,1,High,"(15047.316, 44863.316]",Low
4,5,6734,Sita,Male,Pokhara,Furniture,Online,Cash,7,1841,0.149383,1.364637,11,121,21672,2020-03-31,2024-06-30,10961.90,1988.13,NaN,18.136765,Regular,Medium Risk,1.273557e+08,0.008607,4712.0,NaN,7.403831e+04,15069.108079,-4107.209390,2024,6,2,Sunday,B,Gandaki,0,High,"(7797.481, 15047.316]",Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,8143,John,Female,Lalitpur,Fashion,Distributor,Cash,6,239,0.029632,3.859182,13,403,2607,2021-03-07,2023-03-20,1391.51,305.05,NaN,21.922358,Regular,Low Risk,1.274642e+08,0.001092,11253.0,9551.193434,5.086199e+08,4168.177395,-2776.669065,2023,3,1,Monday,B,NaN,2,Low,"(70.631, 3332.509]",Low
49996,49997,9947,Sita,Female,Kathmandu,Fashion,Online,Khalti,9,3813,0.244077,2.488355,9,114,47247,2023-11-02,2024-07-14,25940.99,1576.34,NaN,6.076656,Premium,High Risk,1.262160e+08,0.020553,782.0,10292.163288,5.086458e+08,1391.508330,24549.485130,2024,7,3,Sunday,A,Bagmati,3,Ultra,"(15047.316, 44863.316]",Low
49997,49998,5871,Ram,Female,Pokhara,Electronics,Retail,eSewa,4,840,0.248546,4.410660,13,224,37181,2022-06-24,2023-02-03,2524.89,478.47,10000.0,18.950305,Regular,Medium Risk,1.273557e+08,0.001983,10178.0,10583.464319,5.086483e+08,25940.993460,-23416.106465,2023,2,1,Friday,B,Gandaki,0,Low,"(70.631, 3332.509]",High
49998,49999,4836,Ram,Female,Lalitpur,Fashion,Retail,Cash,9,4322,0.309872,3.186514,9,371,47952,2023-01-10,2024-08-15,26844.61,7927.03,NaN,29.529301,Premium,Low Risk,1.274642e+08,0.021061,696.0,12281.238880,5.086752e+08,2524.886995,24319.722900,2024,8,3,Thursday,A,NaN,2,Ultra,"(15047.316, 44863.316]",Low
49999,50000,8309,John,Female,Lalitpur,Fashion,Distributor,Cash,9,1087,0.228972,3.115385,14,228,18338,2023-02-26,2024-01-19,7542.97,714.59,NaN,9.473612,Regular,High Risk,1.274642e+08,0.005918,6376.0,12714.224345,5.086827e+08,26844.609895,-19301.644462,2024,1,1,Friday,B,NaN,2,Medium,"(3332.509, 7797.481]",Low

In [111]:
pivot = df.groupby(
    ["city", "gender"]
)["sales"].sum()

pivot.unstack()
pivot

city        gender
Biratnagar  Female    63953731.22
            Male      63693160.30
Kathmandu   Female    62621799.98
            Male      63594194.71
Lalitpur    Female    62548673.52
            Male      64915498.27
Pokhara     Female    63478637.95
            Male      63877026.30
Name: sales, dtype: float64

df["customer_name"].str.upper()
df["customer_name"].str.lower()
df["customer_name"].str.contains("a")
df["customer_name"].str.len()
df["customer_name"].str.replace("a", "@")

In [113]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 10000

df = pd.DataFrame({

    "employee": np.random.choice(
        ["Ram", "Hari", "Sita", "John", "Emily"],
        n
    ),

    "department": np.random.choice(
        ["IT", "HR", "Finance", "Sales"],
        n
    ),

    "city": np.random.choice(
        ["Kathmandu", "Pokhara", "Lalitpur"],
        n
    ),

    "salary": np.random.randint(30000, 200000, n),

    "bonus": np.random.randint(5000, 50000, n),

    "rating": np.random.uniform(1, 5, n),

    "experience": np.random.randint(1, 20, n)
})

df["total_income"] = (
    df["salary"] + df["bonus"]
)

df.head()

,employee,department,city,salary,bonus,rating,experience,total_income
0,John,HR,Kathmandu,179479,15309,4.371433,6,194788
1,Emily,HR,Lalitpur,86714,21173,1.670389,17,107887
2,Sita,Finance,Kathmandu,159613,15872,2.464652,16,175485
3,Emily,Sales,Kathmandu,167711,44800,2.243212,13,212511
4,Emily,IT,Pokhara,32478,36946,1.590963,12,69424

In [114]:
def square(x):
    return x * x

In [115]:
df.groupby("department")["salary"].mean()

department
Finance    114570.464919
HR         114798.634978
IT         113875.060765
Sales      115102.546814
Name: salary, dtype: float64

In [116]:
df.groupby("department")["salary"].agg(
    lambda x: x.mean()
)

department
Finance    114570.464919
HR         114798.634978
IT         113875.060765
Sales      115102.546814
Name: salary, dtype: float64

In [117]:
df.groupby("department")["salary"].agg(

    lambda x: x.max() - x.min()
)

department
Finance    169799
HR         169809
IT         169780
Sales      169921
Name: salary, dtype: int32

EXAMPLE 2 — CUSTOM PERCENTAGE

Find employees earning above 100k in each department.

In [118]:
df.groupby("department")["salary"].agg(

    lambda x: (x > 100000).mean() * 100
)

department
Finance    59.556452
HR         59.526675
IT         57.625755
Sales      59.520063
Name: salary, dtype: float64

In [119]:
df.groupby("department")["salary"].agg(

    lambda x: x.max() - x.mean()
)

department
Finance    85243.535081
HR         85188.365022
IT         85914.939235
Sales      84861.453186
Name: salary, dtype: float64

In [120]:
df.groupby("department").agg({

    "salary": lambda x: x.mean(),

    "bonus": lambda x: x.sum() / x.count()
})

                   salary         bonus
department
Finance     114570.464919  26960.752823
HR          114798.634978  27852.705576
IT          113875.060765  27423.896982
Sales       115102.546814  27338.890244

In [121]:
df.groupby("department")["salary"].agg([

    lambda x: x.mean(),

    lambda x: x.max(),

    lambda x: x.min(),

    lambda x: x.std(),

    lambda x: x.quantile(0.90)
])

               <lambda_0>  <lambda_1>  <lambda_2>    <lambda_3>  <lambda_4>
department
Finance     114570.464919      199814       30015  48585.781620    181433.4
HR          114798.634978      199987       30178  48381.369179    180752.4
IT          113875.060765      199790       30010  49144.562733    182877.4
Sales       115102.546814      199964       30043  49561.435754    183257.0

In [122]:
total_salary = df["salary"].sum()

df.groupby("department")["salary"].agg(

    lambda x: x.sum() / total_salary * 100
)

department
Finance    24.795817
HR         24.975435
IT         24.695002
Sales      25.533746
Name: salary, dtype: float64

In [123]:
df.groupby("department")["employee"].agg(

    lambda x: x.nunique()
)

department
Finance    5
HR         5
IT         5
Sales      5
Name: employee, dtype: int64

In [124]:
df.groupby("department")["rating"].agg(

    lambda x: (x > 4).sum()
)

department
Finance    619
HR         662
IT         624
Sales      622
Name: rating, dtype: int64

In [125]:
df.groupby("department")["salary"].agg(

    lambda x: x[x > 100000].mean()
)

department
Finance    148601.614760
HR         148630.638814
IT         149764.204609
Sales      149937.278255
Name: salary, dtype: float64

In [126]:
df.groupby("department")["salary"].agg(

    lambda x: x[
        x < x.quantile(0.95)
    ].mean()
)

department
Finance    110314.410017
HR         110567.474662
IT         109547.409746
Sales      110845.434548
Name: salary, dtype: float64

In [127]:
df.groupby("department")["salary"].agg(

    lambda x: np.median(
        np.abs(x - np.median(x))
    )
)

department
Finance    42042.5
HR         41699.0
IT         41561.0
Sales      43377.0
Name: salary, dtype: float64

## op 10 % average

In [128]:
df.groupby("department")["salary"].agg(

    lambda x: x.nlargest(
        int(len(x)*0.1)
    ).mean()
)

department
Finance    190533.108871
HR         190191.220884
IT         191218.891129
Sales      191167.606299
Name: salary, dtype: float64

In [129]:
df.groupby("department")["employee"].agg(

    lambda x: ", ".join(
        x.unique()
    )
)

department
Finance    Sita, Hari, John, Ram, Emily
HR         John, Emily, Hari, Ram, Sita
IT         Emily, John, Sita, Ram, Hari
Sales      Emily, Hari, Sita, John, Ram
Name: employee, dtype: object

In [130]:
df.groupby("department")["salary"].agg(

    lambda x:
    "High Paying"

    if x.mean() > 100000

    else "Normal"
)

department
Finance    High Paying
HR         High Paying
IT         High Paying
Sales      High Paying
Name: salary, dtype: object

In [131]:
df.groupby("department")["city"].agg(

    lambda x: x.mode()[0]
)

department
Finance    Kathmandu
HR         Kathmandu
IT           Pokhara
Sales       Lalitpur
Name: city, dtype: object

In [132]:
df.groupby(
    ["department", "city"]
)["salary"].agg(

    lambda x: x.mean()
)

department  city
Finance     Kathmandu    113978.906398
            Lalitpur     115806.961677
            Pokhara      113904.797753
HR          Kathmandu    116688.921893
            Lalitpur     113315.930779
            Pokhara      114324.517282
IT          Kathmandu    113698.231830
            Lalitpur     111970.315469
            Pokhara      115843.773672
Sales       Kathmandu    113636.788177
            Lalitpur     115569.935409
            Pokhara      116012.129780
Name: salary, dtype: float64

In [133]:
df["rolling_salary"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        x.rolling(3).mean()
    )
)

In [134]:
df.groupby("department")["salary"].agg(
    lambda x: x.mean()
)

department
Finance    114570.464919
HR         114798.634978
IT         113875.060765
Sales      115102.546814
Name: salary, dtype: float64

In [135]:
df["dept_avg"] = (

    df.groupby("department")["salary"]

    .transform(
        lambda x: x.mean()
    )
)
df

,employee,department,city,salary,bonus,rating,experience,total_income,rolling_salary,dept_avg
0,John,HR,Kathmandu,179479,15309,4.371433,6,194788,NaN,114798.634978
1,Emily,HR,Lalitpur,86714,21173,1.670389,17,107887,NaN,114798.634978
2,Sita,Finance,Kathmandu,159613,15872,2.464652,16,175485,NaN,114570.464919
3,Emily,Sales,Kathmandu,167711,44800,2.243212,13,212511,NaN,115102.546814
4,Emily,IT,Pokhara,32478,36946,1.590963,12,69424,NaN,113875.060765
...,...,...,...,...,...,...,...,...,...,...
9995,Hari,IT,Lalitpur,81933,5047,4.991514,4,86980,123615.333333,113875.060765
9996,Sita,HR,Pokhara,45479,5133,2.788173,11,50612,114260.333333,114798.634978
9997,Hari,Finance,Kathmandu,106719,27059,2.494050,10,133778,97326.000000,114570.464919
9998,John,Sales,Lalitpur,114532,16238,3.428144,8,130770,99161.666667,115102.546814
9999,Sita,HR,Pokhara,189296,40132,3.732330,9,229428,128709.000000,114798.634978

## z score

In [136]:
df["zscore"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        (x - x.mean()) / x.std()
    )
    
)
df

,employee,department,city,salary,bonus,rating,experience,total_income,rolling_salary,dept_avg,zscore
0,John,HR,Kathmandu,179479,15309,4.371433,6,194788,NaN,114798.634978,1.336886
1,Emily,HR,Lalitpur,86714,21173,1.670389,17,107887,NaN,114798.634978,-0.580485
2,Sita,Finance,Kathmandu,159613,15872,2.464652,16,175485,NaN,114570.464919,0.927072
3,Emily,Sales,Kathmandu,167711,44800,2.243212,13,212511,NaN,115102.546814,1.061480
4,Emily,IT,Pokhara,32478,36946,1.590963,12,69424,NaN,113875.060765,-1.656278
...,...,...,...,...,...,...,...,...,...,...,...
9995,Hari,IT,Lalitpur,81933,5047,4.991514,4,86980,123615.333333,113875.060765,-0.649961
9996,Sita,HR,Pokhara,45479,5133,2.788173,11,50612,114260.333333,114798.634978,-1.432775
9997,Hari,Finance,Kathmandu,106719,27059,2.494050,10,133778,97326.000000,114570.464919,-0.161600
9998,John,Sales,Lalitpur,114532,16238,3.428144,8,130770,99161.666667,115102.546814,-0.011512
9999,Sita,HR,Pokhara,189296,40132,3.732330,9,229428,128709.000000,114798.634978,1.539794

## percentile ranks

In [137]:
df["percentile_rank"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        x.rank(pct=True)
    )
)

## EXAMPLE 20 — NORMALIZATION INSIDE GROUP

In [138]:
df["normalized_salary"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        (x - x.min()) /
        (x.max() - x.min())
    )
)

In [139]:
df.groupby("department").apply(

    lambda x:
    x.nlargest(3, "salary")
)

                employee department       city  salary  bonus    rating  \
department
Finance    3678     Sita    Finance   Lalitpur  199814  29463  1.615653
           5304     Hari    Finance  Kathmandu  199699  19211  4.441052
           4025     John    Finance   Lalitpur  199623  18347  4.399637
HR         7632     Hari         HR  Kathmandu  199987  22978  2.596230
           5085      Ram         HR  Kathmandu  199820  36389  2.049550
           5964     John         HR   Lalitpur  199631   6493  3.402634
IT         844     Emily         IT   Lalitpur  199790  18088  2.457301
           6777      Ram         IT   Lalitpur  199642  36683  3.344824
           2867     John         IT    Pokhara  199626  37287  2.926598
Sales      1422    Emily      Sales   Lalitpur  199964  26185  1.825707
           3965    Emily      Sales  Kathmandu  199887   5003  1.204691
           7142     Hari      Sales  Kathmandu  199768  33722  2.440022

                 experience  total_income  rolling_salary       dept_avg  \
department
Finance    3678           5        229277   137992.000000  114570.464919
           5304          17        218910   165017.333333  114570.464919
           4025           6        217970   108470.000000  114570.464919
HR         7632           7        222965   127017.000000  114798.634978
           5085           2        236209   158705.666667  114798.634978
           5964          15        206124   109326.000000  114798.634978
IT         844            4        217878   153279.666667  113875.060765
           6777          12        236325   142939.000000  113875.060765
           2867          19        236913   165013.333333  113875.060765
Sales      1422           8        226149    92736.000000  115102.546814
           3965          16        204890   124416.000000  115102.546814
           7142          17        233490   132596.000000  115102.546814

                   zscore  percentile_rank  normalized_salary
department
Finance    3678  1.754495         1.000000           1.000000
           5304  1.752129         0.999597           0.999323
           4025  1.750564         0.999194           0.998875
HR         7632  1.760768         1.000000           1.000000
           5085  1.757316         0.999599           0.999017
           5964  1.753410         0.999198           0.997904
IT         844   1.748208         1.000000           1.000000
           6777  1.745197         0.999598           0.999128
           2867  1.744871         0.999195           0.999034
Sales      1422  1.712248         1.000000           1.000000
           3965  1.710694         0.999607           0.999547
           7142  1.708293         0.999213           0.998847

In [140]:
df.groupby("department").apply(

    lambda x:
    x.sort_values(
        "salary",
        ascending=False
    )
)

                employee department       city  salary  bonus    rating  \
department
Finance    3678     Sita    Finance   Lalitpur  199814  29463  1.615653
           5304     Hari    Finance  Kathmandu  199699  19211  4.441052
           4025     John    Finance   Lalitpur  199623  18347  4.399637
           6425     Hari    Finance    Pokhara  199593  46522  1.738543
           5071     Hari    Finance  Kathmandu  199509   8790  1.146291
...                  ...        ...        ...     ...    ...       ...
Sales      2689      Ram      Sales   Lalitpur   30315  49869  2.204049
           9120     Hari      Sales   Lalitpur   30159  26366  4.335905
           3900     John      Sales  Kathmandu   30132  41273  2.807146
           6254     Sita      Sales  Kathmandu   30059   8905  2.419202
           8748     John      Sales    Pokhara   30043  30497  1.608074

                 experience  total_income  rolling_salary       dept_avg  \
department
Finance    3678           5        229277   137992.000000  114570.464919
           5304          17        218910   165017.333333  114570.464919
           4025           6        217970   108470.000000  114570.464919
           6425           5        246115   146770.333333  114570.464919
           5071           3        208299   151374.333333  114570.464919
...                     ...           ...             ...            ...
Sales      2689          10         80184    82860.666667  115102.546814
           9120          11         56525    52607.333333  115102.546814
           3900           1         71405    97177.666667  115102.546814
           6254           6         38964   120734.333333  115102.546814
           8748           5         60540    59158.000000  115102.546814

                   zscore  percentile_rank  normalized_salary
department
Finance    3678  1.754495         1.000000           1.000000
           5304  1.752129         0.999597           0.999323
           4025  1.750564         0.999194           0.998875
           6425  1.749947         0.998790           0.998698
           5071  1.748218         0.998387           0.998204
...                   ...              ...                ...
Sales      2689 -1.710756         0.001967           0.001601
           9120 -1.713904         0.001574           0.000683
           3900 -1.714449         0.001180           0.000524
           6254 -1.715922         0.000787           0.000094
           8748 -1.716245         0.000393           0.000000

[10000 rows x 13 columns]

In [141]:
df.groupby("department").filter(

    lambda x:
    x["salary"].mean() > 100000
)

,employee,department,city,salary,bonus,rating,experience,total_income,rolling_salary,dept_avg,zscore,percentile_rank,normalized_salary
0,John,HR,Kathmandu,179479,15309,4.371433,6,194788,NaN,114798.634978,1.336886,0.891697,0.879229
1,Emily,HR,Lalitpur,86714,21173,1.670389,17,107887,NaN,114798.634978,-0.580485,0.323305,0.332939
2,Sita,Finance,Kathmandu,159613,15872,2.464652,16,175485,NaN,114570.464919,0.927072,0.766129,0.763244
3,Emily,Sales,Kathmandu,167711,44800,2.243212,13,212511,NaN,115102.546814,1.061480,0.802911,0.810188
4,Emily,IT,Pokhara,32478,36946,1.590963,12,69424,NaN,113875.060765,-1.656278,0.014889,0.014536
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Hari,IT,Lalitpur,81933,5047,4.991514,4,86980,123615.333333,113875.060765,-0.649961,0.305030,0.305825
9996,Sita,HR,Pokhara,45479,5133,2.788173,11,50612,114260.333333,114798.634978,-1.432775,0.098676,0.090107
9997,Hari,Finance,Kathmandu,106719,27059,2.494050,10,133778,97326.000000,114570.464919,-0.161600,0.450000,0.451734
9998,John,Sales,Lalitpur,114532,16238,3.428144,8,130770,99161.666667,115102.546814,-0.011512,0.493706,0.497225
9999,Sita,HR,Pokhara,189296,40132,3.732330,9,229428,128709.000000,114798.634978,1.539794,0.945046,0.937041

In [142]:
df.groupby("department").apply(

    lambda x: pd.Series({

        "avg_salary": x["salary"].mean(),

        "high_earners":
        (x["salary"] > 100000).sum(),

        "avg_rating":
        x["rating"].mean(),

        "salary_to_bonus_ratio":
        x["salary"].sum() /
        x["bonus"].sum()
    })
)

               avg_salary  high_earners  avg_rating  salary_to_bonus_ratio
department
Finance     114570.464919        1477.0    2.986668               4.249528
HR          114798.634978        1484.0    3.041333               4.121633
IT          113875.060765        1432.0    2.996156               4.152403
Sales       115102.546814        1513.0    2.991067               4.210213

In [143]:
df.groupby("department").apply(

    lambda x:

    np.average(
        x["salary"],
        weights=x["experience"]
    )
)

department
Finance    114479.385049
HR         114819.465597
IT         114990.877219
Sales      115378.475403
dtype: float64

In [144]:
df.groupby("department").apply(

    lambda x:

    x["salary"].corr(
        x["experience"]
    )
)

department
Finance   -0.003429
HR         0.000776
IT         0.041877
Sales      0.010090
dtype: float64

In [145]:
df["cum_pct"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        x.cumsum() / x.sum()
    )
)

In [146]:
df["moving_avg"] = (

    df.groupby("department")["salary"]

    .transform(

        lambda x:
        x.rolling(
            window=5,
            min_periods=1
        ).mean()
    )
)

In [147]:
result = (

    df

    .groupby("department")

    .apply(

        lambda x: pd.Series({

            "employees":
            len(x),

            "avg_salary":
            x["salary"].mean(),

            "top_earner":
            x["salary"].max(),

            "salary_std":
            x["salary"].std(),

            "high_earner_pct":
            (x["salary"] > 100000).mean()*100,

            "avg_rating":
            x["rating"].mean()
        })
    )

    .sort_values(
        "avg_salary",
        ascending=False
    )
)

groupby + lambda + transform + apply

In [148]:
import os
os.getcwd()

'R:\\adarsha\\365\\sql_projects_day_1\\pandas_projects'