IPL Batting Dataset Description

The dataset contains batting statistics of IPL (Indian Premier League) players from multiple seasons (2008–2025). Each row represents the batting performance of a player in a specific IPL season for a particular team.

The dataset is designed for:

Descriptive Data Analysis
Sports Analytics
SQL & Pandas Practice
GroupBy Operations
Data Visualization
KPI Analysis
Dashboard Development
Business Intelligence Projects

Dataset Columns Description

POS	: Ranking position of player in season
player_name :	Name of the batsman
team	: IPL franchise/team
RUNS	: Total runs scored
MAT : 	Matches played
INNS	: Innings played
NO	: Number of not outs
HS	: Highest score
AVG	: Batting average
BF	: Balls faced
SR	: Strike rate
100	: Total centuries
50	: Total half centuries
4S	: Total fours
6S	: Total sixes
season	: IPL season year
status	: Out / Not Out status

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"R:\sipps_ss\api_datas\ip;l_\super_final.csv")
df

,POS,player_name,team,RUNS,MAT,INNS,NO,HS,AVG,BF,SR,100,50,4S,6S,season,status
0,1,Shaun Marsh,PBKS,616,11,11,2,115,68.44,441,139.68,1,5,59,26,2008,out
1,2,Gautam Gambhir,DC,534,14,14,1,86,41.07,379,140.89,0,5,68,8,2008,out
2,3,Sanath Jayasuriya,MI,518,14,14,2,114,43.16,309,167.63,1,2,58,31,2008,Not_out
3,4,Shane Watson,RR,472,15,15,5,76,47.2,311,151.76,0,4,47,19,2008,Not_out
4,5,Graeme Smith,RR,441,11,11,2,91,49.0,362,121.82,0,3,54,8,2008,out
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2604,97,Kumar Kartikeya Singh,RR,1,1,1,0,1,1.00,1,100.00,0,0,0,0,2025,out
2605,98,Sai Kishore,GT,1,2,1,0,1,1.00,1,100.00,0,0,0,0,2025,out
2606,99,Mohd Arshad Khan,GT,1,1,1,1,1,-,1,100.00,0,0,0,0,2025,Not_out
2607,100,Mohit Sharma,DC,1,2,1,1,1,-,2,50.00,0,0,0,0,2025,Not_out
2608,101,Trent Boult,MI,1,2,1,0,1,1.00,2,50.00,0,0,0,0,2025,out

# TEAM-WISE ANALYSIS

## 1. Total Runs Scored by Each Team

In [5]:
df.columns

Index(['POS', 'player_name', 'team', 'RUNS', 'MAT', 'INNS', 'NO', 'HS', 'AVG',
       'BF', 'SR', '100', '50', '4S', '6S', 'season', 'status'],
      dtype='object')

In [6]:
team_runs = (
    df.groupby('team')['RUNS']
      .sum()
      .sort_values(ascending=False)
)

team_runs

team
MI      40091
RCB     38914
PBKS    38201
KKR     37208
CSK     37166
DC      35586
RR      33586
SRH     28209
DEC     10443
GT       7760
LSG      7462
PWI      6034
GL       4627
RPS      4332
KTK      1757
Name: RUNS, dtype: int64

### 2. Average Strike Rate of Each Team

In [8]:
team_sr = (
    df.groupby('team')['SR']
      .mean()
      .sort_values(ascending=False)
)

team_sr

team
LSG     129.666607
GT      126.028214
CSK     120.171076
SRH     115.648824
PBKS    114.605645
MI      114.479666
KKR     114.202333
RCB     114.109437
DC      111.525050
RR      110.407014
RPS     107.783947
DEC     106.366782
GL      104.097429
PWI     100.992154
KTK     100.030000
Name: SR, dtype: float64

## 3. Team with Most Centuries

In [9]:
team_100s = (
    df.groupby('team')['100']
      .sum()
      .sort_values(ascending=False)
)

team_100s

team
RCB     19
RR      17
PBKS    16
CSK     10
DC       9
MI       8
SRH      7
GT       5
LSG      4
KKR      3
RPS      2
DEC      1
GL       0
KTK      0
PWI      0
Name: 100, dtype: int64

## 4. Team with Most Sixes

In [11]:
team_sixes = (
    df.groupby('team')['6S']
      .sum()
      .sort_values(ascending=False)
)

team_sixes

team
MI      1690
RCB     1668
PBKS    1548
CSK     1526
KKR     1506
DC      1321
RR      1269
SRH     1071
DEC      381
LSG      359
GT       295
PWI      196
RPS      157
GL       155
KTK       53
Name: 6S, dtype: int64

## 5. Team-wise Boundary Percentage

In [14]:
df['boundary_runs'] = (
    df['4S'] * 4 +
    df['6S'] * 6
)

team_boundary = (
    df.groupby('team')
      .agg(
          total_runs=('RUNS', 'sum'),
          boundary_runs=('boundary_runs', 'sum')
      )
)

team_boundary['boundary_percentage'] = (
    team_boundary['boundary_runs'] /
    team_boundary['total_runs']
) * 100

team_boundary

      total_runs  boundary_runs  boundary_percentage
team
CSK        37166          22072            59.387612
DC         35586          21330            59.939302
DEC        10443           5910            56.592933
GL          4627           2770            59.866004
GT          7760           4646            59.871134
KKR        37208          22876            61.481402
KTK         1757            998            56.801366
LSG         7462           4594            61.565264
MI         40091          24736            61.699633
PBKS       38201          23252            60.867517
PWI         6034           3276            54.292343
RCB        38914          23648            60.769903
RPS         4332           2414            55.724838
RR         33586          20126            59.923778
SRH        28209          16266            57.662448

## 6. Team-wise Average Runs Per Player

In [15]:
team_avg_runs = (
    df.groupby('team')['RUNS']
      .mean()
      .sort_values(ascending=False)
)

team_avg_runs

team
CSK     166.663677
GT      138.571429
MI      134.083612
LSG     133.250000
GL      132.200000
SRH     127.642534
KKR     124.026667
PBKS    123.229032
RCB     121.606250
RR      120.812950
DEC     120.034483
DC      117.445545
RPS     114.000000
KTK      97.611111
PWI      92.830769
Name: RUNS, dtype: float64

## 7. Best Team Based on Batting Average

In [20]:
df['AVG']=pd.to_numeric(df['AVG'],errors="coerce")

In [21]:
team_avg = (
    df.groupby('team')['AVG']
      .mean()
      .sort_values(ascending=False)
)

team_avg

team
CSK     22.790183
GT      22.092692
LSG     21.487115
SRH     19.574626
PBKS    19.099671
MI      18.621000
DC      18.470884
RR      18.022279
KKR     17.982891
RCB     17.961981
RPS     17.541579
DEC     17.403333
GL      15.858571
KTK     14.601111
PWI     14.130000
Name: AVG, dtype: float64

In [17]:
df.columns

Index(['POS', 'player_name', 'team', 'RUNS', 'MAT', 'INNS', 'NO', 'HS', 'AVG',
       'BF', 'SR', '100', '50', '4S', '6S', 'season', 'status',
       'boundary_runs'],
      dtype='object')

## 8. Team-wise Total Half Centuries

In [23]:
team_50s = (
    df.groupby('team')['50']
      .sum()
)

team_50s

team
CSK     206
DC      189
DEC      48
GL       27
GT       38
KKR     196
KTK       5
LSG      47
MI      206
PBKS    180
PWI      17
RCB     216
RPS      22
RR      151
SRH     154
Name: 50, dtype: int64

## 9. Most Aggressive Team

In [25]:
aggressive_team = (
    df.groupby('team')['SR']
      .mean()
      .sort_values(ascending=False)
)

aggressive_team

team
LSG     129.666607
GT      126.028214
CSK     120.171076
SRH     115.648824
PBKS    114.605645
MI      114.479666
KKR     114.202333
RCB     114.109437
DC      111.525050
RR      110.407014
RPS     107.783947
DEC     106.366782
GL      104.097429
PWI     100.992154
KTK     100.030000
Name: SR, dtype: float64

## 10. Team with Highest Player Contribution

In [27]:
team_max_runs = (
    df.groupby('team')['RUNS']
      .max()
      .sort_values(ascending=False)
)

team_max_runs

team
RCB     973
GT      890
RR      863
SRH     848
CSK     733
DC      684
PBKS    670
KKR     660
MI      618
LSG     616
DEC     569
RPS     480
PWI     456
GL      442
KTK     357
Name: RUNS, dtype: int64

## PLAYER-WISE ANALYSIS

### 11. Top Run Scorers

In [28]:
top_runs = (
    df.groupby('player_name')['RUNS']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_runs

player_name
Virat Kohli       8094
Shikhar Dhawan    6769
Rohit Sharma      6636
David Warner      6402
Suresh Raina      5528
MS Dhoni          5289
Chris Gayle       4965
Robin Uthappa     4952
Ajinkya Rahane    4716
AB de Villiers    4697
Name: RUNS, dtype: int64

### 12. Players with Highest Average

In [29]:
best_avg = (
    df.groupby('player_name')['AVG']
      .mean()
      .sort_values(ascending=False)
)

best_avg.head(20)

player_name
Vivrant Sharma      69.000000
Simon Katich        56.055000
Sai Sudharsan       51.092500
Luke Pomersbach     51.000000
Quinton De Kock     48.942500
Priyansh Arya       47.000000
Devon Conway        46.845000
Matthew Hayden      45.540000
Adam Voges          45.250000
Andrew Symonds      45.115000
Hashim Amla         43.080000
Ruturaj Gaikwad     42.741667
JP Duminy           42.676250
MS Dhoni            42.295000
Virat Kohli         41.703889
KL Rahul            41.312500
Cameron Green       41.050000
David Warner        40.704286
Paul Collingwood    40.600000
Kevin Pietersen     40.280000
Name: AVG, dtype: float64

## 13. Players with Highest Strike Rate

In [30]:
best_sr = (
    df.groupby('player_name')['SR']
      .mean()
      .sort_values(ascending=False)
)

best_sr.head(20)

player_name
Abu Nechim          300.000000
Luke Wood           300.000000
Bhargav Bhatt       300.000000
Jamie Overton       275.000000
Prerak Mankad       264.580000
Vipraj Nigam        260.000000
Billy Stanlake      250.000000
Raiphi Gomez        246.000000
Romario Shepherd    206.440000
Aniket Verma        205.260000
Umar Gul            205.260000
Priyansh Arya       204.340000
Syed Mohammad       200.640000
Reetinder Sodhi     200.000000
Shashank Singh      195.483333
Ashutosh Sharma     190.075000
Shubham Dubey       180.315000
Phil Salt           177.710000
Luke Wright         176.660000
Shahid Afridi       176.080000
Name: SR, dtype: float64

## 14. Most Consistent Players

In [31]:
consistent = (
    df.groupby('player_name')['RUNS']
      .std()
      .sort_values()
)

consistent.head(20)

player_name
Dilhara Fernando    0.000000
Amit Singh          0.000000
Khaleel Ahmed       0.577350
Barinder Sran       0.577350
Kevon Cooper        0.577350
Fazalhaq Farooqi    0.707107
Beuran Hendricks    0.707107
Romario Shepherd    0.707107
Ajantha Mendis      1.000000
Shaun Tait          1.414214
Callum Ferguson     1.414214
Fabian Allen        1.414214
KP Appanna          1.414214
Pragyan Ojha        1.516575
Ali Murtaza         1.527525
Pravin Tambe        1.914854
Vaibhav Arora       2.000000
Dhruv Shorey        2.121320
Sanvir Singh        2.121320
Noor Ahmad          2.121320
Name: RUNS, dtype: float64

## 15. Players with Most Not Outs

In [32]:
not_outs = (
    df.groupby('player_name')['NO']
      .sum()
      .sort_values(ascending=False)
)

not_outs.head(20)

player_name
MS Dhoni               97
Ravindra Jadeja        77
Kieron Pollard         52
Dinesh Karthik         45
David Miller           45
Yusuf Pathan           44
Dwayne Bravo           44
Hardik Pandya          40
Krunal Pandya          38
Virat Kohli            38
Harbhajan Singh        37
Piyush Chawla          36
Axar Patel             36
AB de Villiers         36
Ravichandran Ashwin    34
Ambati Rayudu          33
Bhuvneshwar Kumar      32
Umesh Yadav            31
Suresh Raina           30
Irfan Pathan           29
Name: NO, dtype: int64

In [33]:
df

,POS,player_name,team,RUNS,MAT,INNS,NO,HS,AVG,BF,SR,100,50,4S,6S,season,status,boundary_runs
0,1,Shaun Marsh,PBKS,616,11,11,2,115,68.44,441,139.68,1,5,59,26,2008,out,392
1,2,Gautam Gambhir,DC,534,14,14,1,86,41.07,379,140.89,0,5,68,8,2008,out,320
2,3,Sanath Jayasuriya,MI,518,14,14,2,114,43.16,309,167.63,1,2,58,31,2008,Not_out,418
3,4,Shane Watson,RR,472,15,15,5,76,47.20,311,151.76,0,4,47,19,2008,Not_out,302
4,5,Graeme Smith,RR,441,11,11,2,91,49.00,362,121.82,0,3,54,8,2008,out,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2604,97,Kumar Kartikeya Singh,RR,1,1,1,0,1,1.00,1,100.00,0,0,0,0,2025,out,0
2605,98,Sai Kishore,GT,1,2,1,0,1,1.00,1,100.00,0,0,0,0,2025,out,0
2606,99,Mohd Arshad Khan,GT,1,1,1,1,1,NaN,1,100.00,0,0,0,0,2025,Not_out,0
2607,100,Mohit Sharma,DC,1,2,1,1,1,NaN,2,50.00,0,0,0,0,2025,Not_out,0
2608,101,Trent Boult,MI,1,2,1,0,1,1.00,2,50.00,0,0,0,0,2025,out,0

## 16. Players with Most Sixes

In [35]:
most_sixes = (
    df.groupby('player_name')['6S']
      .sum()
      .sort_values(ascending=False)
)

most_sixes.head(20)

player_name
Chris Gayle       357
Rohit Sharma      280
Virat Kohli       276
MS Dhoni          255
AB de Villiers    239
David Warner      231
Kieron Pollard    223
Sanju Samson      211
Andre Russell     209
Suresh Raina      203
Shane Watson      190
Robin Uthappa     182
Ambati Rayudu     173
Jos Buttler       164
Glenn Maxwell     160
Yusuf Pathan      158
Rishabh Pant      155
Dinesh Karthik    152
Shikhar Dhawan    152
Yuvraj Singh      149
Name: 6S, dtype: int64

## 17. Players with Most Fours

In [37]:
most_fours = (
    df.groupby('player_name')['4S']
      .sum()
      .sort_values(ascending=False)
)

most_fours.head(20)

player_name
Shikhar Dhawan      768
Virat Kohli         711
David Warner        647
Rohit Sharma        601
Suresh Raina        506
Ajinkya Rahane      485
Robin Uthappa       481
Gautam Gambhir      459
Dinesh Karthik      446
Chris Gayle         405
Suryakumar Yadav    385
Shane Watson        376
AB de Villiers      374
MS Dhoni            367
Parthiv Patel       365
Jos Buttler         364
Sanju Samson        362
Ambati Rayudu       359
Manish Pandey       335
Shubman Gill        316
Name: 4S, dtype: int64

### 18. Players with Highest Individual Scores

In [39]:
highest_scores = (
    df.groupby('player_name')['HS']
      .max()
      .sort_values(ascending=False)
)

highest_scores.head(20)

player_name
Chris Gayle         175
Brendon McCullum    158
Quinton De Kock     140
AB de Villiers      133
KL Rahul            132
Shubman Gill        129
Rishabh Pant        128
Murali Vijay        127
David Warner        126
Jos Buttler         124
Marcus Stoinis      124
Yashasvi Jaiswal    124
Virender Sehwag     122
Paul Valthaty       120
Sanju Samson        119
Andrew Symonds      117
Shane Watson        117
Michael Hussey      116
Shaun Marsh         115
Wriddhiman Saha     115
Name: HS, dtype: int64

## 19. Players with Most Centuries

In [40]:
most_100s = (
    df.groupby('player_name')['100']
      .sum()
      .sort_values(ascending=False)
)

most_100s.head(20)

player_name
Virat Kohli         8
Jos Buttler         7
Chris Gayle         6
David Warner        4
Shane Watson        4
Shubman Gill        4
Sanju Samson        3
KL Rahul            2
K L Rahul           2
Ben Stokes          2
Ajinkya Rahane      2
Jonny Bairstow      2
Brendon McCullum    2
Adam Gilchrist      2
Hashim Amla         2
Murali Vijay        2
Rohit Sharma        2
Ruturaj Gaikwad     2
Shikhar Dhawan      2
Suryakumar Yadav    2
Name: 100, dtype: int64

## 20. Players with Most Half Centuries

In [41]:
most_50s = (
    df.groupby('player_name')['50']
      .sum()
      .sort_values(ascending=False)
)

most_50s.head(20)

player_name
David Warner        61
Virat Kohli         56
Shikhar Dhawan      51
Rohit Sharma        43
Suresh Raina        39
AB de Villiers      37
Gautam Gambhir      35
Chris Gayle         31
Ajinkya Rahane      31
Robin Uthappa       27
KL Rahul            27
Sanju Samson        26
Suryakumar Yadav    24
MS Dhoni            24
Shreyas Iyer        22
Ambati Rayudu       22
Manish Pandey       22
Faf du Plessis      22
Dinesh Karthik      21
Shane Watson        21
Name: 50, dtype: int64

## SEASON-WISE ANALYSIS

### 21. Total Runs in Each Season

In [42]:
season_runs = (
    df.groupby('season')['RUNS']
      .sum()
)

season_runs

season
2008    16699
2009    13157
2010    17696
2011    19903
2012    21317
2013    21416
2014    17918
2015    17409
2016    17962
2017    17907
2018    19098
2019    18574
2020    18508
2021    17716
2022    23052
2023    24429
2024    24659
2025     3956
Name: RUNS, dtype: int64

## 22. Average Strike Rate by Season

In [43]:
season_sr = (
    df.groupby('season')['SR']
      .mean()
)

season_sr

season
2008    108.486800
2009     96.419308
2010    109.249477
2011    108.823106
2012    117.198726
2013    107.148418
2014    111.220985
2015    116.793333
2016    115.034118
2017    112.154825
2018    114.951522
2019    109.617500
2020    107.364737
2021    105.055638
2022    120.406235
2023    121.501928
2024    129.349641
2025    142.485248
Name: SR, dtype: float64

## 23. Highest Run Scorer Each Season

In [46]:
season_top = (
    df.loc[
        df.groupby('season')['RUNS']
          .idxmax()
    ][['season', 'player_name', 'RUNS']]
)

season_top

      season       player_name  RUNS
0       2008       Shaun Marsh   616
150     2009    Matthew Hayden   572
280     2010  Sachin Tendulkar   618
433     2011       Chris Gayle   608
594     2012       Chris Gayle   733
751     2013    Michael Hussey   733
909     2014     Robin Uthappa   660
1041    2015      David Warner   562
1170    2016       Virat Kohli   973
1306    2017      David Warner   641
1449    2018   Kane Williamson   735
1587    2019      David Warner   692
1731    2020          KL Rahul   670
1864    2021   Ruturaj Gaikwad   635
2013    2022       Jos Buttler   863
2175    2023      Shubman Gill   890
2341    2024       Virat Kohli   741
2508    2025   Nicholas Pooran   145

## 24. Total Centuries Each Season

In [47]:
season_100s = (
    df.groupby('season')['100']
      .sum()
)

season_100s

season
2008     6
2009     1
2010     4
2011     6
2012     6
2013     4
2014     3
2015     4
2016     7
2017     5
2018     5
2019     6
2020     5
2021     4
2022     8
2023    12
2024    14
2025     1
Name: 100, dtype: int64

## 25. Total Sixes Each Season

In [48]:
season_sixes = (
    df.groupby('season')['6S']
      .sum()
)

season_sixes

season
2008     620
2009     456
2010     583
2011     638
2012     731
2013     674
2014     714
2015     692
2016     638
2017     705
2018     872
2019     784
2020     734
2021     687
2022    1062
2023    1124
2024    1260
2025     221
Name: 6S, dtype: int64

## 25. Total FOURS Each Season

In [49]:
season_fours = (
    df.groupby('season')['4S']
      .sum()
)

season_fours

season
2008    1692
2009    1110
2010    1705
2011    1915
2012    1911
2013    2051
2014    1562
2015    1607
2016    1632
2017    1608
2018    1652
2019    1653
2020    1582
2021    1548
2022    2017
2023    2174
2024    2174
2025     343
Name: 4S, dtype: int64

## 26. Best Batting Average by Season

In [51]:
season_best_avg = (
    df.groupby('season')['AVG']
      .max()
)

season_best_avg

season
2008    152.00
2009     84.00
2010     59.00
2011     68.00
2012     81.33
2013     70.00
2014     74.20
2015     86.00
2016     81.08
2017     60.00
2018     75.83
2019     83.20
2020    101.00
2021     75.66
2022     68.71
2023     69.00
2024     62.38
2025    101.00
Name: AVG, dtype: float64

## 27. Most Aggressive Season

In [52]:
season_aggression = (
    df.groupby('season')['SR']
      .mean()
      .sort_values(ascending=False)
)

season_aggression

season
2025    142.485248
2024    129.349641
2023    121.501928
2022    120.406235
2012    117.198726
2015    116.793333
2016    115.034118
2018    114.951522
2017    112.154825
2014    111.220985
2019    109.617500
2010    109.249477
2011    108.823106
2008    108.486800
2020    107.364737
2013    107.148418
2021    105.055638
2009     96.419308
Name: SR, dtype: float64

## TEAM + SEASON ANALYSIS

## 28. Team Runs Per Season

In [53]:
team_season = (
    df.groupby(['season', 'team'])['RUNS']
      .sum()
      .reset_index()
)

team_season

     season  team  RUNS
0      2008   CSK  2365
1      2008    DC  2000
2      2008   DEC  1681
3      2008   KKR  1757
4      2008    MI  1831
..      ...   ...   ...
151    2025    MI   296
152    2025  PBKS   229
153    2025   RCB   359
154    2025    RR   548
155    2025   SRH   603

[156 rows x 3 columns]

## 29. Best Team in Every Season

In [54]:
best_team = (
    df.groupby(['season', 'team'])['RUNS']
      .sum()
      .reset_index()
)

best_team = (
    best_team.loc[
        best_team.groupby('season')['RUNS']
                 .idxmax()
    ]
)

best_team

     season  team  RUNS
5      2008  PBKS  2776
10     2009   DEC  2279
20     2010    MI  2549
24     2011   CSK  2461
34     2012   CSK  2717
46     2013    MI  2845
56     2014  PBKS  2824
63     2015    MI  2611
73     2016   RCB  2863
79     2017    MI  2622
84     2018   CSK  2698
95     2019    MI  2554
101    2020    DC  2656
108    2021   CSK  2607
124    2022    RR  2807
128    2023    GT  2906
145    2024   SRH  2906
155    2025   SRH   603

## 30. Team-wise Strike Rate by Season

In [56]:
team_sr_season = (
    df.groupby(['season', 'team'])['SR']
      .mean()
)

team_sr_season

season  team
2008    CSK     107.667647
        DC      108.734667
        DEC     108.912632
        KKR     107.116316
        MI      108.066190
                   ...
2025    MI      113.214167
        PBKS    168.796667
        RCB     186.914286
        RR      133.182500
        SRH     133.265000
Name: SR, Length: 156, dtype: float64

## 31. Team-wise Sixes by Season

In [55]:
team_sixes_season = (
    df.groupby(['season', 'team'])['6S']
      .sum()
)

team_sixes_season

season  team
2008    CSK     86
        DC      54
        DEC     73
        KKR     75
        MI      74
                ..
2025    MI      12
        PBKS    16
        RCB     19
        RR      34
        SRH     32
Name: 6S, Length: 156, dtype: int64

## PLAYER + SEASON ANALYSIS

## 32. Player Growth Across Seasons

In [58]:
player_growth = (
    df.groupby(['player_name', 'season'])['RUNS']
      .sum()
      .reset_index()
)

player_growth.head(20)

       player_name  season  RUNS
0   AB de Villiers    2008    95
1   AB de Villiers    2010   111
2   AB de Villiers    2011   312
3   AB de Villiers    2012   319
4   AB de Villiers    2013   360
5   AB de Villiers    2014   395
6   AB de Villiers    2015   513
7   AB de Villiers    2016   687
8   AB de Villiers    2017   216
9   AB de Villiers    2018   480
10  AB de Villiers    2019   442
11  AB de Villiers    2020   454
12  AB de Villiers    2021   313
13   Aakash Chopra    2008    42
14   Aakash Chopra    2009    11
15     Aaron Finch    2010    21
16     Aaron Finch    2011    47
17     Aaron Finch    2012    55
18     Aaron Finch    2013   456
19     Aaron Finch    2014   309

## 33. Player Peak Seasons

In [59]:
peak = (
    df.loc[
        df.groupby('player_name')['RUNS']
          .idxmax()
    ][['player_name', 'season', 'RUNS']]
)

peak.head(20)

                player_name  season  RUNS
1172         AB de Villiers    2016   687
75            Aakash Chopra    2008    42
761             Aaron Finch    2013   456
2332           Abdul Basith    2023     1
2398            Abdul Samad    2024   182
146            Abdur Razzak    2008     0
2161         Abhijeet Tomar    2022     4
531        Abhimanyu Mithun    2011    27
2242        Abhinav Manohar    2023   114
860          Abhinav Mukund    2013    19
321   Abhishek Jhunjhunwala    2010   183
24           Abhishek Nayar    2008   206
202           Abhishek Raut    2009    78
2350        Abhishek Sharma    2024   484
2370          Abishek Porel    2024   327
1140             Abu Nechim    2015    10
151          Adam Gilchrist    2009   495
1962             Adam Milne    2021    16
322              Adam Voges    2010   181
2309             Adam Zampa    2023    10

## 34. Players Playing Most Seasons

In [60]:
long_career = (
    df.groupby('player_name')['season']
      .nunique()
      .sort_values(ascending=False)
)

long_career.head(20)

player_name
Rohit Sharma           18
MS Dhoni               18
Virat Kohli            18
Ravindra Jadeja        17
Wriddhiman Saha        17
Manish Pandey          17
Ajinkya Rahane         17
Shikhar Dhawan         17
Ravichandran Ashwin    16
Dinesh Karthik         16
Robin Uthappa          15
Piyush Chawla          15
David Warner           14
Ambati Rayudu          14
Sunil Narine           14
Dwayne Bravo           14
Mayank Agarwal         14
Umesh Yadav            14
Kieron Pollard         13
Suresh Raina           13
Name: season, dtype: int64

## 35. Player-wise Average Runs Per Season

In [62]:
avg_runs = (
    df.groupby('player_name')['RUNS']
      .mean()
      .sort_values(ascending=False)
)

avg_runs.head(20)

player_name
Devon Conway        462.000000
David Warner        457.285714
Virat Kohli         449.666667
Faf Du Plessis      428.750000
Suresh Raina        425.230769
Ruturaj Gaikwad     416.000000
Shubman Gill        410.875000
KL Rahul            409.125000
Shikhar Dhawan      398.176471
Gautam Gambhir      393.100000
Sachin Tendulkar    389.000000
Tilak Varma         385.333333
Chris Gayle         381.923077
Kyle Mayers         379.000000
Matthew Hayden      369.000000
Rohit Sharma        368.666667
Jos Buttler         367.500000
Rishabh Pant        366.555556
Rahul Dravid        362.333333
Virender Sehwag     361.428571
Name: RUNS, dtype: float64

## ADVANCED GROUPBY ANALYSIS

## 36. Multi Aggregation Analysis

In [63]:
multi = (
    df.groupby('team')
      .agg({
          'RUNS': ['sum', 'mean', 'max'],
          'SR': ['mean', 'max'],
          '6S': ['sum']
      })
)

multi

       RUNS                           SR            6S
        sum        mean  max        mean     max   sum
team
CSK   37166  166.663677  733  120.171076  300.00  1526
DC    35586  117.445545  684  111.525050  333.33  1321
DEC   10443  120.034483  569  106.366782  176.08   381
GL     4627  132.200000  442  104.097429  176.66   155
GT     7760  138.571429  890  126.028214  300.00   295
KKR   37208  124.026667  660  114.202333  300.00  1506
KTK    1757   97.611111  357  100.030000  173.33    53
LSG    7462  133.250000  616  129.666607  275.00   359
MI    40091  134.083612  618  114.479666  300.00  1690
PBKS  38201  123.229032  670  114.605645  400.00  1548
PWI    6034   92.830769  456  100.992154  400.00   196
RCB   38914  121.606250  973  114.109437  400.00  1668
RPS    4332  114.000000  480  107.783947  233.33   157
RR    33586  120.812950  863  110.407014  266.66  1269
SRH   28209  127.642534  848  115.648824  250.00  1071

## 37. Pivot Table Analysis

In [64]:
pivot = pd.pivot_table(
    df,
    values='RUNS',
    index='team',
    columns='season',
    aggfunc='sum'
)

pivot

season,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
team,,,,,,,,,,,,,,,,,,
CSK,2365.0,2084.0,2403.0,2461.0,2717.0,2669.0,2519.0,2564.0,NaN,NaN,2698.0,2346.0,2095.0,2607.0,2165.0,2600.0,2405.0,468.0
DC,2000.0,26.0,2027.0,1942.0,2501.0,2102.0,1978.0,2061.0,1995.0,2131.0,2250.0,2418.0,2656.0,2382.0,2218.0,2073.0,2465.0,361.0
DEC,1681.0,2279.0,2244.0,2039.0,2200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2318.0,2309.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2517.0,2906.0,1936.0,401.0
KKR,1757.0,1495.0,1974.0,1905.0,2354.0,2134.0,2372.0,1939.0,2133.0,2354.0,2655.0,2352.0,2123.0,2423.0,2109.0,2338.0,2481.0,310.0
KTK,NaN,NaN,NaN,1757.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LSG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2405.0,2326.0,2350.0,381.0
MI,1831.0,1748.0,2549.0,2125.0,2332.0,2845.0,2231.0,2611.0,2091.0,2622.0,2255.0,2554.0,2642.0,2016.0,2100.0,2821.0,2422.0,296.0
PBKS,2776.0,1768.0,2155.0,2079.0,2286.0,2311.0,2824.0,1889.0,2051.0,2099.0,2124.0,2326.0,2242.0,2061.0,2193.0,2416.0,2372.0,229.0
PWI,NaN,NaN,NaN,1669.0,2183.0,2182.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RCB,1865.0,2165.0,2272.0,2325.0,2351.0,2428.0,1992.0,2190.0,2863.0,1760.0,2240.0,2129.0,2158.0,2181.0,2454.0,2393.0,2789.0,359.0
RPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962.0,2370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RR,2424.0,1592.0,2072.0,1601.0,2393.0,2567.0,2059.0,2038.0,NaN,NaN,2276.0,2104.0,2197.0,2087.0,2807.0,2288.0,2533.0,548.0
SRH,NaN,NaN,NaN,NaN,NaN,2178.0,1943.0,2117.0,2549.0,2262.0,2600.0,2345.0,2395.0,1959.0,2084.0,2268.0,2906.0,603.0

## 38. Crosstab Analysis

In [65]:
cross = pd.crosstab(
    df['team'],
    df['status']
)

cross

status  Not_out  out
team
CSK         100  123
DC          123  180
DEC          32   55
GL           12   23
GT           15   41
KKR         115  185
KTK           6   12
LSG          18   38
MI          123  176
PBKS        137  173
PWI          18   47
RCB         134  186
RPS          14   24
RR          116  162
SRH         106  115

## 39. Ranking Players Within Teams

In [67]:
df['team_rank'] = (
    df.groupby('team')['RUNS']
      .rank(method='dense', ascending=False)
)

(df[
    ['player_name', 'team', 'RUNS', 'team_rank']
].head())

         player_name  team  RUNS  team_rank
0        Shaun Marsh  PBKS   616        4.0
1     Gautam Gambhir    DC   534        4.0
2  Sanath Jayasuriya    MI   518        7.0
3       Shane Watson    RR   472       11.0
4       Graeme Smith    RR   441       15.0

## 40. Top 3 Players from Every Team

In [69]:
top3 = (
    df.sort_values(
        ['team', 'RUNS'],
        ascending=[True, False]
    )
    .groupby('team')
    .head(3)
)

top3[['team', 'player_name', 'RUNS']]

      team         player_name  RUNS
751    CSK      Michael Hussey   733
2177   CSK        Devon Conway   672
1864   CSK     Ruturaj Gaikwad   635
1450    DC        Rishabh Pant   684
1732    DC      Shikhar Dhawan   618
1867    DC      Shikhar Dhawan   587
596    DEC      Shikhar Dhawan   569
151    DEC      Adam Gilchrist   495
599    DEC       Cameron White   479
1310    GL        Suresh Raina   442
1179    GL        Suresh Raina   399
1182    GL         Aaron Finch   393
2175    GT        Shubman Gill   890
2346    GT       Sai Sudharsan   527
2016    GT       Hardik Pandya   487
909    KKR       Robin Uthappa   660
595    KKR      Gautam Gambhir   590
1591   KKR       Andre Russell   510
452    KTK    Brendon McCullum   357
459    KTK  Mahela Jayawardena   299
461    KTK          Brad Hodge   285
2014   LSG           K L Rahul   616
2347   LSG           K L Rahul   520
2015   LSG     Quinton De Kock   508
280     MI    Sachin Tendulkar   618
2180    MI    Suryakumar Yadav   605
435     MI    Sachin Tendulkar   553
1731  PBKS            KL Rahul   670
1451  PBKS            KL Rahul   659
1866  PBKS            KL Rahul   626
761    PWI         Aaron Finch   456
762    PWI       Robin Uthappa   434
605    PWI       Robin Uthappa   405
1170   RCB         Virat Kohli   973
2341   RCB         Virat Kohli   741
594    RCB         Chris Gayle   733
1176   RPS      Ajinkya Rahane   480
1309   RPS         Steve Smith   472
1314   RPS      Rahul Tripathi   391
2013    RR         Jos Buttler   863
2179    RR    Yashasvi Jaiswal   625
2343    RR         Riyan Parag   573
1171   SRH        David Warner   848
1449   SRH     Kane Williamson   735
1587   SRH        David Warner   692

In [74]:
dfs=df.iloc[:,-2::-1].iloc[:,::-1]
dfs

,POS,player_name,team,RUNS,MAT,INNS,NO,HS,AVG,BF,SR,100,50,4S,6S,season,status,boundary_runs
0,1,Shaun Marsh,PBKS,616,11,11,2,115,68.44,441,139.68,1,5,59,26,2008,out,392
1,2,Gautam Gambhir,DC,534,14,14,1,86,41.07,379,140.89,0,5,68,8,2008,out,320
2,3,Sanath Jayasuriya,MI,518,14,14,2,114,43.16,309,167.63,1,2,58,31,2008,Not_out,418
3,4,Shane Watson,RR,472,15,15,5,76,47.20,311,151.76,0,4,47,19,2008,Not_out,302
4,5,Graeme Smith,RR,441,11,11,2,91,49.00,362,121.82,0,3,54,8,2008,out,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2604,97,Kumar Kartikeya Singh,RR,1,1,1,0,1,1.00,1,100.00,0,0,0,0,2025,out,0
2605,98,Sai Kishore,GT,1,2,1,0,1,1.00,1,100.00,0,0,0,0,2025,out,0
2606,99,Mohd Arshad Khan,GT,1,1,1,1,1,NaN,1,100.00,0,0,0,0,2025,Not_out,0
2607,100,Mohit Sharma,DC,1,2,1,1,1,NaN,2,50.00,0,0,0,0,2025,Not_out,0
2608,101,Trent Boult,MI,1,2,1,0,1,1.00,2,50.00,0,0,0,0,2025,out,0

In [75]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2609 entries, 0 to 2608
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   POS            2609 non-null   int64
 1   player_name    2609 non-null   object
 2   team           2609 non-null   object
 3   RUNS           2609 non-null   int64
 4   MAT            2609 non-null   int64
 5   INNS           2609 non-null   int64
 6   NO             2609 non-null   int64
 7   HS             2609 non-null   int64
 8   AVG            2547 non-null   float64
 9   BF             2609 non-null   int64
 10  SR             2609 non-null   float64
 11  100            2609 non-null   int64
 12  50             2609 non-null   int64
 13  4S             2609 non-null   int64
 14  6S             2609 non-null   int64
 15  season         2609 non-null   int64
 16  status         2609 non-null   object
 17  boundary_runs  2609 non-null   int64
dtypes: float64(2), int64(13), object(3)
memory usage: 367.0+ KB

In [76]:
dfs.to_csv("final_final_datasets.csv",index=False)

In [77]:
import os
os.getcwd()

'R:\\sipps_ss\\api_datas\\ip;l_'