In [ ]:
📊 PANDAS STACKING & UNSTACKING — REAL WORLD SALES ANALYSIS

 Scenario:
A retail company wants to analyze:
✔ Region-wise Sales
✔ Product-wise Revenue
✔ Monthly Trends
✔ Pivot-style reporting
✔ Hierarchical indexing using MultiIndex

# We will solve this using:
✅ stack()
✅ unstack()
✅ multi-indexing
✅ pivot analysis
✅ real-world business insights

# Read a datasets

In [45]:
import pandas as pd
import numpy as np

np.random.seed(42)

regions = ["Kathmandu", "Pokhara", "Chitwan"]
products = ["Laptop", "Phone", "Tablet"]
months = ["Jan", "Feb", "Mar", "Apr"]

data = []

for region in regions:
    for product in products:
        for month in months:
            units = np.random.randint(20, 120)
            price = np.random.randint(300, 2000)
            sales = units * price
            data.append([region,product,month,units,price,sales])

# Create DataFrame
df = pd.DataFrame(data, columns=["Region","Product","Month","Units_Sold","Unit_Price","Total_Sales"])
df

       Region Product Month  Units_Sold  Unit_Price  Total_Sales
0   Kathmandu  Laptop   Jan          71        1160        82360
1   Kathmandu  Laptop   Feb          34        1430        48620
2   Kathmandu  Laptop   Mar          91        1344       122304
3   Kathmandu  Laptop   Apr         102        1538       156876
4   Kathmandu   Phone   Jan          94        1782       167508
5   Kathmandu   Phone   Feb         107        1696       181472
6   Kathmandu   Phone   Mar         119        1171       139349
7   Kathmandu   Phone   Apr          43         430        18490
8   Kathmandu  Tablet   Jan          41        1632        66912
9   Kathmandu  Tablet   Feb          21         643        13503
10  Kathmandu  Tablet   Mar          49        1105        54145
11  Kathmandu  Tablet   Apr          21        1515        31815
12    Pokhara  Laptop   Jan          79         576        45504
13    Pokhara  Laptop   Feb          52         759        39468
14    Pokhara  Laptop   Mar          77         321        24717
15    Pokhara  Laptop   Apr         108        1884       203472
16    Pokhara   Phone   Jan         110        1382       152020
17    Pokhara   Phone   Feb          61        1799       109739
18    Pokhara   Phone   Mar          79        1275       100725
19    Pokhara   Phone   Apr          34         489        16626
20    Pokhara  Tablet   Jan          81         986        79866
21    Pokhara  Tablet   Feb          81         862        69822
22    Pokhara  Tablet   Mar          74        1567       115958
23    Pokhara  Tablet   Apr          83        1828       151724
24    Chitwan  Laptop   Jan          22        1808        39776
25    Chitwan  Laptop   Feb          70         946        66220
26    Chitwan  Laptop   Mar          40        1140        45600
27    Chitwan  Laptop   Apr          58        1597        92626
28    Chitwan   Phone   Jan          23         900        20700
29    Chitwan   Phone   Feb          79         313        24727
30    Chitwan   Phone   Mar          28        1669        46732
31    Chitwan   Phone   Apr          72        1197        86184
32    Chitwan  Tablet   Jan         103         391        40273
33    Chitwan  Tablet   Feb          79        1778       140462
34    Chitwan  Tablet   Mar          63         808        50904
35    Chitwan  Tablet   Apr          27         334         9018

In [3]:
print(df.head())

      Region Product Month  Units_Sold  Unit_Price  Total_Sales
0  Kathmandu  Laptop   Jan          71        1160        82360
1  Kathmandu  Laptop   Feb          34        1430        48620
2  Kathmandu  Laptop   Mar          91        1344       122304
3  Kathmandu  Laptop   Apr         102        1538       156876
4  Kathmandu   Phone   Jan          94        1782       167508

## Creating a Pivots Tables

In [4]:
pivot_df = df.pivot_table(
    index=["Region", "Product"],
    columns="Month",
    values="Total_Sales",
    aggfunc="sum"
)

pivot_df

Month                 Apr     Feb     Jan     Mar
Region    Product
Chitwan   Laptop    92626   66220   39776   45600
          Phone     86184   24727   20700   46732
          Tablet     9018  140462   40273   50904
Kathmandu Laptop   156876   48620   82360  122304
          Phone     18490  181472  167508  139349
          Tablet    31815   13503   66912   54145
Pokhara   Laptop   203472   39468   45504   24717
          Phone     16626  109739  152020  100725
          Tablet   151724   69822   79866  115958

# Stackings

In [5]:
pivot_df.stack()  # reset back to DataFrame

Region     Product  Month
Chitwan    Laptop   Apr       92626
                    Feb       66220
                    Jan       39776
                    Mar       45600
           Phone    Apr       86184
                    Feb       24727
                    Jan       20700
                    Mar       46732
           Tablet   Apr        9018
                    Feb      140462
                    Jan       40273
                    Mar       50904
Kathmandu  Laptop   Apr      156876
                    Feb       48620
                    Jan       82360
                    Mar      122304
           Phone    Apr       18490
                    Feb      181472
                    Jan      167508
                    Mar      139349
           Tablet   Apr       31815
                    Feb       13503
                    Jan       66912
                    Mar       54145
Pokhara    Laptop   Apr      203472
                    Feb       39468
                    Jan       45504
                    Mar       24717
           Phone    Apr       16626
                    Feb      109739
                    Jan      152020
                    Mar      100725
           Tablet   Apr      151724
                    Feb       69822
                    Jan       79866
                    Mar      115958
dtype: int64

## Reset Index reset all the myulti headers rows

In [8]:
stacked_df=pivot_df.stack().reset_index()
stacked_df

       Region Product Month       0
0     Chitwan  Laptop   Apr   92626
1     Chitwan  Laptop   Feb   66220
2     Chitwan  Laptop   Jan   39776
3     Chitwan  Laptop   Mar   45600
4     Chitwan   Phone   Apr   86184
5     Chitwan   Phone   Feb   24727
6     Chitwan   Phone   Jan   20700
7     Chitwan   Phone   Mar   46732
8     Chitwan  Tablet   Apr    9018
9     Chitwan  Tablet   Feb  140462
10    Chitwan  Tablet   Jan   40273
11    Chitwan  Tablet   Mar   50904
12  Kathmandu  Laptop   Apr  156876
13  Kathmandu  Laptop   Feb   48620
14  Kathmandu  Laptop   Jan   82360
15  Kathmandu  Laptop   Mar  122304
16  Kathmandu   Phone   Apr   18490
17  Kathmandu   Phone   Feb  181472
18  Kathmandu   Phone   Jan  167508
19  Kathmandu   Phone   Mar  139349
20  Kathmandu  Tablet   Apr   31815
21  Kathmandu  Tablet   Feb   13503
22  Kathmandu  Tablet   Jan   66912
23  Kathmandu  Tablet   Mar   54145
24    Pokhara  Laptop   Apr  203472
25    Pokhara  Laptop   Feb   39468
26    Pokhara  Laptop   Jan   45504
27    Pokhara  Laptop   Mar   24717
28    Pokhara   Phone   Apr   16626
29    Pokhara   Phone   Feb  109739
30    Pokhara   Phone   Jan  152020
31    Pokhara   Phone   Mar  100725
32    Pokhara  Tablet   Apr  151724
33    Pokhara  Tablet   Feb   69822
34    Pokhara  Tablet   Jan   79866
35    Pokhara  Tablet   Mar  115958

In [30]:
stacked_df.columns = ["Region","Product","Month","Sales"] # add dthe headings or columns 
stacked_df.head()

    Region Product Month  Sales
0  Chitwan  Laptop   Apr  92626
1  Chitwan  Laptop   Feb  66220
2  Chitwan  Laptop   Jan  39776
3  Chitwan  Laptop   Mar  45600
4  Chitwan   Phone   Apr  86184

In [10]:
print("\n================ CLEAN STACKED DATA ================\n")
stacked_df.head(10)

================ CLEAN STACKED DATA ================

    Region Product Month   Sales
0  Chitwan  Laptop   Apr   92626
1  Chitwan  Laptop   Feb   66220
2  Chitwan  Laptop   Jan   39776
3  Chitwan  Laptop   Mar   45600
4  Chitwan   Phone   Apr   86184
5  Chitwan   Phone   Feb   24727
6  Chitwan   Phone   Jan   20700
7  Chitwan   Phone   Mar   46732
8  Chitwan  Tablet   Apr    9018
9  Chitwan  Tablet   Feb  140462

In [ ]:
unstack() converts row levels into columns

Business Use Case:
Create dashboard-ready reports
Excel-style summaries
Power BI exports

In [31]:
multi_sales = (
    stacked_df
    .set_index(["Region", "Product", "Month"])
)
multi_sales

                          Sales
Region    Product Month
Chitwan   Laptop  Apr     92626
                  Feb     66220
                  Jan     39776
                  Mar     45600
          Phone   Apr     86184
                  Feb     24727
                  Jan     20700
                  Mar     46732
          Tablet  Apr      9018
                  Feb    140462
                  Jan     40273
                  Mar     50904
Kathmandu Laptop  Apr    156876
                  Feb     48620
                  Jan     82360
                  Mar    122304
          Phone   Apr     18490
                  Feb    181472
                  Jan    167508
                  Mar    139349
          Tablet  Apr     31815
                  Feb     13503
                  Jan     66912
                  Mar     54145
Pokhara   Laptop  Apr    203472
                  Feb     39468
                  Jan     45504
                  Mar     24717
          Phone   Apr     16626
                  Feb    109739
                  Jan    152020
                  Mar    100725
          Tablet  Apr    151724
                  Feb     69822
                  Jan     79866
                  Mar    115958

In [32]:
unstacked_df = multi_sales.unstack()  # Unstack to the child level hierarchy
unstacked_df

                    Sales
Month                 Apr     Feb     Jan     Mar
Region    Product
Chitwan   Laptop    92626   66220   39776   45600
          Phone     86184   24727   20700   46732
          Tablet     9018  140462   40273   50904
Kathmandu Laptop   156876   48620   82360  122304
          Phone     18490  181472  167508  139349
          Tablet    31815   13503   66912   54145
Pokhara   Laptop   203472   39468   45504   24717
          Phone     16626  109739  152020  100725
          Tablet   151724   69822   79866  115958

In [13]:
unstacked_df.unstack()  # two Times Unstack convert the row level index to column level Index

            Sales                                                              \
Month         Apr                   Feb                    Jan
Product    Laptop  Phone  Tablet Laptop   Phone  Tablet Laptop   Phone Tablet
Region
Chitwan     92626  86184    9018  66220   24727  140462  39776   20700  40273
Kathmandu  156876  18490   31815  48620  181472   13503  82360  167508  66912
Pokhara    203472  16626  151724  39468  109739   69822  45504  152020  79866


Month         Mar
Product    Laptop   Phone  Tablet
Region
Chitwan     45600   46732   50904
Kathmandu  122304  139349   54145
Pokhara     24717  100725  115958

## Advancer unstackings

In [15]:
stacked_df.head()

    Region Product Month  Sales
0  Chitwan  Laptop   Apr  92626
1  Chitwan  Laptop   Feb  66220
2  Chitwan  Laptop   Jan  39776
3  Chitwan  Laptop   Mar  45600
4  Chitwan   Phone   Apr  86184

### Unstack The row Index to the different Levels

In [16]:
advanced_unstack = (
    stacked_df
    .set_index(["Region", "Month", "Product"])
    ["Sales"]
    .unstack(level="Month")
)
advanced_unstack

Month                 Apr     Feb     Jan     Mar
Region    Product
Chitwan   Laptop    92626   66220   39776   45600
          Phone     86184   24727   20700   46732
          Tablet     9018  140462   40273   50904
Kathmandu Laptop   156876   48620   82360  122304
          Phone     18490  181472  167508  139349
          Tablet    31815   13503   66912   54145
Pokhara   Laptop   203472   39468   45504   24717
          Phone     16626  109739  152020  100725
          Tablet   151724   69822   79866  115958

## Unstack The data with the Region columns

In [17]:
advanced_unstack = (
    stacked_df
    .set_index(["Region", "Month", "Product"])
    ["Sales"]
    .unstack(level="Region")
)
advanced_unstack

Region         Chitwan  Kathmandu  Pokhara
Month Product
Apr   Laptop     92626     156876   203472
      Phone      86184      18490    16626
      Tablet      9018      31815   151724
Feb   Laptop     66220      48620    39468
      Phone      24727     181472   109739
      Tablet    140462      13503    69822
Jan   Laptop     39776      82360    45504
      Phone      20700     167508   152020
      Tablet     40273      66912    79866
Mar   Laptop     45600     122304    24717
      Phone      46732     139349   100725
      Tablet     50904      54145   115958

## Unstack The data with Products

In [18]:
advanced_unstack = (
    stacked_df
    .set_index(["Region", "Month", "Product"])
    ["Sales"]
    .unstack(level="Product")
)
advanced_unstack

Product          Laptop   Phone  Tablet
Region    Month
Chitwan   Apr     92626   86184    9018
          Feb     66220   24727  140462
          Jan     39776   20700   40273
          Mar     45600   46732   50904
Kathmandu Apr    156876   18490   31815
          Feb     48620  181472   13503
          Jan     82360  167508   66912
          Mar    122304  139349   54145
Pokhara   Apr    203472   16626  151724
          Feb     39468  109739   69822
          Jan     45504  152020   79866
          Mar     24717  100725  115958

# Which month generated highest sales?

In [19]:
monthly_sales = (
    stacked_df
    .groupby("Month")["Sales"]
    .sum()
    .sort_values(ascending=False)
)
monthly_sales

Month
Apr    766831
Mar    700434
Jan    694919
Feb    694033
Name: Sales, dtype: int64

In [21]:
df.head()

      Region Product Month  Units_Sold  Unit_Price  Total_Sales
0  Kathmandu  Laptop   Jan          71        1160        82360
1  Kathmandu  Laptop   Feb          34        1430        48620
2  Kathmandu  Laptop   Mar          91        1344       122304
3  Kathmandu  Laptop   Apr         102        1538       156876
4  Kathmandu   Phone   Jan          94        1782       167508

## Set Index methods

In [20]:
multi_index_df = (
    df
    .set_index(["Region", "Product", "Month"])
    .sort_index()
)

multi_index_df

                         Units_Sold  Unit_Price  Total_Sales
Region    Product Month
Chitwan   Laptop  Apr            58        1597        92626
                  Feb            70         946        66220
                  Jan            22        1808        39776
                  Mar            40        1140        45600
          Phone   Apr            72        1197        86184
                  Feb            79         313        24727
                  Jan            23         900        20700
                  Mar            28        1669        46732
          Tablet  Apr            27         334         9018
                  Feb            79        1778       140462
                  Jan           103         391        40273
                  Mar            63         808        50904
Kathmandu Laptop  Apr           102        1538       156876
                  Feb            34        1430        48620
                  Jan            71        1160        82360
                  Mar            91        1344       122304
          Phone   Apr            43         430        18490
                  Feb           107        1696       181472
                  Jan            94        1782       167508
                  Mar           119        1171       139349
          Tablet  Apr            21        1515        31815
                  Feb            21         643        13503
                  Jan            41        1632        66912
                  Mar            49        1105        54145
Pokhara   Laptop  Apr           108        1884       203472
                  Feb            52         759        39468
                  Jan            79         576        45504
                  Mar            77         321        24717
          Phone   Apr            34         489        16626
                  Feb            61        1799       109739
                  Jan           110        1382       152020
                  Mar            79        1275       100725
          Tablet  Apr            83        1828       151724
                  Feb            81         862        69822
                  Jan            81         986        79866
                  Mar            74        1567       115958

## Filter out the Specific regions and The Products sales cfrom the Multi Index series

In [38]:
print("\n================ KATHMANDU LAPTOP SALES ================\n")


multi_index_df.loc[("Kathmandu", "Laptop")]

================ KATHMANDU LAPTOP SALES ================

       Units_Sold  Unit_Price  Total_Sales
Month
Apr           102        1538       156876
Feb            34        1430        48620
Jan            71        1160        82360
Mar            91        1344       122304

In [42]:
print("\n=============== All Region All Products Totakl Sales only  ================\n")


multi_index_df.loc[:,("Unit_Price",	"Total_Sales")]

=============== All Region All Products Totakl Sales only  ================

                         Unit_Price  Total_Sales
Region    Product Month
Chitwan   Laptop  Apr          1597        92626
                  Feb           946        66220
                  Jan          1808        39776
                  Mar          1140        45600
          Phone   Apr          1197        86184
                  Feb           313        24727
                  Jan           900        20700
                  Mar          1669        46732
          Tablet  Apr           334         9018
                  Feb          1778       140462
                  Jan           391        40273
                  Mar           808        50904
Kathmandu Laptop  Apr          1538       156876
                  Feb          1430        48620
                  Jan          1160        82360
                  Mar          1344       122304
          Phone   Apr           430        18490
                  Feb          1696       181472
                  Jan          1782       167508
                  Mar          1171       139349
          Tablet  Apr          1515        31815
                  Feb           643        13503
                  Jan          1632        66912
                  Mar          1105        54145
Pokhara   Laptop  Apr          1884       203472
                  Feb           759        39468
                  Jan           576        45504
                  Mar           321        24717
          Phone   Apr           489        16626
                  Feb          1799       109739
                  Jan          1382       152020
                  Mar          1275       100725
          Tablet  Apr          1828       151724
                  Feb           862        69822
                  Jan           986        79866
                  Mar          1567       115958

## Row and Column Both Folter The katmandu ,laptop  Total Price

In [41]:
print("\n=============== All Region All Products Totakl Sales only  ================\n")


multi_index_df.loc[("Kathmandu","Laptop"),("Unit_Price","Total_Sales")]

=============== All Region All Products Totakl Sales only  ================

       Unit_Price  Total_Sales
Month
Apr          1538       156876
Feb          1430        48620
Jan          1160        82360
Mar          1344       122304